### ISSUE TITLE
Single Slack app to handle multiple workspaces (using Spring Boot, Java, Bolt).

### ISSUE THREAD

**Issue by daxxycodes** [slackapi/java-slack-sdk#1006]
Hi, and I apologize for having to bother you with this.

So I'm using Spring Boot, Java, and Bolt to build a Slack bot. I've followed the instructions for making a Slack app bot that responds to a particular workspace. It works! However, it won't respond when installed into other workspaces (or re-installed into the same workspace).

As my controller, I have
```
@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
    public SlackAppController(App app) {
        super(app);
    }
}
```

And the configuration appears as follows (secrets/tokens redacted):
```
@Configuration
@RequiredArgsConstructor
public class SlackApp {

    @Bean
    public App initSlackApp() {
        String userToken = "xoxp-stuff";
        AppConfig config = AppConfig.builder()
            .signingSecret("a-signing-secret")
            .singleTeamBotToken("xoxb-other-stuff") // corresponding to the one workspace it responds to
            .build();

        App app = new App(config);

        app.command("/hello", (req, ctx) -> {
            return ctx.ack("What's up?");
        });
    
        // also other app.event calls that rely on the bot token and the user token
    }
}
``` 
Now, this server has access to a table which will have multiple rows, each row having a team id, bot token, user token, etc. which corresponds to the JSON that comes back at the completion of the OAuth process when a new user installs this Slack app. (I have a separate server that allows customers the ability to purchase access to the bot.)

What I don't know is how to adapt the above beginning code to either (a) start up many `App`s (one per table row) or (b) build one `App` that will respond to different requests from different workspaces. (I'm told I'm supposed to go with approach (b)).

As a start, I tried to override the `doPost()` method in the servlet in the controller, but that doesn't seem to trigger at all when the bot is supposed to be responding. 

Is there a guide somewhere that will help with this  process (or otherwise, can you give some hints on how to proceed)?

**Comment by seratch** [comment]
Hi @daxxycodes, thanks for asking this question!

I noticed that the Spring Boot example app in this repo had not been demonstrating how to serve the OAuth flow. I just updated the app to cover the use case too: https://github.com/slackapi/java-slack-sdk/tree/main/bolt-spring-boot-examples/src/main/java/example

This example uses the default local file storage based installation data management. For production-grade operations, consider using [other built-in installation stores](https://github.com/slackapi/java-slack-sdk/tree/main/bolt/src/main/java/com/slack/api/bolt/service/builtin) or your own ones for secure and robust data management. Refer to https://slack.dev/java-slack-sdk/guides/app-distribution for more details.

I hope this was helpful to you.

**Comment by seratch** [comment]
@daxxycodes When your app installation issues both bot and user tokens, your InstallationService can return both when you can configure your app as below: 
* The OAuth flow must have both (bot) scopes and user scopes
* When initializing `App` instance, `AppConfig#alwaysRequestUserTokenNeeded` to true - https://github.com/slackapi/java-slack-sdk/blob/v1.23.0/bolt/src/main/java/com/slack/api/bolt/AppConfig.java#L363-L364
  * This option enables your app to call findInstaller in addition to findBot - https://github.com/slackapi/java-slack-sdk/blob/v1.23.0/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java#L152-L202
* Your `InstallationService#findInstaller` needs to be properly implemented - https://github.com/slackapi/java-slack-sdk/blob/v1.23.0/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java

If all the above are properly configured, your middleware / listeners can access user token via `context.getRequestUserToken()` - https://github.com/slackapi/java-slack-sdk/blob/v1.23.0/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java#L241

If you would like to use a different user's token for some reason (generally speaking, I don't recommend this, though), you can directly call `InstallationService` methods and/or run a query to fetch any data from your database.

I hope this helps. Is everything clear now?

**Comment by seratch** [comment]
@daxxycodes 
`ctx.getRequestUserId()` always exists for user interactions such as slash command invocation, button clicks, and modal data submission. 

However, the property is always null for Events API request patterns. Since "message" events and so on have user IDs, the framework may be able to set the property to some of the events in future updates. However, there are still many event patterns that do not provide user ID. 

If you are talking about Events API patterns, please extract user ID from the event payload. If you found a null pattern for the rest of platform features, please let us know how to reproduce the situation.

**Comment by daxxycodes** [comment]
Ah. Currently, my focus is on Events API patterns. For the situation I described above (line `(2)`), it is true that I can get a `user` which corresponds to the `authed_user_id` in the payload, but this value is actually not important to me. I simply need (in the context) `ctx.getRequestUserId()` to be not null so your highlighted block of code can populate the user token. 

But, it's good to know that it's there for slash commands, at least. So, for now, for Events API patterns, it looks like I'll go to the db for the token.

Thank you for taking the time to help me understand what's going on with all this. It's been really helpful. :)
