### ISSUE TITLE
Lambda handler class doesn't account for base64 encoded body

### ISSUE THREAD

**Issue by harshal-dupare** [slackapi/java-slack-sdk#1015]
Currently the [bolt-aws-lambda](https://github.com/slackapi/java-slack-sdk/tree/main/bolt-aws-lambda) package doesn't account for base64 encoded body. I don't know if this was the intended behaviour.  Ideally, I think it should handle that internally and not require the user to overwrite the methods to account for it.

### Category

**bolt**
**bolt-aws-lambda**

**Comment by seratch** [comment]
Hi @harshal-dupare, thanks for sharing this feedback! I just send a pull request fixing this issue. If possible, would you mind trying the change in your app? You can cut and paste the code into your project.

**Comment by harshal-dupare** [comment]
> Hi @harshal-dupare, thanks for sharing this feedback! I just send a pull request fixing this issue. If possible, would you mind trying the change in your app? You can cut and paste the code into your project.

Hi @seratch thanks for the quick fix!
