### ISSUE TITLE
RichTextListElement.java have does not have border and offset fields 

### ISSUE THREAD

**Issue by harinandan-reddy** [slackapi/java-slack-sdk#1029]
RichTextListElement.java have does not have border and offset fields 

When looking at the raw JSON we do have the two fields which are not present in the model object

```
{
        "type" : "rich_text_list",
        "elements" : [ {
          "type" : "rich_text_section",
          "elements" : [ {
            "type" : "text",
            "text" : "two"
          } ]
        }, {
          "type" : "rich_text_section",
          "elements" : [ {
            "type" : "text",
            "text" : "threefour"
          } ]
        } ],
        "style" : "ordered",
        "indent" : 0,
        "offset" : 1,
        "border" : 0
      }
```

#### The Slack SDK version

1.24.0

#### Java Runtime version

openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)

#### OS info

ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Enable event subscription
2. Post a message 
3. View received raw message 

#### Expected result:

Should be able to access the border and offset fields

#### Actual result:

The RichTextListElement.java does not have these fields 

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @harinandan-reddy, thanks for taking the time to report this! We will resolve this issue in the next release.
