### ISSUE TITLE
The filetype API method doc has an unformated/invalid link to file types

### ISSUE THREAD

**Issue by filmaj** [slackapi/java-slack-sdk#1036]
Was trying to find rendered API documentation, ended up googling this URL: https://javadoc.io/static/com.slack.api/slack-api-client/1.1.0/com/slack/api/methods/request/files/FilesUploadRequest.FilesUploadRequestBuilder.html#filetype-java.lang.String-

(not sure if the above URL is the go-to place to see rendered API docs?)

I believe the improperly-formatted link comes from this line of code: https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/methods/request/files/FilesUploadRequest.java#L34

As I play around with this API to try to help with a question around file uploading, I was trying to figure out what were acceptable values for filetype, but with the broken link, I am still unsure of what this string should be. A MIME type? A file extension? cc @seratch

**Comment by seratch** [comment]
@filmaj You can find valid links here: https://slack.dev/java-slack-sdk/
<img width="600" src="https://user-images.githubusercontent.com/19658/186522385-1091b053-7d2b-48b6-83ce-3fd489574fff.png">

Indeed, the part is not correctly formatted. We can improve it. https://oss.sonatype.org/service/local/repositories/releases/archive/com/slack/api/slack-api-client/1.24.0/slack-api-client-1.24.0-javadoc.jar/!/com/slack/api/methods/request/files/FilesUploadRequest.html#setFiletype(java.lang.String)

>As I play around with this API to try to help with a question around file uploading, I was trying to figure out what were acceptable values for filetype, but with the broken link, I am still unsure of what this string should be. A MIME type? A file extension? 

As you can see here: https://api.slack.com/methods/files.upload#arg_filetype, there is the list of available values in our API documents: https://api.slack.com/types/file#file_types

As for the javadocs, we can improve it by adding a valid link to the page.

**Comment by filmaj** [comment]
Ah yes, I should have checked the API method docs, silly of me 🤦 

Wow I totally missed the little book icon link!
