### ISSUE TITLE
Need to store Slack installations in MongoDB 

### ISSUE THREAD

**Issue by alejovazquezsplit** [slackapi/java-slack-sdk#1040]
I am implementing my own installation service using Spring Boot and following the steps here https://slack.dev/java-slack-sdk/guides/app-distribution by implementing the methods from the `InstallationService` interface to store the installations in **mongodb**.

I am trying it in my dev environment (exposed with ngrok) by installing my app using `/oauth/v2/authorize` and then calling `/oauth.v2.access` with the code I got from the `/oauth/v2/authorize` endpoint. After this, the app is installed successfully but looks like my methods `saveInstallerAndBot` and `findBot`/`findInstaller` are not called.

My Slack config looks like this:
```
@Bean
public InstallationService initInstallationService() {
    return new MongoSlackInstallationService();
}

@Bean
public App initSlackApp(@Qualifier("initInstallationService") InstallationService installationService) {
    App app = new App().asOAuthApp(true);
    app.command("/hello", (req, ctx) -> {
        return ctx.ack(":wave: What's up?");
    });
    app.service(installationService);
    return app;
}
```

Maybe I am missing something?

Another question is, do I need to implement OAuthStateService if I'm not using the state param?

Thanks!

#### The Slack SDK version

com.slack.api:bolt-servlet:1.24.0

#### Java Runtime version

openjdk version "11.0.15"

#### OS info

ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	        21G83
Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000

**Comment by seratch** [comment]
Hi @alejovazquezsplit, thanks for asking the question! Refer to the complete Spring Boot app example here: https://github.com/slackapi/java-slack-sdk/tree/v1.24.0/bolt-spring-boot-examples/src/main/java/example

Also, please note that your app installers need to start the OAuth flow at `https://{your app's public domain}/slack/install`, not the slack.com authorize URL.

**Comment by alejovazquezsplit** [comment]
@seratch thank you! I started the flow with `/slack/install` and also updated my `redirect` url which was also wrong and now it's calling my methods.

Another questions I have:
1. Do I need to implement the save and find installer methods from `InstallationService` interface if I will use only the bot token for workspaces/organizations?
2. Do I need to implement `OAuthStateService` if I'm not using the state param so far?

Thanks!

**Comment by alejovazquezsplit** [comment]
@seratch Hi, also another question. I am trying to remove an installation from my DB turning the event handlers on by doing `app.enableTokenRevocationHandlers();` but my delete methods which implement the ones from `InstallationService` are not being called.
The way I am uninstalling the app is by going to the app configuration page and then "Remove app".

Is this the right way to do it?

**Comment by seratch** [comment]
@alejovazquezsplit 
>Do I need to implement the save and find installer methods from InstallationService interface if I will use only the bot token for workspaces/organizations?

In this case, your findInstaller method can always return null values.

>Do I need to implement OAuthStateService if I'm not using the state param so far?

For better security, we don't recommend disabling state parameter validation. With the default settings, your app will use the built-in ClientOnlyOAuthStateService, which simply uses browser cookies only and does not require any server-side data storage for it. You can go with the default one if it's fine for your use case.

>I am trying to remove an installation from my DB turning the event handlers on by doing app.enableTokenRevocationHandlers(); but my delete methods which implement the ones from InstallationService are not being called.

Please double-check if you've already added two events ("tokens_revoked", "app_uninstalled") at your Slack app configuration page: `https://api.slack.com/apps/{your app ID}/event-subscriptions`

I think that we've already provided answers to your questions here. Would you mind closing this issue? Whenever you have a different question in the future, please feel free to create a new issue for it.

**Comment by alejovazquezsplit** [comment]
@seratch thank you!
