### ISSUE TITLE
Slack Bot in socket mode not returning attachments

### ISSUE THREAD

**Issue by nykolaslima** [slackapi/java-slack-sdk#1046]
I have an application already working using slack SDK into socked mode.

It works great when the messages are only with text. When I got a message with an attachment (e.g. A CSV file) the `attachments` attribute is always null.

```
public Response handleMessage(EventsApiPayload<AppMentionEvent> req, EventContext ctx) {
  req.getEvent().getText(); // this returns the text message
  req.getEvent().getAttachments(); //this is always null, even when the message was sent with an attachment into Slack
}
```

Is there any way to get message attachments from slack bot socket mode?

**Comment by mwbrooks** [comment]
Hi @nykolaslima 👋🏻 Great to hear that socket mode has been working well for you!

I believe you'll want to use `req.getEvent().getFiles()` to get a list of the attached files ([api payload reference](https://api.slack.com/events/message/file_share)).

While it's confusing, [`getAttachments()` returns a legacy UI element called "attachments"](https://api.slack.com/messaging/composing/layouts#attachments), which explains why it's blank 😄 

Looking forward to hearing back!

**Comment by nykolaslima** [comment]
@mwbrooks thank you for the response!
I am using `bolt-socket-mode` version `1.25.1` and it doesn't have the `getFiles()` method in `AppMentionEvent` class.

Should I use a different version?

**Comment by WilliamBergamin** [comment]
Hi @nykolaslima thanks for writing in!

The sdk provides the same fields mentioned in the [AppMentionEvent doc](https://api.slack.com/events/app_mention), it seems like only the `text` field is provided for this event and not the full message. In order to get your files I suggest querying it using the data provided by the event, here is an example

```java
public Response handleMessage(EventsApiPayload<AppMentionEvent> req, EventContext ctx) {
    ConversationsHistoryResponse res = app.client().conversationsHistory(r -> r
        .channel(req.getEvent().getChannel())
        .latest(req.getEvent().getTs())
        .inclusive(true)
        .limit(1));
    Message msg = res.getMessages().get(0);
    msg.getFiles()

    return ctx.ack();
}
```

Hopefully this helps you on your journey 🧭

**Comment by nykolaslima** [comment]
Vi @WilliamBergamin !
Thank you very much, it worked!
