### ISSUE TITLE
Bolt Micronaut CommandsTest is ignored

### ISSUE THREAD

**Issue by musketyr** [slackapi/java-slack-sdk#1052]
The `CommandsTest` test suite is not executed and actually broken when executed (tested in different project). The point is that the test is using JUnit 5 but the current Maven build is only executing JUnit 4 tests.

If you manage to execute the test then I can try to fix it.

### Reproducible in:

Latest `main` branch (https://github.com/slackapi/java-slack-sdk/commit/c6c9632f4bc2635c1243165e80ca0794a22e416b)

#### The Slack SDK version

1.25.1

#### Java Runtime version

```
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
```

#### OS info

```
ProductName:    macOS
ProductVersion: 12.2.1
BuildVersion:   21D62
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

1. Checkout the latest version on repository
2. Import it to IntelliJ
3. Select the green triangle next to the `CommandsTest` class name to "Run 'CommandsTest'"

#### Expected result:

The test is executed and some tests are broken.

#### Actual result:

No tests were found

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hey @musketyr, I am also aware of the issue with IDEA but if I remember correctly, the test is executable when you run mvn command instead. Do you already have insights to improve it to be IDEA compatible?

**Comment by seratch** [comment]
Ok, thanks for sharing this. I am sure that they were executed in the past but it no longer works. Do you have any suggestions on it?

**Comment by musketyr** [comment]
I'm long time Gradle user so I'm lost in Maven but I think this guide should help you to execute both JUnit 4 and JUnit 5 tests.

https://stackoverflow.com/questions/47158583/executing-junit-4-and-junit-5-tests-in-a-same-build

It's quite possible that the change was introduced with MIcronaut upgrade to version 3.

**Comment by seratch** [comment]
@musketyr Thanks! 

I've modified pom.xml a little, and now the test can be executed. However, indeed the test fails. Since it's already in the evening in my time zone, I will look into it tomorrow.

```diff
diff --git a/bolt-micronaut/pom.xml b/bolt-micronaut/pom.xml
index dd93caf0..040099b8 100644
--- a/bolt-micronaut/pom.xml
+++ b/bolt-micronaut/pom.xml
@@ -13,6 +13,7 @@
         <micronaut.version>3.6.2</micronaut.version>
         <micronaut-test-junit5.version>3.5.0</micronaut-test-junit5.version>
         <micronaut-rxjava3.version>2.3.0</micronaut-rxjava3.version>
+        <junit5-jupiter.version>5.9.0</junit5-jupiter.version>
         <!-- Note that upgrading this library breaks other dependency resolution -->
         <mockito-all.version>1.10.19</mockito-all.version>
         <jakarta.inject.version>2.0.1.MR</jakarta.inject.version>
@@ -80,6 +81,19 @@
             <version>${micronaut.version}</version>
             <scope>test</scope>
         </dependency>
+
+        <dependency>
+            <groupId>org.junit.jupiter</groupId>
+            <artifactId>junit-jupiter-engine</artifactId>
+            <version>${junit5-jupiter.version}</version>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.junit.jupiter</groupId>
+            <artifactId>junit-jupiter-api</artifactId>
+            <version>${junit5-jupiter.version}</version>
+            <scope>test</scope>
+        </dependency>
         <dependency>
             <groupId>org.mockito</groupId>
             <artifactId>mockito-all</artifactId>
```
