### ISSUE TITLE
formatting of message by chatPostMessage method of Slack Web API in Java language

### ISSUE THREAD

**Issue by MING-LI** [slackapi/java-slack-sdk#1069]
issue/questions:
got a problem with a original text msg to be sent by Slack with  (https://api.slack.com/methods/chat.postMessage)

Format issue
1.  :cry: (cry icon with : cry : without space next to it) or :rage: (angry icon with : rage : without space) emoji and also *ABC* ( * ABC * without space , with * asterisk quoted text) in my original text which got unintentionally interpreted as BOLD txt of ABC 

2. also some text with XX.XX wrongly interpreted as web hyperlink which I would keep it plain text

expected results:
what I desire to have is to keep emoji interpreted as cartoon icon but leave * what so ever text * (* quoted txt ) to be the same 
also keep XX.XX not to be interpreted as web hyperlink e.g. 800.SG (XXX dot YYY text), only be treated as plain text XX.XX

I try read the api doc and try with parse("none") which results in error then I try parse("").
but it does not make any changes to format of message.

Could I ask how the java code should be to make the above request happen?
I checked with the slack support they advise me to ask here and give me a json for format settings, but my code doesn't use json to set the format.

Code in java using slack web api:
```java
 result = client.chatPostMessage(r -> r
                            .token("xoxb-XXXX-XXXX")
                            .channel(id)
                            .text(text)
                            .parse("")
            );
```

Json given from Slack web general query support but they advice me to ask instead here for java syntax
```json
{

	"blocks": [

		{

			"type": "section",

			"text": {

				"type": "plain_text",

				"text": "This is a *plain* text section block with a :cry: emoji .",

				"emoji": true

			}

		}

	]

}
```

#### The Slack SDK version

Web API of slack officially

https://api.slack.com/methods/chat.postMessage

#### Java Runtime version

jdk-11.0.1 (runtime on server)
jdk 1.8 (for code compile and development) 

#### OS info

windows server 2012 on server / Windows 10 on my local host

**Comment by seratch** [comment]
Hi @MING-LI, thanks for asking the question!

Here is a simple Java code example that sends the blocks, which are equivalent to the JSON example:
```java
import com.slack.api.Slack;
import static com.slack.api.model.block.Blocks.asBlocks;
import static com.slack.api.model.block.Blocks.section;
import static com.slack.api.model.block.composition.BlockCompositions.plainText;

public class Main {
  public static void main(String[] args)throws Exception {
    String token = System.getenv("SLACK_BOT_TOKEN");
    Slack.getInstance().methods(token).chatPostMessage(r -> r
      .channel("#random")
      .text("This is a *plain* text section block with a :cry: emoji.")
      .blocks(asBlocks(
        section(s -> s.text(plainText(pt -> pt
          .text("This is a *plain* text section block with a :cry: emoji.")
          .emoji(true)))
        )
      ))
    );
  }
}
```

>also some text with XX.XX wrongly interpreted as web hyperlink which I would keep it plain text
>also keep XX.XX not to be interpreted as web hyperlink e.g. 800.SG (XXX dot YYY text), only be treated as plain text XX.XX

Perhaps, you are talking about the hyperlink that can be automatically set when a human user writes in the Slack UI. If so, there is no way to prevent this from happening on your 3rd party app side. If this can happen with a message posted by your app bot user, please share the steps to reproduce the situation. With that, we may be able to help you out more.

I hope this was helpful to you! If everything is clear now, would you mind closing this issue?

**Comment by seratch** [comment]
@MING-LI 
>Is it correct to understand you mean it cannot be avoided? please correct me if wrong, thanks
>src msg flow in my relaying app >> my slack msg relaying java app >> (through https web API) >> slack channel

OK, now I got the point. If a message by a different app already has the hyperlink syntax in the format, it's out of your app's control. Thus, when parsing the text message, your app may have to ignore/remove the part as necessary.

**Comment by MING-LI** [comment]
Also could I ask if there are documentation for java more details explanation on how to use those functions please?
I wish to have a better understanding of usage of java slack library code for the sample u just shared

**Comment by seratch** [comment]
>if it is possible to turn that auto hyperlink function off?

In the text composer in Slack UI, end-users can remove the link this way:
<img src="https://user-images.githubusercontent.com/19658/194451197-0ae4316b-1a5e-4019-850f-56fe6bdc7a28.gif" width=400 />

However, there is no option to disable the rich text formatting for the entire Slack workspace systems.

>Also could I ask if there are documentation for java more details explanation on how to use those functions please?
I wish to have a better understanding of usage of java slack library code for the sample u just shared
>What's the meaning of block here please? block txt vs the normal txt any difference?

Indeed, before jumping into Java code, utilizing Block Kit and Slack text message formatting may require good understanding of the foundation first. In the Java SDK document site, we have this page explaining how to compose a message using the SDK: https://slack.dev/java-slack-sdk/guides/composing-messages So, checking the page is a good starting point.

Also, the page has many links to the documents under api.slack.com site. Reading those pages should be helpful for learning how to use the platform in general.

**Comment by MING-LI** [comment]
actually the message source is automated machine code generated and then get relayed by Java instead of manually input by user.

**Comment by seratch** [comment]
Your understanding should be correct. Sorry for the inconvenience here. When the link can be present in the Slack client UI while the text in message data is plain, there is no way to disable it for now. The behavior can be revisited in the future, though. As for the feedback on the Slack client apps, I'm sorry for bothering you but please share it using `/feedback` or https://my.slack.com/help/requests/new instead.

**Comment by MING-LI** [comment]
Another issue now for line breaking after using the block syntax and test it out.
 .blocks(asBlocks(
        section(s -> s.text(plainText(pt -> pt
          .text("This is a *plain* text section block with a :cry: emoji.")
          .emoji(true)))
        )
      ))

I found the line break is weird now it go line breaks at column 70 char position or around?

**Comment by seratch** [comment]
I hear you but unfortunately there is no way to customize/adjust the width of blocks in the UI as of today. We've already received this feedback a lot in the past, but I cannot tell whether and when it can be enhanced.

**Comment by MING-LI** [comment]
Thus I understand this as the limitation of blocks (when using Block Kit ) for the .blocks ( )
if I do not use block , just use .text ( ) it will not have this width limitation from my experience currently

**Comment by seratch** [comment]
Thanks again for writing in here. I believe that all the questions are answered. Let me close this thread. If you have a new question, please feel free to open a new question issue.
