### ISSUE TITLE
setup of logger for slack java (logback / slf4j )

### ISSUE THREAD

**Issue by MING-LI** [slackapi/java-slack-sdk#1070]
By default following the example of slack web api, the dependencies like slf4j is necessary to include,
then it is needed to output and persist a log file in drive.

if there is any sample/documentation for slack logger setup for logging purpose both info or debug level (slf4j? or logback)
it could write a log file in a folder \log which the log folder is next to executable main program of .jar for sending msg to slack channel.

guess it needs an appender and config.xml (logback.xml) and add dependencies to pom file

got a main program and some threads will be generated by main function per message connection to be logged to a single logfile.

**Comment by hello-ashleyintech** [comment]
Hi, @MING-LI! Thank so much for writing in! 🎉 

We have [a "Use Logger" section](https://slack.dev/java-slack-sdk/guides/bolt-basics#use-logger) in our "Bolt Basics" guide within the Java SDK docs that touches on using either `logback-classic` or SLF4J with some code snippets. I hope this helps!

**Comment by MING-LI** [comment]
now logback dependencies setup in pom, but the log file doesnt show.

wonder what get wrong, I have try to use filewriter class of java which can write to the desired log destination to eliminate the without access rights factor.

 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.0</version>
        </dependency>

**Comment by WilliamBergamin** [comment]
Hi @MING-LI, there is an example of `logback` configuration in the[ java starter template](https://github.com/slack-samples/bolt-java-starter-template) this is what the [logback.xml file](https://github.com/slack-samples/bolt-java-starter-template/blob/main/src/main/resources/logback.xml) looks like.

I believe a [fileAdapter](https://logback.qos.ch/manual/appenders.html#FileAppender) may be required in order to log to a file.

Hopefully this helps you out 🗺️

**Comment by MING-LI** [comment]
Not sure what still missed out, still no progress
previously my post test should eliminate the write access by writing a test file out with test text inside.

Here is how my logback.xml looks:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property name="LOG_ROOT" value="C:/ABCtask/CDEmyslackjavaapp/logs" />
    <property name="LOG_FILE_NAME" value="slack_msg" />

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_ROOT}/${LOG_FILE_NAME}.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${LOG_ROOT}/${LOG_FILE_NAME}.%d{yyyy-MM-dd}.log</fileNamePattern>
            
            <maxFileSize>10MB</maxFileSize>
            
            <maxHistory>60</maxHistory>
            
            <totalSizeCap>10GB</totalSizeCap>
        </rollingPolicy>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="debug">
        <appender-ref ref="FILE" />
    </root>
</configuration>`


Here comes the pom.xml snippet:

`<dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>slack-api-client</artifactId>
            <version>1.24.0</version>
        </dependency>		
</dependencies>
<build>
		 ...other details etc...
</build>`

**Comment by seratch** [comment]
@MING-LI A few comments on your configuration:
* When you use logback, you don't need to have slf4j-simple. You can (and perhaps should) remove it.
* The latest version of logback is primarily compatible with slf4j-api 2.0. So, using the latest versions for your app may be safer. See also: https://github.com/slackapi/java-slack-sdk/issues/1034

I haven't checked your log configuration on my end but when you are stuck with logging, I generally recommend starting with the examples in the library website (logback-classic in this case) and then gradually modifying it.
