### ISSUE TITLE
Is there an equivalent to JS option installerOptions.directInstall: true ?

### ISSUE THREAD

**Issue by alejovazquezsplit** [slackapi/java-slack-sdk#1072]
Hello, is there a way to redirect the Slack app installations to the permissions screen so we don't have to click on the "Add to Slack" button every time?
Similar to the Javascript option `installerOptions.directInstall: true`

Thanks.

**Comment by srajiang** [comment]
Hey @alejovazquezsplit -  Yes, I believe in this SDK, the way to do this is by setting [this property](https://github.com/slackapi/java-slack-sdk/blob/4dbaaaca5ab74bcbae25c2b802a1e1a567dadff7/bolt/src/main/java/com/slack/api/bolt/AppConfig.java#L158) as false when you initialize your AppConfig. Something like this: 

```java
 AppConfig appConfig = AppConfig.builder()
            .signingSecret("secret")
            .clientId("123.123")
            .clientSecret("secret")
            .scope("app_mention:read,chat:write,commands")
            .oauthStartPath("/slack/oauth/start")
            .oauthCallbackPath("/slack/oauth/callback")
            .redirectUri("https://www.example.com/slack/outh/callback")
            .oauthCompletionUrl("https://wwww.example.com/thank-you")
            .oauthCancellationUrl("https://www.example.com/something-wrong")
            .oAuthInstallPageRenderingEnabled(false) // <---- try this
```

**Comment by alejovazquezsplit** [comment]
@srajiang that worked! Thanks!
