### ISSUE TITLE
Expired_trigger_id when I try to open modal after some time

### ISSUE THREAD

**Issue by KoNstaNtiNos26** [slackapi/java-slack-sdk#1078]
Hello @seratch . Sorry for delay, you beat me on about one day and closed this issue) but I haven't had any appropriate solution how to fix it yet. What I did
 - deleted all applications into workspace;
 - created one new application;
 - updated my dependencies (java bolt framework and java implementation for web socket specification) these I am using now
 ```
<dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>bolt-socket-mode</artifactId>
            <version>1.22.3</version>
 </dependency>
<dependency>
            <groupId>jakarta.websocket</groupId>
            <artifactId>jakarta.websocket-api</artifactId>
            <version>2.1.0</version>
            <scope>provided</scope>
</dependency>
<dependency>
            <groupId>org.glassfish.tyrus.bundles</groupId>
            <artifactId>tyrus-standalone-client</artifactId>
            <version>1.19</version>
</dependency>
```

I think you offered in [803 comment](https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180) to do these steps. Please let me know if there any another ways to think about why I have 'expired_id'

One more thing I should add is that invoking client().viewsOpen(request) method takes much more time that should be (about 5 sec). But why does it last so long?

_Originally posted by @KoNstaNtiNos26 in https://github.com/slackapi/java-slack-sdk/issues/1067#issuecomment-1290535793_

**Comment by seratch** [comment]
Hi @KoNstaNtiNos26, thanks for writing in.

>One more thing I should add is that invoking client().viewsOpen(request) method takes much more time that should be (about 5 sec). But why does it last so long?

This is so unusual. Perhaps, your infra may have proxy server or something similar. I would suggest running your app in a different infra to narrow the issue down (if it's possible).

With given information, I am unable to suggest anything further.  I hope you will figure the cause of your issue out soon.

**Comment by KoNstaNtiNos26** [comment]
thank you, @seratch ! I hope too)
