### ISSUE TITLE
Calling App.message() will overwrite the previous App.message()

### ISSUE THREAD

**Issue by Arxing** [slackapi/java-slack-sdk#1084]
example:

```java
App app = new App();
app.message("pattern1", (event, ctx) -> {
    // block1
});
app.message("pattern2", (event, ctx) -> {
    // block2
});
```
As shown in the above code, "pattern1" will be overwritten by "pattern2" and become invalid.

**Comment by seratch** [comment]
Hi @Arxing, thanks for taking the time to report this issue plus sharing a possible solution for it! Regarding the implementation, I may come up with a bit different approach but either way, the issue needs to be fixed in the next release.
