### ISSUE TITLE
Flood of S3 object metadata not found logs for bot/EABC123-none

### ISSUE THREAD

**Issue by gh-gonzo** [slackapi/java-slack-sdk#1092]
I have a big enterprise grid user, which gives me a flood of logs (hundreds of logs daily). I suppose it shows me that Bolt tries to find if it's an enterprise-wide installation. But is there a reason why it's logged in INFO mode?

```
c.s.a.b.s.b.AmazonS3InstallationService  :
Amazon S3 object metadata not found (key: bot/EABC123-none, AmazonS3Exception:
com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: ...; S3 Extended Request ID: ...; Proxy: null), S3 Extended Request ID: ...)
```

If I understand things correctly, there is no error on my side, and this is normal behavior. Am I right? Can I disable this behavior safety? Why is it working like that? Is there any reason for so excessive logging in INFO mode?

**Comment by seratch** [comment]
Hi @gh-gonzo, thanks for sharing this. Indeed, this does not need to be info-level. We will improve this in future releases.
