### ISSUE TITLE
Persisting data during the OAuth flow in Java app

### ISSUE THREAD

**Issue by rishisaraf11** [slackapi/java-slack-sdk#1095]
Description
We want to map the slack team id with our user id once the slack installation is done.  Currently, we are using AmazonS3InstallationService as a post-installation hook.   We get installation information in saveInstallerAndBot however we don't know how to map slack team id with our user id. To achieve that we want to pass our user context when the user is clicking on our slack install  URL i.e https://xxxxx/messaging/slack/install.  Found this [document](https://slack.dev/node-slack-sdk/oauth#persisting-data-during-the-oauth-flow) how to do it on nodejs however I am not getting how to achieve the same in it in java. Currently, we are using the below SDK version.

```xml
<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt</artifactId>
    <version>1.8.1</version>
</dependency>
```

**Comment by seratch** [comment]
Hi @rishisaraf11, thanks for asking the question! With this Java SDK, you can customize the following callbacks and service layer for the purpose:
* The most relevant part only: [App#oauthPersistenceCallback​(OAuthV2SuccessPersistenceCallback persistenceCallback)](https://oss.sonatype.org/service/local/repositories/releases/archive/com/slack/api/bolt/1.27.1/bolt-1.27.1-javadoc.jar/!/com/slack/api/bolt/App.html#oauthPersistenceCallback(com.slack.api.bolt.service.builtin.oauth.OAuthV2SuccessPersistenceCallback))
* A bit broader part to override: [App#oauthCallback​(OAuthV2SuccessHandler handler)](https://oss.sonatype.org/service/local/repositories/releases/archive/com/slack/api/bolt/1.27.1/bolt-1.27.1-javadoc.jar/!/com/slack/api/bolt/App.html#oauthCallback(com.slack.api.bolt.service.builtin.oauth.OAuthV2SuccessHandler))

Also, the internal code that handles the OAuth flow callback is [here](https://github.com/slackapi/java-slack-sdk/blob/v1.27.1/bolt/src/main/java/com/slack/api/bolt/service/builtin/DefaultOAuthCallbackService.java#L120-L128).

I hope this was helpful to you.

**Comment by rishisaraf11** [comment]
@seratch  thanks reply. Can you let me know how I pass the context of my user(like userId our of our application) when navigating user to install page. Once installation is done we need this userId so that we can map our userId with slack teamId

**Comment by seratch** [comment]
@rishisaraf11 
>Can you let me know how I pass the context of my user(like the userId of our application) when navigating the user to the install page?

This is not feasible in a simple way. The only approach that I can suggest is:
* Ask your user to go through [Sign in with Slack](https://slack.dev/java-slack-sdk/guides/sign-in-with-slack) first
* Save the user ID in browser cookie as a kind of state
* Ask your user to go through the main OAuth flow to install your app

I know that this may be suitable for your use case but without "signing in with Slack" first, your `/slack/install` endpoint is unable to know who the visitor is.

**Comment by rishisaraf11** [comment]
@seratch I found one hack. Let me know if it looks ok to you.


Set cookie value on install handler.  our install app will orgId as query param which then can be access in doGet

```
@WebServlet("/slack/install")
public class SlackOAuthInstallController extends SlackOAuthAppServlet {
    public SlackOAuthInstallController(App app) {
        super(app);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        Map<String, String[]> parameterMap = req.getParameterMap();
        if (parameterMap.get("orgId") != null) {
            Cookie cookie = new Cookie("orgId", parameterMap.get("orgId")[0]);
            resp.addCookie(cookie);
        }
        super.doGet(req, resp);
    }
}

```
Now retrieve the cookie value on oauthPersistenceCallback

```
app.oauthPersistenceCallback(new OAuthV2SuccessPersistenceCallback() {
            @Override
            public void handle(Arguments args) {
                String cookiesHeader = args.getRequest().getHeaders().getFirstValue("cookie");
                List<HttpCookie> cookies = HttpCookie.parse(cookiesHeader);
                Optional<HttpCookie> httpCookie = cookies.stream().filter(cookie -> cookie.getName().equalsIgnoreCase("orgId")).findAny();
                if (httpCookie.isPresent()) {
                    logger.info("Got orgId from cookie" + httpCookie.get().getValue());
                }

            }
        });
```

**Comment by seratch** [comment]
@rishisaraf11 I don't think that it's secure enough to blindly trust the query string value. That being said, as long as the approach works for your specific use case plus you're okay with the security risk, it would be fine. Thanks for sharing this! Would you mind closing this issue now?
