### ISSUE TITLE
How to send an HTTP response when using app.oauthPersistenceCallback

### ISSUE THREAD

**Issue by rishisaraf11** [slackapi/java-slack-sdk#1098]
When calling oauthPersistenceCallback during installation, though the installation happens successfully but URL doesn't get redirected to OAuth completion URL and it stuck to below URL. Below is my code for oauthPersistenceCallback

https://XXX/slack/oauth_redirect?code=2447194999527.4425044381062.4781a36ed78b69cd472e3820e44c76b836acdfbe34ded25363366933d5a84b0e&state=4420b3fb-766c-4d84-b371-c3a007b8ad7d

```
 app.oauthPersistenceCallback(new OAuthV2SuccessPersistenceCallback() {
            @Override
            public void handle(Arguments args) {
                String cookiesHeader = args.getRequest().getHeaders().getFirstValue("cookie");
                List<HttpCookie> cookies = HttpCookie.parse(cookiesHeader);
                Optional<HttpCookie> httpCookie = cookies.stream().filter(cookie -> cookie.getName().equalsIgnoreCase("orgId")).findAny();
                if (httpCookie.isPresent()) {
                    saveSlackInstallationInfo(args, httpCookie);
                }
            }
        });
```

**Comment by seratch** [comment]
Hi @rishisaraf11, the arguments object provides the response object for the URL access. Your callback is responsible to set a valid status, headers, and body. See the default implementation https://github.com/slackapi/java-slack-sdk/blob/v1.27.1/bolt/src/main/java/com/slack/api/bolt/service/builtin/oauth/default_impl/OAuthV2DefaultSuccessHandler.java#L137-L152 to learn how to do it.
