### ISSUE TITLE
Spring boot + SocketModeApp.start() documentation request

### ISSUE THREAD

**Issue by caseyg-ronin** [slackapi/java-slack-sdk#1099]
Using spring-boot and following the slack documentation for socket mode creates a situation where `SlackModeApp.start()` blocks the main thread and stops spring from initializing. Things can mostly still work in this situation, but `SIGINT` and `SIGNTERM` will also fail/block due to a synchronization block in spring's shutdown code. The (now) obvious solution is to use `SlackModeApp.startAsync()`. This request is to update the slack socket mode documentation and spring documentation to call this out.

### The page URLs

* https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt-socket-mode
* https://github.com/slackapi/java-slack-sdk/blob/main/README.md
* https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt#ok-what-about-spring-boot

Thanks!

**Comment by caseyg-ronin** [comment]
> Based on [this doc](https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#spring-boot) that explain how to run Bolt with spring boot, it seems like we instruct to use SpringApplication.run(Application.class, args); instead of SlackModeApp.start(), but this is for an HTTP based application.

That linked doc doesn't use socket mode. Also, the `SpringApplication.run(..)` and `SocketModeApp.start()` are performing completely different operations... one starts spring, the other starts the slack socket mode application.

> A common use case is to run a Bolt socket-mode along a jetty or spring boot app in order to handle Oauth requests [here is an example of this](https://github.com/slack-samples/bolt-java-starter-template/blob/main/src/main/java/OAuthMain.java) in our template project.

This is kinda my point exactly... that app [uses SocketModeApp.startAsync();](https://github.com/slack-samples/bolt-java-starter-template/blob/main/src/main/java/OAuthMain.java#L25) because it needs to run the slack socket mode app and _not_ block the main thread so that the rest of the application can function. All I'm recommending is that you update your documentation to mention that if your application needs to do anything other than just run slack in socket mode, you probably want to use `startAsync()` instead of `start()`.

My specific use case is that I am building a slack bot to do perform build and ci/cd tasks and I want to use socket mode so that I don't have to punch holes through my firewall. On top of that, our company standard is to use kotlin + spring-boot so that all of our apps run consistently and can take advantage of spring's ecosystem for things like externalized configuration, health checks, dependency-injection, etc.

**Comment by WilliamBergamin** [comment]
@caseyg-ronin thanks for the additional information, I miss-understood the initial context of the issue

We could potentially add a side note to the[ `socket-mode`](https://slack.dev/java-slack-sdk/guides/socket-mode) documentation that explicitly explains the difference between `start` and `asyncStart`

Big thank you for sharing your use case, it is always great to get incite on how projects are getting used 💯
