### ISSUE TITLE
What's the difference between Installer and Bot and how to implement InstallationService?

### ISSUE THREAD

**Issue by joarobles** [slackapi/java-slack-sdk#1104]
I'm trying to implement `InstallationService` in order to store tokens using Spring Data JPA and I found the method `saveInstallerAndBot(Installer installer)`: 

1. What's the difference between `Installer` and `Bot` classes? 
2. Why does an Installer also have `Bot` methods such as `getBotAccessToken()`, and a `toBot()` method? 
3. Should I persist them separated or as a single entity?

Thanks and happy new year!

**Comment by seratch** [comment]
Hi @joarobles, thanks for asking the question!

Perhaps, checking [this part of the built-in middleware](https://github.com/slackapi/java-slack-sdk/blob/v1.27.2/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java#L115-L262) should be helpful to understand how those methods are used.

>What's the difference between Installer and Bot classes?

Your app can have only one bot token per a workspace. Contrarily, when your app receives user tokens as well, those tokens can exist a lot for a single workspace. If your app uses only bot token permissions, you don't need to have database tables for both Bot and Installer. Having either works. If you don't need to store the user who installed the app, having bot data would be much simpler.

When you have both bot and user scopes, I'd highly recommend having two tables. It's technically possible to have duplicated bot tokens in user installation table rows. But the query to fetch the latest bot token won't be intuitive and efficient.

>Why does an Installer also have Bot methods such as getBotAccessToken(), and a toBot() method?

Each installation can have a bot token and a user token (although the bot token is always the same). Installer objects can have both.

>Should I persist them separated or as a single entity?

Either is fine but my recommendation is to have separate entities for bot installations and user scope installations. Also, considering that you're going with Spring Data JPA, my suggestion should be easier to implement and maintain.

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by joarobles** [comment]
Hi @seratch! Thanks for your answer, it's much clear now..

One question remains: I was looking at the `DefaultInstaller` class that implements the `Installer` interface. Since the installer represents a regular user that grants OAuth permissions under the `user` scope, why does it have bot attributes as well such as `botId` and `botAccessToken`?

Moreover, the `InstallationService` interface defines a single `saveInstallerAndBot` method, even when the requested scopes are only bot scopes.

**Comment by seratch** [comment]
@joarobles 
> I was looking at the DefaultInstaller class that implements the Installer interface. Since the installer represents a regular user that grants OAuth permissions under the user scope, why does it have bot attributes as well such as botId and botAccessToken?

When your app's installation has any of the bot token scopes, the installation can always have a bot token. This is the same even when the same bot scopes are already granted. Thus, the `Installer` object can have bot-related properties such as bot_id and bot token. Having at least one bot scope (e.g., `commands` for interactivity, shortcuts, slash commands at least) is generally recommended for any apps as those scopes will eventually be necessary for most use cases.

>Moreover, the InstallationService interface defines a single saveInstallerAndBot method, even when the requested scopes are only bot scopes.

If your app wants to save only the bot data model, it's totally fine. You can save data compatible with the bot interface, and your find method can support only bot interface data. The Bolt framework provides the full data anyways.
