### ISSUE TITLE
InstallationService custom implementation

### ISSUE THREAD

**Issue by joarobles** [slackapi/java-slack-sdk#1111]
I'm trying to implement `InstallationService` to persist installations using Spring JPA. I'm having problems with the `find...()` methods because it's not clear enough how the parameters order should be considered.

```java
    /**
     * Returns a bot permission data if exists.
     */
    Bot findBot(String enterpriseId, String teamId);

    /**
     * Returns a user permission data if exists.
     */
    Installer findInstaller(String enterpriseId, String teamId, String userId);
```

Should I look for bots and installations with all the given parameters being present? All parameters are nullable? If that's the case, what should I do to handle them?

I've seen the code in `FileInstallationService` and `AmazonS3InstallationService` but it seems to be plenty of `if` conditions that I could not extrapolate to a rule.

**Comment by seratch** [comment]
Hi @joarobles, thanks for asking the question!

>Should I look for bots and installations with all the given parameters being present? All parameters are nullable? If that's the case, what should I do to handle them?

This depends on how your app installation flow looks like.

If your app requests **only bot scopes**, you don't need to save installer data and implement the `findInstaller()` method. So, implementing only bot-related methods is totally fine! but if you want to keep track of installation history with the installing users, having both can be useful for some purpose.

If your app receives **both bot and user tokens**, implementing both is recommended, but it's optional. If you have `findInstaller()` method, the `context` object may provide a relevant user token for a user associated with the event request.

If you're comfortable checking the framework code more, reading https://github.com/slackapi/java-slack-sdk/blob/v1.27.3/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/MultiTeamsAuthorization.java is the best way to understand how InstallationService can be used in the Bolt framework.

I hope this was helpful to you!

**Comment by seratch** [comment]
Forgot to reply to the nullable or not topic. Checking Python SDK's [this code](https://github.com/slackapi/python-slack-sdk/blob/v3.19.5/slack_sdk/oauth/installation_store/sqlalchemy/__init__.py#L35-L112) can be the most helpful at this moment (you don't need to follow this exactly but checking this should be helpful). As you already notice (thanks for the comment!), RDB support is on our long-term roadmap: https://github.com/slackapi/java-slack-sdk/issues/347 Our SDK team will do its best to add the module as early as possible.
