### ISSUE TITLE
"AppHomeOpenedEvent" request view is null even after home page contents rendered

### ISSUE THREAD

**Issue by se22as** [slackapi/java-slack-sdk#1115]
MY REQUIREMENT: My app has the Home tab and Messages tab turned on.  I would like to render a welcome message in the Messages tab when the user goes to the App Home for the FIRST time.

BACKGROUND: Slack documentation says that the first time the `AppHomeOpened `event is called, the `request's event` will have a NULL "`view`" as no home page UI has been rendered.  Subsequent `AppHomeOpened `events WILL have a `view `on the `requests event` as the home page has been rendered.  I have also confirmed this with Slack Support 

ISSUE: I am seeing that `req.getEvent().getView()` is null on subsequent `AppHomeOpened `events.  I.e. when i go to the app home on the 2nd/3rd/4th time etc.   This does not happen all the time, but it definitely occurs. As a result, we post the welcome message more than once which is WRONG.   Slack support have said my code logic is correct and they can not reproduce any issue in the JavaScript Bolt SDK and therefore suggested I reach out to the Java Bolt SDK to see if there is anyone else seeing this issue. 

QUERY: Is anyone else seeing this behaviour?

```
app.event(AppHomeOpenedEvent.class, (req, ctx) -> {

	try {
		app.executorService().submit(() -> {
			try {
				....
	

				// if home page markup has never been invoked before, post a welcome message in the messages tab
				if (req.getEvent().getView() == null) {
					....
				}


				// generate the home page markup and publish it using
				//ctx.client().viewsPublish(r -> r.token(token).userId(userId).viewAsString(viewAsString));
				
			} catch (....) {
				....
			}
		});
	} catch ......
	}

	return ctx.ack();
});

```

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

(Paste the output of `mvn dependency:tree | grep com.slack.api` or `gradle dependencies | grep com.slack.api`)

slackBoltVersion = '1.27.1'

#### Java Runtime version

$ java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

Windows 10 Pro
19044.2486
Windows Feature Experience Pack 120.2212.4190.0

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Have your application running
2. In Slack click on your application, the app home is rendered
3. Debugging the code shows my "AppHomeOpened" event is fired
4. view the contents of the request in the "AppHomeOpened" event, see that the event.view is null
5. Go to another channel and then back to the app home
6. Debugging the code shows my "AppHomeOpened" event is fired
7.  view the contents of the request in the "AppHomeOpened" event, see that the event.view is null  THIS IS WRONG, it should now have a view

#### Expected result:

(Tell what you expected to happen)

After the very first call into AppHomeOpened event handler, the `req.getEvent().getView()`  should NOT be null

#### Actual result:

After the very first call into AppHomeOpened event handler, the `req.getEvent().getView()`  IS null

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by se22as** [comment]
I think I have logged this question in error. 

When i go to the Home tab, the req.event.view  is not null
When i go to the Messages tab, the req.event.view  is null

I am wondering if when i see the error i am going directly to the messages tab, not the home tab

**Comment by seratch** [comment]
Hi @se22as, thanks for asking the question!

If your app enables the messages tab too, there are two types of app_home_opened events.

The events can be delivered when an end-user visits the messages tab as well. So, to know which tab is opened, you can check the `tab` property in its payload: https://github.com/slackapi/java-slack-sdk/blob/v1.27.3/slack-api-model/src/main/java/com/slack/api/model/event/AppHomeOpenedEvent.java#L32 

The string can be either "messages" or "home" in your use case. Rather than trying to know the user's current state by checking only the existence of `view` in a payload, you can utilize the `tab` property for it.

I hope this helps.

**Comment by se22as** [comment]
Thank you for that comment. I have added in checking the tab first.   I shall see if that resolves the issue or if we are still encountering a null view when the appHomeOpened event occurs on the home tab

**Comment by seratch** [comment]
👋 Did you confirm the solution works for you by chance? We will close this issue after waiting for your response for a while.
