### ISSUE TITLE
A request toward an invalid webhook URL get 200 OK response (expected: 302 redirection)

### ISSUE THREAD

**Issue by tsasaki609** [slackapi/java-slack-sdk#1122]
### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version
com.slack.api:slack-api-client:1.27.3

#### Java Runtime version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Homebrew (build 17.0.5+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.5+0, mixed mode, sharing)

#### OS info
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64

#### Steps to reproduce:
Submitting against a dummy webhook will result in a response with code 200 instead of an error code.

```
final var slack = Slack.getInstance();
final var response = slack.send("https://hooks.slack.com/services/dummy/dummy", Payload.builder().text(message.toString()).build());
if(response.getCode() != 200) {
```

#### Expected result:
Error codes should be returned.

#### Actual result:
Code 200 will be returned.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @tsasaki609, thanks for reporting this issue! We will resolve the issue in the next release.

**Comment by seratch** [comment]
>Error codes should be returned.

I hear you that error code is easier to handle, but the server-side returns 302 status in this case. So, this SDK still does not return any error code even after the forthcoming fix on this issue.

**Comment by tsasaki609** [comment]
> but the server-side returns 302 status in this case.

Thanks for the advice, I will handle it appropriately.
