### ISSUE TITLE
Problems verifying slack requests in spring boot application

### ISSUE THREAD

**Issue by pgtaboada** [slackapi/java-slack-sdk#1124]
I am test-driving a slack integration for our spring boot application. The java sdk really looks nice, but I am running into already known (but not documented) issues and hitting a wall when it comes to the verification.

The known but not documented problem is the one described here:

https://github.com/slackapi/java-slack-sdk/issues/543

To solve this known issue I simply created my own Controller as follows:

```java
@Controller
public class SlackEventsController {
    @Autowired
    private App app;
    private SlackRequestParser requestParser;

    @PostConstruct
    public void PostConstruct() {
        this.requestParser = new SlackRequestParser(app.config());
    }

    @RequestMapping(value = "/mvc/slackEvents", method = RequestMethod.POST)
    protected void doPost(@RequestBody String requestBody, HttpServletRequest req, HttpServletResponse resp) throws IOException {
        SlackRequestParser.HttpRequest rawRequest = SlackRequestParser.HttpRequest.builder()
                .requestUri(req.getRequestURI())
                .queryString(QueryStringParser.toMap(req.getQueryString()))
                .headers(new RequestHeaders(toHeaderMap(req)))
                .requestBody(requestBody)
                .remoteAddress(req.getRemoteAddr())
                .build();
        final Request<?> slackReq = requestParser.parse(rawRequest);
        if (slackReq != null) {
            try {
                Response slackResp = app.run(slackReq);
                ServletAdapterOps.writeResponse(resp, slackResp);
            } catch (Exception e) {
                resp.setStatus(500);
                resp.setContentType("application/json");
                resp.getWriter().write("{\"error\":\"Something is wrong\"}");
            }
        } else {
            ServletAdapterOps.writeResponse(
                    resp,
                    Response.builder()
                            .statusCode(400)
                            .body("Invalid Request")
                            .build());
        }
    }
}
```

It pretty much does exactly what `SlackAppServlet` and `SlackAppServletAdapter` do. 

The Slack-App is just waiting for a button interaction to happen, no magic here.

```java
    @Bean
    public App initSlackApp() {
        final App app = new App(
                AppConfig.builder()
                        .signingSecret("mysigningsecret")
                        .singleTeamBotToken("xoxb-mybottoken")
                        .build()
        );
        app.blockAction("deleteStacktrace", (req, ctx) -> {
            final BlockActionPayload payload = req.getPayload();
            for (BlockActionPayload.Action action : payload.getActions()) {
                LOG.info("ActionId: {}", action.getActionId());
                LOG.info("ActionTs: {}", action.getActionTs());
                LOG.info("ActionInitialChannel: {}", action.getInitialChannel());
                LOG.info("ActionSelectedChannel: {}", action.getSelectedChannel());
                LOG.info("ActionBlockId: {}", action.getBlockId());
            }
            return ctx.ack();
        });
        return app;
    }
```
It actually not significantly more than the hello world example provided online.

As soon as I click on a button on the fancy interaction in slack...

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1474196/223235813-3e846192-9172-47e4-880e-89529130530e.png">

... I always get the error

`Invalid signature detected - v0=00d71285382bd0acb86e91e9fcc9bb16d4446859a59bfe8ff0029e384e6492d6`

I checked and rechecked, regenerated, checked and rechecked my signingSecret. I stepped through the code and I am really generating a completely different signature.

Any tipps on how to fix the verification?

**Comment by seratch** [comment]
Hi @pgtaboada, thanks for asking the question! 

Unfortunately, Spring Boot's `@Controller` style does not work for Slack app endpoints. The reason behind this is that the proper request signature verification for Slack events requires the access to the raw request body string to generate a signature to compare. When using Spring Boot's usual controller mechanism, the framework automatically parses the raw body data for you and after that, there is no way to read the raw data outside the framework.

For this reason, as mentioned in the document [here](https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#spring-boot), you need to use `@WebServlet` style instead.

I hope this helps.

**Comment by aaronq** [comment]
@seratch is there an example for setting up a slack app with spring boot that is in socketmode?

i basically took the non socketmode example, and converted it to use socketmode and started the the app asynchronously at the end.

this seems to work, and is actually receiving response from slack when an event is triggered. we don't have anything else setup, just this bean which i guess just starts up in socket mode and connects to appropriate server.

just curious if there's any issues with following this approach or if there is a better way of doing this.

**Comment by seratch** [comment]
Hi @aaronq, as long as your code properly manages the SocketModeApp instance as a component, I don't see any issues with your approach.

**Comment by aaronq** [comment]
> Hi @aaronq, as long as your code properly manages the SocketModeApp instance as a component, I don't see any issues with your approach.

Thanks for responding @seratch... here's the snippet of our code that is working for us:
```
@Bean
public App initSlackApp() throws Exception {
  App app = new App(AppConfig.builder()
          .singleTeamBotToken(botToken)
          .slack(Slack.getInstance())
          .build());

  app.command("/hello", (req, ctx) -> {
      logger.info("Received a slack command!");
      return ctx.ack(":wave: Hello " + req.getPayload().getUserName() + "!");
  });

  SocketModeApp socketModeApp = new SocketModeApp(appToken, app);
  socketModeApp.startAsync();
  return app;
}
```
Just wanted to see if you spot any red flags by doing this. This successfully inits the app when our spring boot application starts up and will receive all the msgs from Slack.

**Comment by seratch** [comment]
@aaronq As long as the bean is singleton, I don't see any issues. A minor sugggestion is that you may want to call `SocketModeApp#close()` when destroying the compoment (`@PreDestroy` if I remember correctly). With that, your app can safely close its underlying WebSocket connection. That being said, missing the close() method call won't cause any critical issues.
