### ISSUE TITLE
Chained setters

### ISSUE THREAD

**Issue by gh-gonzo** [slackapi/java-slack-sdk#1125]
Firstly, thank you for maintaining Java Slack SDK 🙏 It's such a simplification to have a statically typed interface for all those HTTP requests, automatic installation handling, etc.

Here's my idea to make it even better.

I've been using Java Slack SDK fluent API for a long time and stopped to be a fan of it. In theory, it's very readable.
```java
var response = slack.methods(token).chatPostMessage(req -> req
  .channel("#random")
  .text(":wave: Hi from a bot written in Java!"));
```
But in practice, automatic IDE formatting makes it look a lot worse.
```java
var response =
    slack
        .methods(token)
        .chatPostMessage(
            req ->
                req.channel("#random").text(":wave: Hi from a bot written in Java!"));
```
Note it was a very simple example. **Complex views are really hard to read.** Moreover, I have trouble inventing unique names for all those lambda parameters.

It's worth noticing that recent years have brought a lot of misuse of _Builder Pattern_ to the Java community. Originally, it was primarily used to simplify the involved conditional construction of immutable objects. Nowadays, it's often misused as a remedy for Java's lack of named and default method parameters.

**Before _Builder Pattern_ madness began, there was a simple convention for fluent APIs in Java. Setters returned `this` instead of `void`.** If Slack API employed this convention, we could write the above request this way.

```java
var response =
    slack
        .methods(token)
        .chatPostMessage(
            new ChatPostMessageRequest().setChannel("#random").setText(":wave: Hi from a bot written in Java!"));
```
This version is especially handy in complex views because IDE formats it better, and we don't have to be creative with inventing names for all those lambda parameters.

**I propose to make all `@Data` classes in Java Slack SDK return `this` instead of `void`.** It may sound like an involving task, but it's, in fact, easy to accomplish with just one line added to Lombok's global settings file.
```properties
lombok.accessors.chain = true
```

**Comment by seratch** [comment]
Hi @gh-gonzo, thanks for writing in with details!

For your use case, the builder interface is already available.

```java
Slack.getInstance().methods(token)
    .chatPostMessage(ChatPostMessageRequest.builder().channel("#random").text(":wave: Hi from a bot written in Java!").build());
```

Can you try it out? I hope this helps!

**Comment by gh-gonzo** [comment]
Sure. I know it's subjective, but for many people, chained setters look cleaner than this - no need to call extra methods like `builder()` and `build()`.

**Comment by seratch** [comment]
Thanks for your reply but we are not changing the setters this time. If there is nothing else to discuss here, would you mind if  we close this issue now?

**Comment by gh-gonzo** [comment]
No problem.
