### ISSUE TITLE
MessageMeEvent does not have user property

### ISSUE THREAD

**Issue by cprayer** [slackapi/java-slack-sdk#1128]
When I receive a messageMeEvent from Slack Bolt, the ```username``` field is always null.

![image](https://user-images.githubusercontent.com/24709996/226169611-9d268cbe-0ab8-4841-8ba1-2343c491ce92.png)

[In messageMeEvent docs](https://api.slack.com/events/message/me_message), ```user``` field exists.
![image](https://user-images.githubusercontent.com/24709996/226168804-4b94b7f1-c9d9-4d2b-88da-7ad4284d7bd5.png)

However, in the slack-api-model 1.27.3 version com.slack.api.model.event.MessageMeEvent, there is a ```username``` field. I think during the process of deserialization, the field names are different so the mapping is not functioning correctly.

#### The Slack SDK version
1.27.3

#### Expected result:
When I receive a messageMeEvent from Slack Bolt, the ```username``` field is always null.

#### Actual result:
I want to get a user id from messageMeEvent

**Comment by seratch** [comment]
Hi @cprayer, thanks for taking the time to report this issue. It seems that `user` property is added recently. We will update the model class in the next release.

**Comment by cprayer** [comment]
Thank you for your response!
