### ISSUE TITLE
File Download is Corrupted - Spring Boot App

### ISSUE THREAD

**Issue by arunt4ever** [slackapi/java-slack-sdk#1142]
Unable to download the file using Bot Token or User Token although in some cases User token is able to download the file! 

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`


```

#### The Slack SDK version

(Paste the output of `mvn dependency:tree | grep com.slack.api` or `gradle dependencies | grep com.slack.api`)
[INFO] +- com.slack.api:bolt-jakarta-servlet:jar:1.29.1:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.29.1:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.29.1:compile
[INFO] |  +- com.slack.api:slack-app-backend:jar:1.29.1:compile
[INFO] |  \- com.slack.api:bolt:jar:1.29.1:compile

#### Java Runtime version

(Paste the output of `java -version`)
openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
ProductName:            macOS
ProductVersion:         13.3.1
BuildVersion:           22E261
Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. I am unable to download the file using the Bot Token even though the token is having the following permission
2.[files:read](https://api.slack.com/scopes/files:read)
3.[files:write](https://api.slack.com/scopes/files:write)
4.But I am able to download the file using the User Token with the same permission

#### Expected result:

I wanted to download the file from slack when user clicks an action the message shortcut using the Bot Token but its not working as intended in the example and documentation

#### Actual result:

1. Downloaded file is corrupted when I use the Bot Token to download the file from the my own user direct message.
2. But when I am using the User Token its working.

**Comment by seratch** [comment]
Hi @arunt4ever, thanks for asking the question!

When you updoad a file to somewhere your app's bot user does not have the access (e.g., a user's single person DM), any app's bot user and its tokens (xoxb- prefixed ones) cannot retrieve the file's metadata and content. Thus, the situation only the user token works in the scenario is expected. If the user shares the file in a public/private channel where the app's bot user is a member of, then your bot token can access the file content.

If your app needs to access the files visible only to a specific user, using the user's user token (xoxp-) is the right way to do so. If your app needs to access many people's private files, each of those people needs to go through OAuth flow to grat user scopes like files:read, and your app needs to securely stores all those user tokens and use the tokens appropriately.

I hope this helps.

**Comment by arunt4ever** [comment]
Hi @seratch , Thank you for your response! 
Maintaining user token (xoxp-) for every user will not work! 

I will try to ask the end-users to directly upload files to Bot's DM to access the files.
