### ISSUE TITLE
Redirect User from Slash Command to App Home Tab

### ISSUE THREAD

**Issue by arunt4ever** [slackapi/java-slack-sdk#1159]
Hi, 

I am not able to find any example on how to redirect the user from the slash command to the App's message tab using deep link! 

https://api.slack.com/reference/deep-linking#open_app_home

Below is the example I have but I couldn't figure out the next step! Could you please publish API example on how to use the deep link? 

//  Handle slash command
        app.command("/homeTab", (req, ctx) -> {
            System.out.println(req.getPayload());
            // Construct the URL to your external app
            String APP_ID = req.getPayload().getApiAppId();
            String TEAM_ID = req.getPayload().getTeamId();
            String messageTabDeepLinkUrl = "slack://app?team="+TEAM_ID+"&id="+APP_ID+"&tab=home\n";
            return ctx.ack();
        });

**Comment by WilliamBergamin** [comment]
Hi @arunt4ever thanks for witting in 💯 

Unfortunately I don't think "redirecting" a user when they execute a slash command is possible, the slash command invocation will execute the server side code present in your event handler

What could be done instead is posting an [Ephemeral Message](https://api.slack.com/methods/chat.postEphemeral/code) that contains the [app home deep link](https://api.slack.com/reference/deep-linking#open_app_home) 

This could look ruffly like this
```java
// Handle slash command
app.command("/homeTab", (req, ctx) -> {
    System.out.println(req.getPayload());
    // Construct the URL to your external app
    String APP_ID = req.getPayload().getApiAppId();
    String TEAM_ID = req.getPayload().getTeamId();
    String messageTabDeepLinkUrl = "slack://app?team="+TEAM_ID+"&id="+APP_ID+"&tab=home\n";
    var logger = ctx.logger;
    try {
         var event = req.getEvent();
         // Call the chat.postEphemeral method using the built-in WebClient
         var result = ctx.client().chatPostEphemeral(r -> r
              // Payload message should be posted in the channel where original message was heard
              .channel(event.getChannel())
               // The user the message should appear for
               .user(event.getUser())
               .text(messageTabDeepLinkUr)
           );
         logger.info("result: {}", result);
    } catch (IOException | SlackApiException e) {
         logger.error("error: {}", e.getMessage(), e);
    }
    return ctx.ack();
});
```

**Comment by arunt4ever** [comment]
Thank you @WilliamBergamin for your response! 

I was hoping that I will be able to call or trigger that "slack://" url without user interaction so I can redirect the users from slash command "/messageTab" to the App Home message tab! 

Below is what I was able to come up after posting this question! Little different from your example but I think this works fine for me!  

```java
//  Handle slash command
app.command("/messageTab", (req, ctx) -> {
    ctx.logger.info("Received slash command: " + req.getPayload());
    // Construct the URL to your App Home Tab
    String APP_ID = req.getPayload().getApiAppId();
    String TEAM_ID = req.getPayload().getTeamId();
    String messageTabDeepLinkUrl = "slack://app?team=" + TEAM_ID + "&id=" + APP_ID + "&tab=messages";
    ctx.logger.info("messageTabDeepLinkUrl = " + messageTabDeepLinkUrl);
    return ctx.ack(SlashCommandResponse.builder()
            .blocks(asBlocks(
                    section(s -> s.text(markdownText(pt -> pt.text("Please upload file(s) from <" + messageTabDeepLinkUrl + "|App Home Message Tab>"))))
            ))
            .build());
});
```
