### ISSUE TITLE
Can we have an interface to extract user for slack events

### ISSUE THREAD

**Issue by smallufo** [slackapi/java-slack-sdk#1164]
Currently there are a lot of slack events (com.slack.api.model.event)
I hope there will be an interface , such as IUser : 
```
interface IUser {
  @NotNull
  String getUser();
}
```
And events with user field should implement this value , returning the user string.
It will make devs easy to track which events are related to user interactions.
Thanks.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ x] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

**Comment by seratch** [comment]
Hi @smallufo, thanks for sharing your idea!

Indeed, implementing something like `HasUserID` or `UserEvent` is a common practice in Java programming. However, the data structure of Slack's Events API is not so simple, which makes me hesitant to add such a feature at least in the short term. User IDs in Events API payloads can vary in terms of both their naming and meaning. For instance, user IDs can be labeled as user, user_id, actor_id, etc., and some events can have multiple user IDs. Some of the events may have both affected user_id and actor_id in the future. If it happens, simple `User`-related interface can be misleading. Also, we'd like to avoid having a few types of similar interfaces to cover those scenarios.

Also, I believe that an abstraction like `IUser` may not be particularly useful in most Bolt app development scenarios. You might need a simple and universal user data representation for your app's design. If that's the case, I recommend creating your own interface within your app and building its instance using the SDK's event data. Again, which property to pick up can vary among the events and sometimes it depends on your specific needs.

I hope this information is helpful to you.

**Comment by smallufo** [comment]
Got it . thank you.
