### ISSUE TITLE
(Set a clear title describing your idea)

### ISSUE THREAD

**Issue by Doni108108108** [slackapi/java-slack-sdk#1166]
(Describe your issue and goal here)

### The page URLs

(List the URLs to update here)

* https://slack.dev/java-slack-sdk/
* (examples in this repository)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by filmaj** [comment]
This seems like spam to me.. closing.
