### ISSUE TITLE
How to manually implement  /oauth/install & /oauth/callback function ?

### ISSUE THREAD

**Issue by smallufo** [slackapi/java-slack-sdk#1167]
Slack bolt api version 1.29.2

Because of slack bolt cannot work with [Spring Boot 3 + Spring Security] environment ( issue here  https://github.com/slackapi/java-slack-sdk/issues/1163  )

I tried to migrate my slack app to a stand alone app (run by main)
Single slack app works well . but I cannot successfully migrate oauth servlet ( extends SlackOAuthAppServlet ) to a standalone app : 

Before : 
```
@WebServlet("/slack/oauth/install")
class SlackOAuthInstallController(app: App) : SlackOAuthAppServlet(app)

@WebServlet("/slack/oauth/callback")
class SlackOAuthRedirectController(app: App) : SlackOAuthAppServlet(app)
```
It ran ok prior to spring boot 3

After : 
```
  @JvmStatic
  fun main(args: Array<String>) {
    val ctx = ClassPathXmlApplicationContext("bots.xml")

    val slackApp = ctx.getBean("slackApp") as App
    val oauthApp = (ctx.getBean("oauthApp") as App).apply {
      endpoint("GET", "/slack/oauth/completion") { _, _ ->
        Response.json(200, mapOf("message" to "Thanks!"))
      }
      endpoint("GET", "/slack/oauth/cancellation") { _, _ ->
        Response.json(200, mapOf("message" to "Something wrong!"))
      }
      endpoint(WebEndpoint.Method.GET, "/slack/oauth/install") { req: WebEndpointRequest, ctx: WebEndpointContext ->
        logger.info { "install : ${req.requestBodyAsString}" }
        TODO()
      }
      endpoint(WebEndpoint.Method.GET, "/slack/oauth/callback") { req: WebEndpointRequest, ctx: WebEndpointContext ->
        logger.info { "callback : ${req.requestBodyAsString}" }
        TODO()
      }
    }

    logger.info { "slackApp = $slackApp" }
    logger.info { "oauthApp = $oauthApp" }

    val apps = mutableMapOf(
      "/slack/events" to slackApp,
      "/slack/oauth" to oauthApp
    )

    val server = SlackAppServer(apps, 8080)
    server.start()
  }
```
Notice the 2 TODO() block , I don't know how to correctly implement the code.

The original `SlackOAuthAppServlet` builds request from HttpServletRequest , and execute request , writeResponse here : https://github.com/slackapi/java-slack-sdk/blob/25cd87ea9d08f5591a9114ca68d27e5aa3ff7d30/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackOAuthAppServlet.java#L33 

But the `endpoint()` accepts `WebEndpointRequest` , which is not connected to HttpServletRequest. How to correctly implement it ? Thank you.

Additional code : 
```
  @Bean
  fun oauthApp() : App {
    val config = AppConfig.builder()
      .singleTeamBotToken(botToken)
      .alwaysRequestUserTokenNeeded(true)
      .clientId(clientId)
      .clientSecret(clientSecret)
      .signingSecret(signingSecret)
      .scope(oauthScopes)
      .oauthInstallPath(SLACK_INSTALL_PATH)
      .oauthRedirectUriPath(SLACK_REDIRECT_URI_PATH)
      .oauthCancellationUrl("https://slack.com")
      .oauthCompletionUrl("https://google.com")
      .build()
    val installationService = FileInstallationService(config, "/tmp")
    val stateService = FileOAuthStateService(config, "/tmp")
    return App(config).apply {
      service(installationService)
      service(stateService)
      asOAuthApp(true)
    }
  }
```

Note : 
`SlackAppServer` cannot detect other `@WebServlet` , so it cannot load my old OAuth controllers. I think it can be a feature request.

Dependencies : 
```
<slack.version>1.29.2</slack.version>

    <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-jakarta-servlet</artifactId>
      <version>${slack.version}</version>
    </dependency>
    <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>slack-api-model-kotlin-extension</artifactId>
      <version>${slack.version}</version>
    </dependency>
    <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>slack-api-client-kotlin-extension</artifactId>
      <version>${slack.version}</version>
    </dependency>
    <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-jakarta-jetty</artifactId>
      <version>${slack.version}</version>
    </dependency>
```

**Comment by seratch** [comment]
Hi @smallufo, the endpoint registration you're trying to use is not for the OAuth flow handling. The feature is supposed to be used for serving more general HTTP endpoints. 

Here is a complete Spring Boot 3 example app: https://github.com/slackapi/java-slack-sdk/blob/main/bolt-spring-boot-examples/spring-boot-3/src/main/java/example/SlackAppOAuthController.java

As long as you provide sufficient env varaibles, the example should work for you. If you prefer a different wa to initialize your app, you can manually instantiate `AppConfig` and pass it to `App` instance.

I hope this helps. As we don't have anything further to share on this topic, let me closet this issue now. That said, if you have further questions, please feel free to write in!
