### ISSUE TITLE
bot responding to all threads, I want it to respond only to the thread bot was mentioned

### ISSUE THREAD

**Issue by mallik30** [slackapi/java-slack-sdk#1173]
bot responding to all threads, I want it to respond only to the thread bot was mentioned

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version
attached actual GitHub codebase url above

#### Java Runtime version

java version "13" 2019-09-17

#### OS info

(Paste the output of sw_vers && uname -v on macOS/Linux or ver on Windows OS)
ProductName: macOS
ProductVersion: 13.3.1
ProductVersionExtra: (a)
BuildVersion: 22E772610a
Darwin Kernel Version 22.4.0: Mon Mar 6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. create a thread with the bot mentioned
2. create a regular thread
3. please check the screenshots

#### Expected result:

respond to only Messages in the thread the bot was mentioned @MyBot create

#### Actual result:

responds to all thread

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by mallik30** [comment]
<img width="871" alt="1" src="https://github.com/slackapi/java-slack-sdk/assets/33911547/816ab40d-1c03-4789-9ea6-b66ce964422c">
<img width="894" alt="2" src="https://github.com/slackapi/java-slack-sdk/assets/33911547/bee63904-4ab1-416d-bc68-5584b85d47f0">

**Comment by mallik30** [comment]
below is the sample code that executes for all the threads, I tried to use an event.getBotId() but it is null for regular thread so I cant avoid threads other than MyBot mentioned thread.

```
public void messageEvent() {
	app.event(MessageEvent.class, (payload, ctx) -> {
		MessageEvent event = payload.getEvent();
		// Listen only thread replies, if ThreadTs is present it is a reply
		if (event.getThreadTs() != null) {
			// my code executes for all thread
		}
		return ctx.ack();
	});
}
```
https://github.com/mallik30/actionbot/blob/f0efe1788322a58760523a7820bd429ecfa60de2/src/main/java/com/arjun/slack/api/ActionBotManager.java#L37

**Comment by seratch** [comment]
Hi @mallik30, thanks for asking the question!

As you've already done, checking the existence of thread_ts in a message is the right way to know if the message is posted in a thread. To know whether your app's bot user is mentioned in the thread, the only feasible way is to call [conversations.replies API method](https://api.slack.com/methods/conversations.replies) and find a string part like `<@{your bot's user ID here}>` in their text properties. To know your bot's user ID, you can call either [auth.test API](https://api.slack.com/methods/auth.test) or [bots.info API](https://api.slack.com/methods/bots.info).

I hope this helps.

**Comment by mallik30** [comment]
hi @seratch thank you
