### ISSUE TITLE
AdminInviteRequestsListResponse doesn't map correctly due to return value of List<String> inviteRequests

### ISSUE THREAD

**Issue by Dunkhell** [slackapi/java-slack-sdk#1174]
I'm using latest (1.29.2) version of the SDK, trying to list all pending invites for given team using slack method mentioned in the title. As long as the invite list is empty, the request works. It doesn't work when there's at least 1 pending invite.

#### The Slack SDK version
```xml
<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>slack-api-client</artifactId>
    <version>1.29.2</version>
</dependency>
```

#### Java Runtime version
openjdk version "1.8.0_362"

#### Steps to reproduce:

1. Create AdminInviteRequestsListResponse 
2. Send request using Slack methods()
3. Map result to AdminInviteRequestsListResponse while having at least 1 invite pending
code ran:
```java
protected List<String> listAllInvitesForTeam(String appId, String teamId) {
    log.info("Listing invites for team {}", teamId);
    AdminInviteRequestsListRequest request = AdminInviteRequestsListRequest.builder()
            .token(credentialProvider.getTokenForMethod(appId, SlackApiMethodCategory.LIST_INVITES))
            .teamId(teamId)
            .build();

    try {
        AdminInviteRequestsListResponse response = slack.methods().adminInviteRequestsList(request);
        if (!response.isOk()) {
            log.info("Failed to get invites for team {}: {}", teamId, response.getError());
            throw new SlackException(response.getError());
        }
        log.info("Fetched {} items", response.getInviteRequests().size());
        return response.getInviteRequests();
    } catch (IOException | SlackApiException e) {
        log.info(e.toString());
        throw new SlackException(e.getMessage());
    }
}
```
Code contains custom exceptions and logging, which can be ignored since they do not result in the error

#### Expected result:

Returned value is a List of InviteRequest with correctly mapped values as per documentation 

#### Actual result:

InviteRequests returned as List<String>, resulting in error: 

```
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 32 path $.invite_requests[0]]

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 32 path $.invite_requests[0]
```

**Comment by seratch** [comment]
Hi @Dunkhell, thank you very much for taking the time to report this issue. We apologize for any inconvenience caused. We will look into the issue and resolve it in the next release.
