### ISSUE TITLE
file upload returns 408

### ISSUE THREAD

**Issue by BugsBunnyBR** [slackapi/java-slack-sdk#1178]
Hello there, for many months we have faced the same issue as folks [here](https://github.com/slackapi/python-slack-sdk/issues/1165)

It seems that the official fix is to use the file upload v2 API, can we get this integrated in the SDK?

it seems the same fix was applied in the [node sdk](https://github.com/slackapi/node-slack-sdk/pull/1544)

Thanks

**Comment by zimeg** [comment]
Hey @BugsBunnyBR! The `filesUploadV2` method was added in #1065 which also contains a few examples that might be helpful for migrating to this newer version.

Hopefully this can fix the `408` error you're finding, but please let me know if you're still encountering errors or have other questions!
