### ISSUE TITLE
Add message_blocks property to Attachement class

### ISSUE THREAD

**Issue by dniero95** [slackapi/java-slack-sdk#1179]
Hi to everyone!
I am trying to use bolt java library to integrate forward information in my system. I have some problems to access the right field in the object. First of all I fetch the message using Conversations.history (https://api.slack.com/methods/conversations.history)
Then if the message has a forward in the json response there is a "attachments" field that contains a list of attachment. Now in the tester the json response has a "message_blocks" field, that is basically what I need because I need to parse one by one the blocks in the message object contained in the message_blocks field. The problem is that the "message_blocks field is not present in the bolt Attachment class
https://javadoc.io/doc/com.slack.api/slack-api-model/1.1.1/com/slack/api/model/Attachment.html
https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/Attachment.java
 
It seems like that this field is not mapped
 
I would really like to access that field or find another way to get the blocks information about the forwarded message.
 
Thank you in advance

**Comment by seratch** [comment]
Hi @dniero95, thanks for writing in! Would it be possible to ask you to share the JSON data you’ve fetched using the API tester? We would like to correctly understand what you’re mentioning.

**Comment by seratch** [comment]
Aside from that, you may not be able to forward all the messages as-is. For instance, third-party apps are unable to send most attachments (attachments are basically controlled by Slack, not third-party apps / end-users). So, when you want to forward (in other words, duplicate) a message with the same content, you may have to remove attachments and rich_text blocks, which are also manageable only by Slack client apps.

**Comment by dniero95** [comment]
Thank you for answering me @seratch.

Here a example response from the Conversations.history tester (https://api.slack.com/methods/conversations.history/test). Some info has been replaced with ***. As i was saying it would be really nice to access the message_blocks field in the response for what i need to do. I have written many mathod to parse the LayoutBlock of the massage in my app and when the user forward a message i'd like to parse also the block of the forward. The problem is that in bolt for java the Attachment class https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/Attachment.java doesn't have the attribute message_blocks so i am unable to parse it. 

kind regards

{
    "ok": true,
    "messages": [
        {
            "type": "message",
            "text": "Forward of a message",
            "user": "***",
            "ts": "1688714629.778029",
            "blocks": [
                {
                    "type": "rich_text",
                    "block_id": "2p9z",
                    "elements": [
                        {
                            "type": "rich_text_section",
                            "elements": [
                                {
                                    "type": "text",
                                    "text": "Forward of a message"
                                }
                            ]
                        }
                    ]
                }
            ],
            "team": "***",
            "attachments": [
                {
                    "ts": "1688651267.097029",
                    "author_id": "***",
                    "channel_id": "***",
                    "channel_team": "***",
                    "channel_name": "Direct Message",
                    "is_msg_unfurl": true,
                    "message_blocks": [
                        {
                            "team": "***",
                            "channel": "***",
                            "ts": "1688651267.097029",
                            "message": {
                                "blocks": [
                                    {
                                        "type": "rich_text",
                                        "block_id": "I4a",
                                        "elements": [
                                            {
                                                "type": "rich_text_section",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "text to forward\n\n"
                                                    }
                                                ]
                                            },
                                            {
                                                "type": "rich_text_list",
                                                "elements": [
                                                    {
                                                        "type": "rich_text_section",
                                                        "elements": [
                                                            {
                                                                "type": "text",
                                                                "text": "item 1"
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        "type": "rich_text_section",
                                                        "elements": [
                                                            {
                                                                "type": "text",
                                                                "text": "item 2"
                                                            }
                                                        ]
                                                    }
                                                ],
                                                "style": "bullet",
                                                "indent": 0,
                                                "border": 0
                                            },
                                            {
                                                "type": "rich_text_section",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "\n"
                                                    }
                                                ]
                                            },
                                            {
                                                "type": "rich_text_list",
                                                "elements": [
                                                    {
                                                        "type": "rich_text_section",
                                                        "elements": [
                                                            {
                                                                "type": "text",
                                                                "text": "item 1"
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        "type": "rich_text_section",
                                                        "elements": [
                                                            {
                                                                "type": "text",
                                                                "text": "item 2"
                                                            }
                                                        ]
                                                    }
                                                ],
                                                "style": "ordered",
                                                "indent": 0,
                                                "border": 0
                                            },
                                            {
                                                "type": "rich_text_section",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "bold text",
                                                        "style": {
                                                            "bold": true
                                                        }
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "italic text",
                                                        "style": {
                                                            "italic": true
                                                        }
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "bold italic text",
                                                        "style": {
                                                            "bold": true,
                                                            "italic": true
                                                        }
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "bold italic barrato text",
                                                        "style": {
                                                            "bold": true,
                                                            "italic": true,
                                                            "strike": true
                                                        }
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    }
                                                ]
                                            },
                                            {
                                                "type": "rich_text_quote",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "citazione",
                                                        "style": {
                                                            "bold": true,
                                                            "italic": true,
                                                            "strike": true
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "type": "rich_text_section",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "questo è condice in linea ",
                                                        "style": {
                                                            "bold": true,
                                                            "italic": true,
                                                            "strike": true,
                                                            "code": true
                                                        }
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "\n\n"
                                                    }
                                                ]
                                            },
                                            {
                                                "type": "rich_text_preformatted",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "questo è multilina\n\nlinea"
                                                    }
                                                ],
                                                "border": 0
                                            },
                                            {
                                                "type": "rich_text_section",
                                                "elements": [
                                                    {
                                                        "type": "text",
                                                        "text": "\n"
                                                    },
                                                    {
                                                        "type": "link",
                                                        "url": "https://forums.slackcommunity.com/s/?language=en_US",
                                                        "text": "link to slackcommunity"
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    ],
                    "color": "D0D0D0",
                    "from_url": "***",
                    "is_share": true,
                    "fallback": "[July 6th, 2023 3:47 PM] dario.niero: text to forward\n\n• item 1\n• item 2\n1. item 1\n2. item 2\n\n*bold text*\n\n_italic text_\n\n_*bold italic text*_\n\n~_*bold italic barrato text*_~\n\n&gt; ~_*citazione*_~\n\n~_*`questo è condice in linea`*_~ \n\n```questo è multilina\n\nlinea```\n<https://forums.slackcommunity.com/s/?language=en_US|link to slackcommunity>",
                    "text": "text to forward\n\n• item 1\n• item 2\n1. item 1\n2. item 2\n\n*bold text*\n\n_italic text_\n\n_*bold italic text*_\n\n~_*bold italic barrato text*_~\n\n&gt; ~_*citazione*_~\n\n~_*`questo è condice in linea`*_~ \n\n```questo è multilina\n\nlinea```\n<https://forums.slackcommunity.com/s/?language=en_US|link to slackcommunity>",
                    "author_name": "Dario Niero",
                    "author_link": "***",
                    "author_icon": "***",
                    "author_subname": "dniero95",
                    "mrkdwn_in": [
                        "text"
                    ],
                    "footer": "Direct Message"
                }
            ]
        }
    ],
    "has_more": true,
    "is_limited": false,
    "pin_count": 0,
    "channel_actions_ts": null,
    "channel_actions_count": 0,
    "response_metadata": {
        "next_cursor": "bmV4dF90czoxNjg4NjU2ODE0NDU2MzM5"
    }
}

**Comment by seratch** [comment]
Thanks for sharing the JSON data. As far as I know, the Slack API had been using `attachements[].blocks` for the layout block data. However, perhaps the API server may add `message_blocks` instead in some scenarios. We can add the property in the next release, which can be released early next week.

**Comment by zubchenok** [comment]
this change causes exception. message_blocks of type LayoutBlock cannot be read, because there is no `type` field in message_blocks.
