### ISSUE TITLE
How to get InstallationDetails without using TeamId/EnterpriseId

### ISSUE THREAD

**Issue by tzuanw** [slackapi/java-slack-sdk#1184]
When an app is installed via  "/slack/install" and completes via "/slack/oauth_redirect", I am wondering at that point, is there a way to access the InstallationService without any knowledge of the TeamId that installed it?

Of course, once slack app events are processed, we can know that information but what if we want to know all the InstallationService details at the time of successful installation? The API doesn't seem to allow it. But this doesn't prevent me (as Admin) to open the file:

-rw-r--r--  1 foo  staff   457B Jul 23 18:48 none-T11ABJJA39-U22G1MJHVA1-latest
-rw-r--r--  1 foo  staff   457B Jul 23 18:48 none-T11ABJJA39-U22G1MJHVA1-1690163325620

Is the only way to do this to just read the latest install file and parse the details? 

I hope my question makes sense! Thank you!

**Comment by seratch** [comment]
Hi @tzuanw, thank you for asking the question.

I'm still not entirely sure what your goal here is, but [the `InstallationService` is just an interface](https://oss.sonatype.org/service/local/repositories/releases/archive/com/slack/api/bolt/1.30.0/bolt-1.30.0-javadoc.jar/!/com/slack/api/bolt/service/InstallationService.html) to implement, so you can add any additional operations in your code. The interface does not prevent you from implementing additional methods such as `findAllInstallations()`, `findByWorkspaceDomain(String)`, or any other methods you may need.

Either way, for production-grade apps, you will use your own `InstallationService` backed by a database, not the default local file-based one used for local development.

I hope this helps.

**Comment by tzuanw** [comment]
Great, this answers my question, thank you so much @seratch :pray:
