### ISSUE TITLE
Add health endpoint to built-in Bolt servers

### ISSUE THREAD

**Issue by slushpupie** [slackapi/java-slack-sdk#1185]
Many platform-as-a-service offerings make it easy to deploy a web service, but require a simple health check to know that the app is up and running.  Using the built-in web servers for Bolt make this difficult to achieve, as there is no way to add additional web responses.   Ideally, using the bolt-jetty webserver (or any of the others) would out of the box allow for a "/health" endpoint that indicates the service is up and running healthy. 

### Category (place an `x` in each of the `[ ]`)

* [X] **bolt** (Bolt for Java)
* [X] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @slushpupie! Thanks so much for the suggestion.

This sounds like a great idea for an enhancement! As far as I know this is not currently on our roadmap, so I'll label this issue accordingly so and add it to milestone `1.31.0` so folks in the community know this issue is up for grabs if they'd like to tackle it. Additionally, if you have any ideas on how to implement a solution, we also welcome you to open a PR for this! 😄

**Comment by seratch** [comment]
Hi @slushpupie, thank you very much for taking the time to write in here (as always)! Indeed, bolt-jakarta-jetty and bolt-jetty do not support the use case right now, while it's feasible if you go with Spring Boot and so forth. This should be improved as early as possible. I will look into it later on.

**Comment by slushpupie** [comment]
What about adding a constructor (or other method) to allow adding custom Servlets to the Jetty server (and equivalents for the other servers).  A simple/example health endpoint could be provided.  Something like (obvious pseudo-code):

```java
import com.example.HealthCheckServlet;

public class MyApp {
  public static void main(String[] args) throws Exception {
    // App expects env variables (SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET)
    App app = new App();

    app.command("/hello", (req, ctx) -> {
      return ctx.ack(":wave: Hello!");
    });

    SlackAppServer server = new SlackAppServer(app);
    HealthCheckServlet healthCheckServlet = new HealthCheckServlet();
    server.addServlet(healthEndpoint,"/health");
    server.start(); // http://localhost:3000/slack/events
  }
}
```

```java
public class SlackAppServer {
    //...
    public void addServlet(Servlet servlet, String pathSpec) throws Exception {
        ServletContextChandler handler = server.getHandler();
        handler.addServlet(servlet, pathSpec);
   }
}
```

And the trivial HealthCheckServlet:
```java
public class HealthcheckServlet extends HttpServlet {
        @Override
	public void init() throws ServletException {
		super.init();
	}

	@Override
	protected void doGet(
			HttpServletRequest httpServletRequest,
			HttpServletResponse httpServletResponse)
		throws IOException, ServletException {

                 httpServletResponse.setStatus(HttpServletResponse.SC_OK);
                 PrintWriter out = httpServletResponse.getWriter();
                 out.println("ok");
                 out.close();

	}
}
```

**Comment by seratch** [comment]
Hi @slushpupie, I completely forgot about a feature I added a few years ago... 🤦 

The `app.endpoint` method enables developers to add custom routes like your health check endpoint, so there's no need for you to write a classic servlet code for it. The following example code should work for you, even with bolt-jetty or bolt-jakarta-jetty servers:

```java
app.endpoint("/health", (req, ctx) -> {
    // If you want to run deep health check logic here, you can do so too
    return Response.builder().statusCode(200).body("OK").build();
});
```

I am still open to the idea to have a new method to accept raw servlet objects if the above custom endpoint does not work for you. Let me know what you think.
