### ISSUE TITLE
Custome Error Message after block action.

### ISSUE THREAD

**Issue by jays95jp** [slackapi/java-slack-sdk#1186]
Hi, I am trying to validate user input using block action. I am getting callback in app.blockAction(block_id,....).
But after validating I am not able to send custom error message in opened view. I am using below method to send error message. 

```
 app.blockAction("input_name", new BlockActionHandler() {
            @Override
            public Response apply(BlockActionRequest req, ActionContext ctx) throws IOException, SlackApiException {

                if (req.getPayload().getView().getState() != null && req.getPayload().getView().getState().getValues() != null && req.getPayload().getView().getState().getValues().containsKey("input_name_block") && req.getPayload().getView().getState().getValues().get("input_name_block").get("input_name").getValue().equals("1234")) {

                    String errorResponse = "{" + "\"response_action\": \"errors\"," + "\"errors\": {" + "\"input_name_block\": \"Please enter valid Name.\"" + ",\"radio_block\": \"Please enter valid Name.\"" + "}" + "}";

                    return ctx.ackWithJson(errorResponse);

                }
                return ctx.ack();
            }
        });
```

But after call this method ctx.ackWithJson(errorResponse); modal view is not updating with error message. 
 **Can you please help me how can I send error message to modal view after user input?** **Without submit button click.** 
 
 I am using socket mode connection.

**Comment by seratch** [comment]
Hi @jays95jp, thank you for asking the question. Unfortunately, it's not possible to display a red-colored error to an input block in response to a `block_actions` type request (corresponding to the `app.action` handler pattern in Bolt code). The feature for input validation is only available for `view_submission` requests (which corresponds to `app.view` in Bolt).

I understand this might not be the ideal solution you were hoping for, but I hope this helps to clarify the current functionality.

**Comment by jays95jp** [comment]
Thanks for quick reply @seratch 
Can we add this as enhancement? This is one request from my end.

One more question: 
If we validate field in `view_submission `. but what if validation taking more then 3-5 sec? can we ack after 5-6 sec or any way to increase that ack time?

**Comment by seratch** [comment]
@jays95jp 
>Can we add this as enhancement? This is one request from my end.

Unfortunately, this would require substantial changes on the Slack platform side, and there are no plans to implement such a feature in the near term.

>If we validate field in view_submission . but what if validation taking more then 3-5 sec? can we ack after 5-6 sec or any way to increase that ack time?

Your `app.view` listener still must respond within 3 seconds. Also, there's no option to extend this response time.

I'm sorry for saying no to all your questions here, but I hope the information is helpful regardless.

**Comment by seratch** [comment]
Thanks for adding reactions! Let me close this issue now, but please feel free to write in whenever you have anything else!
