### ISSUE TITLE
bolt micronaut is not support native image run.

### ISSUE THREAD

**Issue by cprashantgupta** [slackapi/java-slack-sdk#1187]
Using bolt-micronaut in micronaut serverless application result in run time error.

#### The Slack SDK version

```
<dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-micronaut</artifactId>
      <version>1.30.0</version>
 </dependency> 
```

#### Java Runtime version

Java 11

#### OS info

Ubuntu Latest

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Create a micronaut serverless project from micronaut lanch 
2. Ass Slack sdk into it.
3. Create maven function using : 
``` 
mvn package -Dpackaging=docker-native -D"exec.mainClass"="io.micronaut.function.aws.runtime.MicronautLambdaRuntime" -D"micronaut.runtime"="lambda" -Pgraalvm
```
4. Execute this on AWS , it result in error.

#### Expected result:

Application was suppose to run successfully. 

#### Actual result:

Exception comes Up - 

```
Caused by: com.amazonaws.serverless.exceptions.ContainerInitializationException: Error starting Micronaut container: Bean definition [com.slack.api.bolt.micronaut.SlackAppController] could not be loaded: Failed to inject value for parameter [slackApp] of class: com.slack.api.bolt.micronaut.SlackAppController
```

**Comment by seratch** [comment]
Hi @cprashantgupta, thanks for writing in. Unfortunately, we don't have plans to add GraalVM support in the short term. We recommend using JavaVM instead. You can refer to https://github.com/slackapi/java-slack-sdk/issues/1009 for more details on the current status of GraalVM support possibility.

**Comment by markchang-st** [comment]
Are there any updates on adding GraalVM support? Thanks

**Comment by seratch** [comment]
We currently have no plans for this, and that's expected to remain the same for at least the next few years.
