### ISSUE TITLE
Question on building a Spring Boot 3 based app

### ISSUE THREAD

**Issue by Harishkumarcratoflow** [slackapi/java-slack-sdk#1190]
```java
@PostMapping(value = "/slack-responseee", produces = MediaType.APPLICATION_JSON_VALUE)
public String responseAction(Object payload) {
	System.out.println("Object: " + payload.toString());
	return "";
}
```

Here is the issue :

First in my slack application, we have interactive buttons to get response from the other user.
When the other user clicks the button, we have one endpoint to process that action even though the request (POST) is happening I have to process that slack  payload as Object, but the request payload is returning null.

Why is that I am getting null as my payload. Is there any other alternative to print that payload as json?
![Screenshot (56)](https://github.com/slackapi/java-slack-sdk/assets/131237138/c09e896a-8332-4cfb-9506-e3cc27160b9f)

![image](https://github.com/slackapi/java-slack-sdk/assets/131237138/a2ad77a8-8871-47cd-878a-946a2e26480e)

**Comment by seratch** [comment]
Hi @Harishkumarcratoflow, thanks for writing in. However, this question is mostly the same with https://github.com/slackapi/java-slack-sdk/issues/1188 . As I replied in the question issue, we are unable to assist you for general Spring boot questions. If you're not sure about how to parse request data on your own, please consider using bolt-java's functionality to do so.
