### ISSUE TITLE
Bolt  issue

### ISSUE THREAD

**Issue by Harishkumarcratoflow** [slackapi/java-slack-sdk#1191]
We highly discourage implementing the code to parse request body data. It's not just for the sake of simplicity, but also for enhanced security. The Bolt framework verifies if a request originates from Slack and ensures the data is never manipulated. For this purpose, the framework parses body data as-is and verifies the x-slack-signature header in the request using the "Signing Secret", which is shared exclusively between Slack and you. Therefore, please consider relying on the Bolt framework instead of trying to implement everything on your own. 
As you mentioned yesterday i have tried  using bolt but i am not receiving any payload when clicking  button in my slackapp.can you provide any sample code in java  to access the interactivepayload.

**Comment by seratch** [comment]
Hi @Harishkumarcratoflow, I will reply to this question in #1188

**Comment by Harishkumarcratoflow** [comment]
@seratch Ok

**Comment by Harishkumarcratoflow** [comment]
@PostMapping(value = "/slack-response", produces = MediaType.APPLICATION_JSON_VALUE)
	public String responseAction(@RequestBody String payload,
            @RequestHeader("X-Slack-Signature") String slackSignature,
            @RequestHeader("X-Slack-Request-Timestamp") String requestTimestamp) {
		
		slackApp.event(ReactionAddedEvent.class, (req, ctx) -> {
			ReactionAddedEvent event = req.getEvent();
			if (event.getReaction().equals("white_check_mark")) {
				ChatPostMessageResponse message = ctx.client().chatPostMessage(r -> r
						.channel(event.getItem().getChannel()).threadTs(event.getItem().getTs())
						.text("<@" + event.getUser() + "> Thank you! We greatly appreciate your efforts :two_hearts:"));
				if (!message.isOk()) {
					ctx.logger.error("chat.postMessage failed: {}", message.getError());
				}
			}
			return ctx.ack();
		});
		
	return "Ok";
	}  this what i was trying but i cannot figure out the issue  when an event is happeing i am unable to process it  and send a response
