### ISSUE TITLE
Slack Backend API - Do not support chat:write.customize with file uploads. 

### ISSUE THREAD

**Issue by cprashantgupta** [slackapi/java-slack-sdk#1195]
We are using Slack API to publish user content to different channels, and the content can be either text or images/video or mix of both. 

We are using following end point for **post conversation** in formatted form (markdown) 

> Note we use custom username (not bot name) as argument to above call, so that it appears as of the user is sending this message. using permission **[chat:write.customize](https://api.slack.com/methods/chat.postMessage#authorship)**

```
https://slack.com/api/chat.postMessage
```

We are using **File upload API process** to upload images/videos/pdf

```
INITIAL - https://slack.com/api/files.getUploadURLExternal
UPLOAD 
MARK COMPLETE - https://slack.com/api/files.completeUploadExternal
```

**Now during mark complete there is no option to send username, hence these appears as two message on slack - one from user other from BOT.**

### Reproducible in:
```
<dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-micronaut</artifactId>
      <version>1.30.0</version>
 </dependency>
```

#### The Slack SDK version

(Paste the output of `mvn dependency:tree | grep com.slack.api` or `gradle dependencies | grep com.slack.api`)

#### Java Runtime version

Java 11

#### OS info
Ubuntu Latest

#### Steps to reproduce:

1. Use SLACK API to post conversation using custom username
2. Use SLACK API to send files

#### Expected result:

Either the post conversation message should link to upload file message and take arguments returned from file upload. 
OR
File upload should have option to change username, so that these appear as consecutive messages. 

#### Actual result:
At present they appear two messages and hence the issue.

### Requirements

We should be able to send messages to slack channel via API with both formatted TEXT and Attachments and they should appear as one.

**Comment by srajiang** [comment]
Hi @cprashantgupta - Yes, confirming that uploading a file with a custom username for your bot is not supported today in our Files API. There doesn't for instance seem to be a corresponding `files:write:customize` scope that I would assume would be needed to support something like this. 

In terms of this SDK we would not be able to support this at the SDK level, but I can definitely drop this as a feature request to our backend teams that manage the Files API.

**Comment by cprashantgupta** [comment]
@srajiang  : Please can you raise this with backend team and is there a way to track this request for backend team ?
