### ISSUE TITLE
Dependabot reports Security vulnerabilities

### ISSUE THREAD

**Issue by MeikeMertschFortum** [slackapi/java-slack-sdk#1198]
Hi!

When importing com.slack.api:bolt-jetty:1.30.0 to my project, Dependabot started warning about possible security issues. 
Could you update the versions of 
- com.squareup.okhttp3:okhttp (contains the okio lib) and 
- org.eclipse.jetty:jetty-webapp (contains the jetty-xml lib), 
please?

<img width="500" alt="Screenshot 2023-08-22 at 07 07 24" src="https://github.com/slackapi/java-slack-sdk/assets/61452719/3a2bbe6f-945b-4c56-a10b-74338dbcb120">

## The Slack SDK version

com.slack.api:bolt-jetty:1.30.0

## Dependency tree

<img width="500" alt="Screenshot 2023-08-22 at 07 15 02" src="https://github.com/slackapi/java-slack-sdk/assets/61452719/001a5a1b-a2f5-4fd3-805d-0d365a07bdbb">

## Issue descriptions by Dependabot

<img width="500" alt="Screenshot 2023-08-22 at 07 07 38" src="https://github.com/slackapi/java-slack-sdk/assets/61452719/94ee0163-ee23-4287-8b13-bf6cdca2ed8d">

<img width="500" alt="Screenshot 2023-08-22 at 07 08 01" src="https://github.com/slackapi/java-slack-sdk/assets/61452719/96a1c8cc-c61a-46a2-afca-50d5af546187">

**Comment by seratch** [comment]
Hi @MeikeMertschFortum, thanks for taking the time to report this! We will upgrade okhttp and its underlying okio in future releases like we have been doing. However, it seems jetty 9.4.51 is the latest version in 9.x series. If you needs to use a newer veresion, you may want to switch to bolt-jakarta-jetty library, which is compatible with jetty 11.x series.

**Comment by kamilgregorczyk** [comment]
Hello @seratch , looks like the vulnerabilities are still there https://mvnrepository.com/artifact/com.slack.api/slack-api-client/1.32.1 is there a plan to update the slack-api-client anytime soon ? Or is there a replacement for it ?

**Comment by seratch** [comment]
@kamilgregorczyk The old versions of Jetty libraries are "test" dependencies, which are used only in unit tests for the slack-api-client library itself. Therefore, it does not affect your app code at all.

**Comment by seratch** [comment]
The latest release does not have any issues mentioned here: https://github.com/slackapi/java-slack-sdk/releases/tag/v1.35.0 Let me close this issue now.
