### ISSUE TITLE
WebSocket Rate limit error occurs because of  code: 1006

### ISSUE THREAD

**Issue by selvaraju99** [slackapi/java-slack-sdk#1199]
HI, We are using Bolt framework 
```xml
<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt-socket-mode</artifactId>
    <version>1.8.0</version>
</dependency>
```

to implement Socket mode. We have bot implemented using Socket mode and our Java component receives onMessage event when the the user sends messages from Bot.We are seeing the ratelimit error very often and it is happening in high frequency in recent days.

```
dtm=08-31-2023T11:13:22.795GMT | priority=ERROR | thread=socket-mode-message-processor-worker-28 | class=c.s.a.m.i.TeamIdCache:46 | method=lambda$lookupOrResolve$0 | appKey= | slackChannelId= | Failed to call auth.test API (error: status: 429, error: ratelimited, needed: null, provided: null, warning: null)
com.slack.api.methods.SlackApiException: status: 429, error: ratelimited, needed: null, provided: null, warning: null
	at com.slack.api.methods.impl.MethodsClientImpl.parseJsonResponseAndRunListeners(MethodsClientImpl.java:2963) ~[slack-api-client-1.8.0.jar:1.8.0]
	at com.slack.api.methods.impl.TeamIdCache.lambda$lookupOrResolve$0(TeamIdCache.java:34) ~[slack-api-client-1.8.0.jar:1.8.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
```

Looks like the reason for this rate limit is because of the below error 

```
dtm=08-31-2023T11:13:22.753GMT | priority=INFO  | thread=WebSocketConnectReadThread-135241 | class=c.s.a.s.SocketModeClient:257 | method=onClose | appKey= | slackChannelId= | onClose listener is called (code: 1006, reason: )
```

We are have tried with Tyrus client library and Java-WebSocket ( version 1.5.3), but in both the cases this error occurs.
Can some help me with this above issue, why the error 1006 occurs>

### Reproducible in:

Yes

#### The Slack SDK version

```
[INFO] +- com.slack.api:bolt:jar:1.8.0:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.8.0:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.8.0:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.8.0:compile
[INFO] +- com.slack.api:bolt-socket-mode:jar:1.8.0:compile
```

#### Java Runtime version

OpenJDK 64-Bit Server VM AppleJDK-17.0.0.35.1 (build 17+35-LTS, mixed mode, sharing)

#### OS info

docker java container deployed AWS Kube.

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

Rate limit should not occur.

**Comment by seratch** [comment]
Hi @selvaraju99, thanks for writing in. It seems that you're using a very old version of the library, which was released 2.5 years ago. Could you try the latest version out and see how it goes? We've applied a bunch of improvements in the last few years. Your issue could be resolved just by upgrading the library.

**Comment by filmaj** [comment]
Agree with what @seratch says, and also, a [WebSocket 1006 close status is "abnormal closure"](https://www.rfc-editor.org/rfc/rfc6455#section-7.4.1), meaning, an the peer closed due to unexpected circumstances. There may be a larger reason for the behaviour, it completely depends on your application and what it is doing.

**Comment by seratch** [comment]
Thank you for trying the latest version. As Fil mentioned above, closing a connection with the error code is not a common situation (we've never received this inquiry in the last few years since this SDK project started), so I suspect something specific to your network or infrastructure might be causing the forced connection closure. Sorry, I don't have any further suggestions so far.
