### ISSUE TITLE
Updating dispatcher text box hint message 

### ISSUE THREAD

**Issue by karishma21mahajan21** [slackapi/java-slack-sdk#1210]
I want to change/update the hint message "Press 'enter' to submit" to some other text.
But not able to find any element to do so.

Below is the text box with "dispatch_action": true:

```json
{
	"title": {
		"type": "plain_text",
		"text": "Add info to feedback",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Save",
		"emoji": true
	},
	"type": "modal",
	"blocks": [
		{
			"type": "input",
			"element": {
				"type": "plain_text_input"
			},
			"label": {
				"type": "plain_text",
				"text": "Label",
				"emoji": true
			},
			"dispatch_action": true
		}
	]
}
```

**Comment by seratch** [comment]
Hi @karishma21mahajan21, thanks for writing in.

Unfortunately, customizing that part is currently not available. As a workaround, adding a "context" type block to display such a note (right after the "input" block) may be helpful for your end-users.

If you'd like to send a product feature request, would you mind sharing the feedback with our customer support team (you can send an inquiry via either `/feedback` in your Slack workspace or from https://my.slack.com/help/requests/new)? They can share your feedback with our product teams more effectively.

We would appreciate it if you could understand this.

**Comment by karishma21mahajan21** [comment]
@seratch 
Thank you for responding but i want to initiate a dispatch action from text box and for that i will have to add "dispatch_action": true" which will automatically add "Press 'enter' to submit"

**Comment by seratch** [comment]
Yes, I understand your question. However, as I mentioned earlier, the platform currently doesn't offer any methods for customizing the label or hint. Moreover, I don't foresee any immediate enhancements to this aspect of the platform. I apologize for the inconvenience!
