### ISSUE TITLE
Error sending message: Failed to send the message. Error: invalid_arguments

### ISSUE THREAD

**Issue by RedHoes** [slackapi/java-slack-sdk#1217]
I add this block into a modal and get this message when I tried the modal.

`Error sending message: Failed to send the message. Error: invalid_arguments","logger_name":"com.chargefuze.manager.slack.DefaultSlackManager","thread_name":"default-nioEventLoopGroup-1-2"`

I tried multi types of blocks but only SectionBlock(MarkdownTextObject,ButtonElement), DividerBlock are accepted

### Reproducible in:

```bash
    InputBlock.builder()
      .label(PlainTextObject.builder().text("Input label").build())
      .optional(false)
      .element(et t
        PlainTextInputElement.builder()
          .actionId(SlackInputConstants.inputButton)
          .placeholder(
            PlainTextObject.builder()
              .text("Enter Repo Name")
              .emoji(false)
              .build()
          )
          .build()
      ).build()
```

#### The Slack SDK version

Module Version: slack.api.model: 1.29.2

#### Java Runtime version

openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

#### OS info

OS Version etc: Ubuntu 22.04.4 LTS

#### Expected result:

(Tell what you expected to happen)

#### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @RedHoes, thanks for asking the question. With currently provided information, I am unable to provide helpful advice. Could you provide a minimal working example code that reproduces your error (meaning, not the small snippet you've already shared)? That would potentially allow me to identify the issue with your code.
