### ISSUE TITLE
Change font, size and color in Layout Block

### ISSUE THREAD

**Issue by RedHoes** [slackapi/java-slack-sdk#1219]
How can I style text within a Slack message using Layout Blocks? Specifically, I want to change the font, size, and color of certain words to create emphasis or highlight important information. Thank you

#### Expected result:

(Tell what you expected to happen)

#### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @RedHoes, thanks for asking the question. 

You can use a few styles like bold and italic using "mrkdwn" formatting and header/context blocks enable you to use bigger/smaller fonts per a block. 
* bold, italic, and so on: https://api.slack.com/reference/surfaces/formatting
* header block (larger font): https://api.slack.com/reference/block-kit/blocks#header
* context block (smaller font): https://api.slack.com/reference/block-kit/blocks#context

However, there is no way to customize font, color, and font size on text. Also, there is no immediate plan to enhance the platform for these use cases. I hope this clarifies.

**Comment by RedHoes** [comment]
Thank you for you answers. But how about the modal, could I customize the size of the modal.

**Comment by seratch** [comment]
Slack's UI optimally supports both desktop and mobile platforms. Therefore, third-party apps can't customize size aspects of any surfaces.
