### ISSUE TITLE
Setting dropdown value based on another dropdown value

### ISSUE THREAD

**Issue by karishma21mahajan21** [slackapi/java-slack-sdk#1221]
I am trying to set a static select dropdown value based on another static select value.
I am able to dispatch an action on first static select dropdown selection.
Able to set values for the second static select dropdown values as well.
But even if i set initial option for second dropdown like below
**dropDownElement.setInitialOption(new val)**
Even though initial value is updated but initial option is still the older value selected.

```java
InputBlock blockElement =  ... // block element fetched from "req.getPayload().getView()"

List<OptionObject> dropdownOptions = dropdown options;
StaticSelectElement dropdownElement = blockElement.getElement();

dropdownElement(dropdownOptions);
dropdownElement(dropdownOptions.get(0));
```

After preparing the new view on BlockActionHandler, I am updating the view with 
```java
ctx.client().viewsUpdate(r -> r
        .viewId(currentViewId)
        .hash(currentHash)
        .view(finalNewView) 
);
```

**Comment by seratch** [comment]
Hi @karishma21mahajan21, thanks for asking the question. However, I still don't understand what your question is. Could you share the modal UI you're trying to build? You can simulate it using Block Kit Builder and share the URL with us: https://app.slack.com/block-kit-builder

**Comment by karishma21mahajan21** [comment]
Hi @seratch,
PFB link:
[block-kit-builder](https://app.slack.com/block-kit-builder/T03N7NT8TPG#%7B%22blocks%22:%5B%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22static_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20an%20item%22,%22emoji%22:true%7D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-2%22%7D%5D,%22action_id%22:%22static_select-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Dropdown1%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22static_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20an%20item%22,%22emoji%22:true%7D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-2%22%7D%5D,%22action_id%22:%22static_select-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Dropdown2%22,%22emoji%22:true%7D%7D%5D%7D)

**Comment by seratch** [comment]
Thanks for your quick reply. It seems that your issue is the same with https://github.com/slackapi/bolt-js/issues/1920#issuecomment-1669627257 . Our team already escalated the issue to the server-side engineering teams, but it seems that it is not yet resolved. Please consider going with the workaround shared in the thread. We apologize for the inconvenience.
