### ISSUE TITLE
TeamBillableInfoRequest missing 2 optional arguments

### ISSUE THREAD

**Issue by Dunkhell** [slackapi/java-slack-sdk#1237]
* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [x] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

There are 2 optional arguments missing in [TeamBillableInfoRequest](https://api.slack.com/methods/team.billableInfo) which are limit and cursor. Would be super handy if they were added in the nearest iteration of the SDK

**Comment by filmaj** [comment]
Nice catch! I believe we could copy [the code used in `ConversationsMembersRequest`](https://github.com/slackapi/java-slack-sdk/blob/d627815a3782f846753d579e087f39d0cd7b5d00/slack-api-client/src/main/java/com/slack/api/methods/request/conversations/ConversationsMembersRequest.java#L24-L36).

Contributions always welcome!
