### ISSUE TITLE
Should the APITestRequest class have a `foo` property?

### ISSUE THREAD

**Issue by filmaj** [slackapi/java-slack-sdk#1243]
See this code: https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/methods/request/api/ApiTestRequest.java#L14-L17

Should this be included?

**Comment by seratch** [comment]
@filmaj The request object has the property just to demonstrate how the `args` property can be returned in its response: https://github.com/slackapi/java-slack-sdk/blob/v1.36.1/slack-api-client/src/main/java/com/slack/api/methods/response/api/ApiTestResponse.java#L11-L15 It's also possible to change it to have a Map object for more dynamic value examples, but I don't think it's so important for many people.

**Comment by filmaj** [comment]
Oh ok, thanks for explaining. 🙇
