### ISSUE TITLE
Can we make multiUsersSelect dropdown mandatory, if required?

### ISSUE THREAD

**Issue by kranti-rh** [slackapi/java-slack-sdk#1255]
While working on a feature for Slack bot using Java, I encountered a challenge with the `multiUsersSelect` dropdown. Unfortunately, there doesn't seem to be a built-in option to make it mandatory. As a workaround, I had to implement a manual check to ensure that at least one value was selected from the dropdown. If the user hasn't selected anything, I reopen the modal. I'm suggesting the addition of a `property` that would allow making the multiUsersSelect dropdown mandatory more seamlessly.

**Comment by seratch** [comment]
Hi @kranti-rh, thanks for asking the question. When you don't set optional: true to the input block, all input blocks should be required by default. Could you double-check if your code does not set the optional flag? Also, explicitly pasing optional: false should work for you too.

**Comment by kranti-rh** [comment]
Hi @seratch, thanks. That worked. So the issue was, previously I was using `section(sectionBlockBuilder -> sectionBlockBuilder...` instead of `input(inputBlockBuilder -> inputBlockBuilder...`. But as per your suggestion `input` builder did the job as it has `.optional` property but `section` didn't.
