### ISSUE TITLE
Kotlin extension should be populated with an earlier api target

### ISSUE THREAD

**Issue by rocketraman** [slackapi/java-slack-sdk#1277]
The Kotlin extension is compiled against 1.9.x and by default can only be used by Kotlin 1.9 and above.

Unless the extension is using language features that are only accessible in 1.9.x, I recommend setting the apiVersion on the kotlin compiler, which will allow it to generate code with earlier metadata (recommend 1.6.x) and be usable for users with earlier versions of Kotlin.

See https://kotlinlang.org/docs/maven.html#attributes-specific-to-jvm, specifically `languageVersion`.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [X] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

**Comment by seratch** [comment]
Thanks for the suggestion! Indeed, this could be improved for Kotlin users.

**Comment by rocketraman** [comment]
> Thanks for the suggestion! Indeed, this could be improved for Kotlin users.

@seratch I submitted a PR. No code changes were required to maintain language and API compat with Kotlin 1.6.

**Comment by rocketraman** [comment]
(BTW, the `kotlin` label on this repo is spelled incorrectly)

**Comment by seratch** [comment]
>(BTW, the kotlin label on this repo is spelled incorrectly)

🤦 Oops, thanks! Fixed.
