### ISSUE TITLE
Request for Exact Size Limit of Timestamp (ts) Field in Java Slack SDK

### ISSUE THREAD

**Issue by amitkuet** [slackapi/java-slack-sdk#1293]
I am currently working with the Java Slack SDK and need to know the exact size limit of the timestamp (ts) field. The documentation provides an example without specifying the definitive size limit, and I require precise details on the size limit to ensure compatibility and proper handling within my application.

Could you please provide the exact size limit of the timestamp (ts) field in the Java Slack SDK? This information is critical for accurately managing the timestamp data and ensuring the smooth operation of my application. Thank you for your assistance.

Here is the ref documentation
https://api.slack.com/methods/conversations.replies

**Comment by seratch** [comment]
Hi @amitkuet, thanks for asking the question!

First off, it's important to note that the "ts" value **must be a string**, and should not be long, integer, or float data. On top of that, the string value comprises a UNIX timestamp in seconds, followed by a period and a unique 6-digit number. For this reason, if you go with non-string data type, misinterpretantion of the data can happen. When it comes to the length of the data, it can be 17 chars at this moment, but it can be 18 in 2037.

Does this make sense to you?
