### ISSUE TITLE
Use the slack huddle api

### ISSUE THREAD

**Issue by RedHoes** [slackapi/java-slack-sdk#1295]
**I wonder if there is anyway to use the slack huddle api** 

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### Java Runtime version

openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Corretto-19.0.2.7.1 (build 19.0.2+7-FR)
OpenJDK 64-Bit Server VM Corretto-19.0.2.7.1 (build 19.0.2+7-FR, mixed mode, sharing)

#### OS info

ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:54 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6030

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

(Tell what you expected to happen)

#### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @RedHoes, thanks for your interest here! Our platform team does not have immediate plans to enhance the set of APIs to support hulddle meetings so far. Please check https://api.slack.com/changelog (it has a RSS feed too! - https://api.slack.com/changelog.rss ) for future updates. Thanks again for writing in!
