### ISSUE TITLE
How to un-register/re-register a message listener

### ISSUE THREAD

**Issue by lz000** [slackapi/java-slack-sdk#1305]
I know we can use `app.message` to listen for a specific pattern. But is there a way to dynamically un-register an event listener for a pattern and re-register the event listener again? and replace event listener?

**Comment by zimeg** [comment]
Hey @lz000 👋 Thanks for the interesting question! When setting up an event listener, like `app.message`, the event is registered to [an events dispatcher](https://github.com/slackapi/java-slack-sdk/blob/e5bb100b9b82c63baf4949a4414a529db2358f5c/bolt/src/main/java/com/slack/api/bolt/App.java#L646-L649) for your app and I don't believe these events can be deregistered once added.

Replacing an existing event listener with a different one, however, does seem possible by [replacing an existing handler](https://github.com/slackapi/java-slack-sdk/blob/e5bb100b9b82c63baf4949a4414a529db2358f5c/bolt/src/main/java/com/slack/api/bolt/App.java#L637-L640) with the latest. This applies to most events except for `message`, which has handlers appended to the list of listeners instead.

I hope this helps but let me know if this is giving you any troubles! I'm also curious if you're trying to re-register certain events or the message one specifically? Some logic within a listener might be another approach to deregister a listener without removing it from the list of event handlers too, but might not be ideal.

**Comment by seratch** [comment]
Specifically talking about `app.message` listener user case, I would recommend having one large `app.event(MessageEvent.class)` listener and having your own dispatcher within it. This approach offers greater flexibility and eliminates the need to focus on Bolt-specific details.

**Comment by lz000** [comment]
@seratch thanks. That wouldn't work for our case, because when we want un-register, we don't want the app to get message from slack at all. With your approach, the app still retrieve message but just ignored

**Comment by seratch** [comment]
Ah I see. Unfortunately, bolt and the Slack platform do not provide a feature that meets your needs. The only approach I can suggest is to have a proxy server in front of your bolt app instances and let the proxy server do a kind of load balancing like you mentioned.

I understand this is not a great answer for you but we don’t have anything else to share on this matter. If everything is clear to you so far, would you mind closing this issue? You can submit new ones whenever you have new but similar questions.
