### ISSUE TITLE
Slack API that allows me to call to install an app on a specific channel and remove an app on a specific channel

### ISSUE THREAD

**Issue by yingzit123** [slackapi/java-slack-sdk#1315]
I hope to develop project that allows me to install an app on a specific channel on slack and remove the app on a specific channel. I have looked through the documentation and saw that there an admins.app.uninstall which uninstall an app from one or many workspaces, or an entire enterprise organization. However, this does not meet my requirement. Is there a way to fulfill my task? 

Thanks.
### The page URLs
https://api.slack.com/methods?query=admin

* https://slack.dev/java-slack-sdk/
* (examples in this repository)

**Comment by seratch** [comment]
Hi @yingzit123, thank you for writing in. Unfortunately, there is no way to install an app into only a specific channel. Your app needs to be installed at the workspace/org level. I understand this is not satisfactory for you, but I hope this clarifies things.

**Comment by yingzit123** [comment]
Hi Seratch. Thank you for your rapid response! I understand. I just want to make sure I explain my question clearly. Let me explain it again cause I am not sure if it may or may not be related to installation problem. I have a tool that react to an emoji in some of the selected channel like sending message in the thread after person in the channel add a emoji as response to a message. I am implementing a UI that hopefully can allow me to add and remove channel for this functionality. Is there such an api for me to do so? Or I still have to do the operation manually on slack api web page. Thanks again!

**Comment by seratch** [comment]
If you meant adding/removing your app's bot user in a channel, the following ones should be useful for it:
- https://api.slack.com/methods/conversations.join
- https://api.slack.com/methods/conversations.leave

**Comment by yingzit123** [comment]
Thanks. So do you mean that by using the join and leave api, I can add the support bot to this channel and remove it from the channel instead of manually clicking the add apps to add bot to this channel? The attachment is what I am talking about.
<img width="570" alt="Screenshot 2024-05-24 at 4 41 20 PM" src="https://github.com/slackapi/java-slack-sdk/assets/170771509/feba9d1f-37d4-465e-8b71-61eb1340901d">

**Comment by seratch** [comment]
Yes, I do. You can try the APIs out to see how they work. It seems there is no other question here. Would it be fine for you to close this issue now? Thanks again for building Slack apps using this SDK!

**Comment by yingzit123** [comment]
Yes. Please close this issue. Thank you so much! That's very helpful.
