### ISSUE TITLE
How do I respond to the url_verification event?

### ISSUE THREAD

**Issue by deeyonn** [slackapi/java-slack-sdk#1317]
Can someone please explain to me how can I respond to the url_verification event when there is no such even found under `com.slack.api.model.event`?, but there are `com.slack.api.app_backend.events.payload.UrlVerificationPayload` and `com.slack.api.bolt.request.builtin.UrlVerificationRequest`.

```java
App app = new App();
app.event(UrlVerificationPayload.class, (req, ctx) -> {return...});
```

```java
App app = new App();
app.event(UrlVerificationRequest.class, (req, ctx) -> {return...});
```

**Comment by zimeg** [comment]
Hey @deeyonn 👋 Thanks for writing in and I'm glad to see this issue could be closed - hopefully with a fix! Could you share the solution you found? It's not immediately obvious to me what the correct response or handling might be 😅

**Comment by deeyonn** [comment]
> Hey @deeyonn 👋 Thanks for writing in and I'm glad to see this issue could be closed - hopefully with a fix! Could you share the solution you found? It's not immediately obvious to me what the correct response or handling might be 😅 

Not sure if its actually implemented, but simply instantiating the App with both mandatory environment variables allowed me to resolve the challenge automatically. I've tried it with ngrok and simply did something like:

```java
App app = new App();
app.start();
```

and gave slack my ngrok endpoint and it verified so I suppose there's some auto url verification implementated somewhere in bolt.
