### ISSUE TITLE
Events Lag Issue

### ISSUE THREAD

**Issue by abubakar364** [slackapi/java-slack-sdk#1320]
I'm using Slack bolt as Event consumer. Sometimes it stops catching all of the events like I send 10 messages and get only 4 events. Is it something that occurs ? 
![Screenshot 2024-06-03 124706](https://github.com/slackapi/java-slack-sdk/assets/150042029/2ce57fce-70b8-4162-9de0-79877fc5ee1e)

**Comment by seratch** [comment]
Hi @abubakar364, thanks for asking the question.

There are two possibilities:
1. If your Slack app server (or socket mode client) has multiple instances, only one of the instances receives an event request while the rest won't.
2. If you enable the app in a highly active channel/workspace, only 30K events per hour will be delivered: https://api.slack.com/apis/rate-limits#events

I hope you figure out the cause soon.

**Comment by abubakar364** [comment]
I only have one app server is running I raised this issue to slack team first and they said that slack is sending events continuously but your application is not consuming. let me share the image of mail. Also my question is how it is possible that slack is sending events but only few are acknowledge rest are not 😞 even not getting logs for that on server side.


![image](https://github.com/slackapi/java-slack-sdk/assets/150042029/f6705717-f3e2-49bc-9b29-0882ccd11348)

**Comment by seratch** [comment]
Thanks for sharing the context. In this case, I'd suggest double-checking all your configurations, including load balancer and network settings. I understand you've already checked many things, but there must be something causing the issue for you. Your app logs may show only a few of the events, but the rest might be unhandled before reaching your app instances. Either way, I don't think we as SDK maintainers can help you further with this. I hope you'll identify the cause of your issue soon.
