### ISSUE TITLE
Can we use "Bot is typing..." feature via APIs?

### ISSUE THREAD

**Issue by kranti-rh** [slackapi/java-slack-sdk#1328]
My bot takes some time to prepare a response. Is there any way to utilize the "Bot is typing..." feature via APIs? I'm using Bolt SDK for Java.

**Comment by seratch** [comment]
Hi @kranti-rh, thanks for asking the question!

Unfortunately, Slack's platform does not have any immediate plans to make enhancements to enable 3rd party apps to display "typing..." indicator. As a workaround, please consider the following approach:
- call chat.postMessage with "Now preparing a response for you..." first
- once the response is ready, call chat.update with channel ID + ts

I understand this is not the best solution for you, but I hope this helps.
