### ISSUE TITLE
`public_url` is missing in `com.slack.api.model.Team`

### ISSUE THREAD

**Issue by Spencer857** [slackapi/java-slack-sdk#1338]
`https://slack.com/api/team.info` sometimes returns `public_url` that contains team website URL. But there is no corresponding field in `com.slack.api.model.Team`.

**Comment by srajiang** [comment]
@Spencer857 Thank you for raising this! Confirming that yes `public_url` is a part of the Team schema and probably should be added to com.slack.api.model.Team.

 I've tagged this as an enhancement, and I'll defer to @seratch as to which milestone to drop this into!

**Comment by seratch** [comment]
Hi @Spencer857, would you mind sharing the difference between url and public_url you've observed? Usually, only team.url is available in a response, which also represents the public `xxx.slack.com` URL. I understand that you've surely received public_url too but wanted to know when and how it can happen before adding the property anyways.

**Comment by Spencer857** [comment]
I noticed that it represents a company website, e.g., `https://acmecorp.com`.

**Comment by seratch** [comment]
Thank you. The property will be added in the next release.
