### ISSUE TITLE
block_suggestion response does not support description in an option

### ISSUE THREAD

**Issue by ESteanes** [slackapi/java-slack-sdk#1343]
https://api.slack.com/reference/block-kit/composition-objects#option

We should be able to add a plain text description to an option object - this is possible using the API but is not available in the SDK

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by seratch** [comment]
Hi @ESteanes, thanks for writing in! [This class](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/block/composition/OptionObject.java) represents the option data structure and it has the description fileld! Hope this helps.

**Comment by ESteanes** [comment]
In that case, are we able to make [BlockSuggestions](https://github.com/slackapi/java-slack-sdk/blob/main/slack-app-backend/src/main/java/com/slack/api/app_backend/interactive_components/response/BlockSuggestionResponse.java#L14) accept the OptionObject class?

**Comment by seratch** [comment]
@ESteanes Oh, I see. The option value didn't support description in the past, but indeed, having a description is now feasible. The class needs to be updated to support the use case. Thanks for reporting this issue! We will resolve it in the next patch version release.
