### ISSUE TITLE
No event class for `channel_convert_to_public`

### ISSUE THREAD

**Issue by mgroth0** [slackapi/java-slack-sdk#1348]
I could not deserialize an event I got from a webhook with this type because there is no class for it. I am using `gson` deserializing which involves statically registering a class for each event type with `EventsApiPayloadParser`.

**Comment by zimeg** [comment]
@mgroth0 no problem! I haven't tested this myself, but a bit more typing might be needed to satisfy the complete `channel_convert_to_public` patterns I think. I'd recommend referencing the parsing for `MessageChannelArchiveEvent` using the above values for now:

- https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/event/MessageChannelArchiveEvent.java
- https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/test/java/test_locally/api/model/event/MessageChannelArchiveEventTest.java

I'm not sure when SDK support might be added either, but I'm searching for more info on the actual event! 📚

> You wouldn't happen to know if there is a way with Slack webhooks to generate fake events of every type for testing purposes would you?

This is a wishlist item of mine haha 🎁 👀  Right now no, but our [developer program](https://api.slack.com/developer-program) offers sandboxed workspaces just for testing! It's not quite programatic but is still so super useful for testing edges 🙏

**Comment by seratch** [comment]
Since this message subtype pattern is not yet available in our public document [here](https://api.slack.com/events/message), I've removed the "bug" label from this issue. With that being said, once we add this pattern to the document, we should support the event payload out of the box!
