### ISSUE TITLE
slack-api-model wrong element type for timestamp in RichTextSectionElement.Date

### ISSUE THREAD

**Issue by jed204** [slackapi/java-slack-sdk#1363]
The timestamp element in doesn't align with the type in the reference documentation. https://api.slack.com/reference/block-kit/blocks#date-element-type

This leads to the block being invalid and rejected by the server.

#### The Slack SDK version

1.4.2

#### Expected result:

```
RichTextSectionElement.Date.builder().format("{date_num}").timestamp(Instant.now().getEpochSecond() + "").build()
```

 should encode to:

```
{
  "type" : "date",
  "timestamp" : 1725726588,
  "format" : "{date_num}",
}
```
(this format passes the Block Kit Builder checks)

#### Actual result:

```
{
  "type" : "date",
  "timestamp" : "1725726588",
  "format" : "{date_num}",
}
```
(this format fails the Block Kit Builder checks due to invalid type)

**Comment by jed204** [comment]
@seratch any idea on timing of the 1.4.2.1 release? Not a huge rush on my side - just looking for a broad timeframe. Thanks!

**Comment by seratch** [comment]
I plan to release the version tomorrow! At the latest, by the end of this week for sure.
