### ISSUE TITLE
Internal Validation Error in Modal with RichTextInputElement

### ISSUE THREAD

**Issue by azihsoyn** [slackapi/java-slack-sdk#1381]
It seems that passing RichTextSectionElement.Text to the initialValue of RichTextInputElementBuilder as shown below results in a validation error within Slack’s modal after [this change](https://github.com/slackapi/java-slack-sdk/pull/1337).

```kt
val richTextSectionElement = RichTextSectionElement.Text(
    text,
    RichTextSectionElement.TextStyle(false, false, false, false, false, false, false)
)

BlockElements.richTextInput { rti: RichTextInputElement.RichTextInputElementBuilder ->  
    rti.actionId(SOME_ACTION_ID).initialValue(richTextSectionElement)  
}
```
(Sorry for the Kotlin code examples.)

I believe the fields `"highlight": false, "client_highlight": false, and "unlink": false` are not allowed in the modal, which is likely causing this issue.

To work around this, you can create the elements using:

```kt
RichTextSectionElement.Text.builder().text(
    text
).build()

RichTextSectionElement.Link.builder().url(
    url
).build()
```

This issue does not occur in version 1.40.2, and it seems to be related to the changes in version 1.40.3.

#### The Slack SDK version

1.40.3 and above

#### Expected result:

The expected behavior is that either no implicit validation error occurs, or a clear validation error is explicitly shown.

#### Actual result:

At first glance, everything seems fine, but no action can be performed unless the initial value is changed (this appears to be a validation error).

**Comment by azihsoyn** [comment]
I have registered the issue, including sharing it with other users. Thanks.

**Comment by seratch** [comment]
Hi @azihsoyn, thanks for writing in.

> RichTextSectionElement.TextStyle(false, false, false, false, false, false, false)

Indeed, a few more arguments were added and some of them may not work for modals. The allowed properties can be changed over time, so we hesitate to add more sub classes specifically for modal views. My recommendation is to avoid using the all-arg constructor. You can use TextStyle's builder method as an easy way to construct a valid object.

If you mean that not only the all-arg constructor use case but also other code patterns do not work, please share code snippets demonstrating it. Either Kotlin or Java is fine.

**Comment by azihsoyn** [comment]
@seratch Thank you for the quick response!

> TextStyle’s builder method

I wasn’t aware of the TextStyleBuilder. It seems that this will work well on my side as well.

> If you mean that not only the all-arg constructor use case but also other code patterns do not work

The issue I found is only with the all-arg constructor case.

**Comment by seratch** [comment]
I got it. Let me close this issue now, but please feel free to write in whenever you have follow-up comments. thank you again for taking the time to share this!
