### ISSUE TITLE
Migrating AWS S3 SDK to v2

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#1402]
As reported at https://github.com/slackapi/java-slack-sdk/pull/1168#pullrequestreview-2474523299, our optional dependency AWS S3 client SDK must be migraded to its v2 by the end of 2025.

Both groupId and artifactId are different:
```diff
-            <groupId>com.amazonaws</groupId>
-            <artifactId>aws-java-sdk-s3</artifactId>
+            <groupId>software.amazon.awssdk</groupId>
+            <artifactId>s3</artifactId>
```

Here is a version range example:
```diff
-        <aws.s3.version>[1.12.62,1.13.0)</aws.s3.version>
+        <aws.s3.version>[2.29.24,3)</aws.s3.version>
```

V2 is fully source-code incompatible, so this work requires rewriting the modules relying on the AWS SDK plus testing the behavior is still the same. It seems there is no need to migrate "aws-lambda-java-core" to something new this time.

See also:
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration.html
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-service-changes.html
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-client-credentials.html
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-java.html

We may want to try the migration tool if it works well for us:
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-tool.html

### Category (place an `x` in each of the `[ ]`)

* [x] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

**Comment by Ankush1oo8** [comment]
So to change only dependicies or other code also

**Comment by seratch** [comment]
Thanks for your interest! but I started working on this. Hope we can work together for future tasks

**Comment by acharyashashank** [comment]
Current Limitations of Migration Tools: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-tool.html#migration-tool-limitations
