### ISSUE TITLE
Is there a way to set up two oauth redirect path in Slack Bolt?

### ISSUE THREAD

**Issue by r-k-m-start1031** [slackapi/java-slack-sdk#1404]
I apologise for my poor English. 
I'm developing a slack bot in kotlin and slack bolt and spring boot.

oauth redirect controller
```kotlin
@WebServlet("/slack/oauth_redirect/a")
class AOauthRedirectSlackAppOAuthController(app: App) : SlackOAuthAppServlet(app)

@WebServlet("/slack/oauth_redirect/b")
class BOauthRedirectSlackAppOAuthController(app: App) : SlackOAuthAppServlet(app)
```

The slack install links have their own path set as the redirect_url.
In addition, the OAuth & Permission Redirect URLs have their own paths set (There is no problem with setting only one `/slack/oauth_redirect`)

The path set in SLACK_REDIRECT_URI_PATH can accept redirects, but the other one cannot.
Also, two paths cannot be set in SLACK_REDIRECT_URI_PATH.

As an alternative,
I set `/slack/oauth_redirect` in SLACK_REDIRECT_URI_PATH and changed `oauthRedirectUriPath`, but I couldn't achieve it because `oauthCallbackPath` could not be changed.

```kotlin
@WebServlet("/slack/oauth_redirect/a")
class AOauthRedirectSlackAppOAuthController(app: App) : SlackOAuthAppServlet(app) {
  app.config().oauthRedirectUriPath += "/a"
  app.config().oauthCallbackPath += "/a" // value is not change
  super.doGet(req, resp)
}
```

Is there any way to solve this problem?

**Comment by hello-ashleyintech** [comment]
Hi, @r-k-m-start1031! thanks for submitting this issue! ✨ 

It is possible to use two Redirect URIs. See [this issue](https://github.com/slackapi/java-slack-sdk/issues/714) for more info.

Based on what you described, it sounds like this might be happening:
> From [here](https://api.slack.com/authentication/oauth-v2#obtaining): If there are multiple Redirect URL values configured, but no redirect_uri parameter is sent, the OAuth flow will use the first Redirect URL listed on the App Management page. You can use the redirect_uri parameter in your oauth/v2/authorize redirect as mentioned above and configure a Redirect URL in the App Management page. Your redirect_uri must match or be a subdirectory of a Redirect URL configured under App Management. A Redirect URL can not contain an anchor (#).

Are you setting the `redirect_uri` parameter in your OAuth flow? More info can be found [here](https://api.slack.com/authentication/oauth-v2#obtaining](https://tools.slack.dev/java-slack-sdk/guides/app-distribution/#slack-config-for-distributing-your-slack-app).

**Comment by r-k-m-start1031** [comment]
@hello-ashleyintech 
Thank you for your response.
Sorry but, I'm not able to communicate my problems well.

>Are you setting the redirect_uri parameter in your OAuth flow? More info can be found [here](https://tools.slack.dev/java-slack-sdk/guides/app-distribution/#slack-config-for-distributing-your-slack-app).

```kotlin
@WebServlet("/slack/oauth_redirect/a")
class AOauthRedirectSlackAppOAuthController(app: App) : SlackOAuthAppServlet(app)

@WebServlet("/slack/oauth_redirect/b")
class BOauthRedirectSlackAppOAuthController(app: App) : SlackOAuthAppServlet(app)
```
I have already set redirect_uri, and I am able to receive callback requests at both endpoints.
However, the following codes are treated as errors, and the message ‘No request pattern detected for’ is output to the console.
https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/util/SlackRequestParser.java#L160

In this case, a check is performed against SLACK_REDIRECT_URI_PATH, and since multiple paths cannot be set for SLACK_REDIRECT_URI_PATH, this problem could not be solved.
https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/AppConfig.java#L329

The variables here could not be rewritten using the method described above.
https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/AppConfig.java#L331
```kotlin
app.config().oauthCallbackPath += "/a" // value is not change
```


So, if there is another way, I would like to know about that solution.

**Comment by seratch** [comment]
I might not fully understand the problem you're facing, but generally, I would suggest manually instantiating `AppConfig` for the two `App` instances. This means using `new App(AppConfig.builder().xxx().yyy().build())` instead of relying on environment variables. Additionally, `oauthCallbackPath` is a legacy property name, and we recommend using only `oauthRedirectUriPath` for configuring the path. 

We have a Spring Boot 3 example app in this repo. The code does not enable two Bolt apps but modifying the code can eventually become what you want to build: https://github.com/slackapi/java-slack-sdk/tree/main/bolt-spring-boot-examples/spring-boot-3/src/main/java/example

**Comment by r-k-m-start1031** [comment]
@seratch 
Thank you for your response.

>I might not fully understand the problem you're facing, but I would suggest manually instantiating AppConfig for the two App instances for your use case. This means using new App(AppConfig.builder().xxx().yyy().build()) instead of relying on environment variables.

I see.
I'll give it a try.

> Additionally, oauthCallbackPath is a legacy property name, and we recommend using only oauthRedirectUriPath for configuring the path.

OK, this is scheduled to be removed in v2.0, right?



What I fundamentally want to do is create two installation links and determine which installation link the slack app was installed from at the OAuth callback destination.
Is there a good solution to this?

**Comment by seratch** [comment]
> this is scheduled to be removed in v2.0

Yes, we don't yet have any timeline for v2 release, but the legacy property may be deleted eventually.

>What I fundamentally want to do is create two installation links and determine which installation link the slack app was installed from at the OAuth callback destination.

Like we've talked above, creating two App instances and associating them to two start URL paths should be a good solution for this. Another approach would be to set browser cookies when starting the installation flow and then check the cookie value on the callback path side should work for this purpose.

**Comment by r-k-m-start1031** [comment]
@seratch @hello-ashleyintech 

>I might not fully understand the problem you're facing, but I would suggest manually instantiating AppConfig for the two App instances for your use case. This means using new App(AppConfig.builder().xxx().yyy().build()) instead of relying on environment variables.

Using this method, I was able to create sample code and confirm that the two redirects worked.
Thank you for your cooperation.

This issue has been closed.
Thank you for your support of this SDK!
I look forward to future updates.
