### ISSUE TITLE
RTMClient Connection Failing Silently

### ISSUE THREAD

**Issue by matteogales** [slackapi/java-slack-sdk#252]
First of all, thank you for writing such a well written API that has made writing a Slack Bot quick and pain free!

Having deployed a Slack application for internal use on AWS, I noticed that after several hours of inactivity (i.e. the application not receiving any messages from Slack, typically overnight) that the connection on the RTMClient appears to die (silently). 

I saw that there were "addCloseHandler" and "addErrorHandler" methods on the RTMClient class that could potentially be used to log the error and reconnect if the connection was dropped. 

Having implemented the RTMErrorHandler and RTMCloseHandler interfaces, added the respective objects as handlers on my instance of RTMClient, and produced a simple reconnection strategy, I then tested the outcome.

Once my Slack application successfully connected to Slack and had received some test messages that I sent from Slack, I pulled the network cable out of my development machine (leaving it out from between a few seconds to a few minutes) to see if the handlers were called.

While I could see other applications (e.g. WhatsApp) on my development machine reporting disconnection errors, and then reconnecting when I put the cable back, I did not see (was running my application in IntelliJ with breakpoint sets, and had logging in place) that my implementations of RTMErrorHandler and RTMCloseHandler were being called.

I also noticed that once I had plugged my network cable back in, and then sent further test messages from Slack, that my application was receiving these messages, so I am guessing that the API must have some kind of internal reconnection facility (?).

Could you please tell if the above behaviour (i.e. the implementations of RTMErrorHandler and RTMCloseHandler not being called) is expected and if there is some way that I can make these methods get called as soon as a connection to Slack is broken (or provide similar behaviour, such as periodically checking if the RTMClient is connected to Slack, and if not reconnecting)?

I have upgraded to version 3.0.1 of the API (from Maven), and was testing this on "Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)" on version 10.13.6 of macOS. I have included a class that it is a cut down version of what I trying to do below.

Please let me know if you need any further information.

```
import com.github.seratch.jslack.*;
import com.github.seratch.jslack.api.rtm.*;

import javax.websocket.*;

/**
 * Run the below application then disable network connection to Slack and see if RTMCloseHandler and RTMErrorHandler methods are called.
 */
public class RtmClientErrorExample implements RTMCloseHandler, RTMErrorHandler, RTMMessageHandler
{
   /**
    * @param unused Unused program arguments.
    */
   public static void main(String[] unused) throws Exception
   {
      String botAccessToken = "Bot User OAuth Access Token";
      RtmClientErrorExample example = new RtmClientErrorExample(botAccessToken);
   }


   /**
    * Connects to slack using the provided Bot User OAuth Access Token.
    *
    * @param botAccessToken The Bot User OAuth Access Token.
    */
   private RtmClientErrorExample(String botAccessToken) throws Exception
   {
      Slack slack = Slack.getInstance();
      RTMClient rtmClient = slack.rtm(botAccessToken);

      rtmClient.addMessageHandler(this);
      rtmClient.addErrorHandler(this);
      rtmClient.addCloseHandler(this);

      rtmClient.connect();
   }

   /**
    * @see RTMMessageHandler
    */
   public void handle(String message)
   {
      System.out.println("Received a message from Slack: " + message);
   }

   /**
    * @see RTMErrorHandler
    */
   public void handle(Throwable throwable)
   {
      System.out.println("Received an error from Slack: " + throwable.getMessage());
   }

   /**
    * @see RTMCloseHandler
    */
   public void handle(CloseReason closeReason)
   {
      System.out.println("Connection to Slack was closed: " + closeReason);
   }
}
```

**Comment by matteogales** [comment]
I have found that periodically checking the connection using a ApiTestRequest, seeing if this can be sent and if so checking the ApiTestResponse, allows me to determine if there is a connection.

If there is no connection (as determined by the above approach), I use the reconnect() method on my RTMClient instance to reconnect to Slack and receive messages once again.

However, It would be helpful to know if anyone thinks that this is a sensible/recommended approach, and if the behaviour/approach I describe in my original message is expected/preferred.

**Comment by seratch** [comment]
Thanks for the detailed information. Honestly, the `close` behavior is a bit surprising to me.

The RTM client internally uses this library for WebSocket connections. The behavior depends on the library.  https://github.com/seratch/jslack/blob/3.0.1/jslack-api-client/pom.xml#L46-L51

If you need a deep dive into this, check tyrus-standalone-client's code and consult the project maintainers.

**Comment by matteogales** [comment]
Thank you for the further information; I will look at the tyrus-standalone-client library and if there is some feature that I think can help will advise, and/or make a code contribution.

The code that I put in place that sends the ApiTestRequests (currently every 5 seconds) seemed to work correctly throughout last night but our app still appeared offline when I checked this morning.

I am now wondering if there is some setting in Slack that I am unaware off that means that the app gets logged out out after a period of time etc.

I have setup a support request with Slack to find out, and if they have some system logs that can help determine the issue, or at least when it is happening.

Just in case they ask, could you please tell me what underlying message (type) that the ApiTestRequest is sending to Slack?

If there is some other test that I can send that is more specific to the RTM (just in case that request type is not testing the RTM connectivity), then please let me know.

Many thanks!!

**Comment by matteogales** [comment]
Thank you for the further information and quick follow up.

Through debugging (and IntelliJ's decompiler) I noticed that the ApiTestRequest wasn't testing the web socket state but sending a message to https://slack.com/api/api.test (sorry, my mistake).

I seem to have resolved the issue (although need to monitor over a more extended time to be sure) by sending "ping" messages using RTMClient.sendMessage(String) and RTMMessageHandler to (hopefully!) receive "pong" messages, and if not, or latency spikes, using RTMClient.reconnect().

As part of this testing I noticed that when my network cable was taken out that it took a few calls (between 2 and 4) on RTMClient.sendMessage(String) before any Exception was thrown from the method to indicate there was no connectivity (my code was calling this method every 5 seconds).

While I didn't look into this in detail, I'm guessing that this is something related to the underlying socket library being called asynchronously, so make take a while before it registers an issue.

**Comment by seratch** [comment]
That makes sense. Hope you won't encounter any issues.

**Comment by seratch** [comment]
@matteogales Hello, how have things been going? Regarding this GitHub issue, I think I don't have anything further I can do for you. If you don't mind, can I close this issue now?

**Comment by matteogales** [comment]
Sorry, should have closed this off; thank you for your help on this.
