### ISSUE TITLE
Undefined signing secret causes NullPointerException

### ISSUE THREAD

**Issue by ace-n** [slackapi/java-slack-sdk#359]
### Issue Type
- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description
Failing to provide a `SLACK_SECRET` to `SlackSignature.Generator`'s constructor causes a `NullPointerException` when calling the resulting `Generator`'s `generate()` method.

---
The issue is reproducible in:
JSlack version: `3.4.1`
OS: `OSX 10.15.3` (though this shouldn't matter)

Repro steps:
1) First, initialize a `SlackSignature.Generator` object **without a signing secret**:
```java
SlackSignature.Generator gen = new SlackSignature.Generator()
```

2) Attempt to generate a message's signature:
```java
gen.generate("1970-01-01T00:00:00Z", "{}")
```

The expected result is:
An `Exception` warning that `SLACK_SECRET` is not defined

The actual result is:
A `NullPointerException` on [line 87 of `SlackSignature.java`](https://github.com/slackapi/java-slack-sdk/blob/8e8ef794e7033e1340aa86abd8acdb2dee5d704d/slack-app-backend/src/main/java/com/slack/api/app_backend/SlackSignature.java#L87).

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Thanks for taking the time to give this feedback 🙏 I will apply the improvement to both jSlack and this 1st party Java Slack SDK.
