### ISSUE TITLE
ChatUnfurlRequest.UnfurlDetail doesn't match the expected API payload

### ISSUE THREAD

**Issue by panghy** [slackapi/java-slack-sdk#399]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

The current fields within UnfurlDetail doesn't won't if you really try to use it, the example given by Slack at: https://github.com/slackapi/sample-app-unfurls/blob/8b2b610e4ad5a2e64d9dd0fae64deac43d9a1c26/basic.js#L22 suggests that each url should have an attachment. Perhaps the attachmentType would dictate what the UnfurlDetail (Slack's documentation is very sparse on this).

---

The issue is reproducible in:
* Module Version: 1.0.0-RC3
* JDK Version: 11.0.2

The steps to reproduce are:
1. Try to respond to a link event with an unfurl.
2. Notice that if you send blocks in the response ("title" and "text" works), Slack cannot parse the attachment

The expected result is:
One is able to attach "fields" to the unfurl details. Other fields should include: "fallback" (which is already in UnfurlDetail today), "color", "title_link" and "image_url".

The actual result is:
If one were to just construct an UnfurlDetail with a single LayoutBlock in "blocks", Slack would not accept it.

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@panghy 
Thanks for taking the time to report this.

Regarding the issue with blocks, you cannot use the attachment-related fields (title, image_url, etc are for attachments) and blocks at the same time. So, please use only Block Kit elements when you go with blocks.

Separately from that, as you mentioned, some fields for attachments were not yet supported in this SDK. I just created a pull request #400 for more support. [A test code in the PR](https://github.com/seratch/java-slack-sdk/blob/5b5f77b78e40dfb4730d8162bf69b7efd06bf8d0/slack-api-client/src/test/java/test_with_remote_apis/methods/chat_Test.java#L486-L538) demonstrates how to build an attachment in the **sample-app-unfurls**. 

<img width="400" src="https://user-images.githubusercontent.com/19658/76731680-54e65c00-67a1-11ea-9e6e-e4ce55701103.png">


The fix will be included in version 1.0.0 release. Thank you!

**Comment by panghy** [comment]
Thanks so much for the quick turnaround!
