### ISSUE TITLE
Proxy support for RTM Client

### ISSUE THREAD

**Issue by atul2017** [slackapi/java-slack-sdk#4]
Does anyone modify RTM client for proxy support. I have proxy setup between my client and slack channel. I tried to do it in RTMClient class but websocket does not have any method to handle the proxy. Please share your code..

**Comment by cypressious** [comment]
It looks like jslack uses OkHttp. Construct an `OkHttpClient` with your proxy settings according to http://stackoverflow.com/questions/37866902/okhttp-proxy-settings and then call `Slack.getInstance(SlackHttpClient(client))` to create a custom slack client.

**Comment by seratch** [comment]
RTMClient doesn't use ok-http. Unfortunately, the WebSocket implementation doesn't support using proxy so far. https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/api/rtm/RTMClient.java

**Comment by MaxG2395** [comment]
Hello, sorry for replying to an old thread, however, does the RTMClient support proxy as of now?

**Comment by seratch** [comment]
Not yet supported.

**Comment by seratch** [comment]
I looked at this a little bit before and thought that it would be possible to support proxy. But I need more time. If someone knows very well about [Project Tyrus](https://github.com/tyrus-project/tyrus), I would love to hear some advice on how to properly implement it in this project.

**Comment by tutufool** [comment]
Any update on this?  I may have similar issue that I'm in an internal network which requires special http proxy to call external address like slack. (both RTM and Web API）

**Comment by seratch** [comment]
@tutufool after 3+ years, I managed to fix this issue. I'm going to backport this to the jSlack library.

**Comment by tutufool** [comment]
btw, can I use jvm level proxy for now as alternative solution?

https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

**Comment by seratch** [comment]
@tutufool probably, no. could you try it out?

**Comment by tutufool** [comment]
will the fix available soon in next release?

**Comment by seratch** [comment]
@tutufool Yes, I've shipped jSlack version 3.4.1 that includes the fix today. Could you try the version out when you have a chance? https://github.com/seratch/jslack-maintenance-releases/pull/4

**Comment by tutufool** [comment]
cool, thanks a  lot !
