### ISSUE TITLE
Hint for a Modal Surface's Input block

### ISSUE THREAD

**Issue by MMotta-zAgile** [slackapi/java-slack-sdk#410]
### Issue Type

Place an `x` in one of the `[ ]`.

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description
According to the [Slack Block kit Reference for Layout blocks](https://api.slack.com/reference/block-kit/blocks#input), the Input block available on the **Modals** surface allows to have the optional field **hint** as a **text object** with a type of **plain_text**; however **hint** is defined as a **String** in the **com.slack.api.model.block.InputBlock** class

The issue is reproducible in:
* Module Version: slack.api.model: 1.0.1
* JDK Version: openjdk version "1.8.0_242"
* OS Version etc: Ubuntu 18.04.4 LTS

The steps to reproduce are:

1. Define a new [Slack Modal View](https://github.com/slackapi/java-slack-sdk/blob/master/slack-api-model/src/main/java/com/slack/api/model/view/View.java)
2. Add an Input Block with a hint
```
import static com.slack.api.model.block.Blocks.*;
import static com.slack.api.model.block.composition.BlockCompositions.*;
import static com.slack.api.model.block.element.BlockElements.*;
import static com.slack.api.model.view.Views.*;
...
view(view -> view
                .callbackId("slack-view-sample")
                .type("modal")
                .notifyOnClose(true)
                .title(viewTitle(title -> title.type("plain_text").text("Slack View for InputBlock")))
                .submit(viewSubmit(submit -> submit.type("plain_text").text("Submit")))
                .close(viewClose(close -> close.type("plain_text").text("Cancel")))
                .blocks(asBlocks(
                        input(input -> input
                                .blockId("input-block")
                                .element(plainTextInput(pti -> pti.actionId("input-block-field").maxLength(255)))
                                .label(plainText(pt -> pt.text("Input Block")))
                                .hint("Maximum 255 characters")
                        )
                ))
    );
```
3. Add the Slack Modal View to an *App* command and invoke the command in Slack

The expected result is:
- The Slack Modal shows an input block with a hint

The actual results is:
- An error is returned when trying to create the Slack Modal Surface
`ViewsOpenResponse(ok=false, warning=null, error=invalid_arguments, needed=null, provided=null, view=null, responseMetadata=ErrorResponseMetadata(messages=[[ERROR] failed to match all allowed schemas [json-pointer:/view], [ERROR] must provide an object [json-pointer:/view/blocks/0/hint]]))`

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by MMotta-zAgile** [comment]
The following git diff fixes the problem

[issue-410.zip](https://github.com/slackapi/java-slack-sdk/files/4405960/issue-410.zip)

**Comment by seratch** [comment]
@MMotta-zAgile Thank you very much for reporting this and the perfect patch. I've submitted a PR #412 addressing this. I will release a new patch version within a few hours.

**Comment by seratch** [comment]
Thank you very much again for taking the time to report this. A new version - 1.0.2 is out now. Please try it out when you have a chance.

**Comment by MMotta-zAgile** [comment]
I have tested version 1.0.2 and it is working as expected.
Thank you for promptly applying the patch.
