### ISSUE TITLE
attachment .blocks results in invalid_attachments response

### ISSUE THREAD

**Issue by untra** [slackapi/java-slack-sdk#415]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description
(using the sdk in kotlin, pardon any confusing syntax differences)

nonempty `.blocks` added to an attachment will not post to the slack api, responds `400 invalid_attachments`. Might also be related to #184 and #187 

I have been posting to our webhook with plain JSON, and this seems to work fine:

```
curl -X POST -H 'Content-type: application/json' --data '{ "attachments": [ { "color": "#00FF00", "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "*I would expect this text to show*" } } ] } ] }' https://hooks.slack.com/services/MY/WEBHOOK
```

However when I try to use the sdk payload builder, it wont send at all (and I think this is being constructed right)

```kt
val payload = Payload.builder()
.attachments(asAttachments(
    attachment { a -> a.color("#00FF00").blocks(asBlocks(
        section { s -> s.text(markdownText("*I would expect this text to show*")) }
    )) }
))
.build()
```

I can however send this payload (empty blocks):

```kt
val payload = Payload.builder()
.attachments(asAttachments(
    attachment { a -> a.color("#00FF00").blocks(asBlocks()) }
))
.build()
```

and this payload will send too (separate blocks and attachments):

```kt
val payload = Payload.builder()
.blocks(asBlocks(
    section { s -> s.text(markdownText("block text!")) }
))
.attachments(asAttachments(
    attachment { a -> a.color("#00FF00").text("attachment text!) }
))
.build()
```

but to construct our message as intended, we cant seem to get payloads constructed with attachments with blocks to post at all at runtime.

The issue is reproducible in:
* Module Version: 1.0.2
* JDK Version: **TODO**: Run `java -version` and pates the result here
```kt
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

```
* OS Version etc: **TODO**: if the issue happens only with specific OS

The steps to reproduce are:
```kt
val slack = Slack.getInstance()
val payload = Payload.builder()
.attachments(asAttachments(
    attachment { a -> a.color("#00FF00").blocks(asBlocks(
        section { s -> s.text(markdownText("*I would expect this text to show*")) }
    )) }
))
.build()
res = slack.send(webhook, payload)
if (res.code != 200) {
  print("slack reported status ${res.code}: ${res.body}")
}
```

The expected result is:

> Either the sdk tells me at compile time what I'm building is incorrect/wont send. Otherwise the api should respond success to the message I'm sending.

The actual result is:

> `400 invalid_attachments`

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@untra Thanks for the detailed report! I will take a look at this today.

**Comment by seratch** [comment]
@untra Thanks for reporting this. I've verified the issue and came up with a PR addressing this #416 
After merging the PR, I will ship a new patch version within a few hours.

**Comment by seratch** [comment]
A new version (1.0.3) including the fix for this issue has been published to the Sonatype OSS repository. The artifacts will be available also in Maven Central soon.

Thank you very much for reporting this issue. Try v1.0.3 out when you have a chance!

**Comment by untra** [comment]
@seratch thanks for the speedy reply, confirmation, and fix! 💪

I've been trying out v1.0.3 and this works as intended now. I was going a little crazy yesterday testing out this sdk for the first time, but I'm so glad to see I was finding a genuine issue and not making a rookie mistake. Serious props to the Slack team for releasing this speedy fix.

Everything else about the sdk seems to work just right for us, but we're still breaking it in. Cheers friend!
