### ISSUE TITLE
Website 404s

### ISSUE THREAD

**Issue by flyinprogrammer** [slackapi/java-slack-sdk#418]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [x] Documentation

### Description

The website is currently 404ing

---

The steps to reproduce are:
1. Go to https://slack.dev/java-slack-sdk/ in a web browser
2. Witness 404

The expected result is:
The beautiful website is there.

The actual result is:
It 404s.

<img width="1101" alt="Screen Shot 2020-04-03 at 10 03 14 AM" src="https://user-images.githubusercontent.com/1844847/78375696-cb050400-7592-11ea-9df5-b226e232aca9.png">

---

Here's a fun picture of an animal to brighten your day:

![kiy-turk-L_onJEdt4sU-unsplash](https://user-images.githubusercontent.com/1844847/78375979-44045b80-7593-11ea-9deb-3cdd7e30da1f.jpg)

Photo by [Kiy Turk](https://unsplash.com/@kiy_turk) on [Unsplash](https://unsplash.com/)

---

### Requirements

* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Thank you for reporting this and I'm sorry for the inconvenience. The team is on it.

**Comment by seratch** [comment]
The issue has been fixed. I'm sorry again for the inconvenience.

**Comment by flyinprogrammer** [comment]
no problem at all you're a hero @seratch !
