### ISSUE TITLE
SlackApiLambdaHandler forbids access to App

### ISSUE THREAD

**Issue by acm19** [slackapi/java-slack-sdk#419]
### Issue Type

- [ ] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

`SlackApiLambdaHandler` is very handy to quickly create a working lambda slack bot. The problem is when you extend from it you have to call it's constructor passing an `App` instance, but you don't have an easy way to modify that instance later on. I can think of a few examples where that is important:
- I would like to add a middleware on top of the default ones. When a single call to `App#use` would suffice I need to either replicate the logic of `buildDefaultMiddlewareList`, use composition instead of inheritance or use a static `App`.
- I would like to add a handler for command, for example. A call to `App#command` would be enough but I have to do some of the workarounds described previously.

I guess the idea is express and no more use cases are required. Would you consider changing this? Is there a reason why you did it this way? Even though create a working lambda would be fast with this class doing something useful would require some kind of workaround as it is.

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@acm19 Hello, thank you for taking the time to write this feedback. Currently, it is supposed to be used like this:

```java
import com.slack.api.bolt.App;
import com.slack.api.bolt.aws_lambda.SlackApiLambdaHandler;
import com.slack.api.bolt.aws_lambda.request.ApiGatewayRequest;

class SampleHandler extends SlackApiLambdaHandler {
  // or having this method in another class is also fine
  static App initializeApp() {
    App app = new App();
    app.command("/echo", (req, ctx) -> ctx.ack(req.getPayload().getText()));
    return app;
  }

  public SampleHandler() { this(initializeApp()); }
  public SampleHandler(App app) { super(app); }
  @Override
  protected boolean isWarmupRequest(ApiGatewayRequest awsReq) { return false; }
}
```

For your information, here is a tiny example written in Kotlin. https://github.com/seratch/bolt-kotlin-on-aws-lambda/blob/master/src/main/kotlin/hello/aws/SlackApiHandler.kt

Do you have an issue with this approach? I can add the getter method for `private final App app;` in `SlackApiLambdaHandler`. But I'm not sure if it is really helpful for your use case yet.

**Comment by acm19** [comment]
Hi @seratch, thank you your quick reply. The problem with that approach is that to modify the app later on you would need to store it in a static variable, which seems weird to me. e.g. after some command you want to start handling a different type of events. Having a `protected` getter method to access `app` from its sub-classes seems a sensible way to do it IMO.

**Comment by seratch** [comment]
I think now I understand what you mean. I never assumed such use cases. It's an interesting design! I'm sure you store the Slack app's state like the completion of the command for setting up somewhere else (e.g., in a database) and your lambda functions access it. If so, the architecture works well.

I can add a protected getter method for the `app` field to the base class within a few days. If you're interested in contributing to this SDK, your pull requests are also welcome!

**Comment by seratch** [comment]
I just created a pull request for this issue. It will be merged soon. Feel free to leave your comments on it if you have.

**Comment by acm19** [comment]
I had created one as well, didn't get to push it before you :) thank you. I'll share it with you anyway as there are a couple of other stuff that might be helpful. I'll have a look today when I leave work.

**Comment by acm19** [comment]
It looks great to me. I just added a comment. I've also submitted a PR of what I would do as well, maybe out of scope but I had written it already and might be useful. You can use some of that code if you want, specially the moving the Javadocs and `App#start` in the constructor might be useful. Thank you again for addressing this so quickly.

**Comment by seratch** [comment]
Thanks for your feedback. I'm going to release a new patch version this week.

**Comment by acm19** [comment]
Brilliant, cheers!
