### ISSUE TITLE
url_verification request fails with bolt-micronaut

### ISSUE THREAD

**Issue by mfuntowicz** [slackapi/java-slack-sdk#426]
Trying to setup the Event API on the Slack App website and setting up the Event callback URL, seems Bolt is not able to parse the `UrlVerificationRequest` properly.

I'm running Java 9 (through Kotlin), with Bolt 1.0.4 on Windows 10

```
[pool-1-thread-2] WARN com.slack.api.bolt.util.SlackRequestParser - No request pattern detected for token=[some_token]&challenge=2dasp7C5rbnT22y2v3IAT95S6WnNUtdpnFckQEQyGl7HjnTa0Y0K&type=url_verification
[pool-1-thread-2] DEBUG io.micronaut.http.server.netty.RoutingInBoundHandler - Encoding emitted response object [Invalid Request] using codec: io.micronaut.runtime.http.codec.TextPlainCodec@28561ca6
```

**Comment by seratch** [comment]
Thanks for reporting this. I've confirmed this is a bug where bolt-micronaut doesn't handle the request properly.

**Comment by seratch** [comment]
@mfuntowicz Thanks for reporting this issue. I just made a pull request addressing the issue at #427. The adapter consists of only two classes here. If you're in a hurry, please copy those to your application. https://github.com/seratch/java-slack-sdk/tree/6386b1dc4b0fb8d0b4c473fea59e3e496fb39611/bolt-micronaut/src/main/java/com/slack/api/bolt/micronaut
