### ISSUE TITLE
Feature parity comparison with slack js-sdk

### ISSUE THREAD

**Issue by Hariprasad-Ramakrishnan** [slackapi/java-slack-sdk#438]
### Issue Type
- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description
Is there a feature parity comparison document for java-sdk vs the js-sdk. This will enable us to choose one sdk over another.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @Hariprasad-Ramakrishnan 👋 
When it comes to the coverage of the Slack Platform features, there is no major difference. 

Both (and we're planning to release Bolt for Python sometime this year. So, eventually three language versions will be available) support the latest features such as Shortcuts, Modals, App Home, Slash Commands, Events API, and so on. 

That said, at this point, Bolt for JS doesn't have the following features yet while Java already supports.

* Built-in OAuth flow implementation
  * This feature will be available in JS too very soon: https://github.com/slackapi/bolt/issues/478
  * https://slack.dev/java-slack-sdk/guides/app-distribution
* SCIM API
  * https://slack.dev/java-slack-sdk/guides/scim-api
* Audit Logs API
  * https://slack.dev/java-slack-sdk/guides/audit-logs-api

Regarding SCIM and Audit Logs, we don't have any plans to support these APIs in other SDKs in the short term. If it's crucial to access such Enterprise Grid features utilizing 1st party SDKs in your use cases, the Java SDK may be a great fit.

Considering the characteristics and pros/cons of language and runtime, Java SDK is not a non-blocking (in other words, event-loop based) programming model while being non-blocking is the nature and the only way in the Node.js world. I recommend choosing the language your team members are most comfortable with.

**Comment by Hariprasad-Ramakrishnan** [comment]
Thanks a lot for the detailed explanation @seratch ...
