### ISSUE TITLE
Add support for Dynamic Select in Dialogs.

### ISSUE THREAD

**Issue by favalos** [slackapi/java-slack-sdk#439]
There are some recent changes at the end of the [Slack Dialog Page](https://api.slack.com/dialogs)

> We introduced key new features to Dialogs:
> 
- > Dynamic select menus support user, conversation, and channel selection.
- > You can populate selections on demand from remote data sources.
- > You can organize options into options_groups.

Place an `x` in one of the `[ ]`.

- [ ] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Your change has been merged into master. Thanks for flagging this and making the fix!
