### ISSUE TITLE
RTM: Process finished with exit code 0

### ISSUE THREAD

**Issue by asthmatic** [slackapi/java-slack-sdk#443]
After connecting with RTM client, if about 30-60 seconds has passed I get a `Process finished with exit code 0` with no error.

Related code:
```
Slack slack = Slack.getInstance();
RTMClient rtmClient = slack.rtm("xoxb-...");
rtmClient.connect();
```
Is this something that is supposed to happen with RTM? If yes then how to I avoid it? This problem aside I can use RTM just fine for listening events and sending messages.

**Comment by seratch** [comment]
Hello, `RTMClient` doesn't have any feature to manage your java process. Even when the client gets some exceptions, it doesn't result in the termination of the whole process.

Try the following example. You may find more information for identifying the cause of your issue. You can run this example just by `SLACK_BOT_TOKEN=xoxb-*** gradle run`.

```gradle
// build.gradle
plugins {
  id("application")
}
repositories {
  mavenCentral()
}
dependencies {
  implementation("com.slack.api:slack-api-client:1.0.6")
  implementation("org.slf4j:slf4j-simple:1.7.30")
  implementation("org.glassfish.tyrus.bundles:tyrus-standalone-client:1.16")
}
application {
  mainClassName = "Example"
}
```

```java
// src/main/java/Example.java 
import com.slack.api.Slack;
import com.slack.api.rtm.RTMClient;

public class Example {
    public static void main(String[] args) throws Exception {
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel","DEBUG");
        Slack slack = Slack.getInstance();
        String classicAppBotToken = System.getenv("SLACK_BOT_TOKEN");
        RTMClient rtm = slack.rtmConnect(classicAppBotToken);
        rtm.connect();
        Thread.sleep(Long.MAX_VALUE); // just for an example
    }
}
```

**Comment by asthmatic** [comment]
Thanks! I tried your example but the results are not telling me much. So its probably related to my setup and not RTMClient or Slack? Being new to the Java so maybe I have missed something important in IDE/Project setup...

```[Grizzly(1)] DEBUG com.slack.api.rtm.RTMClient - session opened: 23ab698f-d122-4de1-a4b4-2ce3f93be81f
[main] DEBUG com.slack.api.rtm.RTMClient - client connected to the server: wss://cerberus-xxxx.lb.slack-msgs.com/websocket/yxunderjvR_ULOPPadMpa3epgDxtVBXKrH1nOZjqf5tBgDckCYAKlMMcUpcw6JqqG7NmF7A7JbjDrvjwXj9g_n-CxbcWy0feu3ySi-CiAy0=
[Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - message: {"type": "hello"}

BUILD SUCCESSFUL in 1m 3s
2 actionable tasks: 2 executed
05:36:03: Task execution finished 'Example.main()'.```

**Comment by seratch** [comment]
>Thread.sleep(Long.MAX_VALUE); seems to work, proccess doesn't exit but is this a normal solution?

It's one easy way to run a process but of course, it's not the only way. Writing your own main loop that can do more or running a process as an HTTP server (to provide more functionalities/endpoints/web pages) are more common patterns. It depends on what you want to achieve.
