### ISSUE TITLE
Regarding conversations.create API, user_ids support

### ISSUE THREAD

**Issue by Hariprasad-Ramakrishnan** [slackapi/java-slack-sdk#447]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

Is there a way to pass user-ids in `conversations.create` API. I don't think java-client supports it now.

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Hariprasad-Ramakrishnan** [comment]
Also wanted to ask, we are currently building an app which will be distributed across slack workspaces. Is user-ids mandatory to be added on channel create ?

**Comment by seratch** [comment]
@Hariprasad-Ramakrishnan The "workspace app" in [the API document](https://api.slack.com/methods/conversations.create#arg_user_ids) is [this one](https://api.slack.com/legacy/workspace-apps). So, you don't need to worry about it. Just creating a conversation and invite members to the channel would work.

**Comment by Hariprasad-Ramakrishnan** [comment]
Thanks for your swift reply. Okay so I'll make 2 API calls for now, once for creating channel and one for inviting members. Will userIds support come anytime soon, just wanted to know.

**Comment by seratch** [comment]
There is nothing I can share with you at this point.

**Comment by Hariprasad-Ramakrishnan** [comment]
Okay thanks !!
