### ISSUE TITLE
Use payload classes without depending on Bolt framework

### ISSUE THREAD

**Issue by natevaughan** [slackapi/java-slack-sdk#458]
### Move interactive payloads to `com.slack.api:slack-api-model`

- [ ] Bug
- [x] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Allow apps not using Bolt to easily deserialize interaction payloads by moving interactivity payloads to the `com.slack.api:slack-api-model` module

Hi!

First, thanks for your amazing work on this SDK. I have to say it's one of best SDK I've yet used; you clearly know how to think like a user of the API and design from the user perspective. Really appreciate the fluent builder APIs throughout and attention to detail in the documentation, particularly the "Under the Hood" pseudocode sections. It only took a few hours to rip out our home-cooked Kotlin Slack SDK and replace it with this library.

My use case is this: I happen to be using Kotlin + Spring Boot to build a slack app that uses the interaction API extensively. I'm uninterested in using Bolt to enable interactivity for two primary reasons: 
 - I prefer not to add a second way of exposing API endpoints in my servlet container
 - Slack is one of many integrations in my application. The less special treatment, the better.

Currently, I'm enabling interactivity as follows:
 - Expose an interactivity endpoint in a traditional Spring Boot controller
 - Accept payloads as `application/x-www-form-urlencoded` and let Spring boot turn that into a `MultiValueMap<String, String>`
 - Deserialize the interaction payload once using GSON to a very simple data type to check the `type`. My simple deserialization class looks like this: `data class SlackActionType(val type: String)`. Because of the slack API design, I don't see any way around this.
 - Deserialize the interaction payload a second time based on the `type` to the appropriate `com.slack.api.app_backend` type (e.g. `BlockActionPayload` or `ViewSubmissionPayload`).
 - ...
 - Profit!

Unfortunately, to deserialize interaction payloads, I have to pull in the entire `com.slack.api:bolt-servlet` dependency. 

I'd love for all of the interaction `Payload` classes to be pulled up into `com.slack.api:slack-api-model` module or alternatively a new module.

Thanks again for the amazing work on this SDK!

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@natevaughan I'm very glad to hear that this project is of value to you!

Regarding the question here, I think there is no necessity to depend on `bolt-servlet` dependency. Your project requires only `slack-api-model` and `slack-app-backend`. The interactivity payloads you mentioned are in `slack-app-backend`. This package provides primitive classes and APIs and is a foundation of Bolt. Needless to say, it doesn't depend on Bolt.

Checking the following samples may be helpful to know how to use `slack-app-backend` package in Spring Boot apps:

* https://github.com/Kunpero/slack-vacation-bot/blob/bb4e97b3fb77a24170bdb414eb53b8ad226fbc52/web/src/main/java/rs/kunpero/vacation/api/VacationController.java
* https://github.com/slackapi/java-slack-sdk/blob/v1.0.7/slack-app-backend/src/test/java/test_with_remote_apis/interactive_messages/BlockKitBackend.java

**Comment by natevaughan** [comment]
Perfect! Don't know how I missed that. 

Thanks for the examples; I just noticed that `PayloadTypeDetector` is provided. Great to know I don't have to implement my own.

It might be a good idea to update this block of documentation from the ["Under The Hood" section of the interactivity documentation](https://slack.dev/java-slack-sdk/guides/interactive-components): 
```
String payloadType = PseudoActionTypeExtractor.extract(payloadString);
```

I think it could be:
```
import com.slack.api.app_backend.dialogs.payload.PayloadTypeDetector;
...
    private static final PayloadTypeDetector TYPE_DETECTOR = new PayloadTypeDetector();
...
        String type = TYPE_DETECTOR.detectType(body);
```
Thanks again for the help!

**Comment by seratch** [comment]
Thanks for the suggestion! Indeed, this is a nice improvement. I'll be on it later.

**Comment by seratch** [comment]
I've updated the document. Let me close this issue now!
