### ISSUE TITLE
The RTM client silently disconnects after a few hours

### ISSUE THREAD

**Issue by gaspardpetit** [slackapi/java-slack-sdk#464]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

The RTM client will silently disconnect after a few hours. There does not seem to be any callback being triggered or easy ways to check the status of the websocket from the RTM api.

I have produced PR https://github.com/slackapi/java-slack-sdk/pull/459 to support ping/pong messages and events, and was hoping that pinging every 30 seconds would help but it did not. At the end, I can see a ping never being answered back.

It could be that the solution is to timeout on a ping event and force a reconnect when the pong response is not heard back within a reasonable amount of time (ex. 15 seconds?)

Is there another way to test if the websocket is still active with the RTM client? or a way to obtain a callback when the websocket connection drops?

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
It seems we need to implement [this logic](https://tyrus-project.github.io/documentation/1.13.1/user-guide.html#d0e1311
) in [`RTMClient#connect()` method](https://github.com/slackapi/java-slack-sdk/blob/v1.0.7/slack-api-client/src/main/java/com/slack/api/rtm/RTMClient.java#L83).

**Comment by gaspardpetit** [comment]
I'll try it out and report, but I am suspicious. The websocket link Slack provides is [only valid for 30 seconds](https://api.slack.com/rtm):

>The Websocket URLs provided by rtm.connect are single-use and are only valid for 30 seconds, so make sure to connect quickly.

So I would think that letting Tyrus automatically reconnect to the same URL would fail. I'll try it and report back my findings. Otherwise, we can at least trigger an event and let the application manually call `reconnect` on the RTMClient

**Comment by gaspardpetit** [comment]
So that was interesting.

```
06:15:49.317 [Grizzly(2)] WARN  com.slack.api.rtm.RTMClient - ### Reconnecting... (reconnect count: 3)
06:15:50.389 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - session opened: f5f1af89-83dd-4665-9ba3-eb1dcbdd2e19
06:15:50.389 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - message: {"type":"error","error":{"msg":"Socket URL has expired","code":1,"source":"gs-iad-1b6o"}}
06:15:50.389 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMEventsDispatcherImpl - No event handler registered for type: error
06:15:55.385 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - session closed: f5f1af89-83dd-4665-9ba3-eb1dcbdd2e19, reason: Closed abnormally.
```

It tried three time (I had that configured) and each time failed because of `Socket URL has expired` as I expected. However, it ended up triggering the `session closed` and my app picked that up and was able to reconnect (I had reconnect logic outside of the websocket, but was not getting this `session closed` event before.

So, I would say partial success. A quick fix would be to implement this with no retry so it immediately fails and the app has a chance to reconnect. A better fix would be to handle this within the RTM client, such that the RMT client calls reconnect to fetch a new URL from slack and performs the reconnection under the hood.

Would you be comfortable with me sending a pull request for the quick fix first and later when you (or I) have time we can look at the better solution? At least for now we would be able to tell people that the work around is to monitor session closed and to reconnect if desired.

**Comment by seratch** [comment]
I'm still not sure about what your "quick fix" is yet but I'd love to know what it is. Could you make a WIP pull request?

When it comes to consistency among 1st party Slack API SDKs, node-slack-sdk and python-slackclient have the concept - `autoReconnect: boolean` while this library doesn't. I'm keen to have the option and make it the default behavior as with those SDKs.

**Comment by gaspardpetit** [comment]
I'll still investigating. I tried a few things - the last "disconnect" I had looked like this:

```
07:43:14.618 [Grizzly(1)] DEBUG com.slack.api.rtm.RTMClient - message: {"type":"pong","time":{"seconds":1590219794,"nanos":599871000},"reply_to":998}
07:43:44.619 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - message: {"type":"pong","time":{"seconds":1590219824,"nanos":600550000},"reply_to":999}
07:43:56.938 [Grizzly(1)] DEBUG com.slack.api.rtm.RTMClient - message: {"type": "goodbye", "source": "gateway_server"}
07:43:56.938 [Grizzly(1)] DEBUG com.slack.api.rtm.RTMEventsDispatcherImpl - No event handler registered for type: goodbye
07:44:14.620 [Grizzly(2)] DEBUG com.slack.api.rtm.RTMClient - message: {"type":"pong","time":{"seconds":1590219854,"nanos":601300000},"reply_to":1000}
```

So it looks like we have to handle that one as well (https://api.slack.com/events/goodbye)

**Comment by seratch** [comment]
Thanks for sharing this! Indeed, this library doesn't provide an automatic-reconnect feature when receiving `goodbye` events yet. As `GoodbyeHandler` interface already exists, all we need to do is implement `GoodbyeHandler` which acquires a new WebSocket endpoint and reconnects to the server-side + enable it as a built-in one.

**Comment by gaspardpetit** [comment]
Hi again,

So good news is that my bot has been able to survive the 8h disconnect from Slack by handling the `goodbye` event. However I am not sure how this should be handled by the java sdk.

My existential concern is the following: I see two ways of handling the loss of the websocket:

1. Handled internally by the Slack SDK - this is the most convenient approach for anyone who's expecting the sdk to just "work". However, getting it right requires a bit of refactoring for the case when Slack is not available.  As it is now, I can attempt a reconnect when we lose the websocket or when Slack says `goodbye`, but what if the reconnect fails (ex. Slack is down)?  Then we'd need a thread that retries periodically, but also we would probably to inform the app that we are offline, and then notify when we are back online.

2. Let the app handle this - in the main loop, check when we get disconnected and attempt to reconnect. If re-connection fails, the main loop can just sleep 30 seconds and retry, and retry and retry until Slack is back online.

It would be possible to do something in-between by providing a reconnect policy - some kind of "restart recipe" that does the logic of #2 but is readily available so that whoever is creating a new bot using RTM does not have to worry about implementing it themselves.

I'll try to present such policy object in a PR so you can tell me what you think.

**Comment by seratch** [comment]
Thanks for sharing your well-considered resolution for this.

For the cases that the auto-reconnect logic should consider are:
* :one: `rtm.connect`/`rtm.start` failures due to Slack outage
* :two: `rtm.connect`/`rtm.start` failures due to rate_limited errors (rtm.* are Tier1)

Regarding :one:, as you mentioned, waiting for the recovery a bit longer than usual and showing the status in info-level logs may be helpful for some apps. We can provide the default policy suitable for 80+% use cases but if it is customizable, that'll be great.

As for :two:, the implementation should have a great consideration of `Retry-After` response header. I don't think we should use `AsyncMethodsClient` for this as it brings a bit more complexity in this case but checking the code would be helpful for learning how to handle rate_limited errors: https://github.com/slackapi/java-slack-sdk/blob/v1.0.7/slack-api-client/src/main/java/com/slack/api/methods/impl/AsyncRateLimitExecutor.java#L160-L162

Also, I think `onClose` is triggered right after your app receives `goodbye` messages from Slack. Based on the assumption, implementing this logic as `RTMCloseHandler` looks better as it can cover any other patterns the RTMClient needs to reconnect to Slack (e.g., disconnected without receiving a `goodbye` message).
https://github.com/slackapi/java-slack-sdk/blob/v1.0.7/slack-api-client/src/main/java/com/slack/api/rtm/RTMClient.java#L141-L149

>Let the app handle this - in the main loop, check when we get disconnected and attempt to reconnect. If re-connection fails, the main loop can just sleep 30 seconds and retry, and retry and retry until Slack is back online.

If we can implement the above as `RTMCloseHandler`, I don't think we should manage another thread on our own (please correct me if I misunderstand).

**Comment by gaspardpetit** [comment]
Sorry for the radio silence. I tried a few things and each time it's a 8+ hour wait to validate :)

It turns out that catching `GoodbyeEvent` and calling `disconnect` on the client when it happens is sufficient to keep the bot running. The disconnect then correctly calls the close callback and the bot gets a chance to reconnect.

What I still don't understand, is why the close event does not get sent when we don't manually disconnect on `Goodbye` and the web socket is closed a few minutes after from the other end.

This is much less urgent now thatI have a workaround, so I guess we can close the issue and I'll come back if I have an improvement to offer.

Cheers,

Gaspard

**Comment by seratch** [comment]
@gaspardpetit Thanks for the response and I'm glad to hear that your app has been working well. I would like to know more details about your code with goodbye events. Does it look like this?
https://github.com/seratch/java-slack-sdk/commit/292339c87e348613843516cc762aae0ad1029fff

Also, if my implementation is valid (I haven't done any tests yet though), what do you think about having this implementation as the built-in message listener since the next version?

**Comment by gaspardpetit** [comment]
Hi @seratch - thanks for looking at improving this! I attempted to do something similar to what you did here. The limitation in this implementation is the case where you will end in the `Failed to reconnect to Slack` case. I was not sure what would happen and did not have time to fully test. Would `CloseHandler` be called if the `reconnect` fails? If so, I think your solution is good, because it means that the app is aware that the connection went away and can either shutdown and let something else restart it, or implement a reconnect loop.

Failure to reconnect will happen during Slack outages, and by handling it "internally" like you did here, you do not really get a chance to retry later, unless you spin a thread that periodically attempts to reconnect.

If you don't start a retry thread, then the app has to expect this to happen and run the rtm client in an external retry loop. But then, if it has to implement an external retry loop, do we even need the internal one?  My conclusion was that we did not. If the disconnection is correctly reported back, it isn't very difficult to wrap the bot execution in a reconnect loop.

I ended up doing it this way - it's a bit long and complicated, but it got me in a state where the bot will reconnect and I can focus on other things. 

1. My Bot has a `waitForDeath` method that blocks until it is disconnected:
```
public interface Bot extends AutoCloseable {
	void waitForDeath(Duration ofSeconds);
}
```

I also defined a lifecycle for my bots that have three phases: 
 - `onPowerOn` which returns a fresh new bot
 - `onHeartbeat` which gets called once per second, giving me a chance to do periodic checks, monitoring, ping, etc. heartbeat; and
 - `close` on the `AutoCloseable` which terminates the bot when connection is lost

```
public interface BotLifecycle<BOT extends Bot> {
	BOT onPowerOn() throws Exception;
	void onHeartbeat(BOT bot);
}
```

2. I use a runner policy that keeps restarting my bot
```
@Slf4j
public abstract class BotRunnerPolicy<BOT extends Bot>
{
	public abstract void run(BotLifecycle<BOT> botLifecycle) throws InterruptedException;

	public void keepRunning(BotLifecycle<BOT> botLifecycle, Supplier<Boolean> shouldStop) throws InterruptedException
	{
		log.info("powering on bot");
		try(BOT bot = botLifecycle.onPowerOn()) {
			while(shouldStop.get() == false) {
				bot.waitForDeath(Duration.ofSeconds(1));
				botLifecycle.onHeartbeat(bot);
			}
		}
		catch(Exception ex) {
			log.warn("while monitoring execution", ex);
		}
		finally {
			log.info("stopping bot");
		}

		// sleep a bit before restarting just so we don't end up in a tight retry loop
		if(shouldStop.get() == false) {
			log.info("hang on, we will be back shortly....");
			Thread.sleep(Duration.ofSeconds(5).toMillis());
		}
	}
}
```

The policy I use is to wait for the JVM to exit:
```
@Slf4j
public class BotRunnerUntilJVMExitsPolicy<BOT extends Bot> extends BotRunnerPolicy<BOT>
{
	@Override
	public void run(BotLifecycle<BOT> botLifecycle) throws InterruptedException {
		while(RuntimeMonitoring.shutdown() == false)  {
			keepRunning(botLifecycle, RuntimeMonitoring::shutdown);
		}
	}
}
```

3. Then in my main function, I run my policy and define how the bot should be re-created when needed:

```
BotRunnerPolicy<SlackBot> botRunnerPolicy = new BotRunnerUntilJVMExitsPolicy<>();
botRunnerPolicy.run(new BotLifecycle<>() {

	Instant m_lastPingTime = Instant.now();

	@Override
	public SlackBot onPowerOn() throws Exception
	{
		SlackBot bot = new SlackBot();
		// register monitoring, command handlers, etc.
		return bot;
	}

	@Override
	public void onHeartbeat(SlackBot bot)
	{
		// probably not needed by everyone, but I monitor ping/pong time
		Instant now = Instant.now();
		if (Duration.between(m_lastPingTime, now).getSeconds() > 30)
		{
			bot.ping();
			m_lastPingTime = now;
		}
	}
});
```

That's for the outer shell. The bot itself monitors a few things:

Signaling death of the bot so it reconnects:
```
private final Object m_waitForDeath = new Object(); 

@Override
public void waitForDeath(Duration duration) throws InterruptedException
{
	synchronized(m_waitForDeath) {
		m_waitForDeath.wait(duration.toMillis());
	}
}

public void signalDeath()
{
	synchronized(m_waitForDeath) {
		m_waitForDeath.notifyAll();
	}
}

@Override
public void close()
{
	try {
		if (m_rtm != null) {
			log.info("shutting down slack bot");
			m_rtm.disconnect();
			m_rtm = null;
		}

		if (m_slack != null) {
			log.info("shutting down slack");
			m_slack.close();
			m_slack = null;
		}
		signalDeath();
	}
	catch(Exception e) {
		log.error("While shutting down", e);
	}
}
```

I register a `CloseHandler` which closes my bot (and therefore pronounces it dead)
```
public SlackBot() throws Exception
{
	m_slack = new Slack();
	m_rtm = m_slack.rtmConnect(token);
	m_rtm.connect();
	m_rtm.addCloseHandler(reason -> close());
}
```

And I register a `GoodbyeEvent` handler that also kills my bot

```
m_dispatcher.register(new RTMEventHandler<GoodbyeEvent>() {
	@Override public void handle(GoodbyeEvent event) {
		close();
	}
});
```

It's a lot of small pieces, but if I summarize, the flow looks like this:

```
while (jvm is running) {
  connect to slack with rtm
  register handler for `GoodbyeEvent` that calls `close()`
  register `CloseHandler` that calls `close()`
  wait for close() to be called
  cleanup
}
```

**Comment by gaspardpetit** [comment]
So I gave it some thoughts, I think you're on a good track. What about this?

https://github.com/eidosmontreal/java-slack-sdk/commit/eb47f3aeb95da14a21ac99dea11cacd38ed73454

**Comment by seratch** [comment]
@gaspardpetit Thank you very much for sharing your knowledge! These are really helpful. To improve the connection management, I would like to implement auto-reconnect and ping/pong heartbeat (it seems tyrus-standalone-client doesn't have the option, so that we need to implement it on our end). If you have interests and time for writing the code, I'd love to work with you on it.

**Comment by gaspardpetit** [comment]
@seratch I will keep looking at this on the side; I can already comment that the code I linked above does not work. Failures to reconnect in the reconnect thread spawn new threads and I ended up with multiple threads trying to reconnect and being rate-limited by Slack 😓

I believe creating a daemon thread like you suggested is the right approach. I will look into this and get back to you.

**Comment by seratch** [comment]
Hi @gaspardpetit, can switching to [Socket Mode](https://slack.dev/java-slack-sdk/guides/socket-mode) be your option for the future? Most of the things you are doing with RTM API are possible in Socket Mode. The exceptions are [receiving user_typing events](https://api.slack.com/events/user_typing) and Web API calls using ["classic bot" permission](https://api.slack.com/authentication/token-types#bot).

I'm pretty sure SocketModeClient should work much more stably for you. I've applied a bunch of improvements for better auto-reconnect logic in the novel implementation. It may be also possible to port the parts into RTMClient but I'm sorry to say that it's not our priority. 

Hope this is helpful to you and if you don't mind, can we close this issue as "won't fix" one?

**Comment by gaspardpetit** [comment]
Thanks for asking. SocketMode is the way to go going forward, I have no objection closing this one.

Thanks again for your work on this library, it is very useful to me :)

**Comment by seratch** [comment]
Thanks for your prompt response and I'm very happy to hear that! Let me close this 🙇
