### ISSUE TITLE
NoSuchMethodError in FileUpload Method

### ISSUE THREAD

**Issue by martinhug** [slackapi/java-slack-sdk#467]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x ] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

**TODO**:
(Describe your issue here)
I have a Problem using the SDK with the WebAPI.
When I call the fileUpload Method i receive a "NoSuchMethodError".
Inside the RequestformBuilder Class inside the MultipartBody.Builder the RequestBody.create has the wrong signature.
It calls RequestBody.create(FILEDATA, MEDIATYPE) where it shoud be RequestBody.create(MEDIATYPE, FILEDATA)

![Requestbody create()](https://user-images.githubusercontent.com/38318479/82672558-cb3f8880-9c40-11ea-9c8d-6927196d06c0.png)
---
(only for a bug report)

**TODO**:
If this is a bug report, filling out the following details about bugs will help us solve your issue sooner.

The issue is reproducible in:
* Module Version: **TODO**: 1.0.7
* JDK Version: **TODO**: openjdk version "11.0.6" 2020-01-14
* OS Version etc: **TODO**: if the issue happens only with specific OS

The expected result is:
**TODO**: File Upload

The actual result is:
**TODO**: NoSuchMethodError
---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
This library is compatible with okhttp 4.x. If your app has to use okhttp 3.x for some reason, you cannot use this library in the project.

**Comment by seratch** [comment]
@martinhug As I as a maintainer of this project don't have any further actions to take, please allow me to close this issue. Please consider upgrading okhttp from 3.14.7 to the latest (4.x).
