### ISSUE TITLE
auth.test short-time cache for SingleTeamAuthorization

### ISSUE THREAD

**Issue by eamelink** [slackapi/java-slack-sdk#468]
### Issue Type

- [?] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I am building a slack app with Bolt, and I'm observing a request to `auth.test` for every incoming request. This comes from here: https://github.com/slackapi/java-slack-sdk/blob/ac2a0107f1a2ac20db20704ac298a44aa4d35a28/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/SingleTeamAuthorization.java#L37

The only parameter to the call (config.getSingleTeamBotToken()) is constant, so doing this for every incoming request seems a bit excessive, even though the Slack API docs state you can use the method a lot.

Should the response from `auth.test` be cached for a while instead of executed on every request?

**Comment by seratch** [comment]
If a token has been revoked, the following middleware, Web API calls fail due to the invalid token. So, checking the validity of tokens every time is the safest way. Also, it's totally fine to excessively call `auth.test` in terms of rate limits.

But I agree that it may be a bit overhead for response time and like the idea to have a short-time cache for it. We should keep the current behavior (=calling `auth.test` for all incoming requests) as-is, but I'm happy to introduce a new option to enable a cache feature with configurable TTLs. I think a few seconds as the default is reasonable for this case.

**Comment by aoberoi** [comment]
after doing some thinking about this, I think we might be okay with only calling `auth.test` once upon boot and saving it as a constant for the lifetime of the app.

if we keep the current implementation and the token is not valid (was revoked or any other reason), then we will emit an error for the developer to handle. there is no smarter behavior we can do (such as refreshing a token). the same would be true for the cached token with TTL. the cache would allow a few events to ignore the validity check, and then after the TTL time, the same thing would happen.

when the validity check is ignored, then listeners will be called and the failure will occur later, when the app needs to send a request to the Slack API. however, some listeners may never need to call the Slack API, they might purely be observing and tracking state. why should those listeners not be given a chance to run? the meaningful failure(s) will still be evident to the developer when the app tries to reach the Slack API.

i think the worst case of allowing the single team authorization to be constant is when a listener contains behavior that depends on the access to Slack API being valid before an API call. the only example i can think of is a listener scheduling some future task that eventually calls the Slack API. but even in this case, the most relevant error would be the one that is returned by the API call in that future task. am i missing some other situations?

**Comment by seratch** [comment]
Thanks for your comment. It may be true for the single team auth. In reality, there is no actual difference between creating permanent cache when booting vs maintaining cache with a short TTL. I'll change the implementation for simplicity and also aligning with Bolt for JS.

On the other hand, for multiple teams auth, such a permanent cache may not be a good fit. At least I don't see any benefits from it. Can we agree that we still should have TTL for multiple teams auth cache (per token)?

Checking the current implementation would be helpful to know what the TTL looks like. https://github.com/slackapi/java-slack-sdk/pull/502/files
