### ISSUE TITLE
Question about adding SpringBoot Bolt App GET endpoints

### ISSUE THREAD

**Issue by rmccright-usf** [slackapi/java-slack-sdk#479]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I have a Spring Boot Bolt App created similarly to the guides and examples. One of my Bots functionalities to to facilitate Oauth Authorization Code grant type for a 3rd party library. This requires a callback endpoint on the Bot. This endpoints needs to be a GET request.

Using the @WebServlet("/slack/events") procedure for creating a HTTP listener using SlackAppServlet interface forces me into using a POST, as well as the Slack message format.

I noticed that the Bold app has a function called app.endpoint which takes Method, Path, Function as params. What is the purpose of this function and can it be used to add a HTTP GET method for my callback purposes?

I tried to re implement SlackAppServlet's implementation of HTTPServlet by adding a doGet method. However, I am unsuccessfully at getting this to work so far.

Any ideas, or suggestions are much appreciated.

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@rmccright-usf Check 
https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackOAuthAppServlet.java

**Comment by seratch** [comment]
@rmccright-usf Check [SlackOAuthAppServlet](https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackOAuthAppServlet.java) may be helpful to know that. As long as you configure `App` correctly (client_id, client_secret, scope etc), it should work. Check [this document](https://slack.dev/java-slack-sdk/guides/app-distribution) to know how to configure `App`.

**Comment by rmccright-usf** [comment]
> @rmccright-usf Checking [SlackOAuthAppServlet](https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackOAuthAppServlet.java) may be helpful to know that. As long as you configure `App` correctly (client_id, client_secret, scope etc), it should work. Check [this document](https://slack.dev/java-slack-sdk/guides/app-distribution) to know how to configure `App`.

So, using this method I am getting this error. Perhaps this is because I am only trying to use the callback ability. Specifically I am trying trigger a callback for authenticating to a NON SLACK api with Oauth through Slack messages.

`2020-06-03 09:30:27.744 DEBUG 40667 --- [nio-3000-exec-2] com.slack.api.bolt.App                   : The handler started (request type: OAuthCallback)
2020-06-03 09:30:27.744  WARN 40667 --- [nio-3000-exec-2] com.slack.api.bolt.App                   : Skipped to handle an OAuth callback request as this Bolt app is not ready for it
2020-06-03 09:30:27.744 DEBUG 40667 --- [nio-3000-exec-2] com.slack.api.bolt.App                   : The handler completed (request type: OAuthCallback)`

**Comment by seratch** [comment]
@rmccright-usf The error indicates your Bolt app doesn't have clientId and clientSecret. These are required for calling `oauth.v2.access`.

* https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt/src/main/java/com/slack/api/bolt/App.java#L835 https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt/src/main/java/com/slack/api/bolt/AppConfig.java#L63-L65

I strongly recommend using state parameter for the OAuth flow and Bolt Java requires to use it. But if you want to have only redirect_uri without state parameter handling, reusing only the following code should work for you.

https://github.com/slackapi/java-slack-sdk/blob/v1.0.8/bolt/src/main/java/com/slack/api/bolt/service/builtin/DefaultOAuthCallbackService.java#L75-L81

**Comment by seratch** [comment]
@rmccright-usf Have you had a chance to check this? Let me know if you have anything further to ask. If my above answer is helpful enough, could you close this question?

**Comment by seratch** [comment]
As I don't have any further actions to take here, please allow me to close this issue now. If you have more to ask here, please feel free to write in or reopen.
