### ISSUE TITLE
Question about how to use Scalatra with Bolt

### ISSUE THREAD

**Issue by timrourke** [slackapi/java-slack-sdk#483]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I'm trying to figure out how to use `com.slack.api.bolt.App` with a brand new Scalatra application. Was hoping @seratch might have some insight since it looks like you contribute to both this project and to Scalatra.

Right now I'm trying to define a Scalatra `POST` request handler for the `/slack/events` endpoint, and then manually deserialize the HttpServletRequest into a SlackRequest. This approach of mine is awful, perhaps you have a better idea?

My Scalatra request handler looks like this:

```scala
  post("/slack/events") {
//      This throws an IOException because the request body is already read. Why?
//      I should also note that `request.body` is empty in this handler. Why?
    val body = request.getReader.lines().collect(Collectors.joining(System.lineSeparator()))
    val headers = new RequestHeaders(toHeaderMap(request))
    val rawRequest = SlackRequestParser.HttpRequest.builder()
      .requestUri(request.getRequestURI)
      .requestBody(body)
      .queryString(QueryStringParser.toMap(request.getQueryString))
      .headers(headers)
      .remoteAddress(request.getRemoteAddr)
      .build()

    val slackRequestParser = new SlackRequestParser(slackApp.config())

    val slackRequest = slackRequestParser.parse(rawRequest)

    try {
//      This throws an IOException because the request body is already read. Why?
//      val slackRequest = slackRequestAdapter.buildSlackRequest(request)
      val res = slackApp.run(slackRequest)
      slackRequestAdapter.writeResponse(response, res)
    } catch {
      case e: Throwable =>
        log(s"Failed to handle a request - ${e.getMessage}", e)
        status = 500
        contentType = "application/json"
        "{\"error\":\"Something is wrong\"}"
    }
  }
```

For some reason, the `request.body` value is always empty, and attempts to read the body of the request (using the SlackRequestParser, or doing it manually as above) fail because something else has already read the request body stream.

1. So first of all, any idea what's reading my request body before my code runs? Can't tell from the stack trace, but I'm probably overlooking something.

2. Second, what's the best way to marry the `com.slack.api.bolt.App` with a Scalatra application?

My main goal is really just to be able to use `com.slack.api.bolt.App` but still define my own HTTP handlers and business logic in the same application codebase, so using Scalatra isn't that important to me, it's just simpler for me to understand than Play and Akka HTTP.

Thanks!

---
(only for a bug report)

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@timrourke Happy to know you're interested in building Slack apps in Scala 😃 

Indeed, the request parser in Scalatra works weirdly... 🤔 If you go with Scalatra, utilizing `com.slack.api.bolt.servlet.SlackAppServlet` would be the easiest way. The following code should work as-is for you.

```scala
import com.slack.api.bolt.App
import com.slack.api.bolt.handler.builtin.SlashCommandHandler
import com.slack.api.bolt.servlet.SlackAppServlet
import javax.servlet.ServletContext
import javax.servlet.http.{HttpServletRequest, HttpServletResponse}
import org.scalatra._

class RootController extends ScalatraServlet {
  get("/") {
    views.html.hello()
  }
}

class SlackAppController(app: App) extends SlackAppServlet(app) with org.scalatra.Handler {
  override def handle(request: HttpServletRequest, response: HttpServletResponse): Unit = doPost(request, response)
}

object Components {
  lazy val slackApp: App = {
    val app = new App()
    val makeRequestHandler: SlashCommandHandler = (req, ctx) => {
      ctx.ack(s"Thanks <@${req.getPayload.getUserId}>!")
    }
    app.command("/make-request", makeRequestHandler)
    app
  }
}

class ScalatraBootstrap extends LifeCycle {
  override def init(context: ServletContext) {
    context.mount(new RootController, "/*")
    context.mount(new SlackAppController(Components.slackApp), "/slack/events")
  }
}
```

That said, Play Framework may be much more popular than Scalatra. Considering the future maintenance, using Play may be a better choice for this case. Here is a minimum working example using Play.

```scala
package controllers

import javax.inject._
import play.api.mvc._
import services.SlackAppService

@Singleton
class SlackAppController @Inject()(
  val controllerComponents: ControllerComponents,
  service: SlackAppService) extends BaseController {

  def index() = Action(parse.raw)(service.run(_))
}

// ---
package services

import akka.util.ByteString
import com.slack.api.bolt.handler.builtin.SlashCommandHandler
import com.slack.api.bolt.request.{RequestHeaders, Request => SlackRequest}
import com.slack.api.bolt.response.{Response => SlackResponse}
import com.slack.api.bolt.util.SlackRequestParser
import com.slack.api.bolt.{App => SlackApp}
import javax.inject.Singleton
import play.api.http.HttpEntity
import play.api.mvc._

import scala.jdk.CollectionConverters._

@Singleton
class SlackAppService {

  private[this] lazy val app = new SlackApp()
  private[this] lazy val parser = new SlackRequestParser(app.config)

  val makeRequestHandler: SlashCommandHandler = (req, ctx) => {
    ctx.ack(s"Thanks <@${req.getPayload.getUserId}>!")
  }
  app.command("/make-request", makeRequestHandler)

  def run(implicit request: Request[RawBuffer]): Result = {
    toPlayResponse(app.run(parseRequest(request)))
  }

  def parseRequest(implicit request: Request[RawBuffer]): SlackRequest[_] = {
    parser.parse(SlackRequestParser.HttpRequest.builder()
      .requestUri(request.uri)
      .queryString(request.queryString.map { case (k, vs) => k -> vs.asJava }.asJava)
      .headers(new RequestHeaders(request.headers.toMap.map { case (k, vs) => k -> vs.asJava }.asJava))
      .requestBody(request.body.asBytes().map(_.utf8String).getOrElse(""))
      .remoteAddress(request.remoteAddress)
      .build())
  }

  def toPlayResponse(response: SlackResponse): Result = {
    val headers = response.getHeaders.asScala
      .filter { case (_, v) => v != null && v.size() > 0 }
      .map { case (k, v) => k -> v.get(0) }
      .toMap
    Result(
      header = ResponseHeader(response.getStatusCode, headers),
      body = HttpEntity.Strict(ByteString(response.getBody), Some(response.getContentType))
    )
  }
}
```

Here are the concrete samples:
* Play: https://gist.github.com/seratch/46c404c6141d34060a1c607822dd25d0
* Scalatra: https://gist.github.com/seratch/c085ac418c53daad24473f38e0363a9a

**Comment by seratch** [comment]
### Limitations with Scala

For your information, there are some limitations to know if you use Bolt in Scala.

As all listener types in Bolt are compatible with Java's functional interface, you can define listeners in handy ways:
* Java: `app.command("/hi", (req, ctx) -> ctx.ack())`
* Kotlin: `app.commnad("/hi") { req, ctx -> ctx.ack() }`

However, you cannot go in a similar way in Scala. For instance, the following code fails to compile.

```scala
// Compilation fails...
app.command("/hi", (req, ctx) => ctx.ack())
```

I'm not an expert on the Scala compiler but it seems this is caused by Scala's a bit unique interpretation of the Java functional interface. To satisfy the compiler, you have to explicitly give a type to them.

```scala
// This works!
val handler: SlashCommandHandler = (req, ctx) => { ctx.ack() }
app.command("/hi", handler)
```

Also, another limitation is about Bolt's utility methods such as `respond`, `ack`, and `say`. The Scala compiler doesn't like overloaded methods in general. So, the following code doesn't compile even though the argument can be a functional interface object.

```scala
ctx.respond(_.responseType("ephemeral").text("Thanks!"))
ctx.respond { r => r.responseType("ephemeral").text("Thanks!") }
```

Instead, building a complete object works.

```scala
val response = SlashCommandResponse.builder().responseType("ephemeral").text("Thanks!").build()
ctx.respond(response)

type Res = BuilderConfigurator[SlashCommandResponse.SlashCommandResponseBuilder]
val response: Res = _.responseType("ephemeral").text("Thanks!")
ctx.respond(response)
```

If you think these limitations are not so frustrating plus you really prefer using Scala than other JVM languages, you can still use this SDK in Scala. Apart from the above, there is no other limitation.

If you want to consider other options, using Kotlin may be a good fit. Kotlin (and of course, Java) doesn't have any of the above limitations. That's the reason why I've added so many Kotlin examples with this SDK.

* Kotlin samples in this repo: https://github.com/slackapi/java-slack-sdk/tree/master/bolt-kotlin-examples/src/main/kotlin/examples
* HTTP4K: https://gist.github.com/seratch/6ea67ae66c05417c87670917e978378d
* Ktor: https://gist.github.com/seratch/7a0cb911025dd69e404c23dba30606fa

Anyways, enjoy building Slack apps on the JVM 👍

**Comment by timrourke** [comment]
@seratch you answered my question, you taught me a lot, and you even provided non-trivial code examples. I'm so grateful!

It looks to me like Play may be a better option, and is more likely to be familiar to future hires on my team. Thanks for the recommendation.

Scala is interesting to me because I currently work on a data team that is already invested in Scala thanks to Apache Spark. Helping the compiler doesn't bother me much, it's really the excellent head start on business logic we can get from Bolt that I am focused on. 

Again, HUGE thanks for your incredible response, thanks for being awesome and making awesome stuff! 🙌

**Comment by timrourke** [comment]
@seratch these answers might be worth enshrining in the docs for future weary adventurers! Let me know, happy to open a PR to write the documentation based on your gists.
