### ISSUE TITLE
Event type extract does not match correctly if there are "type" properties in JSON subentries.

### ISSUE THREAD

**Issue by lgrammel** [slackapi/java-slack-sdk#489]
The current code for extracting event types seems to assume that the "type:" entry that contains the event type is the first type entry in the JSON that follows "event:". However, this is not always the case. 

E.g. in the following message `{"authed_users":["RETRACTED"],"event_id":"RETRACTED","api_app_id":"RETRACTED","team_id":"RETRACTED","event":{"client_msg_id":"b5ac4998-4526-4d0b-8bb0-7bd614c1b774","blocks":[{"elements":[{"elements":[{"text":"test","type":"text"}],"type":"rich_text_section"}],"type":"rich_text","block_id":"Ws3Y"}],"event_ts":"1592257234.003200","channel":"RETRACTED","text":"test","team":"RETRACTED","type":"message","channel_type":"channel","user":"RETRACTED","ts":"1592257234.003200"},"type":"event_callback","event_time":1592257234,"token":"RETRACTED"}` the `"type": "text"`value of the "blocks" field comes first. The event for that message is detected as "text" even though it would need to be "message" to arrive in the correct event handler.

https://github.com/slackapi/java-slack-sdk/blob/a2e96f3582189cbd7e9b0bd5a4504bdba4262ce6/slack-app-backend/src/main/java/com/slack/api/app_backend/events/EventTypeExtractorImpl.java#L23

**Comment by lgrammel** [comment]
(as a workaround I can reorder the fields in the JSON message that gets sent into the EventTypeExtractor so the detection works correctly)

**Comment by seratch** [comment]
@lgrammel Thanks for taking the time to report this! I will fix this and release a new patch version very soon.

**Comment by lgrammel** [comment]
@seratch awesome, thank you! it's great to have this SDK available, makes developing Slack apps a lot easier!
