### ISSUE TITLE
Allow users to specify redirect_uri during OAuth flow?

### ISSUE THREAD

**Issue by timrourke** [slackapi/java-slack-sdk#491]
### Issue Type

- [ ] Bug
- [x] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

I have been using your excellent SDK to do two things:
1. Support installing an app
2. Support "Sign in with Slack"

My use case treats those as separate concerns in how my application works. My solution for supporting logging in with Slack OAuth involves defining 2 separate `com.slack.api.bolt.App` instances, with slightly different configuration, so that I can handle OAuth URLs that are distinct for each use case. One `App` instance is for installing the app, and one is for signing in with Slack.

This strategy has been mostly very practical; I don't have to write any custom OAuth logic since your SDK handles the important parts of the flow. I do need to replace a few components with subclasses to modify behavior slightly for my (perhaps unusual) approach here.
- I've subclassed `FileOAuthStateService` so that I can name the session cookies different things for either Slack `App`
- I need to subclass `App` itself in order to append a `redirect_uri` as a query param to the URL used to exchange an OAuth code for an access token 

The method `com.slack.api.bolt.App::getOauthInstallationUrl` builds URLs for exchanging an OAuth code for an access token. Slack's API documentation suggests that if there are multiple possible OAuth redirect URIs configured for an app, then using the `redirect_uri` query param helps Slack know which OAuth callback URI to send the user to after they accept the scopes.

**Here's my question**: would it make sense to include the redirect URI as configured on the `AppConfig` object when building that "OAuth Installation URL"? Defaulting to whatever the user configured on the `AppConfig` for their app seems sensible for a couple reasons:
- If someone is trying to do something like what I'm after here, they will likely have multiple Slack `App` instances, and the configuration will likely vary in terms of the OAuth URIs
- Not being explicit about which redirect URI to use seems potentially risky, because a user might reconfigure their app, and Slack seems to pick the first option in the list unless it's been explicitly told to use one or the other

For now, I've solved my own problem, but I'm wondering whether a general solution might be useful for others.

My proposal would effect this code: https://github.com/slackapi/java-slack-sdk/blob/master/bolt/src/main/java/com/slack/api/bolt/App.java#L317

```java
    public String getOauthInstallationUrl(String state) {
        AppConfig config = config();
        if (config.getClientId() == null || config.getScope() == null || state == null) {
            return null;
        } else {
            String scope = config.getScope() == null ? "" : config.getScope();
            if (config.isClassicAppPermissionsEnabled()) {
                // https://api.slack.com/authentication/migration
                return "https://slack.com/oauth/authorize" +
                        "?client_id=" + config.getClientId() +
                        "&scope=" + scope +
                        "&state=" + state +
						"&redirect_uri=" + config.getRedirectUri(); // Change here
            } else {
                String userScope = config.getUserScope() == null ? "" : config.getUserScope();
                return "https://slack.com/oauth/v2/authorize" +
                        "?client_id=" + config.getClientId() +
                        "&scope=" + scope +
                        "&user_scope=" + userScope +
                        "&state=" + state +
						"&redirect_uri=" + config.getRedirectUri(); // Change here
            }
        }
    }
```

---

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@timrourke 
Thanks for flagging this. Indeed, the `redirect_uri` is not yet supported in `authorize` URL generation (although verification with an `oauth.v2.access` API call works even without doing so). We can definitely update the logic to support the missing piece.

When it comes to a bit details of the implementation, as the `redirect_uri` is an optional parameter, we should have null check before appending the param.

This seems to be a relatively easy task. If you're interested in making a pull request to fix this issue, I'm happy to review it. If you're busy, I can work on this probably tomorrow.

**Comment by timrourke** [comment]
@seratch I'll open a PR shortly.

**Comment by timrourke** [comment]
@seratch here is the relevant PR: https://github.com/slackapi/java-slack-sdk/pull/492

**Comment by seratch** [comment]
Thanks for reporting and fixing this. The change will be included in the next patch version - https://github.com/slackapi/java-slack-sdk/milestone/5

**Comment by iLvrge** [comment]
Multiple redirect url not working in slack sso

When we try sso it works fine for the first redirect URL and when doing sso for the second one we are getting {"ok":false,"error":"bad_redirect_uri"}. Please help us in resolving the issue

**Comment by furkandoganktf** [comment]
> Multiple redirect url not working in slack sso
> 
> When we try sso it works fine for the first redirect URL and when doing sso for the second one we are getting {"ok":false,"error":"bad_redirect_uri"}. Please help us in resolving the issue

Having the same issue. While redirect URL works fine for the first URL, it is throwing {"ok":false,"error":"bad_redirect_uri"} for the second url
