### ISSUE TITLE
Add Kotlin DSL document when releasing v1.1

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#501]
### Issue Type

- [ ] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [x] Documentation

### Description

* https://github.com/slackapi/java-slack-sdk/issues/428
* https://github.com/slackapi/java-slack-sdk/pull/469

The new Kotlin extension modules are ready to merge and we're going to include them in v1.1.0. When releasing the version, we'll update the document to mention those new Kotlin DSL packages.

* Comprehensive guide on how to use
  * https://slack.dev/java-slack-sdk/guides/composing-messages
  * from the installation of the optional packages to code snippets demonstrating common patterns
  * Gradle setup only - less Kotlin devs use Maven
* Add the two modules on the top page and readme:
  * https://slack.dev/java-slack-sdk/
  * https://github.com/slackapi/java-slack-sdk/blob/master/README.md (a bit outdated - other parts should be updated as well)

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by emanguy** [comment]
Let me know if there are any examples I can contribute!

**Comment by seratch** [comment]
@emanguy Thanks for offering your help! If you're interested in writing the draft of the above documents (mainly guide for Gradle project setup and common code examples), it would be greatly appreciated. Sharing your examples in a comment here is also helpful!

**Comment by emanguy** [comment]
Sure, I can just draft up some markdown files or something. Where should I put them?

**Comment by seratch** [comment]
Checking this PR https://github.com/slackapi/java-slack-sdk/pull/402/files is helpful to understand where to touch. Of course, you don't need to worry about anything about Japanese version. I will work on it after finalizing the English document.

If you're not familiar with Jekyll, follow the instructions here: https://github.com/slackapi/java-slack-sdk/blob/master/docs/README.md

**Comment by emanguy** [comment]
Pull request is up 👍

**Comment by seratch** [comment]
Thank you very much for your contribution here. All the changes have been merged into the `main` branch. I will be releasing v1.1.0 tomorrow. After publishing the jars to Maven Central, I will merge all document changes to the `master` branch (GitHub Pages).
