### ISSUE TITLE
MessageFileShareEvent is not yet available in the latest version (1.0.11)

### ISSUE THREAD

**Issue by teamstand-rishabh** [slackapi/java-slack-sdk#510]
Currently most recent version available in maven repo is 1.0.11.
Please update the  latest version

**Comment by seratch** [comment]
Please wait for a little more. We'll be releasing a new version early next week.

**Comment by teamstand-rishabh** [comment]
Thanks for the update

**Comment by seratch** [comment]
v1.1.0 jars are available in Maven Central repositories. https://repo1.maven.org/maven2/com/slack/api/
