### ISSUE TITLE
Audit Log API Doesn't Use Pagination 

### ISSUE THREAD

**Issue by slushpupie** [slackapi/java-slack-sdk#519]
### Issue Type

- [X] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

When using the Audit Log API, it does not support pagenation, so if request results are larger than the allowed limit (mac 9999 according to the API docs) there is no way to get the other results.

---

The issue is reproducible in:
* Module Version: 1.1.0
* JDK Version: openjdk version "11.0.7" 2020-04-14

The steps to reproduce are:

```kotlin
fun main() {
    val token =System.getenv("SLACK_TOKEN")
    val slack = Slack.getInstance()
    val response = slack.audit(token).getLogs {
            it.oldest(0)
            it.limit(100)
    }
    // You can get the nextCursor, but there is no where to pass it
    nextCursor = response.responseMetadata.nextCursor

    for (entry in response.entries) {
            println(entry)
    }
}
```
---

### Requirements (place an `x` in each of the `[ ]`)

* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
This has been fixed by #520 - thanks for your contribution!
