### ISSUE TITLE
Missing fields in MessageFileShareEvent

### ISSUE THREAD

**Issue by teamstand-rishabh** [slackapi/java-slack-sdk#521]
Need these Fields in **MessageFileShareEvent.java**    
```
private String threadTs;
private String team;
private String botId;
private String parentUserId;
```

**They are present in MessageEvent.java**

**Comment by seratch** [comment]
Hello, thanks for writing in! I've checked this out and found that indeed, some fields available in a payload are missing in the class. I don't think a `file_share` subtype payload has `team` and `bot_id`. I'll add `thread_ts` and `parent_user_id` to the definition.

**Comment by teamstand-rishabh** [comment]
I checked slack event payload and "team_id" is present in it. Can you please populate that team_id in the MessageFileShareEvent  like MessageEvent.

**Comment by seratch** [comment]
@teamstand-rishabh The field is included in this class as with others. https://github.com/slackapi/java-slack-sdk/pull/522/files#diff-bba7b3dac92de864436e59aed7f2c5ce

**Comment by teamstand-rishabh** [comment]
Thanks for that. But can you add in the MessageFileShareEvent.java
Like in the MessageEvent.java https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/event/MessageEvent.java#L28

**Comment by seratch** [comment]
@teamstand-rishabh No, I don't add the field in `file_share` events as it doesn't exist in a real payload. I do understand your inconvenience due to the inconsistency here. However, as an SDK developer, I cannot add any fields that don't exist in the actual payload.
