### ISSUE TITLE
no_file_data error when using fileData with no filename

### ISSUE THREAD

**Issue by sikorski-as** [slackapi/java-slack-sdk#523]
### Issue Type
- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description
I'm trying to upload an image in a Spring Boot + kotlin application using the slack-jdk but unfortunately it fails to upload the file content. I'm almost sure that something is wrong with building a multipart message since sending a file with text content works fine. Might be worth checking [`RequestFormBuilder.java#1128`](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/methods/RequestFormBuilder.java#L1128).

The issue is reproducible in:
* Module Version: 1.1.0
* Openjdk version "**14.0.2" 2020-07-14**
 OpenJDK Runtime Environment (build 14.0.2+12-46), 
 OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
* OS Version etc: macOS Catalina 10.15.5

The steps to reproduce are:
`val filepath = File("path/to/local/file.png")`
`val fileUploadRequest = FilesUploadRequest.builder().fileData(filepath.readBytes()).filetype("png").build()`
`println(methods.filesUpload(fileUploadRequest))`

The expected result is:
Upload a file and get `FilesUploadResponse` with `ok=true` :)

The actual result is:
`FilesUploadResponse(ok=false, warning=null, error=no_file_data, needed=null, provided=null, file=null)`

---

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@sikorski-as Thanks for taking the time to report this!

When you use the `fileData` setter method instead of `file`, giving `filename` at the same time is the way to use the method in the latest version. Here are some test cases reproducing the behaviors. https://github.com/seratch/java-slack-sdk/commit/8ec78c5eaba462b8ba08fb7f56839642a7ccfb9b

That being said, I do understand this is confusing. I will be improving the error message or changing the behavior to set a random name if absent. Thanks again for reporting this.

**Comment by sikorski-as** [comment]
Well, this is surprising 😄 

I added a filename and it fixed the issue, file uploads appropriately.
Thanks for a quick response!

**Comment by VamsiChinta** [comment]
Hey, I found the same issue while using file upload. The file only got uploaded to the slack channel after adding the filename

 ```
     FilesUploadResponse response = slack.methods(token).filesUpload(req -> req
                .channels(Collections.singletonList("xxxxxx"))
                .file(new File("target/site/serenity/index.html")).filename("index.html"));
```
