### ISSUE TITLE
Binary compatibility issue with old Kotlin language version

### ISSUE THREAD

**Issue by Przemek-12** [slackapi/java-slack-sdk#548]
### Issue Type

**TODO**:
Place an `x` in one of the `[ ]`.

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

**TODO**:
I'm developing spring boot application with jdk 13 that uses slack api - slask commands. Requests from slack come to my endpoint and I can read request entity. The problem is when I call Slack.getInstance() method. Compiler throws exception:
java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'.
I was using maven dependency:
	
 	        <dependency>
		    <groupId>com.slack.api</groupId>
		    <artifactId>slack-api-client</artifactId>
		    <version>1.1.3</version>
		</dependency> 

So far, I solved this problem with three other dependencies:

                  <dependency>
                       <groupId>com.github.seratch</groupId>
                       <artifactId>jslack-api-client</artifactId>
                       <version>3.4.2</version>
                  </dependency>
                  <dependency>
                       <groupId>javax.websocket</groupId>
                       <artifactId>javax.websocket-api</artifactId>
                       <version>1.1</version>
                  </dependency>
                  <dependency>
                      <groupId>org.glassfish.tyrus.bundles</groupId>
                      <artifactId>tyrus-standalone-client</artifactId>
                      <version>1.13</version>
                  </dependency>

Using those dependencies is proper way of handling this issue?

---
(only for a bug report)

**TODO**:
If this is a bug report, filling out the following details about bugs will help us solve your issue sooner.

The issue is reproducible in:
* Module Version: **TODO**: x.y.z
* JDK Version: **TODO**: jdk 13
* OS Version etc: **TODO**: windows 10

The steps to reproduce are:
1. use slack-api-client dependency
2.call Slack.getInstance() method

The expected result is:
**TODO**: Slack should get Instance

The actual result is:
**TODO**: What actually happened
log: 09:15:30.110 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

Adding com.fasterxml.jackson.module doesn't work.

java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'

---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
>Compiler throws exception: java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'.

This seems to be a binary-compatibility issue with Kotlin language standard libraries in your project. 

This SDK doesn't directly depend on Kotlin (except Kotlin extensions) but underlying okhttp library relies on Kotlin 1.3 or higher. So, please upgrade Kotlin lang dependencies to the latest. 

Also, Spring Boot may add okhttp 3.x but the old major version is not compatible with this SDK. Explicitly resolving okhttp 4.x may be required as our document does: https://slack.dev/java-slack-sdk/guides/supported-web-frameworks

> jslack-api-client

`jslack-api-client` is not required.

**Comment by Przemek-12** [comment]
Thank you, adding Kotlin dependency worked.

Kind Regards,
Przemek

**Comment by seratch** [comment]
Great to know. Let me close this issue now.
