### ISSUE TITLE
UsersLookupByEmailResponse extends a deprecated class

### ISSUE THREAD

**Issue by pmioulet** [slackapi/java-slack-sdk#549]
`com.slack.api.methods.response.users.UsersLookupByEmailResponse` extends a deprecated class which points back to it as a fix:

```
public class UsersLookupByEmailResponse extends com.slack.api.methods.response.channels.UsersLookupByEmailResponse
```
Using that class in the users package causes deprecation warnings in any code using this. Is this some work in progress?

Thanks.

**Comment by seratch** [comment]
@pmioulet Hello, thanks for asking a question. After releasing v1.0, we noticed that the class was placed in the wrong package (channels). Just in case, the corrected class inherits the old class for backward-compatibility: https://github.com/slackapi/java-slack-sdk/pull/486

 We're going to remove the parent (deprecated) class in the future versions.

**Comment by pmioulet** [comment]
Thanks for your quick reply
