### ISSUE TITLE
How to get appId in the saveInstallerAndBot function

### ISSUE THREAD

**Issue by mihristov** [slackapi/java-slack-sdk#572]
Hi. Thanks for the SDK, it's a great tool for building Slack apps. 
I'm currently trying to get the multi-workspace oauth flow running. Because of our project specifics we want to use the Java SDK (this repo) to generate the installation URL (which is already done) and save the Slack org's credentials in DynamoDB upon successful authorization. Then the other part of the Slack app will be hosted in a NodeJS app using the Slack bolt-js SDK (which is already done) which on his part will read the installations from Dynamo. One problem I have with this setup is that when I read the [Installation](https://github.com/slackapi/node-slack-sdk/blob/main/packages/oauth/src/index.ts#L476) object in the NodeJS app, it expects to have the appId field, which I don't have in the [Java Installer object](https://github.com/slackapi/java-slack-sdk/blob/a973bb43db9c1b6136873f3129252dba63315110/bolt/src/main/java/com/slack/api/bolt/model/builtin/DefaultInstaller.java). Is there a way I get my hands on the App Id in my implementation of the [InstallationService](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java)?
Thanks

#### The Slack SDK version

[INFO] +- com.slack.api:bolt:jar:1.2.0-SNAPSHOT:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.2.0-SNAPSHOT:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.2.0-SNAPSHOT:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.2.0-SNAPSHOT:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.2.0-SNAPSHOT:compile

#### Java Runtime version

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

#### OS info

#51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Hit the installation url
2. Authorize the app in your workspace
3. Enter in the saveInstallerAndBot method in my implementation of the [InstallationService](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java)

#### Expected result:

Have the appId in the [Installer object](https://github.com/slackapi/java-slack-sdk/blob/a973bb43db9c1b6136873f3129252dba63315110/bolt/src/main/java/com/slack/api/bolt/model/builtin/DefaultInstaller.java)

#### Actual result:

No appId :upside_down_face:

**Comment by seratch** [comment]
@mihristov Thanks for writing in! Yes, the field should exist. I will update the code soon.

**Comment by seratch** [comment]
The change has been merged into the `main` branch. I will be releasing v1.2.0-RC1 very soon.

**Comment by seratch** [comment]
v1.2.0-RC1 is available on the Sonatype OSS repositories now. The jars will be synched to the Maven Central soon. Try the version out when you have a chance 👋
