### ISSUE TITLE
Failing to parse request body when using along with Spring Boot 2.1

### ISSUE THREAD

**Issue by drussotto** [slackapi/java-slack-sdk#582]
#### The Slack SDK version

Note: I've tried several versions of bolt/bolt-servlet between 1.0.0-1.2.0 inclusive and gotten the same behavior.

```
[INFO] +- com.slack.api:bolt:jar:1.1.5:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.1.5:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.1.5:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.1.5:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.1.5:compile
```
#### Java Runtime version

`Java 8 SE 1.8.0_221`

#### OS info

So far I have only tested this in local dev environments using ngrok to communicate with Slack. I don't expect this is the cause of the problem, but just in case:

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
```

#### Steps to reproduce:

I am trying to do a slack command integration. The server receives the HTTP POST request from Slack that appears to contain all the correct information and in the correct format according to the API documentation, but my handler never actually gets executed.

#### Expected result:

My slash command handler defined below to get executed:

```
        app.command("/do-the-thing", (req, context) -> {
            
            SlashCommandPayload command = req.getPayload();
            
            slackMessageHandler.handleSlashCommand(command, context);
            
            return context.ack();
        });
```

#### Actual result:

The Slack Request parser receives an empty string as a body, and doesn't know what to do with it. Bolt acknowledges the request with a 200 but doesn't do anything because it doesn't recognize the request as a slash command.

```
 WARN  c.s.api.bolt.util.SlackRequestParser - No request pattern detected for 
```

(blank, because the body given to the method is blank.)

I did some debugging and found that everything appears to be going fine until [this line](https://github.com/slackapi/java-slack-sdk/blob/main/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/ServletAdapterOps.java#L19). The HttpServletRequest has the information in its reader, but this method fails to extract it. Ultimately, a blank String is sent as the body to [SlackRequestParser.parse](https://github.com/slackapi/java-slack-sdk/blob/master/bolt/src/main/java/com/slack/api/bolt/util/SlackRequestParser.java#L61)

### Other notes

As an experiment, when I mock a mostly identical request to our URL where the only change is changing `content-type` Header to `text/plain` as opposed to ` x-www-form-urlencoded` it works, or at least, the parser a) receives a body with actual content and b) recognizes the content as a slash command.

This issue is also unique to slash commands. I am able to successfully receive and process events pushed to our URL from the events API. 

#### Our basic code structure:

```
//SlackBotApplication.java
@SpringBootApplication
@EnableConfigurationProperties
@ServletComponentScan
public class SlackBotApplication {
 
    public static void main(String[] args) {
        try {
            ConfigurableApplicationContext applicationContext = new SpringApplicationBuilder()
                    .sources(SlackBotApplication.class)
                    .run(args);
            Thread.currentThread().join();
        } catch (Exception e) {
            System.out.println("Something went wrong " + e.getMessage());
}
}        }
    }
 
//SlackBotController.java
@WebServlet("/slack/events")
public class SlackAppController extends SlackAppServlet {
    public SlackAppController(App app) {
        super(app);
    }
}
 
//SlackBotConfigs.java
@Configuration
public class SlackBotConfigs {
    
    ...
    
    @Bean
    public App initSlackApp(SlackMessageHandler slackMessageHandler) {
        
        AppConfig appConfig = new AppConfig();
        
        appConfig.setSigningSecret(retrieveConfigurations().getSigningSecret());
        appConfig.setSingleTeamBotToken(retrieveConfigurations().getSlackbotToken());
        
        App app = new App(appConfig);
        
        app.event(AppMentionEvent.class, (payload, ctx) ->  {
            // do some stuff
              return ctx.ack()
        });
 
      app.event(MessageBotEvent.class, (payload, ctx) ->  {
          // do some stuff
          return ctx.ack()
      });
  
      app.command("/do-the-thing", (req, context) -> {
            
          //Do some stuff. Note that this handler never gets executed as a result of the issues we are facing           
          return context.ack();
       });
   }
    ...
}
```

**Comment by seratch** [comment]
@drussotto Hi, thank you for asking this question! 

We have an example built with Spring Boot in the document and it should work for you without this issue. https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#spring-boot

I tried to reproduce your issue by creating a simple Spring Boot app but I was not able to see the same situation. For your information, here is the app that works for me: https://github.com/seratch/slack-java-sdk-issue-582-example-app/blob/main/src/main/java/hello/SlackApp.java

>changing content-type Header to text/plain as opposed to x-www-form-urlencoded it works

This behavior sounds like additional Spring modules or Servlet filters may consume the request body in the case of form requests. If another library/module consumes the `Reader` object to bind a raw string body to some object, the situation described here can arise. 

Can you check your Spring Boot app's configurations and dependencies? Some features affecting form requests may be automatically enabled.

**Comment by drussotto** [comment]
@seratch , thank you so much for your help. I was able to get an example that is the same as yours working, but the original application I'm unable to get working still. I tried stripping out many of our dependencies but still facing the issue. This is the dependency tree of our application which still is not processing requests properly:

```
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.1.5.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.5.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.8:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.8:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.19:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.19:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.19:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.16.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.springframework:spring-web:jar:5.1.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.1.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.1.7.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.1.7.RELEASE:compile
[INFO] |     +- org.springframework:spring-context:jar:5.1.7.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.1.7.RELEASE:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.11.2:compile
[INFO] +- com.slack.api:bolt:jar:1.1.5:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.1.5:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.1.5:compile
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.1.5:compile
[INFO] +- com.squareup.okhttp3:okhttp:jar:4.8.1:compile
[INFO] |  \- com.squareup.okio:okio:jar:2.7.0:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.1.5:compile
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.72:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.72:compile
[INFO] |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.1.5.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.1.5.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.5.RELEASE:compile
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.11.1:compile
[INFO] |  +- org.mockito:mockito-core:jar:2.23.4:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.9.12:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.12:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:compile
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:compile
[INFO] |  +- org.springframework:spring-core:jar:5.1.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:5.1.7.RELEASE:compile
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.6.2:compile
[INFO] |     \- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |        \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] \- org.mockito:mockito-all:jar:1.10.19:test
```

This is the dependency tree of the sample application that is working:

```
[INFO] +- com.slack.api:bolt:jar:1.1.5:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.1.5:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.1.5:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:4.8.1:compile
[INFO] |  |     +- com.squareup.okio:okio:jar:2.7.0:compile
[INFO] |  |     |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.72:compile
[INFO] |  |        \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.1.5:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.1.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.3.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.3.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.3.4.RELEASE:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.26:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.3.4.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.2:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.2:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.2:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.3.4.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.38:compile
[INFO] |  |  +- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.38:compile
[INFO] |  +- org.springframework:spring-web:jar:5.2.9.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.2.9.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.2.9.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.2.9.RELEASE:compile
[INFO] |     +- org.springframework:spring-context:jar:5.2.9.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.2.9.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:2.3.4.RELEASE:runtime
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.3.4.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.3.4.RELEASE:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.3.4.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.3.4.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.4.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.16.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.6.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.6.2:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.6.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.6.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.6.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.6.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.3.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.2.9.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.2.9.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:5.2.9.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
[INFO] +- org.projectlombok:lombok:jar:1.18.12:provided
[INFO] +- junit:junit:jar:4.13:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] \- org.mockito:mockito-core:jar:3.5.13:test
[INFO]    +- net.bytebuddy:byte-buddy:jar:1.10.15:test
[INFO]    +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
[INFO]    \- org.objenesis:objenesis:jar:3.1:test
```


The most obvious difference is that in the broken application, `okhttp` 4.8.1 and `kotlin-stdlib` 1.3.72 are declared as top level dependencies as opposed to being brought in as dependencies of Bolt. If I remove either dependency declaration from my POM the relevant section of the dependency tree looks like this, and note the version change for `kotlin-stdlib`:

```
com.squareup.okhttp3:okhttp:jar:4.8.1:compile
[INFO] |  +- com.squareup.okio:okio:jar:2.7.0:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.71:compile
```

When I run the application this way, it won't even start. I get this error:


```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    okio.Segment.writeTo(Segment.kt:169)

The following method did not exist:

    kotlin.collections.ArraysKt.copyInto([B[BIII)[B

The method's class, kotlin.collections.ArraysKt, is available from the following locations:

    jar:file:/Users/drussotto/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar!/kotlin/collections/ArraysKt.class

It was loaded from the following location:

    file:/Users/drussotto/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of kotlin.collections.ArraysKt

```

In either case, I also get this log in the very beginning of starting my application: `2020-10-12 22:27:49.934 -0700 [main] INFO  o.s.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.` which I don't see in the working sample application. I have to imagine that the root cause is somewhere in this area, but I'm not sure what exactly or how to resolve the issue. Do you have any insight here?

**Comment by drussotto** [comment]
Also, regarding the issue of classpath conflicts for the kotlin-stdlib 1.2.71, I'm not sure why that error even appears since it appears to me that they're referring to classes belonging to the same jar file. I've tried cleaning up that directory and redownloading it, but that didn't do anything helpful.

**Comment by seratch** [comment]
Thanks for sharing this. hmm, I'm not sure if this bin-compatibility issues between Kotlin minor versions is related to your original question about form request handling (probably, this is another issue and unrelated to the original topic, right?).

Generally speaking, issues around Spring Boot apps can be a bit complex depending on what modules and/or Gradle/Maven plugins are used. So, I'm not sure about what is happening in your project yet. If you could share a simple example project reproducing the issue with me, I may be able to help you.

**Comment by drussotto** [comment]
@seratch I don't know if it is, which is why I bring it up. The reason why I think it could be related is that OkHttp requires that kotlin-stdlib dependency, and so I thought there was maybe something that okhttp should or shouldn't do to the request before it reaches the servlet and that could be the cause. Could be totally separate though, as you said - just wanted to share everything I'm seeing.

This repo contains a stripped down version of the project that still gives me the same behavior that I've described earlier. Please take a look when you get the chance and let me know if you're getting the same / any other insights you may glean from it. Thanks again.

https://github.com/drussotto/broken-slack-bot

**Comment by seratch** [comment]
@drussotto Thanks for sharing this. I found that this issue indeed arises with Spring Boot 2.1. Is there any chance of upgrading your Spring Boot version to 2.2+? I've confirmed it surely works with Spring Boot 2.2 and 2.3 (the latest).

**Comment by drussotto** [comment]
@seratch We were able to get our application working with Spring 2.2.8. Thanks so much for your help! I'll close this question now.

**Comment by vikrim1** [comment]
@seratch I'm hitting the same issue with Spring Boot 2.1, and I'm having a harder time upgrading to 2.2. Any other paths to resolving this? Thanks!

**Comment by seratch** [comment]
@vikrim1 Unfortunately, I was not able to find the way to resolve this issue while using Spring Boot 2.1. Running your Bolt app separately in another Spring Boot 2.2+ app is the only other workaround I can suggest.

**Comment by luispollo** [comment]
I'm seeing the same issue with Spring Boot 2.3.11.RELEASE. Any insights into the cause of the original problem in the older version of Spring Boot, in case this is a regression?

**Comment by seratch** [comment]
@luispollo Just in case, I've verified that this issue does not occur with Spring Boot 2.3.11 itself. Here is a tiny app I used for checking it: https://gist.github.com/seratch/00eb210bbab6336a0c6b2304999bbb94 Thus, there should be a particular reason in your application.

>Do you have any examples of features that might affect form requests?

The common causes of the situation described here are:
* Lack of valid string request body (= unmodified as-is string data of request body)
* Invalid system clock settings in the host your app is running

The first one is more common. **If some of your Spring Boot add-ons/extensions parse (=in other words, they consume the `InputStream` of request body) under the hood, your Slack app endpoint is unable to know the valid request body data (as you may know, this is Servlets' limitation).** Also, this is why we encourage using `@WebServet` type controllers for Bolt apps. Your web controller needs the access to the unmodified request body (InputStream) in `HttpServletRequest`.

I hope this was helpful to you and you'll figure out the cause of the situation in your app!

**Comment by luispollo** [comment]
> The first one is more common. If some of your Spring Boot add-ons/extensions parse (=in other words, they consume the InputStream of request body) under the hood, your Slack app endpoint is unable to know the valid request body data (as you may know, this is Servlets' limitation). Also, this is why we encourage using @WebServet type controllers for Bolt apps. Your web controller needs the access to the unmodified request body (InputStream) in HttpServletRequest.

Thanks for the feedback, @seratch. I'm using a `@WebServlet` controller. My suspicion is that one of the request filters in the chain is consuming the input stream before it gets to the controller, but I have 13 filters in my app, so it's taking a while to figure out which one is to blame. 😓

**Comment by lirikooda** [comment]
> > The first one is more common. If some of your Spring Boot add-ons/extensions parse (=in other words, they consume the InputStream of request body) under the hood, your Slack app endpoint is unable to know the valid request body data (as you may know, this is Servlets' limitation). Also, this is why we encourage using @WebServet type controllers for Bolt apps. Your web controller needs the access to the unmodified request body (InputStream) in HttpServletRequest.
> 
> Thanks for the feedback, @seratch. I'm using a `@WebServlet` controller. My suspicion is that one of the request filters in the chain is consuming the input stream before it gets to the controller, but we have dozens of filters, so it's taking a while to figure out which one is to blame. 😓

In my case it was OAuth filter, for anyone struggling with the issue

**Comment by luispollo** [comment]
For anyone finding this thread, after running into this problem a few times, our final solution was to switch to [socket mode](https://api.slack.com/apis/connections/socket), which avoids the needs for HTTP callbacks altogether. Highly recommended.

**Comment by Jankaz2** [comment]
The same problem occurs after updating spring boot from 2.7.x to 3.0.0 where jakarta imports are used. I've also updated slack dependencies according to this example https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#spring-boot 
When I delete spring-security, the problem disappear. I do not have any custom filters, just the basic authentication. Any ideas for solution?

**Comment by seratch** [comment]
@Jankaz2 Thanks for sharing this. Perhaps, since Spring Boot v3, there may be some incompatibility with Spring Security extension. I will look into it later to find out a possible workaround for it but at this point, the only suggestion that I have is just to avoid using Spring Security for your bolt-java apps. If Spring Security is required for the rest of your app (I know this is true), I would suggest separating the Slack app part from the large Spring Boot app (I know this is not great for you, though).

**Comment by Jankaz2** [comment]
I fixed the problem by using custom filter from this [tutorial](https://www.baeldung.com/spring-reading-httpservletrequest-multiple-times)

**Comment by dcalde** [comment]
I found a clean and, I believe, the correct solution for the problem.
As some have already discovered Spring Security is to blame:

`OAuth2AuthenticationProcessingFilter.doFilter() -> tokenExtractor.extractToken() -> request.getParameter()`

Inside `request.getParameter()`, you guessed it, the stream is read.

Since the Slack Api deals with its own authentication, we shouldn't even be processing any of the Spring Security Filter in the first place. Luckily Spring provides a proper way to to do this (Source: https://stackoverflow.com/questions/40475620/spring-security-exclude-url-on-custom-filter):

```
public void configure​(WebSecurity web)
    web.ignoring().antMatchers("/slack/**");
}
```

**Comment by smallufo** [comment]
my spring boot 3 app with slack also failed , even with such a clean spring security config : 
```
@Bean
  fun filterChain(http: HttpSecurity): SecurityFilterChain {

    return http
      .authorizeHttpRequests { authorize ->
        authorize
          // .requestMatchers(antMatcher("/slack/**")).permitAll() // enable this line doesn't help
          .anyRequest().permitAll()
      }
      .build()
  }

```
The only way is to disable spring security : 
```
@SpringBootApplication(
                       exclude = [SecurityAutoConfiguration::class] // to disable SpringSecurity
)
```

dependencies : 
```
org.springframework.boot:spring-boot-dependencies:pom:3.1.0:runtime
com.slack.api:bolt-jakarta-servlet:jar:1.29.2:compile
```

and code is also simple : 
```
@WebServlet("/slack/events")
class SlackEventsController(app: App) : SlackAppServlet(app)
```

**Comment by khiemns54** [comment]
Update for spring 3.x. Using `WebSecurityCustomizer` to ignore slack endpoint

```
    @Bean
    fun webSecurityCustomizer(): WebSecurityCustomizer {
        return WebSecurityCustomizer { webSecurity ->
            webSecurity.ignoring().requestMatchers("/slack/**")
        }
    }
```
