### ISSUE TITLE
Add support for http4k platform for Bolt apps.

### ISSUE THREAD

**Issue by daviddenton** [slackapi/java-slack-sdk#584]
Implement a module to run Bolt apps on top of the http4k platform, by providing an adapter (with tests) between the 2 APIs, which would allow Bolt apps to be run standalone or mixed into bigger application setups. Http4k itself provides a choice of 11 different JVM Server and Serverless backends which can be switched out with one line of code.

Implemented in PR #583

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [X] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Thanks - fixed by #583
