### ISSUE TITLE
Proxy Authentication Support In RTMClient

### ISSUE THREAD

**Issue by jbellenger** [slackapi/java-slack-sdk#586]
It would be great if RTMClient supported proxy authentication. This is useful in our corporate environment that that has access controls around outgoing traffic and requires services to authenticate.

We're currently working around this by crafting a proxy url in the shape of "http://user:password@host" and creating a replacement for RTMClient that sets the right client properties on the underlying glassfish client:

```scala
Option(slack.getConfig.getProxyUrl)
  .map(URI.create)
  .foreach { proxyUri =>
    val auth = Base64.getEncoder.encodeToString(proxyUri.getUserInfo.getBytes("UTF-8"))
    val proxyHeaders = Map("Proxy-Authorization" -> s"Basic $auth")

    client.getProperties.put(ClientProperties.PROXY_URI, proxyUri.toString)
    client.getProperties.put(ClientProperties.PROXY_HEADERS, proxyHeaders.asJava)
  }
```

It would be great to get some flavor of proxy-auth support into the mainline slack-api-client. I'm happy to post a PR for the above approach if this looks good to the project maintainers.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
@jbellenger Hello, thanks for the suggestion (and I personally love Scala code snippets)! I am happy to improve the RTMClient to be easier for your use case. 

We have some unit tests for proxy support. https://github.com/slackapi/java-slack-sdk/blob/v1.2.1/slack-api-client/src/test/java/test_with_remote_apis/ProxyTest.java
Would you mind helping us write a specific unit test for this change?

**Comment by jbellenger** [comment]
It looks like this was fixed in the last update! Thanks @seratch !

**Comment by seratch** [comment]
Glad to hear that! Let me close this issue now.
