### ISSUE TITLE
[micronaut-bolt] -SlackAppController to use  @ExecuteOn(TaskExecutors.IO)

### ISSUE THREAD

**Issue by parisapo** [slackapi/java-slack-sdk#587]
Hello, based on Micronaut's documentation see [here](https://docs.micronaut.io/latest/guide/index.html#reactiveServer) and checking the [SlackAppController.ava](https://github.com/slackapi/java-slack-sdk/blob/main/bolt-micronaut/src/main/java/com/slack/api/bolt/micronaut/SlackAppController.java),  would it make sense to `decorate` the `SlackAppController` with the following?

```java
 @ExecuteOn(TaskExecutors.IO)
 SlackAppController 
```

Thanks for your time

**Comment by seratch** [comment]
I think that depends on the characteristics of a Bolt app.

>Used to, for example, offload blocking I/O operations to specifically configured thread pool.

https://docs.micronaut.io/latest/api/io/micronaut/scheduling/annotation/ExecuteOn.html

In my understanding, `TaskExecutors.IO` is not always the best solution. You may want to specify your own thread pool executor (or other non-blocking approach).

So, I don't think the default controller should specify specific one. If you want to use a task executor, I recommend using your own Micronaut controller with an optimal executor for it.

If many developers just want to use `TaskExecutors.IO` based one and don't want to repeat creating such simple controllers every time creating a new app, I'm happy to add `TaskIOSlackAppController` to the library.

**Comment by parisapo** [comment]
@seratch thanks for your answer.
