### ISSUE TITLE
Java bolt: Getting multiple event notification for the same message posted in Slack

### ISSUE THREAD

**Issue by BaradPuja** [slackapi/java-slack-sdk#592]
Hi Team,

I am using Java bolt for developing a Slack App, i have subscribed to MessageEvent and currently getting multiple event notification for a single message posted in Slack.

**Comment by seratch** [comment]
Hi @BaradPuja probably, your app doesn't respond to the event requests within 3 seconds. In this case, the Slack server retries the same request up to 3 times. https://api.slack.com/events-api#the-events-api__field-guide__error-handling__graceful-retries

As a quick solution, you can use the built-in `ExecutorService` that is accessible by `app.executorService()`. If you prefer another solution such as queue systems, you can go with any others to run your code asynchronously.

```java
app.event(MessageEvent.class, (req, ctx) -> {
  app.executorService().execute(() -> {
    // so any time-consuming operations here
  });
  return ctx.ack(); // You need to return this within 3 seconds
});
```
Here is a working example (for `block_actions` events): https://github.com/slackapi/java-slack-sdk/blob/v1.2.1/bolt/src/test/java/test_locally/app/BlockActionTest.java#L94-L104

**Comment by BaradPuja** [comment]
Hi @Seratch, 
Thank you for the quick response, I tried below sample code still getting multiple event notifications.
app.event(MessageEvent.class, (payload, ctx) -> {
    	  
    	  app.executorService().execute(() -> {
              try {
                  Thread.sleep(50000);
                  ctx.say("Hello, <@" + payload.getEvent().getUser() + ">");
              } catch (Exception e) {
                  Thread.currentThread().interrupt();
              }
          });
          return ctx.ack();
      });

**Comment by seratch** [comment]
Just in case, could you check your web server's response time in its access logs? You app may not be working as you expect for some reasons. Your app needs to **respond to all requests from Slack with 200 OK in less than 3 seconds**.

If you're familiar with [ngrok](https://ngrok.com/), using it along with your Bolt app on your local machine may be easier to check how it works. http://localhost:4040/inspect/http is useful to check the communications with Slack platform servers.

If your app always sends successful responses quickly, this may be a bit rare issue on the Slack server-side. In this case, would you mind contacting our platform support agents from https://my.slack.com/help/requests/new ? As this is a public place, we are unable to ask you to provide more information about your apps and workspaces. I'd be grateful if you could understand this.

**Comment by BaradPuja** [comment]
Ok sure @Seratch, 
I will check and contact if any issues in Slack server side.

One more request, is there any proper documentation for java bolt like method description it's usage etc.
I couldn't find good doc, eac time I have to go throgh the bolt git lab project to understand the method and it's usage.

Thank You!!

**Comment by seratch** [comment]
All the method names in this SDK correspond to the Platform features and the APIs. Refer to the API documents as below:
* https://api.slack.com/methods
* https://api.slack.com/events
* https://api.slack.com/surfaces

As I've provided answers to all your questions, let me close this issue now. Thanks for writing in.
