### ISSUE TITLE
Subscribe to Slack Events

### ISSUE THREAD

**Issue by Syed-SnapLogic** [slackapi/java-slack-sdk#593]
Hi,
  I just have few questions w.r.t to Slack Events Subscription.  I tried this:
![image](https://user-images.githubusercontent.com/5888194/96449542-9efd5780-1232-11eb-8e79-c2651733030a.png)
But my url needs access token, and I don't see any way in slack to supply token.  Can someone help here with how to supply the token?

Secondly, I tried using RTM API. https://api.slack.com/methods/rtm.connect  Do we have SDK for this RTM as well?  Any ref?

**Comment by Syed-SnapLogic** [comment]
@seratch , any thoughts from ur side on this?

**Comment by misscoded** [comment]
Hi @Syed-SnapLogic! Happy to help with this. 🙂

We don't support adding custom tokens to HTTP requests for authenticated gateways, so the best option would be to use RTM, as you've indicated you've attempted to do already.

For our knowledge and to hopefully eventually provide better support, **would you mind letting us know what kind of gateway you're using?**

As for RTM, below are two documents that we recommend reading through to get you set up:

https://github.com/slackapi/java-slack-sdk/blob/main/docs/guides/rtm.md
https://www.javadoc.io/doc/com.slack.api/slack-api-client/latest/com/slack/api/rtm/RTMClient.html

Hope that's helpful! If we can answer any more questions as you move forward, please don't hesitate to reach out. Else, if you think this has answered your question and resolved the issue, feel free to close it.

**Comment by Syed-SnapLogic** [comment]
@misscoded , thank you so much for the response.  I tried, but I am getting "missing scope" error.
Can I know what scope should I add to my token to get this done?  If I pass "client" scope, I am getting error as that scope is deprecated.  Pls help.

**Comment by seratch** [comment]
@Syed-SnapLogic 
>But my url needs access token, and I don't see any way in slack to supply token. Can someone help here with how to supply the token?

For the url verification when setting up Events API, your endpoint just need to echo the `challenge` value in  payload. Here is the code that does it in Bolt for Java. https://github.com/slackapi/java-slack-sdk/blob/v1.2.1/bolt/src/main/java/com/slack/api/bolt/App.java#L944-L950

For a classic app setup for RTM API, try the following steps:

* Create a classic app from https://api.slack.com/apps?new_classic_app=1
* Go to **Features** > **OAuth & Permissions** > **Scopes**
  * Click "Add an OAuth Scope"
  * Search "bot" and choose it
* Go to **Features** > **App Home** 
  * Click "Add Legacy Bot User"
  * Input "Display Name" and "Default username"
  * Click "Add"
* Go to **Settings** > **Install App**
  * Click "Install App to Workspace"
  * Complete the OAuth flow

**Comment by seratch** [comment]
@Syed-SnapLogic Was my previous comment helpful? Let me close this issue after waiting for your response for a few days.

**Comment by Syed-SnapLogic** [comment]
@seratch , I still didn't try it out.  I was using URL based listeners so far.  I shall try it out sooner, and update you if any thing needed.  Good that you closed it for now.  Thnx.
