### ISSUE TITLE
OptionObjectBuilder for Kotlin is creating a null text field for the Kotlin View Builder extension.

### ISSUE THREAD

**Issue by snoozan** [slackapi/java-slack-sdk#594]
I'd like to be able to create option objects using the kotlin view builder extension. I'm not sure if I'm declaring this incorrectly, but the options block builder isn't populating the text field and I don't see a clear cut way to populate that text field.

### Reproducible in:
Creating a View object does not populate the text field within "options" for blocks. This makes the request fail. 

#### The Slack SDK version
```
slack-api-model:1.2.1
slack-api-model-kotlin-extension:1.2.1
```

#### Java Runtime version

```
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
```
#### OS info

MacOS 10.15.6

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Create a view block object.
```
fun buildView(): View {
    return view { thisView -> thisView
            .callbackId("meeting-arrangement")
            .type("modal")
            .notifyOnClose(true)
            .title(viewTitle { it.type("plain_text").text("PriceID/ New Offer").emoji(true) })
            .submit(viewSubmit { it.type("plain_text").text("Submit").emoji(true) })
            .close(viewClose { it.type("plain_text").text("Cancel").emoji(true) })
            .blocks {
                section {
                    markdownText("I need a PriceID / New Offer")
                    blockId("price-id-block")
                }
                actions {
                    radioButtons {
                        actionId("price-id-options")
                        options {
                            option{
                                description("*0% (\$399 - no discount))*", false)
                            }
                        }
                    }
                }
            }
```
This returns a view - note that the [OptionObjectBuilder](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model-kotlin-extension/src/main/kotlin/com/slack/api/model/kotlin_extension/block/composition/OptionObjectBuilder.kt) only takes a description, value and url. 
2. Send a `viewsOpen` api call:
```
            val view = buildView();

            val response = slack.methods(token).viewsOpen { req -> req
                    .triggerId(payload.triggerId)
                    .view(view)
                    .token(token)
            }
```
3. Response returns a failure due to missing text field in options.

#### Expected result:

I'm not sure if text should be populated with the description, or if text should be a field sent. Looking at the code here:
[OptionObjectBuilder text initialization](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model-kotlin-extension/src/main/kotlin/com/slack/api/model/kotlin_extension/block/composition/OptionObjectBuilder.kt#L19), we can see that we're initializing the text to null.

#### Actual result:

Inspecting the created `ActionsBlock`object, we can see that text is a null field:
```
ActionsBlock(type=actions, elements=[RadioButtonsElement(type=radio_buttons, actionId=price-id-options, options=[OptionObject(text=null, value=null, description=PlainTextObject(type=plain_text, text=*0% ($399 - no discount))*, emoji=false), url=null)], initialOption=null, confirm=null)], blockId=null)
```
The error returned from the request:
```
ErrorResponseMetadata(messages=[[ERROR] failed to match all allowed schemas [json-pointer:/view], [ERROR] missing required field: text [json-pointer:/view/blocks/1/elements/0/options/0]])
```

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
@snoozan Thanks for taking the time to report this. This seems to be a bug.

**Comment by seratch** [comment]
@snoozan Ah, no. You can use `text`, `plainText` methods inside `option { }` blocks as `OptionObjectBuilder` implements `TextObjectDsl`. Let me remove the `bug` tag I mistakenly put.

**Comment by snoozan** [comment]
Hey @seratch - you're right! I was trying to just use `text` instead of `markdownText`. Thanks for the help - my fault. 🤦
