### ISSUE TITLE
Slack Java Bolt: Clear conversation history

### ISSUE THREAD

**Issue by BaradPuja** [slackapi/java-slack-sdk#600]
Hi Team,

We have developed a Slack chatbot using Java bolt framework in our org. As there are sensitive information available in the conversation we don't want to save it in Slack server. Also we are looking for clearing Chat history at the end of conversation programmatically.

Could you please help me on this.

Thank You!!

//Puja

**Comment by seratch** [comment]
Hi @BaradPuja you can use [chat.delete](https://api.slack.com/methods/chat.delete) API method to delete a message. You need to call this API method several times to delete all the messages in a thread or conversation. You can check the code in the document page (the Code tab).

<img src="https://user-images.githubusercontent.com/19658/97537903-e4740e80-1a02-11eb-828d-fe9f9f37bfb3.png" width=600>

**Comment by BaradPuja** [comment]
HI @seratch,

is there any method available that we can use only once to delete entire conversation at end?  Also is the conversation saved in Slack Server or not?

//Puja

**Comment by seratch** [comment]
> delete entire conversation

If you mean deleting a channel (or direct message), unfortunately, there is no publicly available API to delete a channel. You can archive channels using [conversations.archive](https://api.slack.com/methods/conversations.archive) but doing so doesn't mean deleting the stored data. 

So, possible ways to achieve your goal would be 1) using `chat.delete` for all messages, or 2) asking your end users to manually delete channels in the Slack UI.

> Also is the conversation saved in Slack Server or not?

As it is a SasS, all data in a workspace is stored in the servers operated by Slack.

As I've answered your question here, would you mind closing this issue now?

**Comment by BaradPuja** [comment]
Hi @seartch,

I was little bit worrying about the data security , as the info is specific to our organization which we don't want to store into Slack server.
We have started using Slack recently in our Organization and   we want to migrate our old chatbots in jabber to Slack. So, If you can help me to get more clarity of the information security it will be a great help.

Thank You!!

**Comment by seratch** [comment]
I'm glad to know that you organization started using Slack! If your company is an Enterprise Grid customer, it may be worth considering [Slack Enterprise Key Management](https://slack.com/enterprise-key-management). I'm sorry to bother you but, not limited to EKM, please [contact Slack's customer support team](https://my.slack.com/help/requests/new) for details of the security topics.

As this is a place for issues of Slack SDKs and I've already provided an answer to your question about the APIs, please allow me to close this issue now. Thanks for using this SDK!

**Comment by BaradPuja** [comment]
Thank you for providing quick response
