### ISSUE TITLE
Java Bolt: unable to get request payload for block action

### ISSUE THREAD

**Issue by BaradPuja** [slackapi/java-slack-sdk#607]
I have started exploring slack interactive component using block kit and currently, facing issue with getting payload on button click.
I am able to create and send block action to slack but unable to get the request payload on button click.
Please find below the code snippet:-
```java
// when a user clicks a button in the actions block
app.blockAction("button-action", (req, ctx) -> {
  System.out.println("inside block action");
  String value = req.getPayload().getActions().get(0).getValue(); // "button's value"
  if (req.getPayload().getResponseUrl() != null) {
    // Post a message to the same channel if it's a block in a message
    ctx.respond("You've sent " + value + " by clicking the button!");
  }

```

**Comment by seratch** [comment]
Hello @BaradPuja , can you check the **Slack App Configuration** part in the document?
https://slack.dev/java-slack-sdk/guides/interactive-components

Configuring Request URL beforehand in **Interactivity & Shortcuts** page is required.

**Comment by BaradPuja** [comment]
Hi @Seratch, I already configured the api url and I am using the same url both for event subscription and interactive component

**Comment by seratch** [comment]
Can you check the following?

* Check your app's access logs to know your app surely received requests from Slack
  * If you use ngrok, access http://localhost:4040/inspect/http
  * if you're not sure about how to check this - having [this kind of middleware](https://github.com/slackapi/java-slack-sdk/blob/v1.2.1/bolt-servlet/src/test/java/samples/BlocksSample.java#L38-L47) may be helpful
* If your app is surely receiving requests and the listener for the action_id "button-action" doesn't work as you expect:
  * Verify if the `action_id` set to the button is **"button-action"** (if you don't have `action_id` in the block element, a randomly generated value should be set to the field)

**Comment by BaradPuja** [comment]
- if you're not sure about how to check this - having this kind of middleware may be 
              app.use method gets executed when I/m posting a message to slack 
                `if(userMsg.equals("help")) {
							ctx.say(asBlocks(
								      actions(actions -> actions
								      .elements(asElements(
								        button(b -> b.actionId("button-action").text(plainText(pt -> pt.text("Yes"))).value("yes"))
								      ))
								    )
								  ));`

- Verify if the action_id set to the button is "button-action" (if you don't have action_id in the block element, a randomly generated value should be set to the field)
    Yes, i am using the same action id but it's not entering to the block action method

**Comment by BaradPuja** [comment]
on button click, no request comes to the app

**Comment by seratch** [comment]
>app.use method gets executed when I/m posting a message to slack

Does this mean you see the request payload log only when your app receives Events API requests? If so, I guess your app's Interactivity feature's configuration is still incorrect. Could you verify the configuration is surely correct again and/or check if shortcuts work (global/message shortcuts use the same Request URL)?

Otherwise, ... this seldomly happens but something wrong may be happening on the Slack's server-side. In this case, re-installing your app into the workspace may help.

Also, turning debug-level logs (by changing slf4j/logback settings) on may be helpful to know what is happening. You can easily check the detailed information in logs.

**Comment by BaradPuja** [comment]
Slash command and shortcuts also not working, only event subscription works for me. I have reinstalled the app multiple times still the same issue

**Comment by seratch** [comment]
hmm, it sounds a bit similar to this issue: https://github.com/slackapi/java-slack-sdk/issues/582

Do you use Bolt in a Web framework? If you use Bolt as part of a Spring Boot 2.1 app, consider upgrading Spring Boot version to 2.2+.

**Comment by BaradPuja** [comment]
yeah, I am using bolt with spring boot. Let me upgrade the version of spring boot. Will it you know if it works

**Comment by BaradPuja** [comment]
Hi @Seartch, 

 Now my app is able to receive block action request payload but in the app block action message top it's showing "only visible to you" . Could you please help on this.
Thank you!

**Comment by seratch** [comment]
@BaradPuja It's [an ephemeral message](https://api.slack.com/messaging/managing#ephemeral). You can use `in_channel` response type. https://api.slack.com/tutorials/slash-commands-style-guide#public_vs_ephemeral_responses

With Bolt for Java, the actual code would be as below:

```java
app.command("/hi", (req, ctx) -> {
  ctx.ack(r -> r.responseType("in_channel").text("Hi"));
  ctx.respond(r -> r.responseType("in_channel").text("Hi"));
```

I'm glad to know you've managed to run your apps with Spring Boot! If I've answered all your questions, could you close this question issue?

**Comment by BaradPuja** [comment]
Yeah Sure, Closing this. Thank you for you quick help and support
