### ISSUE TITLE
Provide option to set Connect & Read Timeout for HTTP client

### ISSUE THREAD

**Issue by anuj-dwivedi** [slackapi/java-slack-sdk#609]
Looks like there is no way to set Connect Timeout and Read Timeout for API calls. When I try to invite few hundred members to a channel then the call at client side is timing out in 10 seconds (default timeout of okHttpClient) though at server side operation is completing fine eventually.

So please provide a way to configure Connect and Read timeout for API calls.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
@anuj-dwivedi Thanks a lot for taking the time to report this! We'll add the settings in `SlackConfig` in the next minor version (1.3.0) that will be available within a few days. 

If you're in a hurry, a workaround at this point is to manually create an `OkHttpClient` instance as below.
```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
  .readTimeout(0, TimeUnit.MILLISECONDS)
  .writeTimeout(0, TimeUnit.MILLISECONDS)
  .callTimeout(0, TimeUnit.SECONDS)
  .build();

SlackHttpClient slackHttpClient = new SlackHttpClient(okHttpClient);
Slack slack = Slack.getInstance(SlackConfig.DEFAULT, slackHttpClient);
```

**Comment by anuj-dwivedi** [comment]
Sure. Thank you @seratch !
