### ISSUE TITLE
UsersLookupByEmailResponse, getUser method deprecated

### ISSUE THREAD

**Issue by Przemek-12** [slackapi/java-slack-sdk#614]
Hi,

I want to fetch user details by email. I'm using UsersLookupByEmailRequest: 
``` 
protected UsersLookupByEmailResponse getUserByEmail(UsersLookupByEmailRequest request)
            throws IOException, SlackApiException {
        return Slack.getInstance().methods().usersLookupByEmail(request);
}
```

I'm returning com.slack.api.methods.response.users.UsersLookupByEmailResponse above. However, when invoking mehod getUser() on returned object, I get error: deprecated. 

It is said under this link: https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/methods/response/channels/UsersLookupByEmailResponse.java, that I should use com.slack.api.methods.response.users.UsersLookupByEmailResponse.

However I still get the same message, that method is deprecated. As I can see, below class extends deprecated class.
```
package com.slack.api.methods.response.users;

public class UsersLookupByEmailResponse extends com.slack.api.methods.response.channels.UsersLookupByEmailResponse {
}
```

**Comment by seratch** [comment]
@Przemek-12 Thanks for taking the time to report this. We will fix this issue in the next release, which is going to be released within a few days.
