### ISSUE TITLE
TimePickerElement malfunctioning in the SDK

### ISSUE THREAD

**Issue by Hariprasad-Ramakrishnan** [slackapi/java-slack-sdk#626]
TimePickerElement malfunctioning in the SDK when used as an accessory for InputBlockElement. It behaves as a DatePickerElement in the UI, prompting Date from the user ad not Timel

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version
[INFO] +- com.slack.api:slack-api-client:jar:1.3.0-RC3:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.3.0-RC3:compile
[INFO] +- com.slack.api:slack-app-backend:jar:1.3.0-RC3:compile

#### Java Runtime version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

#### OS info
ProductName:    macOS
ProductVersion: 11.0.1
BuildVersion:   20B29
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64

#### Steps to reproduce:
1. Open a modal with one block containing InputBlockElement with TimePickerElement as the accessory
2. In the UI it behaves as if a DatePickerElement was added.

#### Expected result:
TimePickerElement is supposed to prompt Time and not just Date.

#### Actual result:
TimePickerElement just prompted Date behaving as a DatePickerElement.
<img width="390" alt="Screenshot 2020-11-20 at 12 59 17 AM" src="https://user-images.githubusercontent.com/58504541/99714455-9fa43a80-2acb-11eb-849e-38b45db9febf.png">

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by Hariprasad-Ramakrishnan** [comment]
@seratch , Hope you are doing good. We used version 1.3.0-RC3 after you raised a PR for https://github.com/slackapi/java-slack-sdk/issues/610. However, TimePickerElement seems to behave just like a DatePickerElement. Please help.

**Comment by seratch** [comment]
@Hariprasad-Ramakrishnan I don't think the issue you mentioned exists but I found an issue with the `timepicker` support. Here is a pull request resolving it. https://github.com/slackapi/java-slack-sdk/pull/627 You can check the `TimepickerSample` code for you reference.

I will be releasing v1.3.1 today.

**Comment by seratch** [comment]
@Hariprasad-Ramakrishnan Running the following example may help you figure out what's wrong with your current code.

```bash
export SLACK_BOT_TOKEN=
export SLACK_SIGNING_SECRET=
gradle run
# ngrok http 3000 - in another terminal
```

#### build.gradle
```gradle
plugins {
  id("application")
}
repositories {
  mavenCentral()
}
dependencies {
  implementation("com.slack.api:bolt-jetty:1.3.1")
  implementation("org.slf4j:slf4j-simple:1.7.30")
}
application {
  mainClassName = "hello.MyApp"
}
```

#### src/main/java/hello/MyApp.java

```java
package hello;

import com.slack.api.bolt.App;
import com.slack.api.bolt.jetty.SlackAppServer;

import java.util.Arrays;

import static com.slack.api.model.block.Blocks.*;
import static com.slack.api.model.block.composition.BlockCompositions.plainText;
import static com.slack.api.model.block.element.BlockElements.timePicker;
import static com.slack.api.model.view.Views.*;
import com.slack.api.model.view.View;

public class MyApp {
  static {
    System.setProperty("org.slf4j.simpleLogger.log.com.slack.api", "debug");
  }

  public static void main(String[] args) throws Exception {
    // App expects env variables (SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET)
    App app = new App();

    app.command("/open-modal", (req, ctx) -> {
      View view = view(v -> v
        .type("modal")
        .callbackId("view-id")
        .title(viewTitle(vt -> vt.type("plain_text").text("My App")))
        .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
        .close(viewClose(vc -> vc.type("plain_text").text("Close")))
        .blocks(asBlocks(
          actions(a -> a.blockId("b1").elements(Arrays.asList(timePicker(t -> t.actionId("time1").initialTime("01:02"))))),
          input(i -> i.blockId("b2").label(plainText("Time")).element(timePicker(t -> t.actionId("time2").initialTime("02:03"))))
        )));
      ctx.client().viewsOpen(r -> r.triggerId(req.getPayload().getTriggerId()).view(view));
      return ctx.ack();
    });
    app.blockAction("time1", (req, ctx) -> {
      ctx.logger.info("action: {}", req.getPayload().getActions().get(0));
      return ctx.ack();
    });
    app.viewSubmission("view-id", (req, ctx) -> {
      ctx.logger.info("values: {}", req.getPayload().getView().getState().getValues());
      return ctx.ack();
    });
    SlackAppServer server = new SlackAppServer(app);
    server.start(); // http://localhost:3000/slack/events
  }
}
```

**Comment by seratch** [comment]
Let me know if you need more help here. I will close this after waiting for your response for a few more days.

**Comment by Hariprasad-Ramakrishnan** [comment]
@seratch , Sorry for the delayed response. Ill pull the latest version, retest and update you.

**Comment by Hariprasad-Ramakrishnan** [comment]
@seratch , Will give an update by today.
