### ISSUE TITLE
Modal does not open when using a TimePickerElement inside of an InputBlock

### ISSUE THREAD

**Issue by DorianXX** [slackapi/java-slack-sdk#632]
Hello, i'm trying to display an Input with a TimePicker in a modal for my Slack application but the modal never shows up.

#### The Slack SDK version
[INFO] +- com.slack.api:bolt:jar:1.3.1:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.3.1:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.3.1:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.3.1:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.3.1:compile

#### Java Runtime version
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

#### OS info
Linux ASUSVivoBook 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### Steps to reproduce:

1. Click on shortcut to open modal defined with the following code :

```
private static View buildDeploymentView(ShortcutPayload shortcutPayload) {
		log.info("Building deployment view");
		return View.builder().callbackId(shortcutPayload.getCallbackId()).type("modal").notifyOnClose(false)
				.title(ViewTitle.builder().type("plain_text").text("New deployment").emoji(true).build())
				.close(ViewClose.builder().text("Close").type("plain_text").build())
				.submit(ViewSubmit.builder().text("Send").type("plain_text").build()).blocks(Arrays
						.asList(InputBlock.builder().blockId("assignment_group").label(PlainTextObject.builder().text("Assignment group").build()).element(
								ExternalSelectElement.builder().actionId("assignment_group_action").minQueryLength(2)
										.placeholder(PlainTextObject.builder().text("Search the assignment group by name...").build()).build()).build(),
								InputBlock.builder().blockId("requester").label(PlainTextObject.builder().text("Requester").build()).element(
										ExternalSelectElement.builder().actionId("requester_action").minQueryLength(8)
												.placeholder(PlainTextObject.builder().text("Search the requester user by ldap...").build()).build())
										.build(), InputBlock.builder().blockId("objective").label(PlainTextObject.builder().text("Objective").build())
										.element(ExternalSelectElement.builder().actionId("objective_action").minQueryLength(0)
												.placeholder(PlainTextObject.builder().text("Choose the objective...").build()).build()).build(),
								InputBlock.builder().optional(true).blockId("desc").element(
										PlainTextInputElement.builder().multiline(true).actionId("desc_action")
												.placeholder(PlainTextObject.builder().text("Optional, min-length 60 characters").build())
												.maxLength(2000).minLength(60).build()).label(PlainTextObject.builder().text("Description").build())
										.build(), InputBlock.builder().blockId("products").label(PlainTextObject.builder().text("Product").build())
										.element(ExternalSelectElement.builder().actionId("product_action").minQueryLength(2)
												.placeholder(PlainTextObject.builder().text("Search and select a product...").build()).build())
										.build(),
								InputBlock.builder().blockId("date").label(PlainTextObject.builder().text("Wished date").build())
										.element(DatePickerElement.builder().actionId("date_action").placeholder(PlainTextObject.builder().text("Choose a date").build()).build()).build(),
								InputBlock.builder().blockId("time").label(PlainTextObject.builder().text("Wished time").build())
										.element(TimePickerElement.builder().actionId("time_action").initialTime("09:00").placeholder(PlainTextObject.builder().text("Choose a time").build()).build()).build())).build();
	}

```
#### Expected result:
Modal opens with all the input described in the code above, including a TimePicker as last block

#### Actual result:
Modal does not open, no errors are triggered, all network calls are OK.

**Comment by seratch** [comment]
@DorianXX 
With this Java SDK, when your API call gets an error code from the Slack server side, you can access the error code by the method `ViewsOpenResponse#getError()` returning a string value: https://slack.dev/java-slack-sdk/guides/web-api-basics#handle-responses

If the error code is `invalid_blocks` in this case, probably the cause of this is that you haven't participated in the developer beta program. The `timepicker` block element is not enabled by default. Go to https://api.slack.com/apps , access your app's configuration page, visit *Features* > *Beta Features*, and turn the feature on.

<img width="500" src="https://user-images.githubusercontent.com/19658/100012103-1451de80-2e16-11eb-951f-997f030fb35e.png">

If you are getting another error, checking https://api.slack.com/methods/views.open#errors should help.

**Comment by DorianXX** [comment]
Hello, thanks for the quick reply.

The error code i'm getting with the method you mentionned is "invalid_arguments" and it is indeed because I wasn't part of the developper beta.
Enabling it on my app did solve my issue.

Have a good day.
