### ISSUE TITLE
How to respond to an interactive button?

### ISSUE THREAD

**Issue by IlyasPatel** [slackapi/java-slack-sdk#642]
I'm a little unsure how to respond to a button click.  The documentation mentions to setup a URL in "Interactivity & Shortcuts" which I have - the 2nd code block.

I have an `.actionId("button_action")` on the button.

I was expecting this code to be executed, but nothing happens - `app.blockAction("button_action", (req, ctx) -> {`

I have confirmed the button click is coming into the REST controller but no response from the blockAction.

```
@SpringBootApplication
public class Application {

    @Bean
	public CommandLineRunner commandLineRunner(){

		return args -> {

            app.command("/top", (req, ctx) -> {

                ChatPostMessageResponse response = ctx.client()
                        .chatPostMessage(r -> r.channel(ctx.getChannelId())
                        .blocks(buildTopResponse())
                );

                return ctx.ack();
            });

	        SlackAppServer server = new SlackAppServer(app);
	        server.start(); // http://localhost:3000/slack/event
		};
	}
}

public List<LayoutBlock> buildWebOrderResponse() {

        List<LayoutBlock> message = new ArrayList<>();

        message.add(
                SectionBlock
                        .builder()
                            .text(MarkdownTextObject.builder().text("*A co-worker signed up for the office potluck!*").build())
                            .accessory(ButtonElement.builder().actionId("button_action").text(PlainTextObject.builder().text("Hello").build()).build())
                .build());

        message.add(DividerBlock
                .builder()
                .build());

        return message;
    }
```

```
@RequestMapping(value = "/interactive", method = RequestMethod.POST)
    public void interactive() {

        // when a user clicks a button in the actions block
        app.blockAction("button_action", (req, ctx) -> {
            String value = req.getPayload().getActions().get(0).getValue(); // "button's value"
            if (req.getPayload().getResponseUrl() != null) {
                // Post a message to the same channel if it's a block in a message
                ctx.respond("You've sent " + value + " by clicking the button!");
            }
            return ctx.ack();
        });
    }
```

**Comment by seratch** [comment]
Hi @IlyasPatel , thanks for asking a question here!

These lines just starts an embedded Jetty HTTP server in your Java app. This means your `App` instance is not working as part of your Spring Boot app yet.

```java
SlackAppServer server = new SlackAppServer(app);
server.start(); // http://localhost:3000/slack/event
```

As suggested here: https://slack.dev/java-slack-sdk/guides/supported-web-frameworks , the recommended way is to have a simple servlet class annotated with `@WebServlet` in your Spring Boot app. As Spring Boot automatically scans `WebServlet` classes under your base package, just having this class should work for you as long as the path does not conflict with other controllers. Also, you can have this along with other `@RequestMapping`/`@RestControlelr` classes.

```java
@WebServlet("/interactive")
public class SlackAppController extends SlackAppServlet {
  public SlackAppController(App app) { // Provide an App instance as a component
    super(app);
  }
}
```

If you have a particular reason where you have to use RequestMapping over WebServlet for Bolt endpoints, your controller method needs to do the similar with this code: https://github.com/slackapi/java-slack-sdk/blob/v1.4.0/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackAppServlet.java#L31-L45

The important thing is that your controller should not consume the InputStream of request body data to construct Java objects. The reason for this is that Slack's request signature verification requires access to the raw string request body (the one which is not modified at all). So, you cannot use any built-in body parsers enabled by Spring Boot framework for this endpoint.

Lastly, we have got many questions about Spring Boot integrations in the past. If you encounter other issues, check these issues: https://github.com/slackapi/java-slack-sdk/issues?q=is%3Aissue+is%3Aclosed+spring 

Hope you will enjoy working with the Bolt for Java framework and building amazing Slack apps!

**Comment by IlyasPatel** [comment]
Thank you for the detailed response. 

I have done what was recommended, I now get the following error after clicking on a button:

I think I need to either upgrade or downgrade the okhttp dependency but not clear where to do this. 

```
2020-12-03 22:44:14,165 ERROR [http-nio-3000-exec-2] o.a.c.c.C.[.[.[.[com.apple.store.slack.won.InteractiveEndPoint] Servlet.service() for servlet [com.apple.store.slack.won.InteractiveEndPoint] in context with path [] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
	at com.slack.api.util.http.SlackHttpClient.postJsonBody(SlackHttpClient.java:168)
	at com.slack.api.app_backend.interactive_components.ActionResponseSender.send(ActionResponseSender.java:21)
	at com.slack.api.bolt.response.Responder.send(Responder.java:52)
	at com.slack.api.bolt.context.ActionRespondUtility.respond(ActionRespondUtility.java:26)
```


I have done a maven dependency tree and the okhttp dependency is here:

[INFO] |  +- com.slack.api:slack-api-client:jar:1.4.0:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |     \- com.squareup.okio:okio:jar:1.17.2:compile


here is an excerpt of my pom file:
```

<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt</artifactId>
    <version>1.4.0</version>
</dependency>
<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt-servlet</artifactId>
    <version>1.4.0</version>
</dependency>
<dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt-jetty</artifactId>
    <version>1.4.0</version>
</dependency>
```

**Comment by seratch** [comment]
@IlyasPatel 
>I think I need to either upgrade or downgrade the okhttp dependency but not clear where to do this.

Yes, you're right. You need to upgrade to v4.x. I guess any of other libraries, frameworks, or maven boms should be bringing the old version to your app.

**Comment by IlyasPatel** [comment]
Thank you for detailed help, all working now.
