### ISSUE TITLE
Radio buttons not triggering block action payloads

### ISSUE THREAD

**Issue by a6dang** [slackapi/java-slack-sdk#644]
I have attempted to include radio buttons in my surfaces, specifically in a modal and a message. I have registered them with an actionId and have used `SlackApp.blockAction` to register a handler for each one. Switching between radio button options does not seem to trigger the block actions.

#### The Slack SDK version

`1.4.0`

#### Java Runtime version

`1.8.0_252`

#### OS info

```ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))
```
withBlocks {
            section {
                text(PlainTextObject.TYPE, "radio buttons")
                accessory {
                    radioButtons {
                        actionId("testing")
                        options {
                            option {
                                text(PlainTextObject.TYPE, "1")
                            }
                            option {
                                text(PlainTextObject.TYPE, "2")
                            }
                        }
                    }
                }
            }
        }
```
```
app.blockAction("testing") { req: BlockActionRequest, context: ActionContext ->
            context.ack() 
}
```
1. Use Slack SDK 1.4.0 (`slack-api-client-kotlin-extension`, `slack-api-model-kotlin-extension`, `bolt-servlet`)
2. Register an `actionId` and respective blockAction on the `SlackApp`
3. Toggle between radio buttons

#### Expected result:

The registered block action handler to trigger.

#### Actual result:

The handler is not triggered and nothing happens.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
@a6dang It seems "value" is missing in your options. The following example should work for you.

```kotlin
options {
  option {
    text(PlainTextObject.TYPE, "1")
    value("1")
  }
  option {
    text(PlainTextObject.TYPE, "2")
    value("2")
  }
}
```

**Comment by a6dang** [comment]
Ah! That was it. Thank you for the help. I'll go ahead and close this issue out.
