### ISSUE TITLE
Include `files` list in Attachment type

### ISSUE THREAD

**Issue by zolstein** [slackapi/java-slack-sdk#647]
When a user clicks on an app shortcut on a message (i.e. in the "More actions" kebab menu of the message) Slack sends a message to the app that includes a description of the message. If the message has an attached message, and _that_ message has an attached file, the message's attachment (`com.slack.api.model.Attachment`) will have a field `files`, mapped to a list of `com.slack.api.model.File`) objects. The `Attachment` class does not include this field, so this information is not included with the rest of the message when deserializing into a POJO, requiring extra steps to retain it. 

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [x] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

**Comment by mwbrooks** [comment]
Hey @zolstein, thanks for uncovering this edge-case and providing the details to reproduce it!

I've marked this an an enhancement and added it to our "To Do" bucket. So it'll be plunked off in our upcoming work.

You seem quite knowledgable about the situation - if you're interested in sending a pull request to implement the `files` attachment, we'd be happy to review and merge the work!

**Comment by seratch** [comment]
@zolstein I think, in a common scenario, the `files` exists at the top level of `message`, not inside any of `message.attachments`. https://github.com/slackapi/java-slack-sdk/blob/v1.4.0/slack-api-model/src/main/java/com/slack/api/model/Message.java#L48

But, I might be missing some patterns. Could you share an example of `attachments` reproducing your situation?

**Comment by zolstein** [comment]
Sure. Here's the JSON payload of an example message that has this issue:
[message_action.txt](https://github.com/slackapi/java-slack-sdk/files/5698220/message_action.txt)

**Comment by seratch** [comment]
@zolstein Aha! Now I understand the pattern. This is a very common situation. I will fix this issue and include the change in the next patch version (if everything goes well, I will release the version within a few hours).

**Comment by zolstein** [comment]
Fantastic! Thanks for the quick fix, and for all the great work you guys do!
