### ISSUE TITLE
Is it possible to upload a file to a backend API using Slack Block kit?

### ISSUE THREAD

**Issue by IlyasPatel** [slackapi/java-slack-sdk#651]
I would like to upload a file to a Springboot service. Is it possible to do this in Slack and using Block kit similar to html type="file" attribute?

Are there any links I can read to perform this?

**Comment by seratch** [comment]
Unfortunately, there is no suitable UI component in Block Kit for your use case. Your app can subscribe file related events listed here: https://api.slack.com/events . If your app have the sufficient permission to read the uploaded files, your app can relay the file content to your backend services.

**Comment by IlyasPatel** [comment]
Would it be possible to add a file within a modal box?  What I'm thinking of doing is:

- User enters `/upload` which will open a modal box for the user to select a few options and drag-and-drop a file.

Or does the file upload only work within the main primary Slack chat window?

**Comment by seratch** [comment]
>Would it be possible to add a file within a modal box? 

No, it is not possible at this time. As I mentioned, Block Kit (the underlying mechanism to build modals) does not offer any components for this use case.

>Or does the file upload only work within the main primary Slack chat window?

Yes, it does. There is no UI component to build your own file uploader.

**Comment by daveuppal** [comment]
It looks like this functionality was just released: https://api.slack.com/reference/block-kit/block-elements#file_input
