### ISSUE TITLE
When multiple workflow steps are added to an app, only the first one is accessible using the SDK.

### ISSUE THREAD

**Issue by joelshea** [slackapi/java-slack-sdk#652]
When an app adds multiple workflow steps, only the first added one is accessible.

#### The Slack SDK version

1.4.0

#### Java Runtime version

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

#### OS info

ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64

#### Steps to reproduce:

I have two steps that I have added to my bot. I've create an interface for each step:

```kotlin
interface IWorkflowStep {
    val id: String
    fun edit(req: WorkflowStepEditRequest, ctx: WorkflowStepEditContext): Response?
    fun save(req: WorkflowStepSaveRequest, ctx: WorkflowStepSaveContext): Response?
    fun execute(req: WorkflowStepExecuteRequest, ctx: WorkflowStepExecuteContext): Response?
}
```

And add each step like such:

```kotlin
for (step in steps) {
    app.step(
        WorkflowStep.builder()
            .callbackId(step.id)
            .edit(step::edit)
            .save(step::save)
            .execute(step::execute)
            .build()
    )
    LOG.info("Added step: ${step::class.simpleName}")
}
```

My understanding of what happens next is the steps are turned into middleware and then added to the stack; when a request is received, they are popped one by one looking for the right step.  But that is where the issue lies:

https://github.com/slackapi/java-slack-sdk/blob/df8585e4704f8b281e2b307d13facd781f0deb0f/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/WorkflowStep.java#L54

At this line, the callback id of the request is checked against this workflow step.  If the match, great everything is fine.  But if they don't, we have a problem.  Because we are already in the `switch` statement AND the cases all lack `break` commands, the execution continues into the next case.  It then tries to miscast the step type on line:

https://github.com/slackapi/java-slack-sdk/blob/df8585e4704f8b281e2b307d13facd781f0deb0f/bolt/src/main/java/com/slack/api/bolt/middleware/builtin/WorkflowStep.java#L63

A (very confusing) exception is thrown:

```
java.lang.ClassCastException: class com.slack.api.bolt.request.builtin.WorkflowStepEditRequest cannot be cast to class com.slack.api.bolt.request.builtin.WorkflowStepSaveRequest
```

Which means the `return chain.next(req);` is never called and subsequent middlewares are not assessed.

#### Expected result:

You should be able to add multiple workflow steps to the bolt app.

#### Actual result:

No workflow step except the first one added can be called without exceptions being thrown.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
@joelshea Thank you very much for taking the time to report this issue. I've confirmed this is a bug and we will be fixing this issue in the next patch version (v1.4.2) next year. 

If you need an immediate workaround for this, please use `app.workflow*` methods instead of `app.step` registration. This issue does not exist with `app.workflow*` listeners.

```kotlin
// src/main/kotlin/MyApp.kt
import com.slack.api.bolt.App
import com.slack.api.bolt.jetty.SlackAppServer
import com.slack.api.bolt.middleware.builtin.WorkflowStep
import com.slack.api.model.block.Blocks.asBlocks


fun main() {
    val app = App()

/*
    val step1 = WorkflowStep.builder()
        .callbackId("step1")
        .edit { req, ctx ->
            ctx.configure(asBlocks())
            ctx.ack()
        }
        .save { req, ctx ->
            ctx.update(emptyMap(), emptyList())
            ctx.ack()
        }
        .execute { req, ctx -> ctx.ack() }
        .build()

    val step2 = WorkflowStep.builder()
        .callbackId("step2")
        .edit { req, ctx ->
            ctx.configure(asBlocks())
            ctx.ack()
        }
        .save { req, ctx ->
            ctx.update(emptyMap(), emptyList())
            ctx.ack()
        }
        .execute { req, ctx -> ctx.ack() }
        .build()

    app.step(step1)
    app.step(step2)
*/

    app.workflowStepEdit("step1") { req, ctx ->
        ctx.configure(asBlocks())
        ctx.ack()
    }
    app.workflowStepSave("step1") { req, ctx ->
        ctx.update(emptyMap(), emptyList())
        ctx.ack()
    }
    app.workflowStepExecute("step1") { req, ctx ->
        ctx.complete(emptyMap())
        ctx.ack()
    }

    app.workflowStepEdit("step2") { req, ctx ->
        ctx.configure(asBlocks())
        ctx.ack()
    }
    app.workflowStepSave("step2") { req, ctx ->
        ctx.update(emptyMap(), emptyList())
        ctx.ack()
    }
    app.workflowStepExecute("step2") { req, ctx ->
        ctx.complete(emptyMap())
        ctx.ack()
    }

    val server = SlackAppServer(app)
    server.start() // http://localhost:3000/slack/events
}
```

```gradle
// build.gradle
plugins {
  id("org.jetbrains.kotlin.jvm") version "1.4.21"
  id("application")
}
repositories {
  mavenCentral()
}
dependencies {
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  implementation("com.slack.api:bolt-jetty:1.4.1")
  implementation("org.slf4j:slf4j-simple:1.7.30") // or logback-classic
}
application {
  mainClassName = "MyAppKt" // add "Kt" suffix for main function source file
}
```

```bash
export SLACK_BOT_TOKEN=xoxb-xxx
export SLACK_SIGNING_SECRET=yyy
gradle run
```

**Comment by seratch** [comment]
@joelshea v1.4.2 resolves this issue. Thanks for reporting this!
