### ISSUE TITLE
Using EventsDispatcher along with BoltEventHandlers

### ISSUE THREAD

**Issue by nicolasrueegg** [slackapi/java-slack-sdk#653]
I register event handlers through `App.event(Class<E> eventClass, BoltEventHandler<E> handler)` as well as through `App.event(EventHandler<?> handler)` in the same Slack application.

`App.event(Class<E> eventClass, BoltEventHandler<E> handler)` adds event handlers with `eventHandlers.put(...)`.
`App.event(EventHandler<?> handler)` registers the handler with `eventsDispatcher.register(handler)`. 

Unfortunately, when registering an event handler through `App.event(EventHandler<?> handler)`, all event handlers registered through `App.event(Class<E> eventClass, BoltEventHandler<E> handler)` will not be considered anymore.
This is due to the fact that as soon as an `eventsDispatcher` is running, `eventHandlers` are not considered anymore as the following code excerpt suggests:

https://github.com/slackapi/java-slack-sdk/blob/df8585e4704f8b281e2b307d13facd781f0deb0f/bolt/src/main/java/com/slack/api/bolt/App.java#L965 :

```
case Event: {
                    if (eventsDispatcher.isRunning()) {
                        eventsDispatcher.enqueue(slackRequest.getRequestBodyAsString());
                        return Response.ok();
                    }
                    EventRequest request = (EventRequest) slackRequest;
                    BoltEventHandler<Event> handler = eventHandlers.get(request.getEventTypeAndSubtype());
                    if (handler != null) {
                        EventsApiPayload<Event> payload = buildEventPayload(request);
                        return handler.apply(payload, request.getContext());
                    }
                    log.warn("No BoltEventHandler registered for event: {}", request.getEventTypeAndSubtype());
                    break;
                }
```
Instead, `c.s.a.a.events.EventsDispatcherImpl      : No event handler registered for type: ...` is logged whenever an event is received for which the event handler was registered through `App.event(Class<E> eventClass, BoltEventHandler<E> handler)`.

Is this on purpose?

#### The Slack SDK version

```
+--- com.slack.api:bolt-servlet:1.4.1
|    +--- com.slack.api:slack-api-model:1.4.1
|    +--- com.slack.api:slack-api-client:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    +--- com.slack.api:slack-app-backend:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.4.1 (*)
|    \--- com.slack.api:bolt:1.4.1
|         +--- com.slack.api:slack-api-model:1.4.1 (*)
|         +--- com.slack.api:slack-api-client:1.4.1 (*)
|         \--- com.slack.api:slack-app-backend:1.4.1 (*)
+--- com.slack.api:bolt:1.4.1 (*)
+--- com.slack.api:bolt-servlet:1.4.1 (n)
+--- com.slack.api:bolt:1.4.1 (n)
+--- com.slack.api:bolt-servlet:1.4.1
|    +--- com.slack.api:slack-api-model:1.4.1
|    +--- com.slack.api:slack-api-client:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    +--- com.slack.api:slack-app-backend:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.4.1 (*)
|    \--- com.slack.api:bolt:1.4.1
|         +--- com.slack.api:slack-api-model:1.4.1 (*)
|         +--- com.slack.api:slack-api-client:1.4.1 (*)
|         \--- com.slack.api:slack-app-backend:1.4.1 (*)
+--- com.slack.api:bolt:1.4.1 (*)
+--- com.slack.api:bolt-servlet:1.4.1
|    +--- com.slack.api:slack-api-model:1.4.1
|    +--- com.slack.api:slack-api-client:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    +--- com.slack.api:slack-app-backend:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.4.1 (*)
|    \--- com.slack.api:bolt:1.4.1
|         +--- com.slack.api:slack-api-model:1.4.1 (*)
|         +--- com.slack.api:slack-api-client:1.4.1 (*)
|         \--- com.slack.api:slack-app-backend:1.4.1 (*)
+--- com.slack.api:bolt:1.4.1 (*)
+--- com.slack.api:bolt-servlet:1.4.1
|    +--- com.slack.api:slack-api-model:1.4.1
|    +--- com.slack.api:slack-api-client:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    +--- com.slack.api:slack-app-backend:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.4.1 (*)
|    \--- com.slack.api:bolt:1.4.1
|         +--- com.slack.api:slack-api-model:1.4.1 (*)
|         +--- com.slack.api:slack-api-client:1.4.1 (*)
|         \--- com.slack.api:slack-app-backend:1.4.1 (*)
+--- com.slack.api:bolt:1.4.1 (*)
+--- com.slack.api:bolt-servlet:1.4.1
|    +--- com.slack.api:slack-api-model:1.4.1
|    +--- com.slack.api:slack-api-client:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    +--- com.slack.api:slack-app-backend:1.4.1
|    |    +--- com.slack.api:slack-api-model:1.4.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.4.1 (*)
|    \--- com.slack.api:bolt:1.4.1
|         +--- com.slack.api:slack-api-model:1.4.1 (*)
|         +--- com.slack.api:slack-api-client:1.4.1 (*)
|         \--- com.slack.api:slack-app-backend:1.4.1 (*)
+--- com.slack.api:bolt:1.4.1 (*)
```

#### Java Runtime version

`Java 11`

#### OS info

```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
```

#### Steps to reproduce:

1. Create a Slack app `app`.
2. Register a handler for `app_home_opened` event like this:` app.event(AppHomeOpenedEvent.class, appHomeOpenedHandler);`
3. Register another handler for e.g., `user_change` like this:  ` app.event(userChangeHandler);`

#### Expected result:

`appHomeOpenedHandler` is called whenever a `app_home_opened` event is received.
`userChangeHandler` is called whenever a `user_change` event is received.

#### Actual result:

`appHomeOpenedHandler` is NOT called when a `app_home_opened` event is received. Instead, a 

```2020-12-27T20:21:38.146517+00:00 app[web.1]: 2020-12-27 20:21:38.146 DEBUG 4 --- [       Thread-2] c.s.a.a.events.EventsDispatcherImpl      : No event handler registered for type: app_home_opened, subtype:```

message is logged.

**Comment by seratch** [comment]
>Is this on purpose?

Yes, it is. The method to use `com.slack.api.app_backend.events.EventsDispatcher` in `App` is supposed to be used only when an existing app relying on the Events API feature in slack-app-backend module migrates to Bolt. If you are building a brand-new Bolt app, **using only `BoltEventHandler` is recommended**. 

That being said, we can improve the logging for easier debugging. I appreciated this input.

**Comment by nicolasrueegg** [comment]
Thanks! I will then simply use `App.event(Class<E> eventClass, BoltEventHandler<E> handler)` to set up all of my event handlers. Appreciate the quick response.
