### ISSUE TITLE
How to handle file uploads 

### ISSUE THREAD

**Issue by regogo** [slackapi/java-slack-sdk#658]
```
       app.event(new FileCreatedHandler() {
            @Override
            public void handle(FileCreatedPayload payload) {
                log.info("File is created");
                FileCreatedEvent event = payload.getEvent();
                log.info("File Id" + event.getFile().getId());
            }
        });
        
```
        
        I'm detecting file created event in the server log but the log.info("file is created") is not called.
        Not sure if im doing it right since the samples in the repo are pretty bare.

**Comment by seratch** [comment]
@regogo Thanks for asking a question 👋 

> The file_created event is sent to all connected clients for a user when that user uploads a file to Slack

As mentioned above in the document, the `file_created` events can be sent only when **your apps' bot user** uploads a file. 
https://api.slack.com/events/file_created

To know the files uploaded by any users, you can use https://api.slack.com/events/file_shared for it.

**Comment by regogo** [comment]
Hi @seratch ,

thanks for answering. as for the code snippet I posted, can you verify that is the correct way of handling file events,
as there were no other samples in the documentation? Thanks

**Comment by seratch** [comment]
Your way also works but, as [the document](https://slack.dev/java-slack-sdk/guides/events-api) suggests, the primary way is to use an event class and its corresponding `BoltEventHandler` as below.

```java
app.event(FileSharedEvent.class, (payload, ctx) -> {
  // do something with the payload
  return ctx.ack();
});
```

**Comment by seratch** [comment]
@regogo Was my previous comment helpful? Let me know if you have anything further here. I will be closing this issue after waiting for your response  for a few more days.
