### ISSUE TITLE
Not able to use conversationsCreate in java

### ISSUE THREAD

**Issue by pantelis17** [slackapi/java-slack-sdk#659]
I need to create new channels by using the slack api in java. As i saw methods like channels.create are deprecated so i tried to use conversations.create. Although i am able to create a channel by using the tester card when i am trying to use the java example it does not work. I replaced the environment variables with the appropriate strings ( bot token and signing secret ) and it seems to hung in server.start(); . I tried to use a debugger in order to spot the problem and it seems that the lamda expression is not running as expected as i get this error: Cannot find local variable 'ctx'.

#### The Slack SDK version

   
   <dependency>
      <groupId>com.slack.api</groupId>
      <artifactId>bolt-jetty</artifactId>
      <version>1.5.0-M1</version>
   </dependency>

#### Java Runtime version

Java 11

#### OS info

Microsoft Windows [Version 10.0.19042.630]

#### Steps to reproduce:

Using the java example replace the signing secret and bot token and run the script

#### Expected result:

A new channel with the given name should be created

#### Actual result:

The script hungs

**Comment by seratch** [comment]
Hello @pantelis17, thanks for asking the question!

Probably, you mentioned this code snippet in the "code" tab. Am I right?

https://api.slack.com/methods/conversations.create/code

<img width="500" src="https://user-images.githubusercontent.com/19658/104191965-8a131780-5461-11eb-9723-c778caba051a.png">

If so, the code snippet is an example demonstrating how to use `conversations.create` API in response to a [message shortcut](https://api.slack.com/interactivity/shortcuts/using#message_shortcuts) invocation.

Just to create a new channel using the web API, all you need to do are:

* Instantiate a Web API client
* Call the conversationsCreate method with sufficient parameters

```java
MethodsClient client = Slack.getInstance().methods();
client.conversationsCreate(r -> r
  // The token you used to initialize your app
  .token(System.getenv("SLACK_BOT_TOKEN"))
  // The name of the conversation
  .name("pretend-channel")
);
```
If you do the same in a listeners in Bolt apps, you can use `ctx.client()` for it.

**Comment by pantelis17** [comment]
@seratch Thank you for the quick response. You are right that way seems to work as expected. Closing this issue, thank you a lot!
