### ISSUE TITLE
MessageEvent model does not include File objects

### ISSUE THREAD

**Issue by amalagraba** [slackapi/java-slack-sdk#664]
Hi,

I'm trying to listen to users posting a code snippet but I see the MessageEvent class does not include files, although the message is handled by the MessageEvent handler and as far as I could see the received json message does indeed have the shared snippet information under "files".

Is this a bug or should I listen to another event? I tried listening to MessageFileShareEvent but it's not fired since the received message does not have a subtype.

I'm currently using com.slack.api:slack-api-client:1.5.1 and com.slack.api:slack-api-model:1.5.1 (which is transitive).

Thanks in advance!

**Comment by amalagraba** [comment]
PS: It can be solved by extending the provided MessageEvent, here's an example:

```java
@Data
@EqualsAndHashCode(callSuper = true)
public class CustomMessageEvent extends MessageEvent {

    private List<File> files;
}
```
(But I still think the library should cover this case)

**Comment by seratch** [comment]
@amalagraba Thanks for sharing this. Did you surely receive `files` in `MessageEvent` (= no subtype payload)? If so, could you share an example payload (please redact IDs and any real values as much as possible)?

I have fixed a similar issue before and my understanding is that `files` can be included only when a payload is either file_share or message_changed subtype. If you are receiving message_changed when you have a file URL in a message, you can subscribe to `MessageChangedEvent` instead of `MessageEvent`.

See also:
* https://github.com/slackapi/java-slack-sdk/issues/494
* https://github.com/slackapi/java-slack-sdk/pull/495#issuecomment-647261142
* https://github.com/slackapi/java-slack-sdk/pull/496

**Comment by amalagraba** [comment]
Hi @seratch, thanks for looking into this. This is the exact message I received (with redacted information ofc)

```json
{
    "type": "message",
    "text": "send this to cvs in stage",
    "files": [
        {
            "id": "FILE_ID",
            "created": 1610968162,
            "timestamp": 1610968162,
            "name": "Sin título",
            "title": "Sin título",
            "mimetype": "text/plain",
            "filetype": "text",
            "pretty_type": "Texto simple",
            "user": "USER_ID",
            "editable": true,
            "size": 2133,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": false,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "REDACTED",
            "url_private_download": "REDACTED",
            "permalink": "REDACTED",
            "permalink_public": "REDACTED",
            "edit_link": "REDACTED",
            "preview": "{\n  \"bookings\" : [ {\n    \"companyId\" : \"E10\",\n    \"officeId\" : 1,\n    \"valuationMode\" : \"STANDARD\",",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text/plain',window.getSelection().toString().replace(/\\u200b/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>{</pre></div>\n<div><pre>  &quot;bookings&quot; : [ {</pre></div>\n<div><pre>    &quot;companyId&quot; : &quot;E10&quot;,</pre></div>\n<div><pre>    &quot;officeId&quot; : 1,</pre></div>\n<div><pre>    &quot;valuationMode&quot; : &quot;STANDARD&quot;,</pre></div>\n</div>\n</div>\n",
            "lines": 89,
            "lines_more": 84,
            "preview_is_truncated": true,
            "is_starred": false,
            "has_rich_preview": false
        }
    ],
    "upload": true,
    "blocks": [
        {
            "type": "rich_text",
            "block_id": "+j9Jb",
            "elements": [
                {
                    "type": "rich_text_section",
                    "elements": [
                        {
                            "type": "text",
                            "text": "send this to cvs in stage"
                        }
                    ]
                }
            ]
        }
    ],
    "user": "USER_ID",
    "display_as_bot": false,
    "team": "TEAM_ID",
    "client_msg_id": "CLIENT_MESSAGE_ID",
    "source_team": "TEAM_ID",
    "user_team": "TEAM_ID",
    "channel": "CHANNEL_ID",
    "event_ts": "1610968163.065700",
    "ts": "1610968163.065700"
}
```
As I stated in my previous comment, extending the event to add the files attribute works just fine. If you need more info let me know.

**Comment by seratch** [comment]
Thanks for sharing this. The message seems to be a text snippet creation. In this scenario, the payload always has the subtype "file_share". I am not sure why this pattern is different with your app yet.

I wanted to reproduce your situation before making changes to this SDK but it's okay now. I am sure you are encountering the situation for some reason. 

If you don't mind, could you send a pull request to fix this (with a corresponding test [here](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/test/java/test_locally/api/model/event/MessageEventTest.java))? If you are busy, I will be quickly fix this tomorrow in my timezone (+09:00). In any case, I will release a new patch version for you shortly.

**Comment by amalagraba** [comment]
Sure thing, I'll submit a pull request adding the files attribute and the corresponding test.

**Comment by seratch** [comment]
@amalagraba Thanks a lot for fixing the issue 👍 A new patch version (1.5.2) has been published.
