### ISSUE TITLE
Errors for View Submission don't show up

### ISSUE THREAD

**Issue by baole** [slackapi/java-slack-sdk#673]
Errors returned by ViewSubmission doesn't show up on Slack UI. Here is my code (Kotlin):

```
app.viewSubmission(Pattern.compile(".*")) { req, context ->
       context.ackWithErrors(mapOf("block_id_participants" to "You should have at least two participants"))
}
```

#### Java Runtime version

Java 1.8

#### OS info

Mac OS

**Comment by seratch** [comment]
@baole I tried to reproduce your situation but I was not able to. Can you try the following example? (You don't need to use Socket Mode).

```kotlin
import com.slack.api.bolt.App
import com.slack.api.bolt.socket_mode.SocketModeApp

fun main() {
  System.setProperty("org.slf4j.simpleLogger.log.com.slack.api", "debug")

  val app = App()

  val view = """{
  "type": "modal",
    "callback_id": "modal-id",
  "title": {
    "type": "plain_text",
    "text": "My App",
    "emoji": true
  },
  "submit": {
    "type": "plain_text",
    "text": "Submit",
    "emoji": true
  },
  "close": {
    "type": "plain_text",
    "text": "Cancel",
    "emoji": true
  },
  "blocks": [
    {
      "type": "input",
      "block_id": "b",
      "element": {
        "type": "plain_text_input",
        "action_id": "a"
      },
      "label": {
        "type": "plain_text",
        "text": "Label",
        "emoji": true
      }
    }
  ]
}"""

  app.command("/socket-mode-run") { req, ctx ->
    ctx.asyncClient().viewsOpen { it.triggerId(req.payload.triggerId).viewAsString(view)}
    ctx.ack()
  }
  app.viewSubmission("modal-id") { _, ctx ->
    ctx.ackWithErrors(mapOf("b" to "Something wrong!"))
  }

  SocketModeApp(app).start()
}
```

**Comment by seratch** [comment]
Also, please make sure if you are using an input type block for the "block_id_participants"

**Comment by seratch** [comment]
👋 Let us know if you need further help for this. I will close this issue after waiting for your response for a few more days.

**Comment by aoza7** [comment]
Hi @seratch, is it not possible to send an error for any other block type but input?

**Comment by seratch** [comment]
@aoza7 Unfortunately, it's not feasible. The only approach that I can suggest is to add a new section block with an error message by updating the whole `blocks` array.

**Comment by aoza7** [comment]
@seratch I see! I have a section block, can it be used to send back error? If not, can you help with an example of what you suggested above?

**Comment by seratch** [comment]
@aoza7 Here is [a working example](https://app.slack.com/block-kit-builder/#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Error*:%20Please%20select%20a%20future%20date!%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22action_id%22:%22action%22%7D%7D%5D%7D). As you can see, it's a kind of workaround so the appearance may not look great to you. I meant simply placing a section block with an error text string. It won't be red color string, also won't represent intuitive association with the interactive block element.

**Comment by aoza7** [comment]
thank you! I will try this
