### ISSUE TITLE
MessageEvent payload doesn't contain user info

### ISSUE THREAD

**Issue by BaradPuja** [slackapi/java-slack-sdk#674]
Hi Team,

I am not receiving user info such as email, enterprise id ..etc in MessageEvent subscription payload,
Could you please help address this issue.

**Comment by seratch** [comment]
Hello @BaradPuja, the payload contain the message poster's user ID and enterprise ID as below.

* user id: https://github.com/slackapi/java-slack-sdk/blob/v1.5.3/slack-api-model/src/main/java/com/slack/api/model/event/MessageEvent.java#L31
* enterprise id: https://github.com/slackapi/java-slack-sdk/blob/v1.5.3/slack-app-backend/src/main/java/com/slack/api/app_backend/events/payload/MessagePayload.java#L12-L13

For fetching more info (e.g., email address) about the user, you can use the [users.info](https://api.slack.com/methods/users.info) API.

**Comment by BaradPuja** [comment]
Hi @seratch ,

The enterprise id I'm getting in message payload is not equal to my original enterprise id, is there any encoding we are using?

Also when I'm using user.info method below is the response I'm getting:-
Result: UsersInfoResponse(ok=false, warning=null, error=missing_scope, needed=users:read, provided=chat:write,incoming-webhook,commands,app_mentions:read,im:history, user=null)

**Comment by seratch** [comment]
@BaradPuja oops, I'm sorry - I was confused. You need to use authorizations[0].enterprise_id instead. https://github.com/slackapi/java-slack-sdk/blob/v1.5.3/slack-app-backend/src/main/java/com/slack/api/app_backend/events/payload/MessagePayload.java#L18

see also: https://github.com/slackapi/java-slack-sdk/issues/629

**Comment by BaradPuja** [comment]
@seratch , I'm still seeing the enterpriseId as "hexadecimal String" where as my actual enterpriseId is purely digit of size 10.

**Comment by seratch** [comment]
@BaradPuja I am not sure what the situation is. Can you turn debug level logging on and see how difference the value in the actual JSON payload and the value you are getting in the Java world are?

**Comment by seratch** [comment]
Let me know if you need further help here. I will close this issue after waiting for your response for a few more days.
