### ISSUE TITLE
Incoming Webhooks example is not working

### ISSUE THREAD

**Issue by tilentur** [slackapi/java-slack-sdk#678]
Incoming Webhooks example (https://slack.dev/java-slack-sdk/guides/incoming-webhooks) is not working. There is no error or any kind of output. Curl counterpart on the other hand works as expected

#### The Slack SDK version

[INFO] +- com.slack.api:slack-api-client:jar:1.5.3:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.5.3:compile
[INFO] |  \- com.slack.api:slack-api-client:jar:1.5.3:compile
[INFO] |     +- com.slack.api:slack-api-model:jar:1.5.3:compile
[INFO] +- com.slack.api:slack-api-client:jar:1.5.3:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.5.3:compile

#### Java Runtime version

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+11, mixed mode, sharing)

#### OS info

Fedora release 33
5.10.10-200.fc33.x86_64 GNU/Linux

#### Steps to reproduce:

Just run the first, non curl, example. It will execute slack.send(...) and nothing will happen. It won't even hit the last System.out.println(...). No output, error and nothing on slack channel.

#### Expected result:

Example should work and error(s) should be outputted as soon as possible.

#### Actual result:

Example stucks on slack.send(...). No errors are reported and nothing is sent to the webhook.

### Requirements

Java

**Comment by seratch** [comment]
@tilentur I am not able to reproduce your situation. Can you make sure if you are giving a valid incoming wehook URL to the Slack instance? The code snippet in the document expects `SLACK_WEBHOOK_URL` env variable. If you do not have it, you can modify the code as below.

```java
import com.slack.api.Slack;
import com.slack.api.webhook.WebhookResponse;

public class Example {
  public static void main(String[] args) throws Exception {
    Slack slack = Slack.getInstance();
    //String webhookUrl = System.getenv("SLACK_WEBHOOK_URL");
    // TODO: YOUR OWN INCOMING WEBHOOK URL HERE
    String webhookUrl = "https://hooks.slack.com/services/T111/B111/XXX";
    String payload = "{\"text\":\"Hello, World!\"}";
    WebhookResponse response = slack.send(webhookUrl, payload);
    System.out.println(response); // WebhookResponse(code=200, message=OK, body=ok)
  }
}
```

**Comment by tilentur** [comment]
@seratch 

Here is my exact code and "we are out" is never printed and there is no exception

```java
public void postNotification() {
        Slack slack = Slack.getInstance();
        String webhookUrl = "https://hooks.slack.com/services/T*****/B*******/xxxxxx";
        Payload payload = Payload.builder().text("hellow").build();

        WebhookResponse response = null;
        try {
            System.out.println("we go in");

            response = slack.send(webhookUrl, payload);

            System.out.println("we are out");
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println(response);
    }
```

**Comment by seratch** [comment]
@tilentur I am not sure what is happening to your app yet. Just in case, I tried your example but it worked for me. How about trying to use debugger in IDE (IntelliJ IDEA, Eclipse, VS Code whatever you prefer)?

**Comment by tilentur** [comment]
@seratch 

I have more details on the issue. As you already confirmed, it does work from typical maven application.

However, my issue can be reproduced if you try to achieve the same thing from a quarkus project.

Steps to reproduce:
- Create getting started project as described in https://quarkus.io/guides/getting-started
- Modify hello function in the sample and include code from example for slack webhooks (provide proper webhook url etc ... )
- Run the application and hit REST endpoint (e.g. curl http://localhost:8080/hello/)
- Application will fail with "org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError" exception

**Comment by seratch** [comment]
@tilentur OK, this is a known issue. Check the following links:
* https://github.com/slackapi/java-slack-sdk/issues/580#issuecomment-706454181
* https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#quarkus-undertow

>After generating a blank project, remove quarkus-universe-bom from the build settings. The reason why we need to remove it is that, as of April 2020, quarkus-universe-bom adds okhttp 3.x to the project while this SDK requires okhttp 4.x.

**Comment by tilentur** [comment]
I see, thanks. I'll revert to using basic HTTP request for posting a message. I works fine.

Feel free to close the ticket
