### ISSUE TITLE
Question about deprecated fields in Incoming Webhook payload class

### ISSUE THREAD

**Issue by guy1699** [slackapi/java-slack-sdk#699]
com.slack.api.webhook.Payload

The "channel" field is deprecated, is it mean that it is not going to work if I send the message with webhook through the Incoming Webhook app ?

**Comment by seratch** [comment]
Hi @guy1699, thanks for asking the question! This SDK should have mentioned the reason behind the deprecation a bit more clearly in javadoc (I will do this later).

Before providing a specific answer to your `channel` parameter question, let me explain the current situation around Incoming Webhooks first. From historical reasons, there are two ways to use Incoming Webhooks in a Slack workspace (I know this is a bit confusing).

* :one: **Create your own Slack App** (recommended way) 
  * Create a Slack app [here](https://api.slack.com/apps?new_app=1)
  * **Features** > **Incoming Webhooks** Enable Incoming Webhook feature for the created app
  * **Settings** > **Install App** Install the app into your development workspace
  * (Slack OAuth confirmation page) Select a channel and click **Allow** button
  * Grab the issued **Webhook URL** and use it for sending messages
* :two: **Use the custom integration "Incoming Webhooks" in App Directory**
  * Access [the App Directory page](https://my.slack.com/apps/A0F7XDUAZ-incoming-webhooks)
  * Click **Add to Slack** button 
  * Select a channel and click the button
  * Grab the issued **Webhook URL** and use it for sending messages

Our current recommendation is :one: for consistent user experience and better app management. With this way, all the deprecated fields **already do not work for you**.

On the other hand, if you use the legacy integration 2️⃣ , those deprecated fields are still available. Even though you are asked to decide one channel to post messages when creating a new one, the legacy integration allows you to post messages in any public channels by passing `channel` parameter.

Unfortunately, there is no equivalent to the `channel` parameter in the current Incoming Webhooks (:one:). Our current recommendation is to utilize [`chat.postMessage` API method](https://api.slack.com/methods/chat.postMessage) with `channel` parameter if your app wants to post to various channels. As for other deprecated parameters like `username` and `icon_url`, [`chat.postMessage` API method](https://api.slack.com/methods/chat.postMessage) with additional [`chat:write.customize`](https://api.slack.com/scopes/chat:write.customize) permission is the right way to do the same.

Thanks again for asking this! This thread should be helpful for others too. If everything is clear now, would you mind closing this issue?

**Comment by seratch** [comment]
Sorry, I forgot to mention this: Probably, you're using 2️⃣ the Incoming Webhook app in App Directory. As long as the legacy integration is available in the platform, you can expect the `channel` parameter (and any others that are deprecated in this Java SDK) should work for you.

**Comment by guy1699** [comment]
Thanks
