### ISSUE TITLE
Java bolt: how to acknowledge MessageEvent as soon as receive and process the user message later if it's taking more time

### ISSUE THREAD

**Issue by BaradPuja** [slackapi/java-slack-sdk#700]
Hi @seratch ,

I have created this issue earlier but it didn't resolve yet. I am still getting multiple MessagEvent notification intermittent.

https://github.com/slackapi/java-slack-sdk/issues/592

Is there a way that we can acknowledge the event as soon as I receive in my App and process, send the response later. if it's possible could you please send me a sample code.

Thank you!!

**Comment by seratch** [comment]
@BaradPuja As an easy way to run time-consuming tasks asynchronously, Bolt provides a built-in ExecutorService:

```java
app.event(AppMentionEvent.class, (req, ctx) -> {
  app.executorService().execute(() -> {
    // do any time-consuming tasks in another thread here
    // you can access request data and Web API client
  });
  // if you don't have any synchronous code in this listener function,
  // the acknowledgement (200 OK response) will be sent immediately
  return ctx.ack();
});
```

**Comment by BaradPuja** [comment]
@seratch , I am using the same approach still see the issue intermittently not always. Also slack server team confirmed with debug log that my app fails to send acknowledgement with in 3 sec occasionally.

Is there any way that we can communicate with slack server asynchronously. I am struggling with this issue since past 3-4 months. It will be great relief if you can help on this.

**Comment by seratch** [comment]
@BaradPuja I just found that my suggestion `app.executorService().execute(() -> {` was wrong. If you are using `execute` method, it does not run the code asynchronously. Instead fo `execute`, you can use `submit` method like `app.executorService().submit(() -> {`. Sorry for the misleading information.

**Comment by BaradPuja** [comment]
there is not much difference between submit() and execute(). I see the issue with submit() as well.
in bolt-js we have async way of communication, why it's not there in java-bolt.

// When a user joins the team, send a message in a predefined channel asking them to introduce themselves
app.event('team_join', async ({ event, client }) => {
  try {
    // Call chat.postMessage with the built-in client
    const result = await client.chat.postMessage({
      channel: welcomeChannelId,
      text: `Welcome to the team, <@${event.user}>! 🎉 You can introduce yourself in this channel.`
    });
    console.log(result);
  }
  catch (error) {
    console.error(error);
  }
});

There is a workaround for bocks, "We need to build a loader view first and then update the view after our process, updating the view requires the viewid unlike creating the view which needs triggerid expiring in 3 seconds". Not sure how to do the same for simple messages

**Comment by seratch** [comment]
@BaradPuja 
Yeah, you're right about the execute/submit. I was just wondering if it may be a cause of some issue in particular Java runtime environment. 

The reason why Bolt for Java did not offer automatic acknowledgement under the hood is that, in the Java world, many developers prefer taking full control of thread pools and asynchronous code execution. As long as an ExecutorService in your app works as we expect, the Bolt for Java's way should stably work. There is no reason to spend more than 3 seconds before responding to incoming requests. 

Let's get back to your specific issue. With given information here, I am unable to provide any further idea. If you share a bit details of your code or a minimal working example reproducing your issue with us, I may be able to provide more suggestion for you, though.

For further discussion on this topic, I have one suggestion. Using this issue tracker for this conversation looks a bit inefficient to me. We need to check emails and/or GitHub notification UI to know updates. GitHub issue tracker works very well for bugs and tasks, but it often doesn't for Q&A.

So, if you don't mind, can we continue discussion in [the community Slack workspace](https://community.slack.com/)? If you are not in the workspace, you can join from [this URL](https://j.mp/community-slack-com). Join #lang-java channel and mention me in the channel.

**Comment by BaradPuja** [comment]
I can login to this.
https://slackcommunity.com/

**Comment by BaradPuja** [comment]
Unfortunately, I couldn't be  in the community Slack workspace. this workspace is blocked for us

**Comment by seratch** [comment]
@BaradPuja If your app is receiving many requests from Slack, increasing thread pool size may help. The default size is 10 but you can increase the capacity by customizing `AppConfig` object. https://github.com/slackapi/java-slack-sdk/blob/v1.6.2/bolt/src/main/java/com/slack/api/bolt/App.java#L401-L403

**Comment by seratch** [comment]
Hi @BaradPuja , I don't have anything further I can do for helping you out here. If you can provide a minimal working example easily reproducing your issue, it'd be greatly helpful to understand what your issue is.

If you don't mind, can we close this issue until we can discuss specific details or the direct cause of your issue. Once we find something specific to resolve, please feel free to reopen this or create a new issue for it.

**Comment by seratch** [comment]
Let me close this issue due for the above reason. Please feel free to write in, reopen, or create a new issue as necessary.
