### ISSUE TITLE
4046char and longer messages get split when sending to channel

### ISSUE THREAD

**Issue by netikras** [slackapi/java-slack-sdk#704]
(Describe your issue and goal here)

### Reproducible in:
1.2.1
1.6.2
haven't tried anything in between, but I'm guessing it's the same

#### The Slack SDK version

`implementation group: 'com.slack.api', name: 'slack-api-client', version: '1.6.2'`

#### Java Runtime version

```
 /usr/lib/jvm/jdk-15/bin/java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

```

#### OS info

```
uname -v
#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

Try and post some long text to some channel. Like this excerpt from a toString() output.
```
"text":"<@ACCOUNTID01> echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
```

#### Expected result:

The text is posted as 1 message.

#### Actual result:

The text gets split into two Slack messages. The longer the text - the more splits will happen

![image](https://user-images.githubusercontent.com/2045031/110139560-d5033880-7ddb-11eb-8da2-84124c7fb54e.png)

IntelliJ decompiler brought me to OKHttp as the most likely culprit. Here:

```
FormBody.kt


  class Builder @JvmOverloads constructor(private val charset: Charset? = null) {
    private val names = mutableListOf<String>()
    private val values = mutableListOf<String>()

    fun add(name: String, value: String) = apply {
      names += name.canonicalize(
          encodeSet = FORM_ENCODE_SET,
          plusIsSpace = true,
          charset = charset
      )
      values += value.canonicalize(
          encodeSet = FORM_ENCODE_SET,
          plusIsSpace = true,
          charset = charset
      )
    }
```

the `value.canonicalize()` call.

Though I'm not a Kotlin dev and it's a Friday afternoon, so I didn't dive any deeper.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @netikras, thanks for taking the time to write in!

Unfortunately, this is a limitation on the server-side and it's not specific to this SDK. You can reproduce the same situation with Python SDK.

```python
import logging
import os
from slack_sdk import WebClient

logging.basicConfig(level=logging.DEBUG)
channel = "#random"
text = "1234567890" * 405
client = WebClient(token=os.environ["SLACK_BOT_TOKEN"])
response = client.chat_postMessage(channel=channel, text=text)

# pip3 install slack-sdk
# export SLACK_BOT_TOKEN=xoxb-
# python3 app.py
```

The chunk size the server-side uses can be changed in the future but I will ask the documentation team to update the API document to mention this possibility in some way.

As a possible workaround, I suggest using files, which can have large text data (or uploading a file in a different cloud storage service and sharing the link in Slack). I know this may not work for your use case but I hope this is helpful to you.

**Comment by netikras** [comment]
![image](https://user-images.githubusercontent.com/2045031/110217686-1409ba80-7ebe-11eb-9023-66eaa74cb458.png)
Indeed, you are correct. I've dumped the http request plain-text to a local `nc` server and I can confirm that the request is being sent out correctly -- as a whole, without any splitting.

My use case requires ousting long pretty-printed links, so posting them as a file or any other workaround won't really cut it. So I take it there's really no way around it, is it..?

**Comment by seratch** [comment]
>My use case requires posting long pretty-printed links, so posting them as a file or any other workaround won't really cut it. So I take it there's really no way around it, is it..?

Unfortunately, I cannot think of any suggestions about the way to use Slack API for it. If it's possible to consider using a url shortener service for it, it can be a workaround. Also, it may be great for user experience too (if you expose the URL as-is in a message).

We, the maintainers of this library, don't have any further action we can take for you at this moment. If you don't mind, can we close this issue now?

**Comment by netikras** [comment]
Thanks @seratch . I do realize you can't change the backend, I just checked with you whether you know anything else about API I don't that could help my use-case. Apparently, we're pretty much on the same page.

Yepp, you can close the ticket. 
Thanks again for your time and for confirming that I've in fact hit a big red bricks wall :)

**Comment by netikras** [comment]
@seratch 

I got a reply from Slack. Is this approach implemented in your library?

```
Aubrey (Slack)
Mar 7, 2021, 8:27 PM PST

Hi <name>,

Thanks for your patience here. I hope you don't mind me stepping in for Elise on your issue.

To avoid these max character limitations, we recommend sending your long string as a hyperlink in a block kit markdown section which would look like this example: https://bit.ly/3bpWlYo

We're hoping that everyone can migrate over to our new Block Kit messaging UI framework. More information about block kit can be found on the following pages:
  · https://api.slack.com/block-kit
  · https://api.slack.com/messaging/attachments-to-blocks
  · https://api.slack.com/tools/block-kit-builder
  · https://api.slack.com/reference/block-kit/block-elements

Please note however that if you choose to use a hybrid payload type that has both attachments and blocks arrays, then that won't work — You must be sending only a blocks array in the payload.

We hope that helps, and that you can migrate to the new payload format. 
Thanks in advance for working on that.

Aubrey 
```

**Comment by seratch** [comment]
@netikras Of course, Block Kit is supported in this library. https://slack.dev/java-slack-sdk/guides/composing-messages#building-blocks-for-rich-message-layouts

However, for your use case, utilizing section blocks does not help as the type of block has 3K character limit for `text` field (as of today): https://api.slack.com/reference/block-kit/blocks#section

**Comment by netikras** [comment]
FTR:

I can indeed mitigate this obstacle with Blocks. Splitting the collection of links into smaller subsets and posting them as separate blocks of the same message will do it for now. A single message can have up to 50 blocks, and each block can have up to 3k chars in 'text', which is 15k chars max per message.

While it saves me for now, I will definitely run into the same problem soon enough, as some of the links are Splunk links. Splunk queries are encoded in the URL and the longer the query - the longer the URL. A mediocre Splunk query I'm using now is already 2.6k chars alone. And I will need more sophisticated queries soon.

IMO it would be useful to have this server-side limitation applied only to post-processed, i.e. visible text, rather than raw message. But that's not actually up to us to decide/change :)

**Comment by mimoo** [comment]
we have the same problem here when we send codeblocks to a channel, probably this should be reopened as this is a weird limitation
