### ISSUE TITLE
Where to pass signing secret to single arg constructor?

### ISSUE THREAD

**Issue by runningcode** [slackapi/java-slack-sdk#711]
I got this stacktrace when starting my app and the error message is unclear:
```
Exception in thread "main" java.lang.IllegalArgumentException: The signing secret is required to generate signature values. Set the env variable SLACK_SIGNING_SECRET or pass the value to the single arg constructor.
	at com.slack.api.app_backend.SlackSignature$Generator.<init>(SlackSignature.java:83)
	at com.slack.api.bolt.App.buildDefaultMiddlewareList(App.java:88)
	at com.slack.api.bolt.App.start(App.java:467)
	at com.slack.api.bolt.jetty.SlackAppServer.start(SlackAppServer.java:128)
```

The part `Set the env variable SLACK_SIGNING_SECRET or pass the value to the single arg constructor.` is unclear to me.
To which class can I pass the signing secret?

The `App` class has a single arg constructor which is the `AppConfig` not a signing secret.
The `SlackAppServer` has a single arg constructor which takes an `App` instance not a signing secret.

There error message is coming from this line:
https://github.com/slackapi/java-slack-sdk/blob/3d4b518d83de40661a0e21b317e8cdcbe7ab14d2/slack-app-backend/src/main/java/com/slack/api/app_backend/SlackSignature.java#L83

### Reproducible in:
This is my app's code:
```
    val app = App()
    val server = SlackAppServer(app);
    server.start();
```

**Comment by mwbrooks** [comment]
Hey @runningcode, thanks for reaching out and the code sample is appreciated! 👋🏻 

I believe the `SLACK_BOT_TOKEN` and `SLACK_SIGNING_SECRET` are [loaded as environment variables](https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt#start-the-app-with-two-env-variables). [This Kolin example](https://github.com/slackapi/java-slack-sdk/blob/3d4b518d83de40661a0e21b317e8cdcbe7ab14d2/bolt-kotlin-examples/src/main/kotlin/examples/middleware/app.kt) that looks similar to your example code and may also help you out.

You can export your environment variables by running the following commands on your terminal:

```zsh
# Replace each value with your token and secret
export SLACK_BOT_TOKEN=xoxb-***
export SLACK_SIGNING_SECRET=123abc***
```

Please keep in mind that the environment variable is only set for your session. You would want to add the export to your profile to load it each time you open your terminal (`.zshrc`, or `.profile` or `.bash_profile` or `.bashrc` depending on your terminal setup).

Depending on your IDE, you may also be able to set the environment variables inside your editor.

Let me know how it goes for you!

**Comment by runningcode** [comment]
Thanks @mwbrooks I appreciate the answer. Your documentation is super clear on how to set the environment variables. I appreciate that.
The error message suggest that there is another option here to use a constructor argument. What constructor can I pass the signing secret to?

**Comment by mwbrooks** [comment]
Hey @runningcode, ah, sorry I didn't realize you're looking for a way to set it without using the environment variables.

Using the [Socket Mode guide's example](https://slack.dev/java-slack-sdk/guides/socket-mode#examples) as inspiration, you can use the `AppConfig` class to build your own instance of the configuration. You can then pass that config into the `App` constructor. [A more detailed example](https://github.com/slackapi/java-slack-sdk/blob/0cca912e718aebf19ee869e850caecdee3022170/bolt-http4k/src/test/java/example/app/ExampleHttp4kBoltServer.java#L13-L18) is tucked away in the tests:

```java
App app = new App(AppConfig.builder()
    .signingSecret("xxx")
    .singleTeamBotToken("xoxb-111-111-xxx")
    .build()
);
```

**Comment by runningcode** [comment]
Perfect! Thanks.
