### ISSUE TITLE
Multiple redirect url not working in slack sso

### ISSUE THREAD

**Issue by iLvrge** [slackapi/java-slack-sdk#714]
When we try sso it works fine for the first redirect URL and when doing sso for the second one we are getting {"ok":false,"error":"bad_redirect_uri"}. Please help us in resolving the issue

**Comment by seratch** [comment]
Hi @iLvrge, thanks for asking the question! Can you please elaborate more on your issue? Does the SSO here mean the one you use for Slack workspace/organization login?

**Comment by iLvrge** [comment]
Ans to your question is Yes,

I have added 2 links in Redirect URLs.  The first one is working but when I try with the second one it is giving me the error bad_redirect_uri .

**Comment by seratch** [comment]
@iLvrge When you have multiple Redirect URIs, having `redirect_uri` parameter in the OAuth flow is required. Set the value in your Bolt app configuration: https://slack.dev/java-slack-sdk/guides/app-distribution#slack-config-for-distributing-your-slack-app

**Comment by iLvrge** [comment]
I am adding, and it works with the first one not with the second one.

**Comment by seratch** [comment]
Just in case, I created a simple OAuth app and saw how it works in the scenario. However, I didn't find any issues with multiple Redirect URIs. 

Please make sure if your `redirect_uri` parameter is a complete URL like `https://xxx.ngrok.io/slack/oauth/callback`. 

Also, I recommend checking the actual URL that your app generates again. The generated URL `https://slack.com/oauth/v2/authorize?client_id=...` must have `redirect_uri` as part of it in this scenario (I'm guessing your app does not generate the authorize URL with redirect_uri).

**Comment by seratch** [comment]
Let me know if you still need further help here. I will close this issue after waiting for your response for a while.

**Comment by iLvrge** [comment]
Thanks Seratch, My issue is fixed.

**Comment by talonx** [comment]
> Thanks Seratch, My issue is fixed.

Can you please elaborate on what worked? I'm not able to get around this. It looks like the first redirect_uri that is added in the Slack app management UI works. The second one always fails. This is when I have 2 URLs configured and it is also part of the authorize call to the Slack API.

**Comment by acidjazz** [comment]
> I found the solution. For anybody else who is facing this - when you have multiple redirect_uris the redirect_uri parameter has to be passed in the call when you are fetching the access token by sending the temporary token ("code") also, not just in the original authorize request. This worked for me.
> 
> Credits go to this SO answer https://stackoverflow.com/a/69659251

after tons of searching i found i needed to do this as well, id suggest putting it in the docs since this is not general oauth2 behavior
