### ISSUE TITLE
slack-api-client pulls okhttp 3.x in Spring Boot apps

### ISSUE THREAD

**Issue by mimozell** [slackapi/java-slack-sdk#722]
First time user of the Slack API client, so I pulled the latest release:
```
implementation("com.slack.api:slack-api-client:1.7.1")
```
I'm noticing the following:
![Screenshot 2021-03-31 at 10 33 27](https://user-images.githubusercontent.com/40452559/113115961-42548e80-920d-11eb-98e8-89ed639e8648.png)

So even though the version 4.9.1 of okhttp is specified by the slack client, the version 3.14.9 is actually being pulled in. I tried to do a `./gradlew build --refresh-dependencies`, but that changed nothing.

It will produce the following error:
![Screenshot 2021-03-30 at 16 16 11](https://user-images.githubusercontent.com/40452559/113116185-7e87ef00-920d-11eb-94db-552029a43b69.png)

I forked the source code to see what is going on, but can't currently see the issue as the latest okhttp version is clearly specified there. 

Setting 
```
implementation("com.squareup.okhttp3:okhttp:4.9.1")
```
manually in my project fixes the issue, but I would prefer it be fixed on the client side if it is a client issue. The project itself is not pulling okhttp through any other dependency from what I can see from my dependency tree.

### Reproducible in:

```
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1 (n)
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
+--- com.slack.api:slack-api-client:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
```

#### Java Runtime version

openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

#### OS info

ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
Darwin Kernel Version 20.3.0:

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @mimozell, thanks for taking the time to write in!

Judging from the screen shots you shared, I'm sure you are talking about Boot apps. I do understand the situation is confusing. However, in my understanding, **slack-api-client module simply depends on only okhttp 4.x and your situation is caused by auto configuration by Spring Boot**. 

If you add slack-api-client (or perhaps any dependencies that depend on okhttp) to Spring Boot applications, Spring Boot somehow forcibly adds okhttp 3.x.

For reference, let me share the outputs of `gradle dependencies` command.

With this gradle build file,

```gradle
plugins {
  id("application")
}
repositories {
  mavenCentral()
}
dependencies {
  implementation("com.slack.api:slack-api-client:1.7.1")
}
```

`gradle dependencies` shows okhttp 4.x is surely resolved and there is no reference to okhttp 3.x as long as you use slack-api-client outside spring boot's dependency resolution.

```
compileClasspath - Compile classpath for source set 'main'.
\--- com.slack.api:slack-api-client:1.7.1
     +--- com.slack.api:slack-api-model:1.7.1
     |    \--- com.google.code.gson:gson:2.8.6
     +--- com.squareup.okhttp3:okhttp:4.9.1
     |    +--- com.squareup.okio:okio:2.8.0
     |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 -> 1.4.10
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10
     |    |    |    \--- org.jetbrains:annotations:13.0
     |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0 -> 1.4.10
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.10 (*)
     +--- com.google.code.gson:gson:2.8.6
     \--- org.slf4j:slf4j-api:1.7.30
```

As you already mentioned, explicitly adding okhttp dependency is a workaround and that's the recommended way so far. If you know there is anything this project can do for avoiding this situation, we'd love to know your ideas.

**Comment by mimozell** [comment]
Yeah, I started thinking the same after I wrote this post - that it is a Spring Boot issue instead :/. I will check out if this is fixed in the later versions of SB, although I'm using one of the latest ones. I'll close this issue after a little bit more of investigation. Thank you! :)

**Comment by mimozell** [comment]
Doesn't seem like there's an improvement in the last version of SB for this. For anyone looking at this in the future, I was using:
```
id("org.springframework.boot") version "2.4.3"
id("io.spring.dependency-management") version "1.0.11.RELEASE"
```
and the only solution seems to be explicitly setting the okhttp version like this:
```
implementation("com.squareup.okhttp3:okhttp:4.9.1")
```
