### ISSUE TITLE
response_type in SlashCommandResponse is ignored and response is always ephemeral 

### ISSUE THREAD

**Issue by sceiler** [slackapi/java-slack-sdk#727]
I want slash commands to be in_channel instead of ephemeral but responseType is ignored when set to in_channel.

### Reproducible in:

```bash

> [INFO] +- com.slack.api:bolt-jetty:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-api-model:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-api-client:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-app-backend:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:bolt:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:bolt-servlet:jar:1.7.1:compile

> openjdk version "14.0.1" 2020-04-14
> OpenJDK Runtime Environment (build 14.0.1+7)
> OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

> ProductName:	macOS
> ProductVersion:	11.2.3
> BuildVersion:	20D91
> Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

```

#### The Slack SDK version

> [INFO] +- com.slack.api:bolt-jetty:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-api-model:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-api-client:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:slack-app-backend:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:bolt:jar:1.7.1:compile
> [INFO] |  +- com.slack.api:bolt-servlet:jar:1.7.1:compile

#### Java Runtime version

> openjdk version "14.0.1" 2020-04-14
> OpenJDK Runtime Environment (build 14.0.1+7)
> OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

#### OS info

> ProductName:	macOS
> ProductVersion:	11.2.3
> BuildVersion:	20D91
> Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Send Slash command to Slack, e.g. /my-slash-command
2. Have an app.command with `ctx.respond(r -> r.responseType("in_channel").text("my text"));`

I also tried various other ways without success:

```
var response = SlashCommandResponse.builder()
  .responseType("in_channel")
  .text("my text")
  .build();

ctx.respond(response);
```

#### Expected result:

The message should contain the request and response as documented here https://api.slack.com/interactivity/slash-commands

#### Actual result:

Request is not shown (ephemeral) and th responseType is ignored.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @sceiler, thanks for writing in!

I checked the actual behavior of the module but it works for me without any issues. Could you check this again and would you mind sharing a minimum working example that reproduces your issue?

**Comment by sceiler** [comment]
Hi @seratch,

I commented out everything and basically my code is this:

```
public class MyApp {
    private static final Logger log = LoggerFactory.getLogger(MyApp.class);

    public static void main(String[] args) throws Exception {
        App app = new App();

        String port = "3000";

        app.command("/chat-bot", (req, ctx) -> {
            ctx.respond(r -> r.responseType("in_channel").text("my text"));
            return ctx.ack(); // respond with 200 OK
        });

        SlackAppServer server = new SlackAppServer(app, Integer.parseInt(port));
        server.start(); // http://localhost:3000/slack/events
    }
}
```
Here is a screenshot as well:
![image](https://user-images.githubusercontent.com/6682932/115310482-2c801c80-a16e-11eb-8835-926bf7b636f6.png)

It looks like it is set but somehow not processed or something in my case. The Slash command is outputting "my text" though, just not honoring the response type for some reason.

**Comment by seratch** [comment]
@sceiler I'm guessing that the appearance of messages in a channel might be confusing to you when you post a in_channel message right after an ephemeral one.

In the following screenshot, only the second one is ephemeral. The last one is not an ephemeral message.
<img width="300" src="https://user-images.githubusercontent.com/19658/115311726-19d80880-a1ab-11eb-9c66-32419df25937.png">

You can check if a message is ephemeral by checking the message menu. If you see "Delete message", the message is ephemeral. 

<img width="400" src="https://user-images.githubusercontent.com/19658/115311684-03ca4800-a1ab-11eb-8a5c-941ccf0e3e6e.png">

If the menu shows the full list of available message shortcuts, the message is not ephemeral.

<img width="400" src="https://user-images.githubusercontent.com/19658/115311687-05940b80-a1ab-11eb-95a5-79f1162aaf6f.png">

If above is not your situation, I'd suggest enabling debug logs and see what the sent data using response_url is. You can enable debug-level logging by `System.setProperty("org.slf4j.simpleLogger.log.com.slack.api", "debug");` if you use `org.slf4j:slf4j-simple`.

Hope this was helpful to you.

**Comment by sceiler** [comment]
I need to double check when I'm back at my computer but I think you are right. I have this confused. However one thing causing this confusion I think is according to the documentation 
"When the response_type is in_channel, both the response message and the initial Slash Command typed by the user will be shared in the channel:"
I don't see the initial slash command in direct message or group message. Need to check what happens in a channel though and might have to work around this. Can you please confirm if the initial slash command is really only send when run in a channel?

**Comment by seratch** [comment]
@sceiler I'm sure you mentioned this page: https://api.slack.com/interactivity/slash-commands

<img width="400" src="https://user-images.githubusercontent.com/19658/115316102-a8e91e80-a1b3-11eb-9863-4d38728d330e.png">

>Can you please confirm if the initial slash command is really only send when run in a channel?

Yes, it works as described in the document. The document page is explaining how to respond to slash commands by HTTP 200 responses. 

I do understand the difference between `ack` and `respond` can be a bit confusing but, in a nutshell,
* `ack`: utility for asynchronously sending HTTP response (or WebSocket message if you use Socket Mode)
* `repsond`: utility for performing a new HTTP request to `response_url`

For this reason, you can use `ack()` with response_type, not `respond()` in this case.

**Comment by sceiler** [comment]
@seratch thanks a lot!! I was not aware that `ack` and `respond` would behave this differently when used with responseType.
With `return ctx.ack(r -> r.responseType("in_channel").text("my text"));` it now works as intended.
