### ISSUE TITLE
Slow event handling on Ktor framework

### ISSUE THREAD

**Issue by kam1sh** [slackapi/java-slack-sdk#730]
Hi! I'm writing service for CI automation, and now I'm about to integrate it with existing Ktor application, but it's very, very slow and I don't understand why. It produces response for >2 seconds! Currently I'm using microservice approach, where chatbot and main service are separate servers (Jetty on bolt, Ktor on the main app), but anyway I'm curious why I got this situation.

I have next questions:

* Is it because Slack with Ktor doesn't work well?
* Or it's Kotlin Coroutines behaviour?
* Or it's about Netty?

When I'll have spare time, I try to answer these questions by myself. But if you have it now, you can look at this :)

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

1.7.1

#### Java Runtime version

1.8.0_282

#### OS info

openSUSE Leap 15.2 (Linux Kernel 5.10.25-2.ge8f7993-default)

#### Steps to reproduce:

Consider we have next dependencies:
```
// build.gradle.kts
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("com.slack.api:bolt:1.7.1")
    implementation("com.slack.api:bolt-ktor:1.7.1")
    val ktorVersion = "1.5.2"
    implementation("io.ktor:ktor:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
}
```

And this main function:
```kotlin
import com.slack.api.bolt.App
import com.slack.api.bolt.ktor.respond
import com.slack.api.bolt.ktor.toBoltRequest
import com.slack.api.bolt.util.SlackRequestParser
import com.slack.api.model.event.MessageEvent
import io.ktor.application.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    val app = App()
    val requestParser = SlackRequestParser(app.config())
    app.event(MessageEvent::class.java) { payload, ctx ->
        if (payload.event.text == "ping") {
            ctx.client().chatPostMessage { it
                .channel(ctx.channelId)
                .text("BONK")
            }
        }
        ctx.ack()
    }
    app.start()
    val server = embeddedServer(Netty, port = 8080) {
        routing {
            post("/slack/events") {
                val request = toBoltRequest(call, requestParser)
                val response = app.run(request)
                respond(call, response)
            }
        }
    }
    server.start(wait = true)
}
```

#### Expected result:

I expected that request handling will take same or less time. Like, if I rewrite this example on top of bolt-jetty, it will take ~0.5 seconds on my machine.

#### Actual result:

But in fact respond is produced only after ~2.93 seconds.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @kam1sh, thanks for writing in!

I'm not sure what the cause of the issue in your Ktor app yet. How about checking the spent time for each phase as below? In addition to the following code, you may want to check the spent time inside your listener methods.

```kotlin
    val logger = LoggerFactory.getLogger("main")
    val server = embeddedServer(Netty, port = 3000) {
        routing {
            post("/slack/events") {
                val startingMillis = System.currentTimeMillis()
                val request = toBoltRequest(call, requestParser)

                val reqConvMillis = System.currentTimeMillis()
                logger.info("request conversion: ${reqConvMillis - startingMillis} ms")

                val response = app.run(request)

                val boltAppMillis = System.currentTimeMillis()
                logger.info("Bolt app execution: ${boltAppMillis - reqConvMillis} ms")

                respond(call, response)

                val respondMillis = System.currentTimeMillis()
                logger.info("respond call: ${respondMillis - boltAppMillis} ms")
            }
        }
    }
```

If the majority of the time is spent outside the Bolt app execution, you can adjust the configuration of Ktor Netty server. I'm not thinking there is room for improvement in Bolt's Ktor adapter module (it's a quite simple adapter) but once we identify something to fix in this library, I'm happy to fix it and release a patch version including it.

**Comment by kam1sh** [comment]
@seratch Thank you for fast response :) After digging for a while I think I found the root cause:
```kotlin
package com.slack.api.bolt.ktor

suspend fun respond(call: ApplicationCall, boltResponse: Response) {
    for (header in boltResponse.headers) {
        for (value in header.value) {
            call.response.header(header.key, value)
        }
    }
    call.response.status(HttpStatusCode.fromValue(boltResponse.statusCode))
    if (boltResponse.body != null) { // <<<
        call.respond(TextContent(boltResponse.body, ContentType.parse(boltResponse.contentType)))
    }
}
```

There is check body is not null, then respond with body and content-type. But what if there is no body? Then Ktor will never respond! This is why I've got 2.5 seconds -- because Slack reaches timeout and closes connection after that time.

Here is workaround:
```kotlin
        val status = HttpStatusCode.fromValue(boltResponse.statusCode)
        if (boltResponse.body != null) {
            call.respondText(boltResponse.body, ContentType.parse(boltResponse.contentType), status)
        } else call.respond(status)
```

**Comment by seratch** [comment]
@kam1sh Wow, this is amazing! If you don't mind, could you send a pull request for the fix (no rush!)? I would love to have your name [here](https://github.com/slackapi/java-slack-sdk/graphs/contributors) 😄
