### ISSUE TITLE
Sending rich_text yields invalid_block

### ISSUE THREAD

**Issue by jeffalder** [slackapi/java-slack-sdk#736]
I want to compose a rich text message because I prefer the stronger typing of `RichTextSectionElement.Text` and `RichTextSectionElement.Emoji`. However, the snippet below yields `invalid_blocks` when passed to the API.

### Reproducible in:

Adoptium Java 11.0.11 (fka AdoptOpenJDK)
Linux
Slack Bolt API 1.7.1

#### The Slack SDK version

```
+--- com.slack.api:bolt-jetty:1.7.1
|    +--- com.slack.api:slack-api-model:1.7.1
|    +--- com.slack.api:slack-api-client:1.7.1
|    |    +--- com.slack.api:slack-api-model:1.7.1 (*)
|    +--- com.slack.api:slack-app-backend:1.7.1
|    |    +--- com.slack.api:slack-api-model:1.7.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.7.1 (*)
|    +--- com.slack.api:bolt:1.7.1
|    |    +--- com.slack.api:slack-api-model:1.7.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.7.1 (*)
|    |    \--- com.slack.api:slack-app-backend:1.7.1 (*)
|    +--- com.slack.api:bolt-servlet:1.7.1
|    |    +--- com.slack.api:slack-api-model:1.7.1 (*)
|    |    +--- com.slack.api:slack-api-client:1.7.1 (*)
|    |    +--- com.slack.api:slack-app-backend:1.7.1 (*)
|    |    \--- com.slack.api:bolt:1.7.1 (*)
```

#### Java Runtime version

AdoptOpenJDK Java 11.0.11

#### OS info

Linux

#### Steps to reproduce:

Construct a `LayoutBlock` like this:
```java
import static com.slack.api.model.block.Blocks.richText;
import static com.slack.api.model.block.element.BlockElements.richTextSection;

                richText(rt -> rt.elements(List.of(
                        richTextSection(rts -> rts.elements(List.of(
                                RichTextSectionElement.Text.builder().text("Approved by ").build(),
                                RichTextSectionElement.User.builder().userId("U1234567890").build(),
                                RichTextSectionElement.Text.builder().text("!").build()
                        )))
 )))
```

Pass it to a `ChatPostMessageRequest`.

#### Expected result:

Message posted

#### Actual result:

```
ChatPostMessageResponse(ok=false, warning=null, error=invalid_blocks, needed=null, provided=null, deprecatedArgument=null, errors=null, responseMetadata=null, channel=null, ts=null, message=null)
```

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by jeffalder** [comment]
I tried it with just text:
```java
import com.slack.api.model.block.element.RichTextSectionElement;
import static com.slack.api.model.block.Blocks.richText;
import static com.slack.api.model.block.element.BlockElements.richTextSection;

                List.of(richText(r -> r.elements(List.of(richTextSection(s -> s.elements(List.of(
                        RichTextSectionElement.Text.builder().text("Richly approved.").build()
                )))))))
```

Here's the form request:
```
channel=C0XXXHXXKS&thread_ts=1619907067.015900&text=yu%20fully%20approved%21&link_names=0&mrkdwn=1&blocks=%5B%7B%22type%22%3A%22rich_text%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22Richly%20approved.%22%7D%5D%7D%5D%7D%5D&unfurl_links=0&unfurl_media=0&thread_ts=1619907067.015900&reply_broadcast=0
```

form decoded:
```
blocks=[{"type":"rich_text","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Richly approved."}]}]}]
```

And this works in the block kit builder.

**Comment by seratch** [comment]
Hi @jeffalder, thanks or asking the question!

Unfortunately, any 3rd party Slack apps are unable to populate the `rich_text` blocks. As mentioned in [this changelog](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less), those blocks are available only for Slack client apps (Desktop, Web Browser, iOS, Android)' WYSIWYG editors. 

This SDK supports the types of the rich_text blocks only for parsing `conversations.history` data and so forth. For constructing rich messages, please use top-level `text` field with the [Slack text format](https://api.slack.com/reference/surfaces/formatting) or `blocks` with other types.

**Comment by jeffalder** [comment]
Thanks for the quick answer! Is this documented elsewhere other than 1 sentence from a blog post from 2 years ago? I clearly missed that in scanning for hints, and I'd be interested in helping other developers not make the same mistake I did.

**Comment by seratch** [comment]
@jeffalder 
>Is this documented elsewhere other than 1 sentence from a blog post from 2 years ago?

No, it isn't. We don't want to highlight rich_text blocks in the Bolt document by adding a section for it but I'm happy to add quick comments in the javadocs if it may help new users.

**Comment by seratch** [comment]
@jeffalder Thanks again for reporting this and the improvement by #740 ! The newer version (v1.8.0) including your change will be released before long.

**Comment by gnawf** [comment]
Ok so this is unsupported. I could not find this anywhere. Can this be documented here? https://api.slack.com/methods/chat.postMessage

Right now all you get is `invalid_blocks` which is frustrating. No accompanying `errors` (it's null).

At least populate the `errors` in the response or make a new error saying rich text is unsupported.
