### ISSUE TITLE
On submitting the modal with error the response is not getting posted to the Modal.

### ISSUE THREAD

**Issue by Jyothinayak123** [slackapi/java-slack-sdk#737]
I want to validate the dates if the given date is before the current date and throw an error " Invalid date: Input provided has old date". I'm able to create hashmap for errors and get the error response locally with status code:200. On sending the response to UI of Modal it throw below error,

_{"ok":false,"error":"validation_failed","errors":{"start-block":"Invalid date: Input provided has old date""}_

           Map<String, String> errors = new HashMap<>();
            DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH:mm");
 			LocalDateTime start = LocalDateTime.parse(startDateTime , formatTime);
 			LocalDateTime stop = LocalDateTime.parse(endDateTime , formatTime);
 			LocalDateTime now = LocalDateTime.now();
 			if(start.isBefore( now ))
 			{
 				errors.put("start-block", "Invalid date: Input provided has old date");
            }  
 			if (!errors.isEmpty()) {
 			return ctx.ack(r->r.responseAction("errors").errors(errors)); }

response: Response(statusCode=200, contentType=application/json; charset=utf-8, headers={}, body={"response_action":"errors","errors":{"start-block":"Invalid date: Input provided has old date"}})

Please help me on this issue

**Comment by misscoded** [comment]
Hi @Jyothinayak123! In this case, we recommend that you give this [example](https://github.com/slackapi/java-slack-sdk/blob/main/bolt-servlet/src/test/java/samples/ViewSample.java) a go first and verify that it's working as expected, exactly as it's written. From there, you should be able to work backwards with your own variation. Here is some [additional documentation](https://slack.dev/java-slack-sdk/guides/modals) that might provide greater detail beyond that point. 

Let us know if doing the above sorts the issue out!

**Comment by seratch** [comment]
@Jyothinayak123 

>{"ok":false,"error":"validation_failed","errors":{"start-block":"Invalid date: Input provided has old date""}

How did you get this API response? As you may notice, `ack()` method just returns an HTTP response (or WS message for Socket Mode). Therefore, this is not a response to `ack()` call. The `"ok": false` response is obviously a response from Slack for an API call (say, `views.update`) you performed in a different way.

The code `if (!errors.isEmpty()) { return ctx.ack(r->r.responseAction("errors").errors(errors)); }` looks doing the right thing. I guess you may have some other difficulties or may be confused with something else. If you can share a complete Java code reproducing your situation, we may be able to help you out.

**Comment by seratch** [comment]
@Jyothinayak123 Let us know if you need more help here. I will close this issue after waiting for your response for a while.

**Comment by seratch** [comment]
Let me close this issue but, if you have something further to ask/discuss here, please feel free to write in!
