### ISSUE TITLE
Blocks support in app_mention event payload

### ISSUE THREAD

**Issue by maganth-seetharaman** [slackapi/java-slack-sdk#738]
The `app_mention` event payload provides the both `text` and `blocks` fields but the SDK supports only the `text` field. 
The feature request is for the SDK to support the `blocks` field in [AppMentionEvent classs](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/event/AppMentionEvent.java)

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [X] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by Hariprasad-Ramakrishnan** [comment]
We need it @seratch for a development for an app we are building. If you are taking requests from people for the next development iteration, please do take this. Thank you !

**Comment by seratch** [comment]
Thanks @maganth-seetharaman @Hariprasad-Ramakrishnan for taking the time to report this! I've submitted the pull request #739 fixing this issue. The changes will be included in the next minor version (v1.8.0). I cannot tell the release date but it won't take long.

**Comment by Hariprasad-Ramakrishnan** [comment]
Thanks for the super fast response as always @seratch.
