### ISSUE TITLE
Is message.channels event is missed in java-slack-sdk?

### ISSUE THREAD

**Issue by mikewoe** [slackapi/java-slack-sdk#746]
Want to check only channel messages to handle it by bot

As i see in [Event API](https://api.slack.com/events/message.channels) we have special event for this type of messages.

But i cannot find class for this event in sdk.

As workaround i can listen every message, and filter by channel_type, but if we have special event for this hope to use it)

**Comment by seratch** [comment]
Hi @mikewoe, thanks for asking this!

Either `app.event(MessageEvent.class, ...)` or `app.message("keyword", ...)` works for you. Here is the document: https://slack.dev/java-slack-sdk/guides/events-api

 If your app needs to receive the only message events happening in public channels, your app configuration can have only `message.channels` in the **Features** > **Event Subscriptions** page. Your Bolt code does not need to have anything specific about the channel type.

Let me close this question but please feel free to write in if you have follow-up questions!
