### ISSUE TITLE
use of lombok detracts from otherwise very useful code

### ISSUE THREAD

**Issue by PaulAndersonHSI** [slackapi/java-slack-sdk#747]
request: please consider removing lombok

it clutters things up and obscures more than it helps. Most IDE's have the trivial constructor, getter, setter, toString, equals etc. all built in already.

All we're left with is something that generates chaining operations.

first thing I'm going to do with this code is strip out the lombok dependency. Less is more. SImple is better than complex

**Comment by seratch** [comment]
Hi, thanks for taking the time to write in and the suggestion!

As you mention, we can do the same with Lombok's accessor/constructor/toString/equals generation by utilizing IDE's code generation feature (although the generated code tends to have so many lines of code). 

Also, I do understand your point from the library user perspective. When you download the source code and use code jump to this SDK, your IDE may not link to plain Java code.

>All we're left with is something that generates chaining operations.

I guess you indicated the [`@Builder`](https://projectlombok.org/features/Builder) annotation by this. It is a key feature we rely on, and if we get rid of Lombok, the lines of code we have to add to keep the same level of usability and backward compatibility would be huge. Also, the builder code support is not yet available in the latest JDK, Kotlin, and any other alternatives (even if the latest JDK supports something, we cannot drop supports for older JDKs, though). As you know, the feature enables us to provide the following interface. We want to avoid manually crafting these for a large number of API request classes.

```java
ChatPostMessageRequest.builder().channel("C111").text("Hi there!").build();
Slack.getInstance().methods("xoxb-").chatPostMessage(req -> req.channel("C111").text("Hi there!"));

App app = new App(AppConfig.builder()
  .signingSecret("secret")
  .clientId("123")
  .scope("commands,chat:write")
  .classicAppPermissionsEnabled(true)
  .build()
);
```

If we have something nice supporting the builder feature in the future, we may consider getting rid of Lombok. But for now, we are not planning to do so. Thanks again for the suggestion here, but I would appreciate it if you could understand this.
