### ISSUE TITLE
CORS issue while installing Slack App having Oauth endpoint in Spring Boot

### ISSUE THREAD

**Issue by sanveer-osahan** [slackapi/java-slack-sdk#761]
(Describe your issue and goal here)

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

```
[INFO] +- com.slack.api:bolt:jar:1.7.0:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.7.0:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.7.0:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.7.0:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.7.0:compile
```

#### Java Runtime version

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

#### OS info

ubuntu 20.04

#### Steps to reproduce:

1. I followed the comments from https://github.com/slackapi/java-slack-sdk/issues/555 and set up Oauth endpoint in Spring Boot.
2. Planning my app to be used in multiple workspaces, sharing the url having install path - 
`<a href="https://my.url/slack/install"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcSet="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>`
3. Integrated the above button in Angular. 

When I click the button from frontend:

#### Expected result:

The Slack App to redirectd to callback url and installation is initiated.  

#### Actual result:

Getting the following error:  
Access to XMLHttpRequest at 'https://slack.com/oauth/v2/authorize?client_id=xxxx&scope=chat:write,users:read,users:read.email&user_scope=&state=xxxx&redirect_uri=https%3A%2F%2Fmy.url%2Fslack%2Foauth%2Fcallback' (redirected from 'https://my.url/slack/install') from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Note:** It works when the install path - https://my.url/slack/install is directly accessed.

**Additional Steps:**
Tried adding the following to SlackInstallController:

```java
@WebServlet("/slack/install")
public class SlackInstallController extends SlackOAuthAppServlet {

  public SlackInstallController(App app) {
    super(app);
  }

  @Override
  protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
    super.doGet(req, resp);
    resp.setHeader("Access-Control-Allow-Origin", "*");
    resp.setHeader(
        "Access-Control-Allow-Methods",
        "POST, GET, OPTIONS, DELETE, CONNECT,DEBUG, DONE, HEAD, PUT");
  }
}
``` 
But still facing the same issue.

**Comment by seratch** [comment]
Hi @sanveer-osahan, thanks for asking the question!

>Note: It works when the install path - https://my.url/slack/install is directly accessed.

This is the only way that we support. Instead of performing an XHR with `/slack/install`, you can simply redirect an end user to `/slack/install` 

Although I am sure redirecting users to `/slack/install` should be far easier, if you have a reason to handle the redirection in your JavaScript code, you can do so with your own code. There is no way to reuse the `/slack/install` path for it but you can reuse the part generating the authorize URL with a valid state parameter on your server-side: https://github.com/slackapi/java-slack-sdk/blob/v1.8.1/bolt/src/main/java/com/slack/api/bolt/App.java#L943-L944

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by sanveer-osahan** [comment]
Thanks @seratch for the response,

Simply redirect would work. But there's a problem here. Let me give you more context on this.
I want the `/slack/intstall` path to be secured. Any user without a token should not be able to access this. The reason is for mapping the application's user id with slack installer. 
I have my custom OauthStateService and InstallationService.

I'm not sure on how I'll be able to simply redirect the user with Auth token.

> There is no way to reuse the `/slack/install` path for it but you can reuse the part generating the authorize URL with a valid state parameter on your server-side: https://github.com/slackapi/java-slack-sdk/blob/v1.8.1/bolt/src/main/java/com/slack/api/bolt/App.java#L943-L944

Can you please provide more context on this?

**Comment by seratch** [comment]
@sanveer-osahan 
>I want the /slack/intstall path to be secured. Any user without a token should not be able to access this. The reason is for mapping the application's user id with slack installer. I have my custom OauthStateService and InstallationService.

Does this mean the browser user can have a kind of session cookie associated with your service's login session token? If so, let me try to suggest a bit more clear idea as below.

>There is no way to reuse the /slack/install path for it but you can reuse the part generating the authorize URL with a valid state parameter on your server-side: https://github.com/slackapi/java-slack-sdk/blob/v1.8.1/bolt/src/main/java/com/slack/api/bolt/App.java#L943-L944
>Can you please provide more context on this?

"No way to reuse the path" means that you cannot reuse the path as-is for XHR request handling. You can reuse some parts of the built-in OAuth flow supports such as the authorize URL builder and state parameter generation.

What I suggest here is to write your own server-side code on your own (the following code is pseudo code). 

```java
// Check the login session token first before starting the installation flow
String currentUserLoginSessionToken = extract(slackRequest);
if (!isLoggedIn(slackRequest, currentUserLoginSessionToken)) {
  return redirectToLoginPage(slackRequest);
}

// Generate the Slack authorize URL (https://slack.com/oauth/v2/authorize ... )
// See also: https://api.slack.com/authentication/oauth-v2
// You use your own state service
String state = oAuthStateService.issueNewState(slackRequest, currentUserLoginSessionToken, response);
String authorizeUrl = buildAuthorizeUrl(state);

// If you want to render a web page before the redirection
if (config().isOAuthInstallPageRenderingEnabled()) {
  Response response = Response.builder().statusCode(200).build();
  response.setContentType("text/html; charset=utf-8");
  response.setBody(config().getOAuthInstallPageRenderer().render(authorizeUrl));
  return response;
} else {
  // immediately nagivate the user to the authorize URL  
  Map<String, List<String>> responseHeaders = new HashMap<>();
  Response response = Response.builder().statusCode(302).headers(responseHeaders).build();
  responseHeaders.put("Location", Arrays.asList(authorizeUrl));
  return response;
}
```

I found that some may want to have only the additional part in the beginning (like the part `Check the login session token first before starting the installation flow`) [here](https://github.com/slackapi/java-slack-sdk/blob/v1.8.1/bolt/src/main/java/com/slack/api/bolt/App.java#L940). In the future versions, Bolt framework can have a customizable point. It may not fit your use case but if you need something like that, let us know. I cannot tell when we can release the update but I will try to prioritize the work.

Did I adequately answer your questions here?

**Comment by sanveer-osahan** [comment]
@seratch I do have some clearity now. Thanks

>Does this mean the browser user can have a kind of session cookie associated with your service's login session token? If so, let me try to suggest a bit more clear idea as below.

I'm not using session cookies as of now. The application is stateless and using JWT token in as header - Authorization: Bearer token.

> I found that some may want to have only the additional part in the beginning (like the part Check the login session token first before starting the installation flow) here. In the future versions, Bolt framework can have a customizable point. It may not fit your use case but if you need something like that, let us know. I cannot tell when we can release the update but I will try to prioritize the work.

Yes having something like this would really help. Would be really helpful if it will work for JWT.

**Comment by seratch** [comment]
@sanveer-osahan 
Thanks for your quick reply. And, this makes sense > JWT token in Authorization header

>Yes having something like this would really help. Would be really helpful if it will work for JWT.

Unfortunately, for the built-in `/slack/install` endpoint logic, we are not planning to support this use case in the short term. Please consider implementing your own server-side logic that meets your requirements. As I mentioned above, you still can reuse state value generator, authorize URL generator, and so forth.

**Comment by sanveer-osahan** [comment]
@seratch  Thanks. Closing this.
