### ISSUE TITLE
No way to set subteam in AdminConversationsSetConversationPrefsRequest.Pref

### ISSUE THREAD

**Issue by anuj-dwivedi** [slackapi/java-slack-sdk#766]
Hi,

As per documentation of API https://api.slack.com/methods/admin.conversations.setConversationPrefs , we may set Type, User and Subteam in the `who_can_post` Pref however nested class `com.slack.api.methods.request.admin.conversations.AdminConversationsSetConversationPrefsRequest$Pref`  seem to have option for setting Type and User only. There is no option to set Subteam.

Similarly the response class AdminConversationsGetConversationPrefsResponse also does not return subteam. 

Would be great to have subteam introduced in both Get and Set conversation prefs methods.

Thanks,
Anuj

**Comment by seratch** [comment]
Hi @anuj-dwivedi, thanks for taking the time to report this! And you are right. The `subteam` should be supported in the requests. We will fix this issue in the next minor version.
