### ISSUE TITLE
Add integration test to verify users.info API call with stranger user ID (Slack Connect)

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#768]
The existing users.info integration tests do not verify the patterns with stranger users, which are the ones in a different org/workspace connected through Slack Connect. 

For this reason, the generated JSON data does not have the property `is_stranger: boolean` (the property can exist only when a user is a stranger as of today): https://github.com/slackapi/java-slack-sdk/blob/main/json-logs/samples/api/users.info.json

 This incomplete data affects API response type generation in node-slack-sdk.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by SivaTharun** [comment]
@seratch can i work on this issue?

**Comment by seratch** [comment]
@SivaTharun Thanks for saying this! All we need to do here are:

* Prerequisites: 
  * You have a paid Slack workspace for testing
  * You can create a Slack Connect shared channel with other workspaces for testing
* You add a new test pattern that calls `users.info` with a user ID of a stranger https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/test/java/test_with_remote_apis/methods/users_Test.java
* You add a new env variable `SLACK_SDK_TEST_STRANGER_USER_ID` to https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/test/java/config/Constants.java and use the user ID in the added test

If you are comfortable to work on this, we are happy to have your contribution!
