### ISSUE TITLE
thread_ts support in message_changed event

### ISSUE THREAD

**Issue by maganth-seetharaman** [slackapi/java-slack-sdk#774]
In `message_changed` event, the `thread_ts` is sent by Slack but is missing in the [MessageChangedEvent class](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/event/MessageChangedEvent.java).
This is a feature request to support `thread_ts` in `message_changed` event.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [X] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by srajiang** [comment]
@maganth-seetharaman Thanks for writing in! 👋 
From what I can see, supporting `thread_ts` would also include supporting `parent_user_id` as they are both returned by Slack. 

I've gone ahead and added this to our backlog. If you have time open a PR as well we'd love the contribution!
