### ISSUE TITLE
CI build stability issue on GitHub Actions

### ISSUE THREAD

**Issue by seratch** [slackapi/java-slack-sdk#779]
The test execution on GitHub Actions is sometimes very unstable. The common reasons are:

* Permission defined error when spinning up a mock HTTP server in tests --> rerunning the tests helps
*  Somehow the execution hangs --> rerunning the build may help

I'm still unsure about the best (or the most acceptable) way to eliminate (or mitigate) this issue yet but we can explore the ways to improve this.

* Change the runs-on env
  * We switched from ubuntu-latest to ubuntu-18.04  for mitigating this issue before but it may be about time to revisit this
* Select the tests to run
  * We currently run all the unit tests with Java 8, 11, and 14 but it may be possible to select some for Java 8 and 11
 
If someone who is knowledgeable on this, your inputs would be greatly appreciated!

**Comment by seratch** [comment]
Merged #780 and dropped Java 11 build. As we still have Java 8 and 14, removing the version should be okay. We've never observed any issues specific to the version - 11.

**Comment by filmaj** [comment]
Do you have any links to logs or output showing the permission denied issue, or have any insight into what is causing the issues? I wouldn't mind taking a look.

**Comment by seratch** [comment]
@filmaj It sometimes happens but retrying the job helps (thus, I always retry it..). So, we don't have any logs so far. https://github.com/slackapi/java-slack-sdk/issues/757 is a bit more specific about the issue. The situation can start when something on the GitHub Actions side has been changed (perhaps, new runtime version deployment or any other server-side events). Introducing retries by https://github.com/slackapi/java-slack-sdk/pull/758 mitigated the issue but it didn't eliminate it.

**Comment by seratch** [comment]
It seems that @filmaj's amazing pull request https://github.com/slackapi/java-slack-sdk/pull/800 eliminated the permission denied error issue! As we are not observing "Somehow the execution hangs --> rerunning the build may help" issue recently, let me close this issue for now!
