### ISSUE TITLE
A video link posted in a channel, causes a IllegalStateException for Conversation history API call

### ISSUE THREAD

**Issue by sitamarn** [slackapi/java-slack-sdk#785]
This link is posted on a Slack channel:
https://i.imgur.com/brgYmPX.gifv

When I create a Conversation history API call on this channel, I get this exception:

Conversation history API call has failed. channelId=*****, errMsg=java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4586 path $.messages[3].attachments[0].video_html

#### The Slack SDK version
com.slack.api:slack-api-client:jar:1.8.1:compile
com.slack.api:slack-api-model:jar:1.8.1:compile
com.slack.api:bolt-servlet:jar:1.8.1:compile
com.slack.api:slack-app-backend:jar:1.8.1:compile
com.slack.api:bolt:jar:1.8.1:compile
com.slack.api:slack-api-model:jar:1.8.1:compile
com.slack.api:slack-api-client:jar:1.8.1:compile
com.slack.api:slack-app-backend:jar:1.8.1:compile
com.slack.api:bolt-servlet:jar:1.8.1:compile

#### Java Runtime version

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Corretto-16.0.1.9.1 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Corretto-16.0.1.9.1 (build 16.0.1+9, mixed mode, sharing)

#### OS info

Microsoft Windows [Version 10.0.19042.1110]

#### Steps to reproduce:

        <dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>slack-api-client</artifactId>
            <version>1.8.1</version>
        </dependency>
        <dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>bolt-servlet</artifactId>
            <version>1.8.1</version>
        </dependency>

#### Expected result:

I would except to get a list of messages including the one with the attached link.

#### Actual result:

The exception below:
Conversation history API call has failed. channelId=*****, errMsg=java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4586 path $.messages[3].attachments[0].video_html

**Comment by seratch** [comment]
Hi @sitamarn, thanks for taking the time to report this issue and we're sorry about the error you don't have any workaround.

I will try to reproduce this on my own later but if possible, may I ask you to provide the raw JSON string data that causes this situation with the Java SDK JSON parser? You can use [the API tester](https://api.slack.com/methods/conversations.history/test) to see the raw response body in the browser.

**Comment by sitamarn** [comment]
Sorry, I can't share the response body, since it's a private data.
But it's easy to reproduce, I have managed to do it many times in different workspaces.

**Comment by seratch** [comment]
Sorry, I should have been a bit clearer about that. I do understand that it's not possible to share the whole message in this public place.

>$.messages[3].attachments[0].video_html

I just wanted to know what kind of data, not a string is set in this scenario.

>But it's easy to reproduce, I have managed to do it many times in different workspaces.

I will check this when I have time. Thanks again for reporting this!

**Comment by seratch** [comment]
👋 v1.10.0-RC1 (release candidate) is now available in the Maven Central repositories! Try the version out if you have a chance to see the issue is resolved 🙇 We'll release v1.10.0 within a few days.
