### ISSUE TITLE
Missing subteam in AdminConversationsGetConversationPrefsResponse

### ISSUE THREAD

**Issue by anuj-dwivedi** [slackapi/java-slack-sdk#787]
Hi,

I noticed that issue #766 is closed but only half of the problem is fixed. I don't see that subteam is being returned by `com.slack.api.methods.response.admin.conversations.AdminConversationsGetConversationPrefsResponse `

Not sure if it is intentional or a miss but would be great if this can be fixed, as there is no other way to query whether a subteam is set in channel posting permission.

Please let me know if you need any further info.

Thanks,
Anuj

**Comment by seratch** [comment]
Hi @anuj-dwivedi, thanks for reporting this issue! This issue will be resolved in the next release.

**Comment by seratch** [comment]
Hi @anuj-dwivedi, I took some time to check this issue but I found that the server-side does not return the subteams in the scenario. The issue should be already reported to the teams concerned. Once the response from the server-side is enhanced, the response data class in this SDK will be updated. We're sorry about the inconvenience here.

**Comment by seratch** [comment]
As we are unable to track the progress on the server-side here, let us close this issue in this client-side SDK project. Once the server-side is updated, we will reflect the changes to this SDK.
