### ISSUE TITLE
Question about pagination on search APIs

### ISSUE THREAD

**Issue by mostafamos** [slackapi/java-slack-sdk#798]
If the searchresult object has more than 20 records, getmatches has only 20 and this limits usability

how to override this number?

**Comment by seratch** [comment]
Hi @mostafamos, thanks for asking the question! For search,* API methods, you can pass `page`/`count` parameters for pagination. Refer to the API document for more details: https://api.slack.com/methods/search.all#arg_page

**Comment by mostafamos** [comment]
@seratch thanks 😊 it works but the API call result count takes up to 4 minutes to update when changing the query tag on slack, why so slow? If I updated a recent thread and test it takes 5 seconds only

**Comment by seratch** [comment]
@mostafamos Taking a few minutes to reflect changes to the search index is not common but the delay can depend on the backend service's behavior. We will escalate your feedback to the teams concerned. Thanks for your feedback!

It seems that everything is clear now. Let me close this issue but please feel free to write in whenever you have further to ask/discuss regarding this topic!
