### ISSUE TITLE
Is there any way to get RTM events (not the messages) history

### ISSUE THREAD

**Issue by BootGenius** [slackapi/java-slack-sdk#810]
Hi. Can you please describe if there is any way to get not-handled events in the bot application? For example, if I have an application that listens through the web sockets to the Slack events (like channel created/deleted, the message created, reaction added/removed). When the application is not running there will be some events that are not handled. I want to recover all the events when I run the application again. Is it possible to do it with Slack API? 
P.S. Yes, I understand that ideally, we should have a reliable queue like Redis or another that will store all the events inside.

**Comment by seratch** [comment]
Hi @BootGenius, thanks for asking the question! 

When your server is not responding, the Slack server-side does three retries at maximum in the exponential backoff manner. But, unfortunately, there is no mean to know unhandled requests after the retries. Also, the lost events won't be delivered any more.

I hope this was helpful to you!

**Comment by BootGenius** [comment]
@seratch. Thanks for the answer. Then I have 2 related questions:
1)  Can we query the deleted messages/reactions/channels using Slack API?
2)  Can we query modified messages/reactions/channels using Slack API?

**Comment by seratch** [comment]
@BootGenius Unfortunately, three is no way to do 1. and 2. both. If a message is modified, the `message` object has `edited` attribute, but your app cannot access its historical data using APIs.

**Comment by BootGenius** [comment]
ok. Got it. Thanks for the answer
