### ISSUE TITLE
Is there a way to get from Slack API the date when the user visited the workspace last time?

### ISSUE THREAD

**Issue by BootGenius** [slackapi/java-slack-sdk#811]
Hi. Can you please answer if there is a way to get from Slack API the date when the user visited the workspace last time?

**Comment by seratch** [comment]
Hi @BootGenius, you can receive a detailed information about a user by calling [users.info API](https://api.slack.com/methods/users.info) but unfortunately, the last access time is not included in its response. If knowing whether a user is currently active is enough (probably, that's not the case, though), [users.getPresence API](https://api.slack.com/methods/users.getPresence) is available for it.

**Comment by BootGenius** [comment]
Got it. Thanks
