### ISSUE TITLE
how to format the text into code snippet while sending through a payload in java to slack

### ISSUE THREAD

**Issue by KruthikHM** [slackapi/java-slack-sdk#812]
<img width="712" alt="Screenshot 2021-08-13 at 11 27 37 AM" src="https://user-images.githubusercontent.com/80741022/129324257-634c1387-637a-4ea1-82eb-729eccd34355.png">

I need the sql queries in code snippet format

**Comment by seratch** [comment]
@KruthikHM Doing as below should work for you.

```java
    String message = "Task ID: xxx\n" +
            "Comment: yyy\n" +
            "```\n" +
            "SELECT * FROM USERS WHERE ID = ?\n" +
            "```\n";
```

**Comment by KruthikHM** [comment]
> @KruthikHM Doing as below should work for you.
> 
> ```java
>     String message = "Task ID: xxx\n" +
>             "Comment: yyy\n" +
>             "```\n" +
>             "SELECT * FROM USERS WHERE ID = ?\n" +
>             "```\n";
> ```

Thank you very much, it helped.
