### ISSUE TITLE
Unable to connect to RTM Api using java-slack-sdk

### ISSUE THREAD

**Issue by BootGenius** [slackapi/java-slack-sdk#816]
Hi. Can you please help me. I'm trying to use java-slack-sdk to establish the connection to Slack RTM Api using the following code:
```
RTMClient rtmClient1 = Slack.getInstance().rtmStart("xoxb-TOKEN");
```
The bot token is taken from my test app home page

When I do this I get not_allowed_token_type response. Can you please help me with the solution?

**Comment by seratch** [comment]
Hi @BootGenius, thanks for asking the question!

For new app development, **we highly recommend [Socket Mode](https://slack.dev/java-slack-sdk/guides/socket-mode) as it provides more functionalities in addition to receiving [events](https://api.slack.com/events)**. The only thing that Socket Mode does not support while RTM does is to receive `user_typing` events and some minor ones. With Socket Mode, your app can handle slash command invocations, modal data submissions, button clicks, and any other user interactions. All of these are  unsupported in RTM.

But, if you have an inevitable reason to run an RTM app, you still can create a new "classic" app for RTM. The token that you got `not_allowed_token_type` with is not usable for RTM connections.

<img width="500" src="https://user-images.githubusercontent.com/19658/129663078-30b16ed0-edd8-484c-aaf5-b210ed538313.png">

* Go to https://api.slack.com/authentication/basics#soon and click "Create a classic Slack app" button
* You will be navigated to https://api.slack.com/apps?new_classic_app=1 and you can create an RTM compatible app
* Don't upgrade the permission model of the app although the admin page encourages to do so. Once your app is upgraded from classic to the latest app model, the app is no longer eligible to establish RTM connections. The upgraded one is only compatible with Socket Mode.

I hope this was helpful to you!

**Comment by BootGenius** [comment]
Thanks for the answer. Yes, I was able to run socket_mode_app. Then the question is is it possible to use batch_presence_aware=1 parameter with socket_mode_app?

**Comment by seratch** [comment]
@BootGenius No, unfortunately, the parameter and presence change subscription as whole are unsupported in Socket Mode apps.

**Comment by BootGenius** [comment]
Got you. Thanks for the help
