### ISSUE TITLE
emoji.list missing include_categories option

### ISSUE THREAD

**Issue by slushpupie** [slackapi/java-slack-sdk#821]
The Slack API for `emoji.list` has an option for `include_categories`, but the SDK does not support that option.

Note:  As of 8/20, https://api.slack.com/methods/emoji.list does not mention this option, however, https://api.slack.com/methods/admin.emoji.list does, so I would consider this a public feature of the API.  I have reported this documentation discrepancy to Slack directly, as well. So hopefully the documentation will be more clear soon.

**Comment by seratch** [comment]
Hi @slushpupie, thanks for taking the time to flag this! Thanks for sharing the feedback with the team! Once the document is updated, we will add the parameter to the API client SDKs.

**Comment by slushpupie** [comment]
@seratch Any chance this will get updated?  Do you have any sway with the API documentation team on getting this fixed there?

**Comment by seratch** [comment]
@slushpupie The server-side team made the option publicly available today. So I've added the option in this Java SDK and then just released a new patch version including the change. Thank you very much for your patience here. We're so sorry for being kept you waiting for such a long time.
