### ISSUE TITLE
OAuth does not work in Spring Boot + Bolt app

### ISSUE THREAD

**Issue by flecso-app** [slackapi/java-slack-sdk#827]
I am implementing a slack app using Bolt Java with Spring Boot and am trying to distribute the app but am having problems getting the oAuth2 flow working. I am getting "payload: VerificationCodePayload(code=xx.xx, state=, error=null)"  error . I've read here that Bolt Java requires the state parameter for the OAuth flows, but can't figure out how to setup my project so that state parameters are generated and properly injected into the flow and session. Any direction would be greatly appreciated!

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version
```

[INFO] +- com.slack.api:bolt:jar:1.8.1:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.8.1:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.8.1:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.8.1:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.8.1:compile
```

#### Java Runtime version

11.0.12+0

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

I'm trying to use this [Sharable URL](https://slack.com/oauth/v2/authorize?client_id=2251176255649.2262004209891&scope=chat:write,chat:write.customize,commands,im:history,im:write,incoming-webhook,links:write,users.profile:read,users:read,users:read.email&user_scope=) to add a slack app I'm devloping to another workspace. I'm actively working on the applications so that URL points to my development environment that is fronted by ngrok.

#### Actual result:

Getting error 
`2021-08-30 22:23:17.150  WARN 5013 --- [nio-5000-exec-1] .b.s.b.o.d.OAuthDefaultStateErrorHandler : Invalid state parameter detected - payload: VerificationCodePayload(code=sdftrgf.dfgdfg., state=, error=null)`

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by filmaj** [comment]
Hello @flecso-app,

Are you able to share a project where this error is reproducible?

**Comment by seratch** [comment]
@flecso-app 
Take a look at this document to learn the proper way to implement the OAuth in Spring Boot apps: https://slack.dev/java-slack-sdk/guides/app-distribution#build-slack-oauth-using-spring-boot 

Also, start your installation flow from `https://{your app domain}/slack/install`, not directly from `https://slack.com/oauth/v2/authorize`.

**Comment by seratch** [comment]
👋 @flecso-app let us know if you need more help here!
