### ISSUE TITLE
The interactive messages in slack will disappear automatically after a period of time

### ISSUE THREAD

**Issue by fu1212** [slackapi/java-slack-sdk#830]
<img width="236" alt="1" src="https://user-images.githubusercontent.com/58798121/131451541-ce33cbfe-0278-4d69-8a7b-5100f435f589.png">

Question: As shown in the figure above, when I click the 'Yes' button, a message will appear under the button, but after a period of time, the message will disappear automatically. Why? How to solve this problem? I want this message to never disappear.

The code is as follows:
```
// when a user clicks a button in the actions block
app.blockAction("button-action", (req, ctx) -> {
  String value = req.getPayload().getActions().get(0).getValue(); // "button's value"
  if (req.getPayload().getResponseUrl() != null) {
    // Post a message to the same channel if it's a block in a message
    ctx.respond("You've sent " + value + " by clicking the button!");
  }
  return ctx.ack();
});
```

**Comment by seratch** [comment]
Hi @fu1212, thanks for asking the question!

The default mode of messages posted by `respond`, which sends a reply using `response_url` in a payload, is "ephemeral" mode. Refer to https://api.slack.com/messaging/managing#ephemeral for more details of ephemeral messages. 

>I want this message to never disappear.

You can customize the behavior this way:

```java
ctx.respond(r -> r.responseType("in_channel").text("your message here"))
```

I hope this helps!

**Comment by fu1212** [comment]
@seratch Thank you for your answer.
