### ISSUE TITLE
Interactive messages only appear below the last message

### ISSUE THREAD

**Issue by fu1212** [slackapi/java-slack-sdk#831]
<img width="261" alt="1630393367(1)" src="https://user-images.githubusercontent.com/58798121/131458018-a1c1d198-f190-40f6-86cb-f92e79253d57.png">

Question: As shown in the figure above, I received two messages in slack. Whether I click the 'Approve' button or the 'Yes' button, the returned message only appears below the last message. Why? I hope the returned message will only appear under the button I clicked. How to do?

Please help, thank you!

My code is as follows:
```
app.blockAction("button-action", (req, ctx) -> {
  Response respond= ctx.ack();
  String value = req.getPayload().getActions().get(0).getValue(); // "button's value"
  if (req.getPayload().getResponseUrl() != null) {
    // Post a message to the same channel if it's a block in a message
    ctx.respond("You " + value + " it");
  }
  return respond;
});
```

**Comment by seratch** [comment]
Hi @fu1212, thanks for asking a question again!

Unfortunately, once your channel has new other messages before clicking the button, it's not possible to re-order the messages in the channel. If you want to replace the message with the button, I would recommend using `replace_original` option in your response_url call payload as below:

```java
ctx.respond(r -> r
  .responseType("in_channel")
  .replaceOriginal(true)
  .text("Thanks for the approval!")
);
```

If everything is clear now, would you mind closing this question?

**Comment by fu1212** [comment]
<img width="311" alt="1630395070(1)" src="https://user-images.githubusercontent.com/58798121/131461799-280da57b-f2c6-45d3-862d-417c342f61d7.png">

Hi @seratch , Thank you for your answer! I want to ask again, can't the interactive message appear in the position marked in the screenshot after I click the 'Approve' button?

I want to achieve an effect similar to that shown in the screenshot below. There are many buttons here. When I click one of them, the interactive message will appear below it.
<img width="459" alt="3" src="https://user-images.githubusercontent.com/58798121/131463022-8cd4da2d-ba62-440d-b7a4-e9ed663713e4.png">

**Comment by seratch** [comment]
@fu1212 As I mentioned in my previous comment, you can update the message with `replace_original: true` option. If you don't want to modify the original message, an alternative solution is to post a reply in a thread. Hope this helps.

**Comment by fu1212** [comment]
@seratch   ok, thank you!
