### ISSUE TITLE
How to respond on slash command asynchronous way?

### ISSUE THREAD

**Issue by yoyojin-dev** [slackapi/java-slack-sdk#844]
I use `slack-bolt:1.12.0` and `kotlin:1.5.30`.
I have long-time computations before I'm able to send a response on a slash command. Due to Slack requirements of responding time I have to execute `app.ack()` first and only after that do the other stuff. It is not only about slash command but views, attachements and everything else.

#### Actual result:

Right now I have to use CompletableFutures in the registration of the command to prevent Slack errors:

```
app.command("/issue") { req, ctx ->
    val payload = req.payload.text.trim()
    CompletableFuture.runAsync {
        ctx.respond( produceResponse(req) )
    }
    ctx.ack()
}
```
In every examples I managed to find a response is sent just like this:
```
app.command("/command") { req, ctx ->
    ctx.respond("Response example")
    ctx.ack("Command acked")
}
```
Was it designed on purpose? These scheme could lead to Slack timeout errors and show ugly "dispatch_failed" error to the users if something goes wrong even if the computations aren't as long as I have. Moreover, it doesn't work properly with Kotlin Coroutines because coroutines are expected to be finished before we return the `ack()` value (or it could be just my misunderstanding of how coroutines work)

#### Expected result:

I expected its usage more simple, for instance:
```
app.command("/issue") { req, ctx ->
    ctx.ack("Command acked")  // Telling Slack a hook was consumed
    ctx.respond( produceResponse(req) ) // Sending a proper response which takes times to be built.
    // other actions connected to the command
}
```

**Comment by seratch** [comment]
Hi @yoyojin-dev, thanks for asking the question! Perhaps, my comment at https://github.com/slackapi/java-slack-sdk/issues/825#issuecomment-906409841 can be an answer for your question. In the Java world, managing thread pools is not so simple. That's why bolt-java does not encapsulate the layer from developers.

I hope this helps! If you have further questions, let us know.

**Comment by yoyojin-dev** [comment]
Hi, @seratch ! Thank you for the very quick answering!
Perhaps, it would be great to include that code to the Java/Kotlin examples to prevent further questions like this:)
