### ISSUE TITLE
Sometimes the Submit and Close actions of the view are not monitored by the slack app

### ISSUE THREAD

**Issue by fu1212** [slackapi/java-slack-sdk#847]
Hello

I use Socket Mode to develop the slack application. I create a view. After opening the view, I want to get some information when I click the submit button, but I don't get any reaction after clicking the button. The operation is not monitored by the app, so the code doesn't print any logs. 
This phenomenon does not occur every time. why? Please help.

My Code:
```java
app.viewSubmission("meeting-arrangement", (req, ctx) -> {
            System.out.println("**************begin**************");
            String privateMetadata = req.getPayload().getView().getPrivateMetadata();
            Map<String, Map<String, ViewState.Value>> stateValues = req.getPayload().getView().getState().getValues();
            String agenda = stateValues.get("agenda-block").get("agenda-action").getValue();
            System.out.println("privateMetadata->"+privateMetadata);
            System.out.println("agenda->" + agenda);
            System.out.println("**************end**************");
            return ctx.ack();
        });

SocketModeApp socketModeApp = new SocketModeApp(appToken, SocketModeClient.Backend.JavaWebSocket, app);
socketModeApp.start();
```

**Comment by seratch** [comment]
Hi @fu1212, thanks for asking the question!

Your situation may be similar to https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180 

As I suggested in the issue, can you try creating a new app-level token and disabling other existing ones to ensure only one active connection receives all requests?

**Comment by fu1212** [comment]
ok，thank you!

**Comment by fu1212** [comment]
Hi @seratch,
When I change the appToken of this app, the phenomenon of no response when I click the button no longer exists. But sometimes there are other problems. 
When I click the button once, it will repeatedly execute the business logic in viewSubmission many times, and there will be such an error prompt that the view cannot be closed.
<img width="304" alt="1632376981(1)" src="https://user-images.githubusercontent.com/58798121/134461778-704319d8-539d-4c5f-bb37-109de12eb8b5.png">

why? Please help, thank you!

**Comment by seratch** [comment]
@fu1212 Can you check the following points to figure out what's happening to your app?

* Does every single request reach your Socket Mode app for sure? You can turn debug-level logging on to see more details of the incoming requests.
* Does your app.view listener complete within 3 seconds in the scenario? If not, that's the cause of the user-facing error.

**Comment by fu1212** [comment]
@seratch 
1. yes, I only clicked the button once, but the console printed the same log in the app.view listener several times. 
2. yes, I use asynchronous method to process the time-consuming logic, and other logic will not exceed 3 seconds in my app.view listener

**Comment by seratch** [comment]
>yes, I only clicked the button once, but the console printed the same log in the app.view listener several times.

I think that this is a result of timeout retries from Slack. Your app didn't acknowledge requests for some reason. But I cannot suggest anything further with the given information. If you can provide a minimum working example that reproduces your situation, I may be able to advice more.

**Comment by fu1212** [comment]
[log.txt](https://github.com/slackapi/java-slack-sdk/files/7215662/log.txt)
Please check the log file. The above situation occurs in this case. 
When I restart the project, which is equivalent to restarting the socket mode service of slack, everything is normal again.

But if my project goes online, I can't always restart the project to avoid this problem.
Can you provide good suggestions and solutions?
Do you need to restart the socket mode service at intervals? And how to restart?

**Comment by seratch** [comment]
@fu1212 Thanks for sharing the log. According to the log, it seems that the situation is the same with your issue https://github.com/slackapi/java-slack-sdk/issues/849. Thus, the modal error is just a result of the disconnection.

You logs tell that the underlying WebSocket client detected the connectivity issue (= ping-pong communication had not been successful for a while).

>2021-09-22 13:48:26.006  INFO 8 --- [onLostChecker-1] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: 1006, reason: The connection was closed because the other endpoint did not respond with a pong in time. For more information check: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection)
>2021-09-22 13:48:26.006  INFO 8 --- [onLostChecker-1] c.s.api.socket_mode.SocketModeClient     : Failed to send a ping message (exception: java.lang.InterruptedException, message: sleep interrupted)

In the other line of the log, your app received "408 Request Timeout" for outgoing communications.

>2021-09-22 13:47:18.688  INFO 8 --- [tReadThread-349] c.s.api.socket_mode.SocketModeClient     : onClose listener is called (code: 1002, reason: Invalid status code received: 408 Status line: HTTP/1.1 408 Request Timeout)

Is your running environment behind a proxy server / corporate firewall? If so, consulting with your admins about the appropriate way to run WebSocket applications in the environment.

Also, do you have any particular reason to use the Java-WebSocket based implementation? The lost connectivity detection is the library's functionality. Thus, we are unable to help you regarding the details of its behavior. If you don't have a strong reason to use the library, using the Tyrus based one (this is our primary recommendation) to see if there is any difference may worth trying.

Lastly, in normal situations, you can expect the SocketModeClient automatically reconnects and you don't need to periodically restart your app. With that being said, if you need to restart the Socket Mode client, you can use `startAsync()` method and `stop()` method to manually reconnect to Slack. 

* https://github.com/slackapi/java-slack-sdk/blob/v1.12.1/bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java#L95-L97
* https://github.com/slackapi/java-slack-sdk/blob/v1.12.1/bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java#L112-L116

With this way, the `startAsync()` method does not block your app's current thread. If you want to retain the process running by your own code, [running your main thread like the `start()` method](https://github.com/slackapi/java-slack-sdk/blob/v1.12.1/bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java#L107-L109) plus maintaining the Socket Mode client's state in a different thread is an easy way to do so.

**Comment by fu1212** [comment]
thank you!
