### ISSUE TITLE
RMI thread Deadlock 

### ISSUE THREAD

**Issue by shaburov** [slackapi/java-slack-sdk#85]
`take()` is not the best solution for the`BlockingQueue<Runnable>`

System props
```
awt.toolkit=sun.lwawt.macosx.LWCToolkit
file.encoding=UTF-8
file.separator=/
gopherProxySet=false
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
java.class.path=target/Smoker.jar
java.class.version=55.0
java.home=/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
java.io.tmpdir=/var/folders/2h/mjw8k1v93z9_t746q075t7j80000gp/T/
java.library.path=/Users/oshabur/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.rmi.server.randomIDs=true
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.1+13
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.java.com/bugreport/
java.vendor.version=18.9
java.version=11.0.1
java.version.date=2018-10-16
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=Oracle Corporation
java.vm.version=11.0.1+13
jdk.debug=release
line.separator=\n
os.arch=x86_64
os.name=Mac OS X
os.version=10.14.1
path.separator=:
sun.arch.data.model=64
sun.boot.library.path=/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/lib
sun.cpu.endian=little
sun.cpu.isalist=
sun.io.unicode.encoding=UnicodeBig
sun.java.command=target/Smoker.jar -Dslack.bot.access.list=oshaburov,oshaburov
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=UTF-8
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=unknown
```
Parking threads
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/15269131/49449444-eff53580-f7eb-11e8-9506-d1e5e3cde43f.png">

CPU Time
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/15269131/49449603-4d898200-f7ec-11e8-9b5a-39b57ce23fe0.png">

CPU samples 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/15269131/49450125-6ba3b200-f7ed-11e8-87d5-1336af5d5e8e.png">

Full thread dump
[thread_dump.txt](https://github.com/seratch/jslack/files/2644530/thread_dump.txt)

Code
```java
public class Smoker {
    private static boolean isRun = false;
    private static final Logger LOG = LoggerFactory.getLogger(Smoker.class);

    public static void main(String[] args) {
        isRun = true;
        String token = BaseMessageHandler.getToken();
        try (RTMClient rtm = new Slack().rtm(token)) {
            LOG.info("Real Time Messaging client started");
            rtm.addMessageHandler(new UserMessageHandler());
            rtm.addMessageHandler(new GroupMessageHandler());
            rtm.addErrorHandler(new ErrorHandler());
            rtm.connect();
            addShutdownHook();
            while (isRun) {
                sleep(1000);
            }
        } catch (Throwable e) {
            LOG.error("Unexpected exception. Service died.", e);
        } finally {
            Runtime.getRuntime().exit(1);
        }
    }
}
```

Log example
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15269131/49450975-3730f580-f7ef-11e8-93e5-c34cffddadd3.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/15269131/49451354-11582080-f7f0-11e8-9e3c-f4bdb0f01301.png">

**Comment by shaburov** [comment]
UPD
<img width="658" alt="image" src="https://user-images.githubusercontent.com/15269131/49451191-b0c8e380-f7ef-11e8-8e46-2a7c44f9e261.png">

**Comment by seratch** [comment]
I am sorry for my belated response to this. Thank you for the detailed report. We need to improve this in some way.

**Comment by d-subrahmanyam** [comment]
Can we have some more context on the issue? I was trying to sift through this, but couldn't help find any reference.

**Comment by seratch** [comment]
If I understand this correctly, the thread deadlock situation may arise due to the internal resource management by the underlying tyrus client library. I'm not sure if the latest version of 1.x series resolves this but we haven't received this feedback  apart from this issue yet.

I will keep this issue open for a while but we may close this issue in the future.

**Comment by seratch** [comment]
Let me close this issue due to inactivity but please feel free to write in if you have something similar or more information on it.
