### ISSUE TITLE
How do you deserialize the objects?

### ISSUE THREAD

**Issue by darewreck54** [slackapi/java-slack-sdk#854]
Is there any helper method to deserialize the models?  For example, Layout is an interface but to successfully use deserializer like jackson's Object Mapper you need to either add annotation to the object or create custom deserializer to account for the `type` defined in the class.  The latter requires work on the consumer of the SDK if they want to utilize the types like `ChatPostMessageResponse` vs defining their own types.

Thanks,
Derek

**Comment by seratch** [comment]
@darewreck54 We use GSON for serializing / deserializing JSON data. For some types, we have type adapters like these: https://github.com/slackapi/java-slack-sdk/blob/v1.12.1/slack-api-client/src/main/java/com/slack/api/util/json/GsonFactory.java#L43-L65

If you would like to use Jackson for your type binding, you can do the same in your own code. We are not planning to add Jackson support on this SDK side.

Let me know if you have anything further to ask/discuss here.

**Comment by seratch** [comment]
@darewreck54 Let us know if you need more help here 👋 If we don't hear back, we'll close this issue in a few days.

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have something related to this topic 👋
