### ISSUE TITLE
How to share my app with other workspaces?

### ISSUE THREAD

**Issue by Mike1212-12** [slackapi/java-slack-sdk#855]
Hello, 
I want to confirm a few questions:
1. Apps using Socket Mode cannot be submitted to the App Directory?
2. Is Socket Mode not intended for publicly distributed apps?
3. Under socket mode, can I make the app publicly distributed without submitting to app directory?
4. As long as I intend to publicly distribute my app, regardless of submitting it to app directory or not, I can't use socket mode and must enable HTTP Request URLs ?

**Comment by seratch** [comment]
Hi @Mike1212-12, thanks for writing in!

>Apps using Socket Mode cannot be submitted to the App Directory?

>Apps using Socket Mode are not currently allowed in the public Slack App Directory.
https://api.slack.com/apis/connections/socket

As mentioned in the above page, this is not possible. To list your app in App Directory, your app needs to use the HTTP URL mode instead.

>Is Socket Mode not intended for publicly distributed apps?
>As long as I intend to publicly distribute my app, regardless of submitting it to app directory or not, I can't use socket mode and must enable HTTP Request URLs ?

It's not recommended, but as long as your app is used by a few small workspaces, it should work without any issues.

>Under socket mode, can I make the app publicly distributed without submitting to app directory?

If your end-users in other workspaces know the installation URL, they can install your app. One downside is that they will see the following message in the app management page:

<img width="400" src="https://user-images.githubusercontent.com/19658/134828495-415fbe64-e11f-4ed9-a20d-542e4bf23f02.png">

I hope this was helpful to you!

**Comment by Mike1212-12** [comment]
I see. Thank you!
