### ISSUE TITLE
Add the missing "pronouns" field to User.Profile data class

### ISSUE THREAD

**Issue by petehannam** [slackapi/java-slack-sdk#857]
With the addition of [pronouns](https://slack.com/intl/en-gb/help/articles/1500011115781-Manage-pronoun-display-for-member-profiles) to user's profiles, there's a field returned as part of the Profile structure ```pronouns```. This is returned as part of the response when using the [tester](https://api.slack.com/methods/users.profile.get/test) but it isn't represented in the [SDK client](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/User.java) entity ```com.slack.api.model.User.Profile```.

It's not a custom field, so as things currently stand I don't think it's possible to set directly via the SDK - it would be great if it could be exposed.

Thanks,
Pete

**Comment by misscoded** [comment]
Hi @petehannam -- thanks for taking the time to bring this to our attention! We'll augment the model to include the new `pronouns` field shortly. 🙂
