### ISSUE TITLE
Where to start the SocketModeApp service

### ISSUE THREAD

**Issue by Mike666888abc** [slackapi/java-slack-sdk#861]
When you use socket mode to run your app, can the following code only be used in the main function of your project?

```java
App app = new App(appConfig);
SocketModeApp socketModeApp = new SocketModeApp(appToken, SocketModeClient.Backend.JavaWebSocket,app);
socketModeApp.start();
```

**Comment by seratch** [comment]
Hi @Mike1212-12, thanks for writing in! 

If you would like to simply run the Socket Mode client only, you can use the `start()` method. If you would like to have the Socket Mode client as part of your larger application (e.g., web application, managed batch processing system), you may want to use [`startAsync()` methoed](https://github.com/slackapi/java-slack-sdk/blob/v1.12.1/bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java#L95-L97) to start the Socket Mode client in a background thread.

I hope this helps!

**Comment by Mike1212-12** [comment]
@seratch Thank you for your solution. I want to know why? What is the difference between the two methods?

**Comment by seratch** [comment]
@Mike1212-12 
As mentioned above, the `start()` blocks the current thread. This is useful for keeping your app process running with less effort. Also, that's the common pattern for a simple Socket Mode app process that does not do anything else. 

On the other hand, if you would like to have a Socket Mode client as part of a larger application, blocking the current thread (in other words, the main thread) may not be a good fit. Your app may want to something else for other parts while bootstrapping. This is why this SDK provides `startAsync()` and `stop()` methods.

If the latter one is not your use case, there is no need to check how to use `startAsync()` and `stop()` methods. You can simply go with the `start()` method.

Does this make sense to you?

**Comment by seratch** [comment]
@Mike1212-12 Let us know if you need more help here 👋 If we don't hear back for a few days, we'll close this issue.
