### ISSUE TITLE
Newly imported java-slack-sdk project build fails in IntelliJ IDEA 

### ISSUE THREAD

**Issue by ikolomiets** [slackapi/java-slack-sdk#865]
Current (1.12.2-SNAPSHOT) version of java-slack-sdk when imported into latest (2120.2.2) IntelliJ IDEA can't be built with IDEA (building it with maven in the console works fine). The failure is due to bolt-helidon which complains about missing Flow API classes (added in Java 9):

```
/work/java-slack-sdk/bolt-helidon/src/main/java/com/slack/api/bolt/helidon/SlackAppService.java:62:26
java: cannot access java.util.concurrent.Flow
  class file for java.util.concurrent.Flow not found
```

To account for this, bolt-helidon's pom.xml overrides default Java language level (set in parent's pom.xml to 1.8) to 11. Unfortunately, for some reason it doesn't work in IDEA.

There is a simple tweak to parent pom.xml that fixes it: https://github.com/slackapi/java-slack-sdk/pull/866

### Category

* [ ] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

**Comment by seratch** [comment]
Fixed by #866
