### ISSUE TITLE
Can't send message without mrkdwn format because Missing mrkdwn in chat.postMessage.json

### ISSUE THREAD

**Issue by YoshiInTokyo** [slackapi/java-slack-sdk#867]
Hi,

When I developed slack app with python-slack-sdk, I noticed 'mrkdwn' option is disabled in chat.postMessage.
I tried to post message by tester in api homepage (https://api.slack.com/methods/chat.postMessage), but the result was the same.
This indicates that it is a bug in the slack api itself, not in python-slack-sdk.

And, I checked 'node-slack-sdk' to find api type are generated from java-slack-sdk/json-logs/samples/api/* 
(please see node-slack-sdk/packages/web-api/src/response/* or node-slack-sdk/scripts/generate-web-api-types.sh)

In java-slack-sdk/json-logs/samples/api/chat.postMessage.json, I cannot find 'mrkdwn' args.
So, I think this is the cause of the bug.
Please add mrkdwn option to java-slack-sdk/json-logs/samples/api/chat.postMessage.json.

#### Steps to reproduce:

1. goto tester (https://api.slack.com/methods/chat.postMessage/test)
2. set mrkdwn to false and input some text
3. 'mrkdwn' is not in responce json and result is formatting with mrkdwn (Failed to turn off mrkdwn!)

This is my first issue to post on github, so there may be some mistakes, but please help me out.

Thanks,
Yoshi

**Comment by seratch** [comment]
HI @YoshiInTokyo, thanks for writing in! 

I'm not sure about the difficulty that you're having yet. You should be able to use the `mrkdwn` argument in any of the SDKs. Also, the `java-slack-sdk/json-logs/samples/api/chat.postMessage.json` is generated from chat.postMessage API **response**, not its arguments. Thus, if I understand your message here correctly, the JSON file is unrelated.

If a text message using the [Slack format](https://api.slack.com/reference/surfaces/formatting#basics) does not work for you, can you share examples reproducing your issue?

I hope this helps!

**Comment by YoshiInTokyo** [comment]
Thank you for your quick response!

I'm sorry that I don't know all the details and that my writing is inadequate.

To reproduce it, in the [tester](https://api.slack.com/methods/chat.postMessage/test), fill in the bot token and channel, set mrkdwn to false, and put `M$_{BH}/M_{odot}$` in the text box.
The message sent to you should not be italicized, but it is in fact italicized.
<img width="124" alt="image" src="https://user-images.githubusercontent.com/49469846/135979262-3d154a7d-8431-47dc-bf1f-4c1275e00635.png">

**Comment by seratch** [comment]
@YoshiInTokyo Thanks for sharing the details.

I've also observed the same behavior when having `text` value along with `mrkdwn: false`. The issue should be resolved on the Slack product side and we'll escalate the issue to the engineering teams. 

One workaround that I can suggest is to use `blocks` for safety. For instance, if you have a `plain_text` typed text in a block, the outlook of it would be always the one you would like to have. You can use [Block Kit Builder](https://app.slack.com/block-kit-builder/#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22M$_%7BBH%7D/M_%7Bodot%7D$%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22M$_%7BBH%7D/M_%7Bodot%7D$%22%7D%7D%5D%7D) to preview how blocks work.

<img width="600" src="https://user-images.githubusercontent.com/19658/135986755-130683f3-6e6e-49e8-863b-574d1e897475.png">

Thanks again for flagging the issue and I hope this was helpful to you.

**Comment by YoshiInTokyo** [comment]
@seratch 
Thank you for your advice!

Now, I try to use this[ third-party extension](https://github.com/thisiscam/math-with-slack) to render latex syntax, and this extension is only valid in text field, not blocks.
So, I regret to said that your method is not matched for my purpose.

Anyway, I hope that my issue improves slack api.

Bests,
Yoshi.

P.S. I apologize for sending the issue to this repository, not the help center.

**Comment by seratch** [comment]
Hi @YoshiInTokyo, thanks for your reply! Another workaround would be to customize the extension project and use pre tags surrounded by ``` instead of giving a raw input to your Python code.

I've escalated the issue to the teams concerned. As we are unable to track the progress of the server-side bug fixes in this SDK issue tracker, let us close this issue now. When you would like to know the progress of the updates on the server-side, I'm sorry to bother you but please contact our customer support agents. Thanks again for your feedback here 🙇
