### ISSUE TITLE
Slack WebSocket "error":"a request for an unknown workspace detected"

### ISSUE THREAD

**Issue by adiz50** [slackapi/java-slack-sdk#873]
I've been trying to connect to Slack API through WebSocket but I encountered an issue. To be precise Slack seems to connect with my app and it is sending reactions to events but I am getting an error:

INFO 11624 --- [essor-worker-35] c.s.a.b.m.b.MultiTeamsAuthorization      : auth.test result: null, io error: null, api error: null
WARN 11624 --- [essor-worker-35] c.s.api.bolt.socket_mode.SocketModeApp   : Unsuccessful Bolt app execution (status: 401, body: {"error":"a request for an unknown workspace detected"})

I've been stuck with this error for a few days, here is my code:

```java
@Service
@Configurable
public class SlackApp {

    @Autowired
    private SlackConfig slackConfig;

    @Bean
    public App initSlackApp(){
        //here goes the code
        String botToken = "xoxb-token";
        String appToken = "xapp-token";

        App app = new App(AppConfig.builder().singleTeamBotToken(botToken)
                .clientSecret("secret").clientId("clientId").build());

        SocketModeApp socketModeApp;
        try{
            socketModeApp = new SocketModeApp(appToken, app);
            socketModeApp.startAsync();
        }catch(Exception e){
            e.printStackTrace();
        }

        app.event(ReactionAddedEvent.class, (event, ctx) -> {
            System.out.println("it works");
            ctx.say("May I help you?");
            return ctx.ack();
        });

        app.command("/hello", (req, ctx) -> {
            ctx.say("What's up?");
           return ctx.ack();
        });
        return app;
    }
}
```

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

![image](https://user-images.githubusercontent.com/81270090/138338723-7639f9c6-7f61-4a2b-a6aa-7b898312b097.png)

#### Java Runtime version

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

#### OS info

Microsoft Windows [Version 10.0.19043.1288]

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

Print "it works" after adding reaction to slack message and not getting error 401

#### Actual result:

After adding reaction to message I am getting error:
```
INFO 11624 --- [essor-worker-35] c.s.a.b.m.b.MultiTeamsAuthorization      : auth.test result: null, io error: null, api error: null
WARN 11624 --- [essor-worker-35] c.s.api.bolt.socket_mode.SocketModeApp   : Unsuccessful Bolt app execution (status: 401, body: {"error":"a request for an unknown workspace detected"})
```

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @adiz50, thanks for writing in! 

According to the logs that you've shared, `MultiTeamsAuthorization` (perhaps, with the default file system based installation service) is used for resolving a token for an incoming request because you passed OAuth related settings for your `App` initialization. You can remove the part `clientSecret("secret").clientId("clientId")` in the code.

I hope this was helpful to you!
