### ISSUE TITLE
Dispatch error while using slash command

### ISSUE THREAD

**Issue by adiz50** [slackapi/java-slack-sdk#885]
I have been working on slack bot made using websocket, I am struggling with an error that shows up when you try to use a command, specifying it is an Dispatch_failed error. I have been testing commands locally using ngrok and after the error shows up it executes the command code but it doesn't work on server. Here is the code I am using to execute commands.

```java
public void startSlackTeamApp(String botToken){
        App app = new App(AppConfig.builder().singleTeamBotToken(botToken).build());

        SocketModeApp socketModeApp;
        try{
            socketModeApp = new SocketModeApp(slackConfig.getAppToken(), app);
            socketModeApp.startAsync();
        }catch(Exception e){
            e.printStackTrace();
        }
        eventListener(app);
    }

    public void eventListener(App app){

        var slack = Slack.getInstance();


        app.command("/addteam", (req, ctx) -> {
            SlashCommandPayload slashCommandPayload = req.getPayload();
            String payload = req.getPayload().getText();
            ArrayList<String> args = new ArrayList<>(Arrays.asList(payload.split(" ")));
            if(EmailValidator.getInstance().isValid(args.get(0))){
                Optional<User> user = userService.getUsersByEmail(args.get(0).strip());
                if(user.isPresent() && user.get().getRole().equals("PM")){
                    Optional<Team> team = teamService.findTeamByTeamNameAndOwnerId(args.get(1),user.get().getId());
                    if(team.isPresent()){
                        team.get().setSlackChannel(req.getPayload().getChannelId());
                        teamService.updateTeam(team.get());
                        Optional<SlackTeamsModel> slackTeamsModel = slackService.getSlackBySlackTeamId(slashCommandPayload.getTeamId());
                        slackTeamsModel.get().setTeamId(team.get().getTeamId());
                        slackService.updateSlackTeam(slackTeamsModel.get());
                        ChatPostMessageResponse response = Slack.getInstance().methods().chatPostMessage(ChatPostMessageRequest.builder()
                                .text("Configuration successful!").token(slackTeamsModel.get().getBotToken()).channel(ctx.getChannelId()).build());
                        if(!response.isOk()) throw new IllegalStateException(response.getError());
                        return ctx.ack();
                    }
                }else{
                    ctx.say("Invalid team name or you are not a PM");
                    return ctx.ack();
                }
            }else{
                ctx.say("Invalid email");
                return ctx.ack();
            }
            return ctx.ack();
        });

    }
}
```

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

![image](https://user-images.githubusercontent.com/81270090/141179220-73171792-ff7c-4be3-8a4a-0fca411c59c6.png)

#### Java Runtime version

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

#### OS info

Microsoft Windows [Version 10.0.19043.1288]

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

Command should be executed without dispatch error

#### Actual result:

I am getting '/addteam failed with the error "dispatch_failed"'

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @adiz50 , thanks for asking the question!

If the situation is caused by a 3-second-timeout error, you can use `app.executorService()` to run some of your code in a different thread. Refer to https://github.com/slackapi/java-slack-sdk/issues/825#issuecomment-906409841 for more details.

If your listener function is never called, you can do the following:
* Enable debug-level logging to see more detailed info
* Make sure if the command name is the same with the one in your code
* Make sure if you do not have other active Socket Mode client processes (see also: https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180)

I hope any of these advices would be helpful to you!

**Comment by adiz50** [comment]
Hi @seratch, thanks for helping. Your response was very helpful now everything works as it should!
