### ISSUE TITLE
Input Block with the plain_text_input type in the modal window is not validating when optional is false, in other words, required

### ISSUE THREAD

**Issue by oleksii-yavtushenko-sp** [slackapi/java-slack-sdk#890]
Input Block with the plain_text_input type in the modal window is not validating when optional is false.
It is not checked whether plain_text_input is empty or not.

### Reproducible in:

Reproducible in any modal window with Input Block with plain_text_input when optional is false.

#### The Slack SDK version
"com.slack.api:bolt-servlet:1.11.0",
"com.slack.api:bolt-socket-mode:1.11.0",
"com.slack.api:bolt:1.11.0",
"com.slack.api:slack-api-client:1.11.0",
"com.slack.api:slack-api-model:1.11.0",
"com.slack.api:slack-app-backend:1.11.0"

#### Java Runtime version

java -version: openjdk version "11.0.9" 2020-10-20

#### OS info

macOS 11.6.1 20G224

#### Steps to reproduce:

1. Create input block with the multiline plain_text_input in the modal window : 
`{
			"type": "input",
			"label": {
				"type": "plain_text",
				"text": "Label text",
				"emoji": true
			},
			"element": {
				"type": "plain_text_input",
				"multiline": true
			},
			"optional": false
		}`

<img width="576" alt="Screenshot 2021-11-15 at 14 07 30" src="https://user-images.githubusercontent.com/89919872/141779512-b28dfea9-12f2-4477-96af-d113f19293d8.png">

2. Submit modal window without typing anything to the plain_text_input.
3. Check the result: it is submitted.

#### Expected result:

It won't be submitted and required error will be shown as on the selector:

<img width="495" alt="Screenshot 2021-11-15 at 14 51 51" src="https://user-images.githubusercontent.com/89919872/141785395-47b82f86-e850-484a-9fef-1de33091704e.png">

#### Actual result:

It is submitted with empty text in it.

### UPDATE:

Finally, I found the root of my problem.
Shortly, this issue is reproducing when the element's optional field became from true to false during interactions with modal window. For example:
1. I have modal window with external select and optional plain_text_input.
<img width="520" alt="Screenshot 2021-11-16 at 18 33 21" src="https://user-images.githubusercontent.com/89919872/142026236-38307a29-8871-419d-a125-bbf8401ec95b.png">
 
 2. When I choose something from the external select, it goes to the blockSuggestion code, where we have some ctx.asyncClient().updateView() logic. In this logic, we are changing plain_text_input optional field to false, so it becomes required.
 
<img width="503" alt="Screenshot 2021-11-16 at 18 35 36" src="https://user-images.githubusercontent.com/89919872/142026641-d1c3c31b-015f-4e52-9e6d-7800a9f27571.png">

3. After it, if I submit this modal window, no validation will be applied.
 
 This is my code snippet: 

```java
app.globalShortcut("test-global-shortcut", (req, ctx) -> {
  ctx.asyncClient().viewsOpen(r -> r
    .triggerId(req.getContext().getTriggerId())
    .view(view(v -> v
      .type("modal")
      .callbackId("test-view")
      .title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
      .close(viewClose(vc -> vc.type("plain_text").text("Close")))
      .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
      .blocks(asBlocks(input(i -> i.blockId("select_block_id")
          .optional(false).label(plainText("Label")).element(externalSelect(s ->
            s.actionId("selects_action_id")))),
        input(input -> input
          .blockId("agenda-block")
          .optional(true)
          .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
          .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
        ))))));
  return ctx.ack();

}).blockSuggestion("selects_action_id", (req, ctx) -> {
  ctx.asyncClient().viewsUpdate(vu -> vu
    .viewId(req.getPayload().getView().getId())
    .hash(req.getPayload().getView().getHash())
    .view((view(v -> v
      .type("modal")
      .callbackId("test-view")
      .title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
      .close(viewClose(vc -> vc.type("plain_text").text("Close")))
      .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
      .blocks(asBlocks(input(i -> i.blockId("select_block_id")
          .optional(false).label(plainText("Label")).element(externalSelect(s ->
            s.actionId("selects_action_id")))),
        input(input -> input
          .blockId("agenda-block")
          .optional(false)
          .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
          .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
        )))))));

  return ctx.ack(c -> c.options(List.of(Option.builder().text(plainText("Option")).value("Option").build()))); }
)
.viewSubmission("test-view", (req, ctx) -> ctx.ack())
```

**Comment by mwbrooks** [comment]
Hi @oleksii-yavtushenko-sp,

Thank you for the detailed issue and steps to reproduce your modal.

I believe this is an issue with `slackapi/java-slack-sdk` because the `optional` property works with `slackapi/bolt-js`:

![image](https://user-images.githubusercontent.com/21328/141866427-320c91ca-f82a-4bc1-a777-3dfaa94384a2.png)

@seratch If you'd like, I can try to reproduce this issue with Bolt Java as well, unless have time available.

**Comment by seratch** [comment]
@mwbrooks I don't think this is a bug. 
@oleksii-yavtushenko-sp Can you try this example? As long as you configure the blocks in a modal, the optional flag should be respected.

```java
package hello;

import com.slack.api.bolt.App;
import com.slack.api.bolt.jetty.SlackAppServer;

import static com.slack.api.model.block.Blocks.asBlocks;
import static com.slack.api.model.block.Blocks.input;
import static com.slack.api.model.block.composition.BlockCompositions.plainText;
import static com.slack.api.model.block.element.BlockElements.plainTextInput;
import static com.slack.api.model.view.Views.*;

public class ModalExampleApp {

  public static void main(String[] args) throws Exception {
    App app = new App();

    app.globalShortcut("test-global-shortcut", (req, ctx) -> {
      ctx.asyncClient().viewsOpen(r -> r
          .triggerId(req.getContext().getTriggerId())
          .view(view(v -> v
              .type("modal")
              .callbackId("test-view")
              .title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
              .close(viewClose(vc -> vc.type("plain_text").text("Close")))
              .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
              .blocks(asBlocks(input(input -> input
                  .blockId("agenda-block")
                  .optional(false)
                  .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
                  .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
              )))
          )));
      return ctx.ack();
    });
    app.viewSubmission("test-view", (req, ctx) -> ctx.ack());

    SlackAppServer server = new SlackAppServer(app);
    server.start(); // http://localhost:3000/slack/events
  }
}
```

**Comment by oleksii-yavtushenko-sp** [comment]
@seratch Thank you for the great example.
Finally, I found the root of my problem.
Shortly, this issue is reproducing when the element's optional field became from true to false during interactions with modal window. For example:
1. I have modal window with external select and optional plain_text_input.
<img width="520" alt="Screenshot 2021-11-16 at 18 33 21" src="https://user-images.githubusercontent.com/89919872/142026236-38307a29-8871-419d-a125-bbf8401ec95b.png">
 
 2. When I choose something from the external select, it goes to the blockSuggestion code, where we have some ctx.asyncClient().updateView() logic. In this logic, we are changing plain_text_input optional field to false, so it becomes required.
 
<img width="503" alt="Screenshot 2021-11-16 at 18 35 36" src="https://user-images.githubusercontent.com/89919872/142026641-d1c3c31b-015f-4e52-9e6d-7800a9f27571.png">

3. After it, if I submit this modal window, no validation will be applied.
 
 This is my code snippet: 
 `app.globalShortcut("test-global-shortcut", (req, ctx) -> {
				ctx.asyncClient().viewsOpen(r -> r
					.triggerId(req.getContext().getTriggerId())
					.view(view(v -> v
						.type("modal")
						.callbackId("test-view")
						.title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
						.close(viewClose(vc -> vc.type("plain_text").text("Close")))
						.submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
						.blocks(asBlocks(input(i -> i.blockId("select_block_id")
								.optional(false).label(plainText("Label")).element(externalSelect(s ->
									s.actionId("selects_action_id")))),
							input(input -> input
								.blockId("agenda-block")
								.optional(true)
								.element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
								.label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
							))))));
				return ctx.ack();
			}).blockSuggestion("selects_action_id", (req, ctx) -> {
				ctx.asyncClient().viewsUpdate(vu -> vu
					.viewId(req.getPayload().getView().getId())
					.hash(req.getPayload().getView().getHash())
					.view((view(v -> v
						.type("modal")
						.callbackId("test-view")
						.title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
						.close(viewClose(vc -> vc.type("plain_text").text("Close")))
						.submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
						.blocks(asBlocks(input(i -> i.blockId("select_block_id")
								.optional(false).label(plainText("Label")).element(externalSelect(s ->
									s.actionId("selects_action_id")))),
							input(input -> input
								.blockId("agenda-block")
								.optional(false)
								.element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
								.label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
							)))))));

				return ctx.ack(c -> c.options(List.of(Option.builder().text(plainText("Option")).value("Option").build()))); }
			)
			.viewSubmission("test-view", (req, ctx) -> ctx.ack())`

**Comment by seratch** [comment]
@oleksii-yavtushenko-sp Thanks for sharing more details! Now I understand what the issue you've faced is.

One thin that I have to say is that performing `views.update` API call in response to a `block_suggestion` request should not be an expected way to manipulate the modal view. Stable Slack client app's behaviors may not be guaranteed if you go with the way. Also, performing the API method many times (every time an end-user sends the search keyword change) may affect the end-user's experience (slow data loading, UI glitches like this).

I would suggest updating the modal in response to a `block_actions` request instead. If your end-user selects an item in your external data source select menu, your app receives the request. Modifying a modal at the timing is a very common practice. It should work for you (if not, we'll escalate the issue to the server-side teams).

I hope this was helpful to you!

**Comment by oleksii-yavtushenko-sp** [comment]
To be honest, I was using on my main app `block_actions` request. But in this example, without any reason, it won't go to this block. Could you please check the same behaviour, but on the `block_actions` request? If it is reproducible, what can you suggest to do in such a case?

**Comment by seratch** [comment]
@oleksii-yavtushenko-sp
I've confirmed the same behavior can arise with block_actions, unfortunately. As a workaround, the only thing I can suggest at this moment is to change block_id / action_id for the affected block. Here is an example app that I used for verifying the behavior:

```java
package hello;

import com.slack.api.app_backend.interactive_components.response.Option;
import com.slack.api.bolt.App;
import com.slack.api.bolt.jetty.SlackAppServer;

import java.util.Arrays;

import static com.slack.api.model.block.Blocks.asBlocks;
import static com.slack.api.model.block.Blocks.input;
import static com.slack.api.model.block.composition.BlockCompositions.plainText;
import static com.slack.api.model.block.element.BlockElements.externalSelect;
import static com.slack.api.model.block.element.BlockElements.plainTextInput;
import static com.slack.api.model.view.Views.*;

public class ModalExampleApp {

  public static void main(String[] args) throws Exception {
    App app = new App();

    app.globalShortcut("test-global-shortcut", (req, ctx) -> {
      ctx.client().viewsOpen(r -> r
        .triggerId(req.getContext().getTriggerId())
        .view(view(v -> v
          .type("modal")
          .callbackId("test-view")
          .title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
          .close(viewClose(vc -> vc.type("plain_text").text("Close")))
          .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
          .blocks(asBlocks(
            input(i -> i
              .blockId("select_block_id")
              .optional(true)
              .dispatchAction(true)
              .label(plainText("Label"))
              .element(externalSelect(s -> s.actionId("selects_action_id"))
            )),
            input(input -> input
              .blockId("agenda-block")
              .optional(true) // optional
              .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
              .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
            ))
          )
        )));
      return ctx.ack();

    });

    app.blockSuggestion("selects_action_id", (req, ctx) -> ctx.ack(c -> c.options(Arrays.asList(
        Option.builder().text(plainText("Customer")).value("customer").build(),
        Option.builder().text(plainText("Partner")).value("partner").build()
    ))));

    app.blockAction("selects_action_id", (req, ctx) -> {
      ctx.client().viewsUpdate(vu -> vu
        .viewId(req.getPayload().getView().getId())
        .hash(req.getPayload().getView().getHash())
        .view((view(v -> v
          .type("modal")
          .callbackId("test-view")
          .title(viewTitle(vt -> vt.type("plain_text").text("Modal by Global Shortcut")))
          .close(viewClose(vc -> vc.type("plain_text").text("Close")))
          .submit(viewSubmit(vs -> vs.type("plain_text").text("Submit")))
          .blocks(asBlocks(
            input(i -> i.blockId("select_block_id")
              .optional(true)
              .dispatchAction(true)
              .label(plainText("Label"))
              .element(externalSelect(s -> s.actionId("selects_action_id"))
            )),
            input(input -> input
              // As a workaround, change block_id or action_id
              .blockId("agenda-block___")
              .optional(false) // required
              .element(plainTextInput(pti -> pti.actionId("agenda-action").multiline(true)))
              .label(plainText(pt -> pt.text("Detailed Agenda").emoji(true)))
            ))
          ))
        )));
      return ctx.ack();
    });

    app.viewSubmission("test-view", (req, ctx) -> ctx.ack());

    SlackAppServer server = new SlackAppServer(app);
    server.start();
  }
}
```

We're sorry about the unexpected behavior of the platform. I hope this workaround works for you.

**Comment by oleksii-yavtushenko-sp** [comment]
@seratch Thank you for this workaround! This helped me in resolving my issue.
