### ISSUE TITLE
Is bolt-micronaut compatible with Micronaut 3.x?

### ISSUE THREAD

**Issue by volgin** [slackapi/java-slack-sdk#891]
I am trying bolt-micronaut, but I keep getting 400 (Bad Request) errors. I took a quick look at the source code - I don't see anything that should break from Micronaut 2.4 to 3.2, but maybe I am missing something.

**Comment by seratch** [comment]
Hi @volgin, thanks for writing in!

The bolt-micronaut package does not support Micronaut 3.x yet: https://github.com/slackapi/java-slack-sdk/blob/v1.14.0/bolt-micronaut/pom.xml#L13-L15 

We'll update the module to be compatible with 3.x in the future, but it may take at least a few weeks (possibly a few months). 

If you need an immediate solution for it, please consider modifying the module in your app. The module consists of only two source files and they are fairly simple ones: https://github.com/slackapi/java-slack-sdk/tree/v1.14.0/bolt-micronaut/src/main/java/com/slack/api/bolt/micronaut

**Comment by volgin** [comment]
Which is the best dependency to use then instead of bolt-micronaut?

**Comment by seratch** [comment]
Do you mean you're fine with not using Micronaut? If so, many developers tend to choose Spring Boot for Bolt app development. If you are fine with the framework, the only necessary optional dependency is `bolt-servlet`. 

Refer to the following resources:

* https://slack.dev/java-slack-sdk/guides/supported-web-frameworks#spring-boot
* https://github.com/slackapi/java-slack-sdk/blob/v1.14.0/bolt-spring-boot-examples/pom.xml#L21-L30

I hope this helps!

**Comment by volgin** [comment]
@seratch I just copied these 2 files directly into my Micronaut project, and everything worked. The only change was replacing `@Inject` and `@Singleton` annotations with Jakarta. I am still working on the complete code, but it looks like migrating bolt-micronaut should take very little effort.

Cheers and thank you for great work and quick responses!

**Comment by seratch** [comment]
@volgin Thanks for the info! I just submitted a PR that resolves the issue here: https://github.com/slackapi/java-slack-sdk/pull/903
