### ISSUE TITLE
How is bolt-aws-lambda logging configured to work with Lambda's logger?

### ISSUE THREAD

**Issue by andyRokit** [slackapi/java-slack-sdk#908]
I created a very simple Hello World for `bolt-aws-lambda`:

```
public PingApp(App app) {
  super(app);

  app.service(new AmazonS3InstallationService("pingapp-state-bucket"));

  app.event(MessageEvent.class, (req, ctx) -> {
    ctx.logger.info("I've been pinged");
    return ctx.ack();
  });
}
```

```
<dependencies>
  <dependency>
    <groupId>com.slack.api</groupId>
    <artifactId>bolt-aws-lambda</artifactId>
    <version>1.6.1</version>
  </dependency>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
    <version>1.12.129</version>
  </dependency>
<dependencies>
```

However, triggering it resulted in the following CloudWatch logs:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I was able to overcome the issue by implementing the following workaround:  https://stackoverflow.com/a/46494684/4432463

However, this doesn't strike me as the "right" solution.  I looked through the `bolt-aws-lambda` source code, but couldn't spot anything obvious which would connect the `slf4j` output to Lambda's log appender.  Have I missed something?

**Comment by seratch** [comment]
Hi @andyRokit, please follow their document for logging: https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html

**Comment by andyRokit** [comment]
It looks like the stackoverflow answer I referenced was based on the `Advanced logging with Log4j 2 and SLF4J` section of that page.  When I implement it I can see all the logging coming through from `com.slack.api.bolt`.

I guess my question is, how come that's left to the user of `bolt-aws-lambda`?  Can the `bolt-aws-lambda` project itself not wire up the bolt logging to the Lambda appender?

I'll go with the approach for now, but if you agree that it's probably something `bolt-aws-lambda` should handle, I might have a go at creating a PR once I become more familiar with the SDK.

**Comment by seratch** [comment]
The internals of the Bolt framework uses an slf4j logger. Also, the default logger that you can use in listener functions is the same. For this reason, regardless of the slf4j bridge solutions, you need to have some way to use an slf4j logger in AWS Lambda functions. For this reason, I would recommend following AWS's recommendation on slf4j in their document.

If you find something that this SDK can do for developers in the future, please let us know then. We are happy to have an example and/or enhance the bolt-aws-lambda module as necessary.

**Comment by andyRokit** [comment]
I guess for really simple "Hello world" Lambdas I'd use the LambdaLogger (rather than utilise a logging framework or take the morally questionable approach of `System.out`!).

So the overhead of having to hook up slf4j comes from `bolt-aws-lambda`.  If I was just using Slack's SDK directly (i.e. not the Lambda specific version), I'd agree that this would be a reasonable thing to do.  But having to do it from a library designed to be used with Lambda makes it seem a bit boilerplate.

I'll close off this question (as I have a solution and appreciate the reasoning) and if I see the opportunity to introduce an inbuilt bridge into `bolt-aws-lambda` I'll either raise it as a feature request or a pull request.

Thanks!
