### ISSUE TITLE
Howto get UserId in global middleware

### ISSUE THREAD

**Issue by TheManWhoStaresAtCode** [slackapi/java-slack-sdk#909]
I'm trying to write a global middleware, that should extract the userId of the request (if there is any) and otherwise ignore the request. The ultimate goal is to call the userInfo endpoint and provide some additional user information to all listeners.

For most request types (at least the ones I'm interested in) I can simply call the type specific payload function and then obtain the user and its id:
```
fun Request<*>.extractSlackUserId(): String? =
    when (this) {
        is SlashCommandRequest -> payload.userId
//        is EventRequest -> how to get the userId here?
        is AttachmentActionRequest -> payload.user.id
        is BlockActionRequest -> payload.user.id
        is BlockSuggestionRequest -> payload.user.id
        is GlobalShortcutRequest -> payload.user.id
        is MessageShortcutRequest -> payload.user.id
        is ViewClosedRequest -> payload.user.id
        is ViewSubmissionRequest -> payload.user.id
        else -> null
    }
```
However, I cannot find any way to extract the userId from an EventRequest - can you provide me with guidance how to extract the userId in that case? Please note, that all events where the userId is not part of the payload can be ignored by my middleware.

Furthermore, I was wondering if this is really code I as framework user should write or whether this is something which should be part of the framework as it might be handy for others as well. What are you thoughts about this?

**Comment by seratch** [comment]
Hi @TheManWhoStaresAtCode, thanks for asking the question!

For others except the Events API patterns, you can use `req.getContext().getRequestUserId()` (`req.context.requestUserId` in Kotlin) to know the user's ID that is associated with a request.

```java
app.use((req, resp, chain) -> {
  String userId = req.getContext().getRequestUserId();
  return chain.next(req);
});
```

However, in the case of Events API, unfortunately, how to access a user's ID can vary among the events. It can be `$.event.user`, `$.event.user.id`, `$.authorizations[0].user_id`, and so on. Moreover, in some events, the user ID that you are interested can be named differently such as `actor_id` and `inviter`. This is why the context object for Events API does not have requestUserId property. 

I would recommend writing your own extractor method to know the relevant user IDs for your event handing.

I hope this helps.

**Comment by seratch** [comment]
Let us close this issue due to inactivity but please feel free to write in if you have any follow ups!

**Comment by nicolasrueegg** [comment]
Hi @seratch , if I understand your response correctly, `Context.getRequestUserId()` usually returns `null` when the `Context` object is an `EventContext`. For `Context` objects of other types (e.g., `ActionContext`), `getRequestUserId()` returns the user ID associated with the request. Is there any particular reason why this is not the case with `EventContext.getRequestUserId()`?

**Comment by seratch** [comment]
@nicolasrueegg As I mentioned in my last comment as below, 
> how to access a user's ID can vary among the events.

there is no single simple way to determine user ID associated with an Events API request. Also, some of events really do not have user ID as part of the events. An easy-to-understand example would be [`app_uninstalled`](https://api.slack.com/events/app_uninstalled) event.

We can add some better supports for commonly used events such as message events but it's not applicable to all for the above reason.

As this issue is already closed, if you have follow up questions, please feel free to create a new question issue.

**Comment by nicolasrueegg** [comment]
Okay, so it's the Events API itself that sometimes doesn't contain the user ID (or at least not always in the same place). Not being able to access it from `EventContext.getRequestUserId()` is merely a consequence of that. Thanks for explaining!
