### ISSUE TITLE
user-scope only OAuth does not work since v1.10

### ISSUE THREAD

**Issue by loc02998375** [slackapi/java-slack-sdk#913]
`App::buildAuthorizeUrl` previously returned a correct URL with `config.getScope() == null`. A new condition causes the method to return null when scopes are missing (`(!config.isOpenIDConnectEnabled() && config.getScope() == null)`). 

I tried to create a URL manually with only user scopes and the installation goes through successfully, indicating that the scopes are not required.

#### The Slack SDK version

1.16.0

#### Steps to reproduce:

Create app config without scopes.

#### Expected result:

Auth url returned correctly.

#### Actual result:

null is returned with error: "App#buildAuthorizeUrl(String) returned null due to some missing settings"

**Comment by seratch** [comment]
Hi @loc02998375, thanks for taking the time to report this issue. You're right that this is a bug affecting your use case. We'll fix the issue in the next patch release.
