### ISSUE TITLE
Fails to spin up a Bolt app due to a proxy connection issue

### ISSUE THREAD

**Issue by ashishbende3** [slackapi/java-slack-sdk#927]
While attempting to follow the instructions mentioned on [getting started with bolt guide](https://slack.dev/java-slack-sdk/guides/getting-started-with-bolt ), I got /hello failed with the error "operation_timeout" error. 

It is similar to issue #485, and the recommendation was to use only SLACK_BOT_TOKEN and SLACK_SIGNING_SECRET tokens. However, if I don't provide clientId and clientSecret additionally, the SlackAppServer won't start (`[main] INFO com.slack.api.bolt.jetty.SlackAppServer - ⚡️ Bolt app is running!`). But providing clientId/clientSecret in turn needs Oauth handling.

The behavior is same irrespective of using environment variables or AppConfig approach. Also if I run the app without any token configuration (either via AppConfig or environment variables), the server is starting okay but request url verification fails and slack command fails with the dispatch error (`/hello failed with the error "dispatch_failed"`).

#### The Slack SDK version

com.slack.api:bolt-jetty:1.18.0

#### Java Runtime version

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

#### OS info

Oracle Linux 7 (4.1.12-124.49.3.1.el7uek.x86_64)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.Install the app with a /hello slash command handler
2. Serve MyApp with the code you proposed in your example (replacing your example slash command name with "/hello")
3.Use ngrok to expose local environment to Slack app
4.Configure Slack app to use ngrok URL
5.Run app with env vars for the creds specified in the Slack app's admin pages

#### Expected result:
SlackAppServer is running and can perform request-url verification and slack command operations.

Sample output when clientId, clientSecret, bot-token and signing keys are provided : 

```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1666ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 1.8.0_171-b11
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@29176cc1{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@6c3f5566{HTTP/1.1, (http/1.1)}{0.0.0.0:8000}
[main] INFO org.eclipse.jetty.server.Server - Started @1895ms
[main] INFO com.slack.api.bolt.jetty.SlackAppServer - ⚡️ Bolt app is running!

```
Sample output when no tokens are configured  : 
```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1211ms to org.eclipse.jetty.util.log.Slf4jLog
[main] WARN com.slack.api.bolt.App - Skipped adding any authorization middleware - you need to call `app.use(new YourOwnMultiTeamsAuthorization())`
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 1.8.0_171-b11
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2928854b{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@6c3f5566{HTTP/1.1, (http/1.1)}{0.0.0.0:8000}
[main] INFO org.eclipse.jetty.server.Server - Started @1440ms
[main] INFO com.slack.api.bolt.jetty.SlackAppServer - ⚡️ Bolt app is running!
```

#### Actual result:

Nothing gets logged after
```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1672ms to org.eclipse.jetty.util.log.Slf4jLog
```
Couldn't perform request url verification or slash command handling.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @ashishbende3, thanks for asking the question!

As you already mentioned, with OAuth related settings, your `App` excepts there is a working `InstallationService` in your `App` instance.

>Sample output when clientId, clientSecret, bot-token and signing keys are provided :

So, if I understand correctly, you'd like to run your app with a single bot token, not with the OAuth flow enabled settings, right? 

If that's the case, please remove the clientId and clientSecret. You can remove them from the default name env variables by running `unset SLACK_CLIENT_ID` and `unset SLACK_CLIENT_SECRET` in the terminal session. Also, an alternative way to force single workspace mode would be calling `App#asOAuthApp(false)` in your code.

I hope this helps.

**Comment by ashishbende3** [comment]
Hi @seratch, thank you so much for the quick response! Yes, that is correct. I want to run my app with the singleTeamBotToken and SigningSecrete alone. But unless I provide clientSecret and clientId additionally, the SlackAppServer won't start (where we usually see 'INFO com.slack.api.bolt.jetty.SlackAppServer - ⚡️ Bolt app is running!' in the log). 

The app is running behind a proxy with ngrok tunnel. By setting clientSecret/clientId I was able to verify the event API request url. Also, as you have suggested, I tried disabling OAuth app setting in the code, but slash command still failed with the timeout error (Applying a middleware (name: com.slack.api.bolt.middleware.builtin.MultiTeamsAuthorization)).

If I have only the SigningSecrete and singleTeamBotToken tokens, I see following line in the log but no indication on Server starting - 
[main] INFO org.eclipse.jetty.util.log - Logging initialized @1483ms to org.eclipse.jetty.util.log.Slf4jLog

**Comment by seratch** [comment]
@ashishbende3 
> Is it possible (and okay) to disable it? or what/how can I configure authentication endpoint with the proxy?

There is a way to disable the API call but it cannot be a solution for this. After the initialization step, your app has to perform the API calls many times.

You can tell the underlying API clients (the Slack instance) your proxy URL this way:
```java
AppConfig appConfig = new AppConfig();
appConfig.setSingleTeamBotToken(System.getenv("SLACK_BOT_TOKEN"));
appConfig.setSigningSecret(System.getenv("SLACK_SIGNING_SECRET"));
appConfig.getSlack().getConfig().setProxyUrl("http://proxy-host:999/");
App app = new App(appConfig);
```

**Comment by seratch** [comment]
I'm sure that we've provided an answer to your question here. Let us close this issue now but, if you have any follow ups, please feel free to write in!

**Comment by WorkingAngel** [comment]
@seratch I faced similar issue as this post, I already setup my proxy server, but it still failed with network unreachable issue.

`[main] INFO org.eclipse.jetty.util.log - Logging initialized @537ms to org.eclipse.jetty.util.log.Slf4jLog
[java.net.SocketException: Network is unreachable (connect failed), java.net.SocketException: Network is unreachable (connect failed)]
[main] ERROR com.slack.api.methods.impl.TeamIdCache - Failed to call auth.test API (error: Network is unreachable (connect failed))
`

here is my snipped code of server start, may I know how can I setup in code to solve this issue?


        AppConfig conf = new AppConfig();
        conf.setSigningSecret(SLACK_SIGNING_SECRET);
        conf.setSingleTeamBotToken(SLACK_BOT_TOKEN);

        conf.getSlack().getConfig().setProxyUrl(System.getenv("http_proxy"));

        System.out.println(conf.getSlack().getConfig().getProxyUrl());
        System.out.println(conf.getSigningSecret());
        System.out.println(conf.getSingleTeamBotToken());

        App app = new App(conf);

        app.command("/hello", (req, ctx) -> {
            return ctx.ack(":wave: Hello!");
        });

        SlackAppServer server = new SlackAppServer(app, 8888);
        server.start(); // http://localhost:3000/slack/events
