### ISSUE TITLE
NoClassDefFoundError: com.slack.api.util.http.listener.DetailedLoggingListener when calling Slack.getInstance()

### ISSUE THREAD

**Issue by uucp-io** [slackapi/java-slack-sdk#928]
Seems like the same as (unresolved) issue #173.

I suspect a newbie mistake/misconfiguration, but I can't figure it out with my experience level.

#### The Slack SDK version

1.18.0

#### Java Runtime version

Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 18, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)

#### OS info

ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64

#### Steps to reproduce:

Working from: https://github.com/slackapi/java-slack-sdk#slack-api-client

1. Added example code to project.
2. Compile (works!)
3. Run (throws exception)

#### Expected result:

Return a slack connection.

#### Actual result:

```
    java.lang.NoClassDefFoundError: com.slack.api.util.http.listener.DetailedLoggingListener
        at com.slack.api.SlackConfig.<init>(SlackConfig.java:135)
        at com.slack.api.SlackConfig$1.<init>(SlackConfig.java:32)
        at com.slack.api.SlackConfig.<clinit>(SlackConfig.java:32)
        at com.slack.api.Slack.<clinit>(Slack.java:65)
```

**Comment by seratch** [comment]
Hi @uucp-io, thanks for writing in!

I am not sure why the situation can arise on your end. The `DetailedLoggingListener` class should exist in the same jar file. I cannot think of the cause of the binary-compatibility error that you're observing.

I'm not an Android app expert at all but Android Studio should have the similar view for external dependencies. Can you find both classes `Slack` and `DetailedLoggingListener` in the list? They should exist in `com.slack.api:slack-api-client` package.

<img width="300" src="https://user-images.githubusercontent.com/19658/152248277-d4cb17dd-7d8a-4b81-849d-428425792e1e.png">

Another speculation that came to my mind is some class loader issue in your Android app but I don't have any suggestions based on the guess.

I hope you'll figure the cause out soon!

**Comment by uucp-io** [comment]
When I inspect the generated .apk package, I can locate the `DetailedLoggingListener` class in the `classes.dex` file.  There are byte totals for each of the four member functions, so this leads me to believe that the library data is present.

I tried creating an entirely new project with the only line of code being `Slack slack = Slack.getInstance();`, but sadly, even this fails with the above error.

I tried deleting all of the slack files from gradle, forcing it to download them afresh.  This didn't make any difference.

**Comment by uucp-io** [comment]
I've solved the issue.  It turns out that Java 8 is incompatible with Android SDK 22 (Lollipop, aka. Android 5.0), which is unfortunately what Android Studio suggests when creating a new project (for maximum compatibility).  See https://forums.zeroc.com/discussion/46658/noclassdeffounderror-android-studio

For new projects, make sure to build for SDK version 24 (Nougat, aka. Andorid 7.0).

For existing projects you can change this by editing `build.gradle (:app)` and changing the `minSdk` or `minSdkVersion` (different names for the same thing), for example: 
```
android {
    ...

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 24
    ...
```

You will also need to update your emulator so it's running Nougat as well.

I suppose another option would be to downgrade Java, but I didn't try that.
