### ISSUE TITLE
100% CPU usage when working with a high number of workspaces

### ISSUE THREAD

**Issue by sidneyamani** [slackapi/java-slack-sdk#933]
We noticed a flaw in the Java SDK. When interacting with a large number of workspaces, the rate-limiting algorithm consume 100% CPU. After profiling our server we noticed that 96% of the CPU is spent on `BaseMemoryMetricsDataStore$MaintenanceJob.run()`. Particularly the methods `updateCurrentQueueSize` and `updateNumberOfLastMinuteRequests`. I believe this is because our app deals with a large number of workspaces (~8,000) and the maintenance job runs every [50ms](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java#L45).

As a temporary solution, we are considering turning off stats on `MethodConfig`.

Any other suggestion to mitigate/fix the issue? 

#### The Slack SDK version

1.18.0

#### Java Runtime version

(Paste the output of `java -version`)

#### OS info

Linux

#### Steps to reproduce:

Create an app that unfurl links from ~8,000 workspaces.

#### Expected result:

Reasonable CPU usage.

#### Actual result:

100% CPU usage after running for 16h.
The CPU usage progressively increases until the server restarts.

**Comment by seratch** [comment]
Hi @sidneyamani, thanks for writing in! Also, being installed into 8K workspaces is quite fantastic 👏 

>As a temporary solution, we are considering turning off stats on MethodConfig.

Yes, you're right. Changing the option should mitigate the issue for you. The downside is that, if your app relies on the smart rate limiter that MethodsClient offers, your app may start having rate-limited errors for heavily used Web API endpoints (especially Tier 1 and Tier 2 ones).

>Any other suggestion to mitigate/fix the issue?

This should be definitely improved on this SDK side. I'm thinking of adding a few more options to customize/optimize the behavior to cover your great use case. Let me share a few points in my mind right now:

* For managing a large-scale metrics data, we recommend [the Redis backend implementation](https://github.com/slackapi/java-slack-sdk/blob/v1.18.0/slack-api-client/src/main/java/com/slack/api/scim/metrics/RedisMetricsDatastore.java). However, the one also has the same issue as of v1.18. We will add a new option to enable developers to run the metrics data maintenance job in an offline host, which does not handle incoming requests from Slack. This should be available for the use cases like yours.
* If `statsEnabled` is false (like your workaround), the background `cleanerExecutor` job should be disabled too. We may want to have a kind of `NoopMetricsDatastore` for the use case.

Let us know if you have any other suggestions or comments. If everything goes well, we will come up with pull requests for improvements and ship a new version by the end of this week. I hope this timeline works for you.

**Comment by sidneyamani** [comment]
Hey Kazuhiro,

Thanks your quick reply. 

> We will add a new option to enable developers to run the metrics data maintenance job in an offline host, which does not handle incoming requests from Slack. This approach needs be available for the use cases like yours.

We should be able to setup an offline host to achieve run the maintenance job. However, I'm afraid that running that task every 50ms may lead  lead to a similar outcome.

> Let us know if you have any other suggestions or comments.

I don't understand the role of the maintenance job enough to suggest anything with confidence. 
There a few things I find surprising though:
1. The 50ms interval seems short and arbitrary. Is there a reason the job needs to be run so frequently? Would making the interval configurable make sense?
2. Every maintenance job run goes through all the known (workspace, method-name) pairs that may have had a requests and update their number of requests and current queue size.  Could we instead maintain a set of (workspaces, methods-name) pairs for which a request was seen since the last maintenance job run and only process these? 

>  If everything goes well, we will come up with pull requests for improvements and ship a new version by the end of this week. I hope this timeline works for you.

Thanks so much for being so responsive.

**Comment by seratch** [comment]
@sidneyamani Thanks for your quick reply.

>The 50ms interval seems short and arbitrary. Is there a reason the job needs to be run so frequently? Would making the interval configurable make sense?

Yes, this is so true. I forgot to mention this in my last reply but I'm planning to revisit the internal and also make it configurable. Just to share the context, the reason why I chose the extremely short period for this is to support all the tiers even including the chat.postMessage special tier. That being said, the 50ms was just decided by my testing results with a small number of installations, without a great consideration for scalability.

>Every maintenance job run goes through all the known (workspace, method-name) pairs that may have had a requests and update their number of requests and current queue size. Could we instead maintain a set of (workspaces, methods-name) pairs for which a request was seen since the last maintenance job run and only process these?

This is also a great suggestion! I'll add this optimization as well.

Thanks for these great inputs!

**Comment by seratch** [comment]
Thanks for being patient about this issue. I just submitted a pull request eliminating this issue #934 . 

While reviewing the current implementation again, I concluded that we don't need to run the background maintenance thread every 50 milliseconds at all. I've changed the default interval from 50 to 1,000 milliseconds in the PR. Also, I've improved the logic to skip the team IDs that don't have any updates since the previous maintenance execution (thanks for the suggestion!).

With these changes, the CPU usage issue here should be completely resolved (or at least significantly improved) even with the default settings. If a developer would like to adjust the interval / prefers the previous behavior, now it's also possible to set their own custom values to metrics datastore in constructor. 

I haven't observed any critical downside by the change so far. The only impact should be that the rate limiter can be slightly modest about API execution in a burst-traffic situation. 

@sidneyamani 
I just published the latest revision including the changes in the PR as 1.19.0-SNAPSHOT: https://oss.sonatype.org/content/repositories/snapshots/com/slack/api/slack-api-client/1.19.0-SNAPSHOT/
If you have a chance to try it out, your feedback would be greatly appreciated. Either way, we are going to release v1.19.0 including the fix within two business days.

**Comment by sidneyamani** [comment]
Thanks so much for fixing the issue. 

FYI, we noticed that disabling stats doesn't make much of a difference (with version 1.18.0). The CPU usage still increases linearly as the number of workspaces goes up.

We are looking forward to trying the new SDK (1.19.0). Unfortunately, given our release process we won't have time to test the new SDK before its release, but I'll definitely give you an update once we have 1.19.0 running on our production environment.

**Comment by seratch** [comment]
@sidneyamani 
>FYI, we noticed that disabling stats doesn't make much of a difference (with version 1.18.0). The CPU usage still increases linearly as the number of workspaces goes up.

Thanks for sharing this. I will look into the logic more to identify the reason of this. 

By the way, does your app use only MethodsClient? Aren't SCIMClient and AuditClient used?

**Comment by seratch** [comment]
Hi @sidneyamani, I've merged the PR #934 and released a new version - v1.19.0 onto the Maven Central repository.

I hope the version works very well for your app. Also, if the default configuration isn't great enough for you, you can adjust the behavior by:
* Set `rateLimiterBackgroundJobIntervalMillis` to a longer value than 1,000 milliseconds (the default)
* `statsEnabled: false` to either `SlackConfig` or `MethodsConfig` etc. 
Refer to the release note for more details. https://github.com/slackapi/java-slack-sdk/releases/tag/v1.19.0

The first one won't cause any big problem. The only downside would be the rate limiter in this SDK can be more conservative on the intervals between the same API calls. As for the second one, with this way, your app will be responsible for handling rate-limited error patterns.

Thanks again for reporting this issue. I hope the fix I applied this time helps.

**Comment by sidneyamani** [comment]
Hey Kazuhiro, 

Thanks so much for the fix. We've been running it in production for a week and the CPU is sitting around 10% now. The CPU still increases linearly but the slope is a lot gentler. We haven't reenabled stats yet though. I'll let you know if reenabling stats causes leads to any unexpected behaviour.
