### ISSUE TITLE
Update a message by adding a PDF file to it

### ISSUE THREAD

**Issue by robertt240** [slackapi/java-slack-sdk#942]
I am trying to update a message by adding a PDF file to it, but I cannot achieve it. 

Is this even possible to do? 
If yes, please tell what I am doing wrong. 

My code:
```
methodsClient.chatUpdate(ChatUpdateRequest.builder()
                .token(apiToken)
                .channel(originalMessage.getChannel())
                .ts(originalMessage.getTs())
                .text(message)
                .build()));
methodsClient.filesUpload(FilesUploadRequest.builder()
                .token(apiToken)
                .filetype("pdf")
                .filename("test.pdf")
                .fileData(bytes)
                .channels(List.of(originalMessage.getChannel()))
                .build();
```

The result of this code is that the file is uploaded in separate message instead of being added to the original message.

Best I can do is to provide `threadTs` to `FileUploadRequest`, then the file is added as separate message but in a thread reply to the main message. 

I've also tried to first upload a file without specyifying a channel and then updating the message by adding a file attachment, but this did nothing -> file didn't show as an attachment or a message:
```
var uploadResponse = methodsClient.filesUpload(FilesUploadRequest.builder()
                .token(apiToken)
                .filetype("pdf")
                .filename("test.pdf")
                .fileData(bytes)
                .build();
methodsClient.chatUpdate(ChatUpdateRequest.builder()
                .token(apiToken)
                .channel(originalMessage.getChannel())
                .ts(originalMessage.getTs())
                .attachments(List.of(Attachment.builder().files(List..of(uploadResponse.getFile)))
                .text(message)
                .build()));

```

#### The Slack SDK version

1.20.0

#### Java Runtime version

Java 17

#### OS info

Windows 11

**Comment by filmaj** [comment]
I'm removing the "stale" status of this ticket, and noting that our internal team responsible for this particular backend API is aware of the issue and it has been triaged, but no progress has been made thus far. For other Slack folks dealing with this issue in the future, the internal ticket identifier is MSG-27596.

In the mean time, my last comment stands: if you create a message with a file attached to it, you can update its file(s) using `chat.update` to your heart's content. The bug is that a message created with no file originally attached will not be updated with any new files attached to it via the `chat.update` API.

**Comment by MattB543** [comment]
Hey @filmaj any update on this?

You said
> if you create a message with a file attached to it, you can update its file(s) using chat.update to your heart's content

But is there a way to send a message w/ a file attached to it?

It seems like messages and files are always separate entities. I can upload a file by itself into a channel and then update that file w/ a new file ID by using chat.update but I can't seem to send a message with blocks + a file.

Any ideas?
