### ISSUE TITLE
@ServletComponentScan in Spring Boot app does not respect custom ServletContextListener

### ISSUE THREAD

**Issue by ManuelG28** [slackapi/java-slack-sdk#947]
#### The Slack SDK version

```
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0 (n)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
```

#### Java Runtime version

openjdk version "15.0.2" 2021-01-19

#### OS info

ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

#### Steps to reproduce:

I'm trying to make a bot that will be connected to a DataBase in GCP. The connection is set up through a private IP. For this reason I'm Implementing this class:

```java
@WebListener("Creates a connection pool that is stored in the Servlet's context for later use.")
public class ConnectionPoolContextListener implements ServletContextListener {
```

But I'm getting the following error when the application is trying to connect to that database. `java.sql.SQLNonTransientConnectionException: Cannot connect to MySQL server on localhost:3,306.
Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.`

The curious part of this error is if I don't use the `@ServletComponentScan` in my main class SlackBotApplication. (as the documentation suggest it) it won't fail. It will connect to my database but the slack endpoint won't be load. 

I know that this issue is not 100% related to slack but I've been spending two days trying to solve it, I check my database, my credentials and everything is fine, on the past I connected a database with a spring boot application using that code and everything is fine, the only difference is that I didn't use bolt and `@ServletComponentScan` annotation.

**Comment by filmaj** [comment]
Hey @ManuelG28 , sorry you're having this issue. As you said, this isn't directly related to Slack code, so it is difficult for me to help you. However, one thing I did notice in the error message is there seems to be a comma (`,`) in the port of the database URL (`localhost:3,306`). Usually, port 3306 is the default MySQL port. Do you perhaps have the port misconfigured and accidentally entered a comma in it?

**Comment by ManuelG28** [comment]
@filmaj The first time that I read that issue I thought that could be a wrong credential or something like that because of the `,`.  But isn't this case, some people have the same log when they have that error trying to connect to a SQL database in GCP. 

Is there any way to get all of the /slack/events request without needing to use the `@ServletComponentScan` annotation? As I told you before, if I delete that annotation, it will connect to the database but the events won't be captured by slack.

**Comment by filmaj** [comment]
Interesting... not really sure why that could be the case, but perhaps if our Java expert @seratch sees these, he can provide better guidance than I have so far.

As for how to see all the `/slack/events` requests incoming, I think you can override the `SlackAppServlet` `doPost` method to see all incoming requests. You can see the source for the `doPost` method directly [in the `SlackAppServlet` implementation](https://github.com/slackapi/java-slack-sdk/blob/main/bolt-servlet/src/main/java/com/slack/api/bolt/servlet/SlackAppServlet.java#L31-L46). I think you can override this method with your own implementation. Perhaps there is also an easier way - I'm sorry, I do not yet have full familiarity with the Java codebase; I hope @seratch can chime in to provide better guidance 😞

**Comment by seratch** [comment]
Hi @ManuelG28, thanks for writing in!

As already discussed in the issue you submitted at Google Cloud team's repository above, I also think that this is something unexpected caused by Spring Boot's `@ServletComponentScan` annotation.

I haven't checked if this works yet but can you try adding a dedicated package for your Slack app web controllers (say, `servlets.slack`) plus passing the package name to the annotation `@ServletComponentScan("servlets.slack")`? If this works for your use case, I will update our document to encourage developers to specify base package to scan.

**Comment by ManuelG28** [comment]
@seratch You are the GOAT!. Moving the SlackAppController to a different package and specifying it in the `ServletComponentScan` fixed the issue.

Indeed, would be nice to clarify this point in the documentation, even if my stack is kind of different some people could have this difficult issue.

**Comment by seratch** [comment]
Thanks for confirming! I've updated the document: https://github.com/slackapi/java-slack-sdk/commit/f1e459d30022fd3e78c9975a24da72087d4c9bf1
