### ISSUE TITLE
How to Get URL after ChatPostMessageResponse from postMessage()

### ISSUE THREAD

**Issue by thegracelu** [slackapi/java-slack-sdk#949]
I have something like this
```
Result<ChatPostMessageResponse, SlackError> postMessageResponse = slackClient
        .postMessage(chatPostMessageParams)
        .get();
```
Where it posts the message to a slack channel. But I want to get the URL of the posted message so I can use it for something else. How do I do that? 

#### Java Runtime version

11.0.12

#### OS info

ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

**Comment by seratch** [comment]
Perhaps, you've already found this but you can use https://api.slack.com/methods/chat.getPermalink for it
