### ISSUE TITLE
My bot isn't sending messages if is in cloud

### ISSUE THREAD

**Issue by ManuelG28** [slackapi/java-slack-sdk#950]
Hello ✋🏻  it's me again! 
Currently, my slack app works in a local environment. I used to test it with ngrok and everything works fine, slash commands, mention events, and interactivity with text blocks. 

When I deployed my app in GCP, only slash commands and interactivity with text blocks worked properly. 
![image](https://user-images.githubusercontent.com/36460775/157257781-fcef0bde-e390-4f4d-95da-53c492dd07f6.png)
Mention events made a request and it received a POST 200 but my bot is not sending the message. 
I also tried to send the message as ephemeral but it didn't send the message.
### Reproducible in:

+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0 (n)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
+--- com.slack.api:bolt-servlet:1.18.0
|    +--- com.slack.api:slack-api-model:1.18.0
|    +--- com.slack.api:slack-api-client:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    +--- com.slack.api:slack-app-backend:1.18.0
|    |    +--- com.slack.api:slack-api-model:1.18.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.18.0 (*)
|    \--- com.slack.api:bolt:1.18.0
|         +--- com.slack.api:slack-api-model:1.18.0 (*)
|         +--- com.slack.api:slack-api-client:1.18.0 (*)
|         \--- com.slack.api:slack-app-backend:1.18.0 (*)
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49

#### The Slack SDK version

implementation 'com.slack.api:bolt-servlet:1.18.0'

implementation 'com.slack.api:bolt-servlet:1.18.0'

#### Java Runtime version

openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

#### OS info

Cloud run on GCP

#### Steps to reproduce:

1. Deploy my slack bolt app in Cloud Run
2. Change my endpoints in slash commands, events and interactivity & shortcuts
3. Test my app, slash commands and interactivity works properly. App Mention doesn't send my message.

#### Expected result:

App mention sends messages and ephemerals.

**Comment by filmaj** [comment]
Hi @ManuelG28 

Can you share any code in your app? It would be helpful to see how your shortcut handlers, which are running properly, are written and compare it to how your mention handlers are written to try to figure out what is going on.

Also, just to clarify, the screenshot you posted is of incoming app mention events being POSTed from Slack to your app? Do you happen to have the request and response body details available? That would also help determine what is happening.

Lastly, not sure if you saw the [example in the root of this repo for a Google Cloud Functions-based Bolt for Java app](https://github.com/slackapi/java-slack-sdk/tree/main/bolt-google-cloud-functions-example) - perhaps it may be useful to you.

**Comment by ManuelG28** [comment]
Tbh I don't know how I fixed this issue. But not it works properly.
