### ISSUE TITLE
Add setToken(String) to MethodsClient request Interface

### ISSUE THREAD

**Issue by numeralnathan** [slackapi/java-slack-sdk#954]
When a request fails due to an expired access token, I refresh it.  I would like to set the request's token and resend the request.  This is difficult to do without a `setToken(String)` method in the `SlackApiRequest` interface.

### Category (place an `x` in each of the `[ ]`)

* [X] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

**Comment by seratch** [comment]
HI @numeralnathan, thanks for writing in!

The setter for token parameter already exists. As you can see in [the document section for the API client usage](https://slack.dev/java-slack-sdk/guides/web-api-basics), the way to instantiate the request class is to use its builder interface. For instance, when you make an `auth.test` API request,

```java
AuthTestRequest req = AuthTestRequest.builder().token("your-new-token").build();
AuthTestResponse response = Slack.getInstance().methods().authTest(req);
```

or 

```java
AuthTestResponse response = Slack.getInstance().methods().authTest(req -> req.token("your-new-token"));
```

either of above is the way to set a token for each request.

Also, the reason why `getToken` is defined in the interface is that `MethodsClient` checks if there is a passed token in a given request object. We are not adding `setToken(String)` to the interface at least in the short term. The Javadocs can be more clear on this, though.

**Comment by seratch** [comment]
I will update the javadoc as part of the issue https://github.com/slackapi/java-slack-sdk/issues/955

**Comment by numeralnathan** [comment]
@seratch The setter for the token only exists in the builder.  I would like a setter on the request objects (i.e., `SlackApiRequest`).

Let's say the access token expires at the perfectly wrong time.  The API replies with an expired access token error.  If there were a setter on `SlackApiRequest`, then I can write a generic method that checks for the expired access token error, refreshes it and sets the new access token on the `SlackApiRequest`.  Without the setter, then I have to write this code for each and every type of request.

**Comment by seratch** [comment]
@numeralnathan Thanks for your reply.

>Without the setter, then I have to write this code for each and every type of request.

Since this makes sense, I just reopened this issue.

One thing to consider is that changing the `SlackApiRequest` interface is a breaking change for existing code such as custom classes implementing the interface. To avoid such, introducing a new sub-interface (`ModifiableSlackApirequest` or so) for the built-in request classes  (and possibly custom ones on a user side) would be a reasonable way to enhance this SDK for the use case mentioned here.

**Comment by numeralnathan** [comment]
Another thought is to create a `default` setter in `SlackApiRequest`.  The interface's method simply throws `UnsupportedOperationException`.  For example,...

```
/**
 * The default implementation throws {@link UnsupportedOperationException}.
 * Implementing classes are encouraged to allow for setting the token and changing the Javadoc to state such.
 * 
 * @throws UnsupportedOperationException always thrown
 */
default void setToken(String token)
{
   throw new UnsupportedOperationException("SlackApiRequest.setToken() is not implemented.");
}
```

**Comment by seratch** [comment]
@numeralnathan 
I was not sure whether Lombok requires explicit `@Override` in this case. I just checked how it works and found that Lombok's auto setter generation overrides the default `setToken(String)` for me. We can go with your suggestion here. Thanks for the suggestion!

**Comment by seratch** [comment]
@numeralnathan 
Thanks for the feedback. I just submitted a pull request resolving this: https://github.com/slackapi/java-slack-sdk/pull/957 Your feedback is welcome if there is any!
