### ISSUE TITLE
The bot refresh token is overridden with the user refresh token in OAuthV2DefaultSuccessHandler.java

### ISSUE THREAD

**Issue by dguerinCoveo** [slackapi/java-slack-sdk#960]
When rotating the bot access token, the user refresh token is used because the bot refresh token is overridden [here](https://github.com/slackapi/java-slack-sdk/blob/v1.21.0/bolt/src/main/java/com/slack/api/bolt/service/builtin/oauth/default_impl/OAuthV2DefaultSuccessHandler.java#L79-L81). 

#### The Slack SDK version

```
[INFO] +- com.slack.api:slack-api-client:jar:1.20.2:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.20.2:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.20.2:compile
[INFO] |  +- com.slack.api:slack-app-backend:jar:1.20.2:compile
[INFO] |  \- com.slack.api:bolt:jar:1.20.2:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.20.2:compile
[INFO] |  |  +- com.slack.api:slack-api-model:jar:1.20.2:compile
[INFO] |  \- com.slack.api:bolt-servlet:jar:1.20.2:compile
[INFO] |     +- com.slack.api:slack-app-backend:jar:1.20.2:compile
[INFO] |     \- com.slack.api:bolt:jar:1.20.2:compile
[INFO] |  \- com.slack.api:slack-api-client:jar:1.20.2:compile
[INFO] +- com.slack.api:bolt:jar:1.20.2:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.20.2:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.20.2:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.20.2:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.20.2:compile
[INFO] |  |  +- com.slack.api:slack-api-model:jar:1.20.2:compile
[INFO] |  \- com.slack.api:bolt-servlet:jar:1.20.2:compile
[INFO] |     +- com.slack.api:slack-app-backend:jar:1.20.2:compile
[INFO] |     \- com.slack.api:bolt:jar:1.20.2:compile
```

#### Steps to reproduce:

1. Install a test Slack application using Java Slack SDK with `AmazonS3OAuthStateService`
2. Check the AWS bucket for the bot information that was saved
3. Notice that the bot_refresh_token is in fact the user refresh token

#### Expected result:

The bot_refresh_token should the same as the one we see in the OAuth & Permissions section of the app Dashboard.

#### Actual result:

The bot_refresh_token is the same as the user refresh token we see in the OAuth & Permissions section of the app Dashboard.

**Comment by seratch** [comment]
Hi @dguerinCoveo, thank you very much for taking the time to report this issue and we are sorry for the misbehavior. You are right that this is a bug on the lines of code that you've pointed out.

We will quickly resolve this issue and will release a new patch version shortly (within a few hours or so)
