### ISSUE TITLE
Slack Bolt Java cannot connect to proxy in socket mode

### ISSUE THREAD

**Issue by spins0140** [slackapi/java-slack-sdk#971]
I am trying to connect to proxy with socket mode using Slack Bolt Java framework:

```        
        System.setProperty( "http.proxyHost", "..." );
        System.setProperty( "http.proxyPort", "80" );
        
        AppConfig appConfig = new AppConfig();
        appConfig.setSigningSecret("...");
        appConfig.setSingleTeamBotToken("...");
        App app = new App(appConfig);

        new SocketModeApp(appToken, app).start();
```
It is able to successfully call `apps.connections.open` and `auth.test` APIs:
```
POST https://slack.com/api/apps.connections.open
{"ok": true, "url": "wss:\/\/wss-primary.slack.com\/link...}

POST https://slack.com/api/auth.test
{"ok": true, "app_name": ...}
```
But I am getting this error saying `"Failed to reconnect to Socket Mode server: javax.websocket.DeploymentException: Connection to 'wss://wss-primary.slack.com/link/?ticket=... failed' `

This method fails: `com.slack.api.socket_mode.impl.SocketModeClientTyrusImpl.connect()`

I also checked it with http mode and it was working fine and was able to connect to proxy.

Can somebody explain what could be wrong?

**Comment by seratch** [comment]
Hi @spins0140, the `SocketModeApp` supports the proxy settings for sure. I am afraid that your proxy server may not allow WebSocket connections. I would suggest confirming with your admins.
