### ISSUE TITLE
cannot find a way to define the channel description or topic during creation

### ISSUE THREAD

**Issue by guy1699** [slackapi/java-slack-sdk#975]
I'm using the code below to create a channel.
I cannot find a way to define the channel description or topic.

### Reproducible in:

``` 
      Slack slack = Slack.getInstance();
      MethodsClient methods = slack.methods(botAccessToken, teamId);
      ConversationsCreateResponse response =
          methods.conversationsCreate(builder -> builder.teamId(teamId).name(name).isPrivate(isPrivate));
```

#### The Slack SDK version

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ atrium-api ---
[INFO] com.salesforce.atrium:atrium-api:jar:0.0.1-SNAPSHOT
[INFO] +- com.salesforce.sconems:scone-starter-springwebmvc:jar:9.4.1:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.3:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.18:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.18:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.18:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.18:compile
[INFO] |  +- org.springframework:spring-expression:jar:5.3.18:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.18:compile
[INFO] +- com.salesforce.sconems:scone-starter-webadmin:jar:9.4.1:compile
[INFO] |  +- com.salesforce.sconems:abstractions:jar:9.4.1:compile
[INFO] |  |  +- com.salesforce.servicelibs:config-env:jar:5.16.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile
[INFO] |  |  +- com.github.zafarkhaja:java-semver:jar:0.9.0:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- org.apache.commons:commons-configuration2:jar:2.7:compile
[INFO] |  |  +- org.glassfish:javax.el:jar:3.0.1-b08:compile
[INFO] |  |  \- org.hibernate.validator:hibernate-validator:jar:6.1.7.Final:compile
[INFO] |  +- com.salesforce.sconems:scone-starter-jetty:jar:9.4.1:compile
[INFO] |  |  \- com.salesforce.sconems:scone-starter-jetty-api:jar:9.4.1:compile
[INFO] |  +- com.salesforce.sconems:scone-starter-jetty-impl:jar:9.4.1:compile
[INFO] |  |  +- com.salesforce.sconems:scone-starter-open-context:jar:9.4.1:compile
[INFO] |  |  |  +- com.salesforce.servicelibs:open-context-impl:jar:1.0.1-rel1-scone_94x:compile
[INFO] |  |  |  \- com.salesforce.servicelibs:open-context-marshallers:jar:1.0.1-rel1-scone_94x:compile
[INFO] |  |  +- com.salesforce.servicelibs:open-context-api:jar:1.0.1-rel1-scone_94x:compile
[INFO] |  |  +- com.salesforce.servicelibs:open-context-servlet:jar:1.0.1-rel1-scone_94x:compile
[INFO] |  |  +- com.salesforce.servicelibs:open-context-spring-web:jar:1.0.1-rel1-scone_94x:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.2:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  +- javax.websocket:javax.websocket-api:jar:1.0:compile
[INFO] |  |  +- javax.websocket:javax.websocket-client-api:jar:1.0:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-annotations:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-io:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-jndi:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-plus:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-rewrite:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-security:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util-ajax:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:javax-websocket-client-impl:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-server:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:9.2:compile
[INFO] |  |  +- org.ow2.asm:asm-analysis:jar:9.2:compile
[INFO] |  |  +- org.ow2.asm:asm-commons:jar:9.2:compile
[INFO] |  |  +- org.ow2.asm:asm-tree:jar:9.2:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.32:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-jetty:jar:2.4.13:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-web:jar:2.6.3:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  +- com.salesforce.servicelibs:lilikoi:jar:0.0.0-rel1:compile
[INFO] |  +- com.salesforce.servicelibs:logging:jar:6.21.1-rel12-scone_94x:compile
[INFO] |  +- com.salesforce.servicelibs:metrics-api:jar:5.30.1-rel13-scone_94x:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.4.13:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter:jar:2.6.3:compile
[INFO] +- com.heroku.sdk:heroku-maven-plugin:jar:3.0.4:compile
[INFO] |  +- com.heroku.sdk:heroku-deploy:jar:3.0.4:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.19:compile
[INFO] |  |  +- org.eclipse.jgit:org.eclipse.jgit:jar:5.6.0.201912101111-r:compile
[INFO] |  |  |  +- com.jcraft:jsch:jar:0.1.55:compile
[INFO] |  |  |  +- com.jcraft:jzlib:jar:1.1.1:compile
[INFO] |  |  |  +- com.googlecode.javaewah:JavaEWAH:jar:1.1.6:compile
[INFO] |  |  |  +- org.bouncycastle:bcpg-jdk15on:jar:1.64:compile
[INFO] |  |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |  +- com.heroku.api:heroku-api:jar:0.43:compile
[INFO] |  |  +- com.heroku.api:heroku-json-jackson:jar:0.43:compile
[INFO] |  |  \- com.heroku.api:heroku-http-apache:jar:0.43:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.5.0:compile
[INFO] |  |  \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:compile
[INFO] |  |     +- javax.enterprise:cdi-api:jar:2.0:compile
[INFO] |  |     |  +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO] |  |     |  \- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO] |  |     \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile
[INFO] |  +- org.apache.maven:maven-core:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.5.0:compile
[INFO] |  |  |  \- org.apache.maven:maven-builder-support:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven:maven-resolver-provider:jar:3.5.0:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.0.3:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.0.3:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.0.3:compile
[INFO] |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.0.3:compile
[INFO] |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.1.0:compile
[INFO] |  |  +- com.google.inject:guice:jar:no_aop:4.0:compile
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.24:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[INFO] |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:3.5.0:compile
[INFO] |  +- org.apache.maven.plugins:maven-dependency-plugin:jar:3.1.1:compile
[INFO] |  |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[INFO] |  |  +- org.apache.maven.reporting:maven-reporting-impl:jar:2.3:compile
[INFO] |  |  |  +- org.apache.maven.doxia:doxia-core:jar:1.2:compile
[INFO] |  |  |  |  \- xerces:xercesImpl:jar:2.9.1:compile
[INFO] |  |  |  |     \- xml-apis:xml-apis:jar:1.3.04:compile
[INFO] |  |  |  \- commons-validator:commons-validator:jar:1.3.1:compile
[INFO] |  |  |     \- commons-digester:commons-digester:jar:1.6:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-sink-api:jar:1.4:compile
[INFO] |  |  |  \- org.apache.maven.doxia:doxia-logging-api:jar:1.4:compile
[INFO] |  |  +- org.apache.maven.doxia:doxia-site-renderer:jar:1.4:compile
[INFO] |  |  |  +- org.apache.maven.doxia:doxia-decoration-model:jar:1.4:compile
[INFO] |  |  |  +- org.apache.maven.doxia:doxia-module-xhtml:jar:1.4:compile
[INFO] |  |  |  +- org.apache.maven.doxia:doxia-module-fml:jar:1.4:compile
[INFO] |  |  |  +- org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile
[INFO] |  |  |  +- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-30:compile
[INFO] |  |  |  |  \- junit:junit:jar:4.13.2:test
[INFO] |  |  |  |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile
[INFO] |  |  |  +- org.apache.velocity:velocity:jar:1.5:compile
[INFO] |  |  |  |  \- oro:oro:jar:2.0.8:compile
[INFO] |  |  |  \- org.apache.velocity:velocity-tools:jar:2.0:compile
[INFO] |  |  |     +- commons-chain:commons-chain:jar:1.1:compile
[INFO] |  |  |     +- dom4j:dom4j:jar:1.1:compile
[INFO] |  |  |     +- sslext:sslext:jar:1.2-0:compile
[INFO] |  |  |     +- org.apache.struts:struts-core:jar:1.3.8:compile
[INFO] |  |  |     +- org.apache.struts:struts-taglib:jar:1.3.8:compile
[INFO] |  |  |     \- org.apache.struts:struts-tiles:jar:1.3.8:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-archiver:jar:3.6.0:compile
[INFO] |  |  |  +- org.iq80.snappy:snappy:jar:0.4:compile
[INFO] |  |  |  \- org.tukaani:xz:jar:1.8:runtime
[INFO] |  |  +- org.apache.maven.shared:file-management:jar:3.0.0:compile
[INFO] |  |  |  \- org.apache.maven.shared:maven-shared-io:jar:3.0.0:compile
[INFO] |  |  |     +- org.apache.maven:maven-compat:jar:3.0:compile
[INFO] |  |  |     \- org.apache.maven.wagon:wagon-provider-api:jar:2.10:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-io:jar:3.0.0:compile
[INFO] |  |  +- org.apache.maven.shared:maven-dependency-analyzer:jar:1.10:compile
[INFO] |  |  +- org.apache.maven.shared:maven-dependency-tree:jar:3.0.1:compile
[INFO] |  |  |  \- org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[INFO] |  |  +- org.apache.maven.shared:maven-common-artifact-filters:jar:3.0.1:compile
[INFO] |  |  |  \- org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[INFO] |  |  |     \- org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[INFO] |  |  |        \- org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[INFO] |  |  +- org.apache.maven.shared:maven-artifact-transfer:jar:0.9.1:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  \- classworlds:classworlds:jar:1.1:compile
[INFO] |  \- org.twdata.maven:mojo-executor:jar:2.3.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-bootstrap:jar:3.1.1:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-starter:jar:3.1.1:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-context:jar:3.1.1:compile
[INFO] |     |  \- org.springframework.security:spring-security-crypto:jar:5.4.9:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-commons:jar:3.1.1:compile
[INFO] |     \- org.springframework.security:spring-security-rsa:jar:1.0.10.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-config:jar:3.1.1:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-config-client:jar:3.1.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.1:compile
[INFO] +- com.salesforce.atrium:atrium-core:jar:0.0.1-SNAPSHOT:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  +- commons-io:commons-io:jar:2.8.0:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.6.2:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |  |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator-annotation-processor:jar:6.1.7.Final:compile
[INFO] |  +- org.hibernate:hibernate-jpamodelgen:jar:5.4.32.Final:compile
[INFO] |  +- org.springframework:spring-jdbc:jar:5.3.13:compile
[INFO] |  \- org.postgresql:postgresql:jar:42.2.24:compile
[INFO] +- jakarta.json:jakarta.json-api:jar:2.0.1:compile
[INFO] +- org.springframework.data:spring-data-elasticsearch:jar:4.3.4:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.13:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.4.15:compile
[INFO] |  +- org.elasticsearch.client:transport:jar:7.9.3:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch:jar:7.9.3:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-core:jar:7.9.3:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-secure-sm:jar:7.9.3:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-x-content:jar:7.9.3:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.11.4:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.11.4:compile
[INFO] |  |  |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.11.4:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-geo:jar:7.9.3:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-core:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-analyzers-common:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-backward-codecs:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-grouping:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-highlighter:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-join:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-memory:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-misc:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queries:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queryparser:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-sandbox:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-spatial-extras:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-spatial3d:jar:8.6.2:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-suggest:jar:8.6.2:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-cli:jar:7.9.3:compile
[INFO] |  |  |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[INFO] |  |  |  +- com.carrotsearch:hppc:jar:0.8.1:compile
[INFO] |  |  |  +- com.tdunning:t-digest:jar:3.2:compile
[INFO] |  |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.11:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] |  |  |  \- org.elasticsearch:jna:jar:5.5.0:compile
[INFO] |  |  +- org.elasticsearch.plugin:reindex-client:jar:7.9.3:compile
[INFO] |  |  |  \- org.elasticsearch:elasticsearch-ssl-config:jar:7.9.3:compile
[INFO] |  |  +- org.elasticsearch.plugin:lang-mustache-client:jar:7.9.3:compile
[INFO] |  |  |  \- com.github.spullara.mustache.java:compiler:jar:0.9.6:compile
[INFO] |  |  +- org.elasticsearch.plugin:percolator-client:jar:7.9.3:compile
[INFO] |  |  +- org.elasticsearch.plugin:parent-join-client:jar:7.9.3:compile
[INFO] |  |  \- org.elasticsearch.plugin:rank-eval-client:jar:7.9.3:compile
[INFO] |  +- org.elasticsearch.plugin:transport-netty4-client:jar:7.9.3:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.72.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.72.Final:compile
[INFO] |  |  \- io.netty:netty-transport:jar:4.1.72.Final:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:7.9.3:compile
[INFO] |  |  +- org.elasticsearch.plugin:mapper-extras-client:jar:7.9.3:compile
[INFO] |  |  \- org.elasticsearch.plugin:aggs-matrix-stats-client:jar:7.9.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] +- co.elastic.clients:elasticsearch-java:jar:8.1.3:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:7.9.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.13:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  \- org.eclipse.parsson:parsson:jar:1.0.0:compile
[INFO] +- com.salesforce.sconems:scone-starter-logging-json:jar:9.4.1:compile
[INFO] |  +- com.salesforce.servicelibs:logback-util:jar:1.1.0-rel2:compile
[INFO] |  +- com.salesforce.servicelibs:logging-logback-json:jar:1.2.1-rel6-scone_94x:compile
[INFO] |  |  +- org.codehaus.janino:commons-compiler:jar:2.7.8:compile
[INFO] |  |  +- org.codehaus.janino:janino:jar:2.7.8:compile
[INFO] |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.32:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.2.9:compile
[INFO] +- org.springframework:spring-web:jar:5.3.18:compile
[INFO] +- com.google.guava:guava:jar:31.0.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.7.1:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] +- com.slack.api:bolt:jar:1.6.2:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.6.2:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.6.2:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.6.2:compile
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.3.2:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.0.0:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
[INFO] |     +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |     \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
[INFO] +- org.hibernate:hibernate-core:jar:5.6.1.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.1:compile
[INFO] |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] |  +- org.jboss:jandex:jar:2.2.3.Final:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  +- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.5:compile
[INFO] |     +- org.glassfish.jaxb:txw2:jar:2.3.5:compile
[INFO] |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] +- org.springframework:spring-orm:jar:5.3.18:compile
[INFO] +- com.zaxxer:HikariCP:jar:5.0.1:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.6.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.4.13:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.4.13:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3.1:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.3.1:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.18.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.6.28:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.18:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
[INFO] +- org.mockito:mockito-inline:jar:3.8.0:test
[INFO] +- org.mockito:mockito-core:jar:3.9.0:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
[INFO] |  \- org.objenesis:objenesis:jar:3.1:test
[INFO] +- joda-time:joda-time:jar:2.10.13:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.22:compile
[INFO] \- org.apache.commons:commons-text:jar:1.9:compile

#### Java Runtime version

openjdk version "15.0.6" 2022-01-18
OpenJDK Runtime Environment Zulu15.38+18-SA (build 15.0.6+5-MTS)
OpenJDK 64-Bit Server VM Zulu15.38+18-SA (build 15.0.6+5-MTS, mixed mode)

#### OS info

macOS

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1.
2.
3.

#### Expected result:

(Tell what you expected to happen)

#### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

**Comment by seratch** [comment]
Hi @guy1699, thanks for asking the question! This might be a bit confusing but there are other specific endpoints for setting those metadata:

* https://api.slack.com/methods/conversations.setTopic
* https://api.slack.com/methods/conversations.setPurpose

You can use the same name methods in MethodsClient: https://github.com/slackapi/java-slack-sdk/blob/v1.21.2/slack-api-client/src/main/java/com/slack/api/methods/MethodsClient.java#L1121-L1127

I hope this was helpful to you!
