### ISSUE TITLE
Sending a message to slack channel as an authorized user

### ISSUE THREAD

**Issue by magicalanmol100** [slackapi/java-slack-sdk#978]
I want to send message to slack channel as an authorised user. For that I set "asUser" property to true, while creating an object of ChatPostMessageRequest class. I see that this property is deprecated. Can u please tell mw the alternative for this use case ?

![image](https://user-images.githubusercontent.com/44744081/165476255-c2bb373a-0e29-4b8d-8e89-939009e5d427.png)

**Comment by seratch** [comment]
Hi @magicalanmol100, thanks for asking the question! 

If your app has the **user token** (`xoxp-` prefix) of the authorized user, you can perform chat.postMessage API call with the token. In this case, your app can pass only channel, text, blocks in the API request. You don't need to set any additional options.

If you would like to utilize your app's **bot token** (`xoxb-` prefix) to send a message with a specific user's name and icon (the message itself is still by your app, not the user), your app can have [chat:write.customize](https://api.slack.com/scopes/chat:write.customize) scope for it. Refer to https://api.slack.com/methods/chat.postMessage#authorship for more details.

I hope this was helpful to you.

**Comment by Dharani96556** [comment]
> Hi @magicalanmol100, thanks for asking the question!
> 
> If your app has the **user token** (`xoxp-` prefix) of the authorized user, you can perform chat.postMessage API call with the token. In this case, your app can pass only channel, text, blocks in the API request. You don't need to set any additional options.
> 
> If you would like to utilize your app's **bot token** (`xoxb-` prefix) to send a message with a specific user's name and icon (the message itself is still by your app, not the user), your app can have [chat:write.customize](https://api.slack.com/scopes/chat:write.customize) scope for it. Refer to https://api.slack.com/methods/chat.postMessage#authorship for more details.
> 
> I hope this was helpful to you.

That's true @seratch , but I am looking for a way to dynamically post a message according to the current user for my bot.
I researched on [Slack API Docs](https://api.slack.com/docs), and came up with a solution to use `as_user=True` as a parameter inside `client.chat_postMessage()` which didn't work.
Any solution on that?

**Comment by seratch** [comment]
@Dharani96556 As mentioned above, here is the solution for your use case:

>If your app has the user token (xoxp- prefix) of the authorized user, you can perform chat.postMessage API call with the token. In this case, your app can pass only channel, text, blocks in the API request. You don't need to set any additional options.

This means your app needs to collect user tokens from all the users who want your app to post a message on their behalf. The as_user option is a legacy one and no longer works. Thus, collecting user tokens is the only solution available for you.

**Comment by seratch** [comment]
If you mean posting a chat:write.customize bot message with a user's icon, you can call `users.info` API to retrieve the user's icon image URL and pass the URL to chat.postMessage API call w/ a bot token.
