### ISSUE TITLE
Can we get userInfo using @user.name

### ISSUE THREAD

**Issue by ssapa** [slackapi/java-slack-sdk#985]
We have a requirement to support user.name for getting user information. So would like to know whether we have any method to support this..

The SDK we are using is **slack_api_client**.

The SDK version is : 1.1.5

**Comment by seratch** [comment]
Hi @ssapa, thanks for asking the question!

If your app knows a user's ID, the app can use [`users.info` API method](https://api.slack.com/methods/users.info). 

However, no endpoint accepts a user's name for looking up. You need to fetch all the results of [`users.list` API method](https://api.slack.com/methods/users.list) and find the user with the name. One thing that you need to be aware of is that, in Slack, multiple users can have exactly the same name. In this case, you cannot identify a user by a name string.

I hope this helps.

**Comment by Syed-SnapLogic** [comment]
@seratch , can I have two people with same @username within one workspace?

**Comment by seratch** [comment]
Yes, the situation can arise. Those users’ IDs are different, though.

**Comment by seratch** [comment]
I think that everything is already clear here. Let me close this issue now.
