### ISSUE TITLE
Acknowledgment is not sent immediately (as in Python API)

### ISSUE THREAD

**Issue by asomov** [slackapi/java-slack-sdk#993]
It is possible in Python to acknowledge immediately and then run a long process and show the result once it is available. As shown in this code:

```
@app.command("/my_command")
def list_files(ack, respond, command):
  ack(
    response_type="in_channel",
    text=f"Request received from <@{command['user_id']}>",
  )
  result = long_running_process(command['text'])
  respond(text=result, response_type="in_channel")
```

Unfortunately, this way is impossible in the Java API (I use Kotlin of course, but it is not important here)
The acknowledgment must be returned at the end. It means I have to create async process for long-running tasks. It adds unnecessary complexity.
**Is there a way to acknowledge it immediately in Kotlin?**

```
        app.command("/list_cdr") { request: SlashCommandRequest, ctx: SlashCommandContext ->
            val res = ctx.ack { r: SlashCommandResponseBuilder ->
                r.text(":white_check_mark: Request from <@${ctx.requestUserId}>")
                    .responseType("in_channel")
            }
            // the Acknowledgment should be sent now !!!
            
            val text = request.payload.text
            val textResponse =  service.longRunningProcess(text)
            ctx.respond { r: SlashCommandResponseBuilder ->
                r.text(textResponse).responseType("in_channel")
            }
            res
        }
```

**Comment by seratch** [comment]
@asomov Thanks for asking the question! The way to asynchronously acknowledge a request is a bit different in the Java SDK. Please refer to https://github.com/slackapi/java-slack-sdk/issues/825#issuecomment-906409841 for details.

**Comment by asomov** [comment]
Thank you for the quick response. The proposed solution works perfectly for me !

Should it be somehow described in the docs? Because there are many similar questions already:

https://github.com/slackapi/java-slack-sdk/issues/700

**Comment by seratch** [comment]
Thanks for the great suggestion! We will update the documents to have this information 🙌
