### ISSUE TITLE
File type is ignored when uploading a binary file (MS Excel file)

### ISSUE THREAD

**Issue by silk-bahamut** [slackapi/java-slack-sdk#995]
I would like to upload a file and keep the mime type correct.
I tried with a byte array in fileData or a file in the file field, but none worked as expected.

#### The Slack SDK version

[INFO] +- com.slack.api:bolt-servlet:jar:1.22.2:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.22.2:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.22.2:compile
[INFO] |  +- com.slack.api:slack-app-backend:jar:1.22.2:compile
[INFO] |  \- com.slack.api:bolt:jar:1.22.2:compile

#### Java Runtime version

java correto 17.0.3

#### OS info

Microsoft Windows [Version 10.0.19044.1706]

#### Steps to reproduce:

1. Create a workbook with apache POI
2. Upload it to slack
3. The file is listed as binary, all given type are ignored
4. 
```
    Path tempPath = Files.createTempFile("export", ".xlsx");
    try (var workbook = new XSSFWorkbook()) {
      workbook.createSheet("test")
          .createRow(0)
          .createCell(0)
          .setCellValue("test");
      try (var outputStream = Files.newOutputStream(tempPath)) {
        workbook.write(outputStream);
      }
    }
    ctx.client().filesUpload(FilesUploadRequest.builder()
        .channels(List.of("#Random"))
        .initialComment("Export excel")
        .filename("export.xlsx")
        .filetype("xlsx")
        .file(tempPath.toFile())
        .build());
```

#### Expected result:

The file should be listed as excel spreadsheet and not binary.

#### Actual result:

The file is Binary
![image](https://user-images.githubusercontent.com/4752288/173196392-85e4d17c-15dd-4f34-8e8b-e3d5e72768ca.png)

**Comment by seratch** [comment]
Hi @silk-bahamut, thanks for asking the question! I tried to reproduce the issue on my end with an example Excel file but it worked for me as below:

```java
import com.slack.api.Slack;
import com.slack.api.methods.MethodsClient;
import com.slack.api.methods.response.files.FilesUploadResponse;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

public class Main {
    public static void main(String[] args) throws Exception {
        MethodsClient client = Slack.getInstance().methods(System.getenv("SLACK_BOT_TOKEN"));
        Path excelFile = Paths.get("/path-to-file-dir/test.xlsx");
        byte[] fileContent = Files.readAllBytes(excelFile);
        FilesUploadResponse response = client.filesUpload(r -> r
                .channels(Arrays.asList("C03E94MKU"))
                .initialComment("Here you are!")
                .fileData(fileContent)
                .filetype("xlsx")
        );
        System.out.println(response.getError());
        System.out.println(response.getFile());
    }
}
```

<img width="500" src="https://user-images.githubusercontent.com/19658/173261400-18a4d9fd-ce66-470d-8470-a76be1247485.png">

Perhaps, your code and/or the file data generated by Apache POI may not be compatible with the file format detection on the Slack sever-side. I hope that you will figure the cause out soon.

**Comment by silk-bahamut** [comment]
@seratch yes indeed, it seems that way.

**Comment by whymaomao** [comment]
Hi, @erayerdem I used HSSFSheet to create the xls type file. And this works for me. 
<img width="505" alt="image" src="https://github.com/slackapi/java-slack-sdk/assets/18661218/09af42a8-0007-4c7b-9fb7-023badc9ae32">

**Comment by erayerdem** [comment]
thanks a lot I will try :)

**Comment by erayerdem** [comment]
@

> Hi, @erayerdem I used HSSFSheet to create the xls type file. And this works for me. <img alt="image" width="505" src="https://user-images.githubusercontent.com/18661218/238502490-09af42a8-0007-4c7b-9fb7-023badc9ae32.png">

its worked how did you find this solution , you made my day
