### ISSUE TITLE
Writing Tests for interactive components

### ISSUE THREAD

**Issue by anantsxna** [slackapi/java-slack-sdk#996]
Firstly, I wanna say how nice the documentation for slack-api and this module is. I am just a beginner but I found most my questions answered easily available.

My problem: I am building a Slack Bot that has interactive Input blocks and I am using the blockAction method to process the input. 

```
app.command(
      "/abcd",
      (req, ctx) -> {
         String channelId = req.getContext().getChannelId();
         String text = req.getPayload().getText();
         if(syntaxCheck(text) == PASSED) {
             return ctx.ack(GOOD_ARGUMENTS);
            } else {
                return ctx.ack(BAD_ARGUMENTS);
            }
      }
  );

```

I want to write JUNit tests for App.blockAction methods and similarly for App.command methods. How do I accomplish this? Are there any examples/resources? Thank you so much for your time.

#### The Slack SDK version

slack v1.22.2

#### Java Runtime version

Java 18

**Comment by seratch** [comment]
Hi @anantsxna, thanks for asking the question! Also, I am very glad to hear that you are enjoying this SDK for building apps 🙌 

When it comes to unit testing, this SDK does not provide a handy way to write tests at this moment. Adding testing module is on our roadmap but I cannot tell when we can deliver yet.

For now, the only approach that I suggest is to write your own mock server for Web API calls plus build a request payload data [like this project does](https://github.com/slackapi/java-slack-sdk/blob/v1.22.2/bolt/src/test/java/test_locally/app/BlockActionTest.java). I know that this is not simple enough but I hope this was helpful to you.

**Comment by anantsxna** [comment]
Hi @seratch, Thanks so much for responding! I'll check out that example.
